// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"github.com/goplus/lib/c/time"
	"unsafe"
)

const BIO_TYPE_DESCRIPTOR = 256
const BIO_TYPE_FILTER = 512
const BIO_TYPE_SOURCE_SINK = 1024
const BIO_TYPE_NONE = 0
const BIO_TYPE_MEM = 1025
const BIO_TYPE_FILE = 1026
const BIO_TYPE_FD = 1284
const BIO_TYPE_SOCKET = 1285
const BIO_TYPE_NULL = 1030
const BIO_TYPE_SSL = 519
const BIO_TYPE_MD = 520
const BIO_TYPE_BUFFER = 521
const BIO_TYPE_CIPHER = 522
const BIO_TYPE_BASE64 = 523
const BIO_TYPE_CONNECT = 1292
const BIO_TYPE_ACCEPT = 1293
const BIO_TYPE_NBIO_TEST = 528
const BIO_TYPE_NULL_FILTER = 529
const BIO_TYPE_BIO = 1043
const BIO_TYPE_LINEBUFFER = 532
const BIO_TYPE_DGRAM = 1301
const BIO_TYPE_ASN1 = 534
const BIO_TYPE_COMP = 535
const BIO_TYPE_CORE_TO_PROV = 1049
const BIO_TYPE_DGRAM_PAIR = 1050
const BIO_TYPE_DGRAM_MEM = 1051
const BIO_TYPE_START = 128
const BIO_TYPE_MASK = 255
const BIO_NOCLOSE = 0
const BIO_CLOSE = 1
const BIO_CTRL_RESET = 1
const BIO_CTRL_EOF = 2
const BIO_CTRL_INFO = 3
const BIO_CTRL_SET = 4
const BIO_CTRL_GET = 5
const BIO_CTRL_PUSH = 6
const BIO_CTRL_POP = 7
const BIO_CTRL_GET_CLOSE = 8
const BIO_CTRL_SET_CLOSE = 9
const BIO_CTRL_PENDING = 10
const BIO_CTRL_FLUSH = 11
const BIO_CTRL_DUP = 12
const BIO_CTRL_WPENDING = 13
const BIO_CTRL_SET_CALLBACK = 14
const BIO_CTRL_GET_CALLBACK = 15
const BIO_CTRL_PEEK = 29
const BIO_CTRL_SET_FILENAME = 30
const BIO_CTRL_DGRAM_CONNECT = 31
const BIO_CTRL_DGRAM_SET_CONNECTED = 32
const BIO_CTRL_DGRAM_SET_RECV_TIMEOUT = 33
const BIO_CTRL_DGRAM_GET_RECV_TIMEOUT = 34
const BIO_CTRL_DGRAM_SET_SEND_TIMEOUT = 35
const BIO_CTRL_DGRAM_GET_SEND_TIMEOUT = 36
const BIO_CTRL_DGRAM_GET_RECV_TIMER_EXP = 37
const BIO_CTRL_DGRAM_GET_SEND_TIMER_EXP = 38
const BIO_CTRL_DGRAM_MTU_DISCOVER = 39
const BIO_CTRL_DGRAM_QUERY_MTU = 40
const BIO_CTRL_DGRAM_GET_FALLBACK_MTU = 47
const BIO_CTRL_DGRAM_GET_MTU = 41
const BIO_CTRL_DGRAM_SET_MTU = 42
const BIO_CTRL_DGRAM_MTU_EXCEEDED = 43
const BIO_CTRL_DGRAM_GET_PEER = 46
const BIO_CTRL_DGRAM_SET_PEER = 44
const BIO_CTRL_DGRAM_SET_NEXT_TIMEOUT = 45
const BIO_CTRL_DGRAM_SET_DONT_FRAG = 48
const BIO_CTRL_DGRAM_GET_MTU_OVERHEAD = 49
const BIO_CTRL_DGRAM_SCTP_SET_IN_HANDSHAKE = 50
const BIO_CTRL_DGRAM_SET_PEEK_MODE = 71
const BIO_CTRL_GET_KTLS_SEND = 73
const BIO_CTRL_GET_KTLS_RECV = 76
const BIO_CTRL_DGRAM_SCTP_WAIT_FOR_DRY = 77
const BIO_CTRL_DGRAM_SCTP_MSG_WAITING = 78
const BIO_CTRL_SET_PREFIX = 79
const BIO_CTRL_SET_INDENT = 80
const BIO_CTRL_GET_INDENT = 81
const BIO_CTRL_DGRAM_GET_LOCAL_ADDR_CAP = 82
const BIO_CTRL_DGRAM_GET_LOCAL_ADDR_ENABLE = 83
const BIO_CTRL_DGRAM_SET_LOCAL_ADDR_ENABLE = 84
const BIO_CTRL_DGRAM_GET_EFFECTIVE_CAPS = 85
const BIO_CTRL_DGRAM_GET_CAPS = 86
const BIO_CTRL_DGRAM_SET_CAPS = 87
const BIO_CTRL_DGRAM_GET_NO_TRUNC = 88
const BIO_CTRL_DGRAM_SET_NO_TRUNC = 89
const BIO_CTRL_GET_RPOLL_DESCRIPTOR = 91
const BIO_CTRL_GET_WPOLL_DESCRIPTOR = 92
const BIO_CTRL_DGRAM_DETECT_PEER_ADDR = 93
const BIO_CTRL_DGRAM_SET0_LOCAL_ADDR = 94
const BIO_FP_READ = 2
const BIO_FP_WRITE = 4
const BIO_FP_APPEND = 8
const BIO_FP_TEXT = 16
const BIO_FLAGS_READ = 1
const BIO_FLAGS_WRITE = 2
const BIO_FLAGS_IO_SPECIAL = 4
const BIO_FLAGS_RWS = 7
const BIO_FLAGS_SHOULD_RETRY = 8
const BIO_FLAGS_UPLINK = 0
const BIO_FLAGS_BASE64_NO_NL = 256
const BIO_FLAGS_MEM_RDONLY = 512
const BIO_FLAGS_NONCLEAR_RST = 1024
const BIO_FLAGS_IN_EOF = 2048
const BIO_RR_SSL_X509_LOOKUP = 1
const BIO_RR_CONNECT = 2
const BIO_RR_ACCEPT = 3
const BIO_CB_FREE = 1
const BIO_CB_READ = 2
const BIO_CB_WRITE = 3
const BIO_CB_PUTS = 4
const BIO_CB_GETS = 5
const BIO_CB_CTRL = 6
const BIO_CB_RECVMMSG = 7
const BIO_CB_SENDMMSG = 8
const BIO_CB_RETURN = 128
const BIO_POLL_DESCRIPTOR_TYPE_NONE = 0
const BIO_POLL_DESCRIPTOR_TYPE_SOCK_FD = 1
const BIO_POLL_DESCRIPTOR_TYPE_SSL = 2
const BIO_POLL_DESCRIPTOR_CUSTOM_START = 8192
const BIO_C_SET_CONNECT = 100
const BIO_C_DO_STATE_MACHINE = 101
const BIO_C_SET_NBIO = 102
const BIO_C_SET_FD = 104
const BIO_C_GET_FD = 105
const BIO_C_SET_FILE_PTR = 106
const BIO_C_GET_FILE_PTR = 107
const BIO_C_SET_FILENAME = 108
const BIO_C_SET_SSL = 109
const BIO_C_GET_SSL = 110
const BIO_C_SET_MD = 111
const BIO_C_GET_MD = 112
const BIO_C_GET_CIPHER_STATUS = 113
const BIO_C_SET_BUF_MEM = 114
const BIO_C_GET_BUF_MEM_PTR = 115
const BIO_C_GET_BUFF_NUM_LINES = 116
const BIO_C_SET_BUFF_SIZE = 117
const BIO_C_SET_ACCEPT = 118
const BIO_C_SSL_MODE = 119
const BIO_C_GET_MD_CTX = 120
const BIO_C_SET_BUFF_READ_DATA = 122
const BIO_C_GET_CONNECT = 123
const BIO_C_GET_ACCEPT = 124
const BIO_C_SET_SSL_RENEGOTIATE_BYTES = 125
const BIO_C_GET_SSL_NUM_RENEGOTIATES = 126
const BIO_C_SET_SSL_RENEGOTIATE_TIMEOUT = 127
const BIO_C_FILE_SEEK = 128
const BIO_C_GET_CIPHER_CTX = 129
const BIO_C_SET_BUF_MEM_EOF_RETURN = 130
const BIO_C_SET_BIND_MODE = 131
const BIO_C_GET_BIND_MODE = 132
const BIO_C_FILE_TELL = 133
const BIO_C_GET_SOCKS = 134
const BIO_C_SET_SOCKS = 135
const BIO_C_SET_WRITE_BUF_SIZE = 136
const BIO_C_GET_WRITE_BUF_SIZE = 137
const BIO_C_MAKE_BIO_PAIR = 138
const BIO_C_DESTROY_BIO_PAIR = 139
const BIO_C_GET_WRITE_GUARANTEE = 140
const BIO_C_GET_READ_REQUEST = 141
const BIO_C_SHUTDOWN_WR = 142
const BIO_C_NREAD0 = 143
const BIO_C_NREAD = 144
const BIO_C_NWRITE0 = 145
const BIO_C_NWRITE = 146
const BIO_C_RESET_READ_REQUEST = 147
const BIO_C_SET_MD_CTX = 148
const BIO_C_SET_PREFIX = 149
const BIO_C_GET_PREFIX = 150
const BIO_C_SET_SUFFIX = 151
const BIO_C_GET_SUFFIX = 152
const BIO_C_SET_EX_ARG = 153
const BIO_C_GET_EX_ARG = 154
const BIO_C_SET_CONNECT_MODE = 155
const BIO_C_SET_TFO = 156
const BIO_C_SET_SOCK_TYPE = 157
const BIO_C_GET_SOCK_TYPE = 158
const BIO_C_GET_DGRAM_BIO = 159
const BIO_C_SET_SEND_FLAGS = 160
const BIO_FAMILY_IPV4 = 4
const BIO_FAMILY_IPV6 = 6
const BIO_FAMILY_IPANY = 256
const BIO_BIND_NORMAL = 0
const BIO_SOCK_REUSEADDR = 1
const BIO_SOCK_V6_ONLY = 2
const BIO_SOCK_KEEPALIVE = 4
const BIO_SOCK_NONBLOCK = 8
const BIO_SOCK_NODELAY = 16
const BIO_SOCK_TFO = 32

type BIOHostservPriorities c.Uint

const (
	BIO_PARSE_PRIO_HOST BIOHostservPriorities = 0
	BIO_PARSE_PRIO_SERV BIOHostservPriorities = 1
)

type BIOLookupType c.Uint

const (
	BIO_LOOKUP_CLIENT BIOLookupType = 0
	BIO_LOOKUP_SERVER BIOLookupType = 1
)

type BIOSockInfoType c.Uint

const BIO_SOCK_INFO_ADDRESS BIOSockInfoType = 0

type BioAddrSt struct {
}
type BIO_ADDR = BioAddrSt
type BioAddrinfoSt struct {
}
type BIO_ADDRINFO = BioAddrinfoSt

// llgo:type C
type BIOCallbackFn = func(_llcppg_param1 *BIO, _llcppg_param2 c.Int, _llcppg_param3 *c.Char, _llcppg_param4 c.Int, _llcppg_param5 c.Long, _llcppg_param6 c.Long) c.Long

// llgo:type C
type BIOCallbackFnEx = func(_llcppg_param1 *BIO, _llcppg_param2 c.Int, _llcppg_param3 *c.Char, _llcppg_param4 c.SizeT, _llcppg_param5 c.Int, _llcppg_param6 c.Long, _llcppg_param7 c.Int, _llcppg_param8 *c.SizeT) c.Long
type BioMethodSt struct {
}
type BIO_METHOD = BioMethodSt

// llgo:type C
type BIOInfoCb = func(_llcppg_param1 *BIO, _llcppg_param2 c.Int, _llcppg_param3 c.Int) c.Int
type BioInfoCb = BIOInfoCb
type StackStBIO struct {
}

// clang-format off
//
// llgo:type C
type SkBIOCompfunc = func(_llcppg_param1 **BIO, _llcppg_param2 **BIO) c.Int

// clang-format off
//
// llgo:type C
type SkBIOFreefunc = func(_llcppg_param1 *BIO)

// clang-format off
//
// llgo:type C
type SkBIOCopyfunc = func(_llcppg_param1 *BIO) *BIO

// Prefix and suffix callback in ASN1 BIO
//
// llgo:type C
type Asn1PsFunc = func(_llcppg_param1 *BIO, _llcppg_param2 **uint8, _llcppg_param3 *c.Int, _llcppg_param4 unsafe.Pointer) c.Int

// llgo:type C
type BIODgramSctpNotificationHandlerFn = func(_llcppg_param1 *BIO, _llcppg_param2 unsafe.Pointer, _llcppg_param3 unsafe.Pointer)

// BIO_sendmmsg/BIO_recvmmsg-related definitions
type BioMsgSt struct {
	Data    unsafe.Pointer
	DataLen c.SizeT
	Peer    *BIO_ADDR
	Local   *BIO_ADDR
	Flags   c.Uint64T
}

// BIO_sendmmsg/BIO_recvmmsg-related definitions
type BIO_MSG = BioMsgSt
type BioMmsgCbArgsSt struct {
	Msg           *BIO_MSG
	Stride        c.SizeT
	NumMsg        c.SizeT
	Flags         c.Uint64T
	MsgsProcessed *c.SizeT
}
type BIO_MMSG_CB_ARGS = BioMmsgCbArgsSt
type BioPollDescriptorSt struct {
	Type  c.Uint32T
	Value _llcppg_anon_0
}
type _llcppg_anon_0 struct {
	_xgo_union [1]uint64
}
type BIO_POLL_DESCRIPTOR = BioPollDescriptorSt
type Hostent struct {
}
type BIOSockInfoU struct {
	_xgo_union [1]uint64
}

//go:linkname BIOGetNewIndex C.BIO_get_new_index
func BIOGetNewIndex() c.Int

//go:linkname BIOSetFlags C.BIO_set_flags
func BIOSetFlags(b *BIO, flags c.Int)

//go:linkname BIOTestFlags C.BIO_test_flags
func BIOTestFlags(b *BIO, flags c.Int) c.Int

//go:linkname BIOClearFlags C.BIO_clear_flags
func BIOClearFlags(b *BIO, flags c.Int)

//go:linkname BIOGetCallback C.BIO_get_callback
func BIOGetCallback(b *BIO) BIOCallbackFn

//go:linkname BIOSetCallback C.BIO_set_callback
func BIOSetCallback(b *BIO, callback BIOCallbackFn)

//go:linkname BIODebugCallback C.BIO_debug_callback
func BIODebugCallback(bio *BIO, cmd c.Int, argp *c.Char, argi c.Int, argl c.Long, ret c.Long) c.Long

//go:linkname BIOGetCallbackEx C.BIO_get_callback_ex
func BIOGetCallbackEx(b *BIO) BIOCallbackFnEx

//go:linkname BIOSetCallbackEx C.BIO_set_callback_ex
func BIOSetCallbackEx(b *BIO, callback BIOCallbackFnEx)

//go:linkname BIODebugCallbackEx C.BIO_debug_callback_ex
func BIODebugCallbackEx(bio *BIO, oper c.Int, argp *c.Char, len c.SizeT, argi c.Int, argl c.Long, ret c.Int, processed *c.SizeT) c.Long

//go:linkname BIOGetCallbackArg C.BIO_get_callback_arg
func BIOGetCallbackArg(b *BIO) *c.Char

//go:linkname BIOSetCallbackArg C.BIO_set_callback_arg
func BIOSetCallbackArg(b *BIO, arg *c.Char)

//go:linkname BIOMethodName C.BIO_method_name
func BIOMethodName(b *BIO) *c.Char

//go:linkname BIOMethodType C.BIO_method_type
func BIOMethodType(b *BIO) c.Int
func (p *_llcppg_anon_0) XGof_ref_fd() *c.Int {
	return (*c.Int)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_0) XGof_ref_custom() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_0) XGof_ref_custom_ui() *c.UintptrT {
	return (*c.UintptrT)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_0) XGof_ref_ssl() **SSL {
	return (**SSL)(unsafe.Pointer(p))
}

// ...pending macros have inappropriate return type
//
//go:linkname BIOCtrlPending C.BIO_ctrl_pending
func BIOCtrlPending(b *BIO) c.SizeT

//go:linkname BIOCtrlWpending C.BIO_ctrl_wpending
func BIOCtrlWpending(b *BIO) c.SizeT

//go:linkname BIOCtrlGetWriteGuarantee C.BIO_ctrl_get_write_guarantee
func BIOCtrlGetWriteGuarantee(b *BIO) c.SizeT

//go:linkname BIOCtrlGetReadRequest C.BIO_ctrl_get_read_request
func BIOCtrlGetReadRequest(b *BIO) c.SizeT

//go:linkname BIOCtrlResetReadRequest C.BIO_ctrl_reset_read_request
func BIOCtrlResetReadRequest(b *BIO) c.Int

//go:linkname BIOSetExData C.BIO_set_ex_data
func BIOSetExData(bio *BIO, idx c.Int, data unsafe.Pointer) c.Int

//go:linkname BIOGetExData C.BIO_get_ex_data
func BIOGetExData(bio *BIO, idx c.Int) unsafe.Pointer

//go:linkname BIONumberRead C.BIO_number_read
func BIONumberRead(bio *BIO) c.Uint64T

//go:linkname BIONumberWritten C.BIO_number_written
func BIONumberWritten(bio *BIO) c.Uint64T

// For BIO_f_asn1()
//
//go:linkname BIOAsn1SetPrefix C.BIO_asn1_set_prefix
func BIOAsn1SetPrefix(b *BIO, prefix *Asn1PsFunc, prefix_free *Asn1PsFunc) c.Int

//go:linkname BIOAsn1GetPrefix C.BIO_asn1_get_prefix
func BIOAsn1GetPrefix(b *BIO, pprefix **Asn1PsFunc, pprefix_free **Asn1PsFunc) c.Int

//go:linkname BIOAsn1SetSuffix C.BIO_asn1_set_suffix
func BIOAsn1SetSuffix(b *BIO, suffix *Asn1PsFunc, suffix_free *Asn1PsFunc) c.Int

//go:linkname BIOAsn1GetSuffix C.BIO_asn1_get_suffix
func BIOAsn1GetSuffix(b *BIO, psuffix **Asn1PsFunc, psuffix_free **Asn1PsFunc) c.Int

//go:linkname BIO_SFile C.BIO_s_file
func BIO_SFile() *BIO_METHOD

//go:linkname BIONewFile C.BIO_new_file
func BIONewFile(filename *c.Char, mode *c.Char) *BIO

//go:linkname BIONewFromCoreBio C.BIO_new_from_core_bio
func BIONewFromCoreBio(libctx *OSSL_LIB_CTX, corebio *OSSL_CORE_BIO) *BIO

//go:linkname BIONewFp C.BIO_new_fp
func BIONewFp(stream *c.FILE, close_flag c.Int) *BIO

//go:linkname BIONewEx C.BIO_new_ex
func BIONewEx(libctx *OSSL_LIB_CTX, method *BIO_METHOD) *BIO

//go:linkname BIONew C.BIO_new
func BIONew(type_ *BIO_METHOD) *BIO

//go:linkname BIOFree C.BIO_free
func BIOFree(a *BIO) c.Int

//go:linkname BIOSetData C.BIO_set_data
func BIOSetData(a *BIO, ptr unsafe.Pointer)

//go:linkname BIOGetData C.BIO_get_data
func BIOGetData(a *BIO) unsafe.Pointer

//go:linkname BIOSetInit C.BIO_set_init
func BIOSetInit(a *BIO, init c.Int)

//go:linkname BIOGetInit C.BIO_get_init
func BIOGetInit(a *BIO) c.Int

//go:linkname BIOSetShutdown C.BIO_set_shutdown
func BIOSetShutdown(a *BIO, shut c.Int)

//go:linkname BIOGetShutdown C.BIO_get_shutdown
func BIOGetShutdown(a *BIO) c.Int

//go:linkname BIOVfree C.BIO_vfree
func BIOVfree(a *BIO)

//go:linkname BIOUpRef C.BIO_up_ref
func BIOUpRef(a *BIO) c.Int

//go:linkname BIORead C.BIO_read
func BIORead(b *BIO, data unsafe.Pointer, dlen c.Int) c.Int

//go:linkname BIOReadEx C.BIO_read_ex
func BIOReadEx(b *BIO, data unsafe.Pointer, dlen c.SizeT, readbytes *c.SizeT) c.Int

//go:linkname BIORecvmmsg C.BIO_recvmmsg
func BIORecvmmsg(b *BIO, msg *BIO_MSG, stride c.SizeT, num_msg c.SizeT, flags c.Uint64T, msgs_processed *c.SizeT) c.Int

//go:linkname BIOGets C.BIO_gets
func BIOGets(bp *BIO, buf *c.Char, size c.Int) c.Int

//go:linkname BIOGetLine C.BIO_get_line
func BIOGetLine(bio *BIO, buf *c.Char, size c.Int) c.Int

//go:linkname BIOWrite C.BIO_write
func BIOWrite(b *BIO, data unsafe.Pointer, dlen c.Int) c.Int

//go:linkname BIOWriteEx C.BIO_write_ex
func BIOWriteEx(b *BIO, data unsafe.Pointer, dlen c.SizeT, written *c.SizeT) c.Int

//go:linkname BIOSendmmsg C.BIO_sendmmsg
func BIOSendmmsg(b *BIO, msg *BIO_MSG, stride c.SizeT, num_msg c.SizeT, flags c.Uint64T, msgs_processed *c.SizeT) c.Int

//go:linkname BIOGetRpollDescriptor C.BIO_get_rpoll_descriptor
func BIOGetRpollDescriptor(b *BIO, desc *BIO_POLL_DESCRIPTOR) c.Int

//go:linkname BIOGetWpollDescriptor C.BIO_get_wpoll_descriptor
func BIOGetWpollDescriptor(b *BIO, desc *BIO_POLL_DESCRIPTOR) c.Int

//go:linkname BIOPuts C.BIO_puts
func BIOPuts(bp *BIO, buf *c.Char) c.Int

//go:linkname BIOIndent C.BIO_indent
func BIOIndent(b *BIO, indent c.Int, max c.Int) c.Int

//go:linkname BIOCtrl C.BIO_ctrl
func BIOCtrl(bp *BIO, cmd c.Int, larg c.Long, parg unsafe.Pointer) c.Long

//go:linkname BIOEof C.BIO_eof
func BIOEof(b *BIO) c.Int

//go:linkname BIOCallbackCtrl C.BIO_callback_ctrl
func BIOCallbackCtrl(b *BIO, cmd c.Int, fp *BIOInfoCb) c.Long

//go:linkname BIOPtrCtrl C.BIO_ptr_ctrl
func BIOPtrCtrl(bp *BIO, cmd c.Int, larg c.Long) unsafe.Pointer

//go:linkname BIOIntCtrl C.BIO_int_ctrl
func BIOIntCtrl(bp *BIO, cmd c.Int, larg c.Long, iarg c.Int) c.Long

//go:linkname BIOPush C.BIO_push
func BIOPush(b *BIO, append *BIO) *BIO

//go:linkname BIOPop C.BIO_pop
func BIOPop(b *BIO) *BIO

//go:linkname BIOFreeAll C.BIO_free_all
func BIOFreeAll(a *BIO)

//go:linkname BIOFindType C.BIO_find_type
func BIOFindType(b *BIO, bio_type c.Int) *BIO

//go:linkname BIONext C.BIO_next
func BIONext(b *BIO) *BIO

//go:linkname BIOSetNext C.BIO_set_next
func BIOSetNext(b *BIO, next *BIO)

//go:linkname BIOGetRetryBIO C.BIO_get_retry_BIO
func BIOGetRetryBIO(bio *BIO, reason *c.Int) *BIO

//go:linkname BIOGetRetryReason C.BIO_get_retry_reason
func BIOGetRetryReason(bio *BIO) c.Int

//go:linkname BIOSetRetryReason C.BIO_set_retry_reason
func BIOSetRetryReason(bio *BIO, reason c.Int)

//go:linkname BIODupChain C.BIO_dup_chain
func BIODupChain(in *BIO) *BIO

//go:linkname BIONread0 C.BIO_nread0
func BIONread0(bio *BIO, buf **c.Char) c.Int

//go:linkname BIONread C.BIO_nread
func BIONread(bio *BIO, buf **c.Char, num c.Int) c.Int

//go:linkname BIONwrite0 C.BIO_nwrite0
func BIONwrite0(bio *BIO, buf **c.Char) c.Int

//go:linkname BIONwrite C.BIO_nwrite
func BIONwrite(bio *BIO, buf **c.Char, num c.Int) c.Int

//go:linkname BIO_SMem C.BIO_s_mem
func BIO_SMem() *BIO_METHOD

//go:linkname BIO_SDgramMem C.BIO_s_dgram_mem
func BIO_SDgramMem() *BIO_METHOD

//go:linkname BIO_SSecmem C.BIO_s_secmem
func BIO_SSecmem() *BIO_METHOD

//go:linkname BIONewMemBuf C.BIO_new_mem_buf
func BIONewMemBuf(buf unsafe.Pointer, len c.Int) *BIO

//go:linkname BIO_SSocket C.BIO_s_socket
func BIO_SSocket() *BIO_METHOD

//go:linkname BIO_SConnect C.BIO_s_connect
func BIO_SConnect() *BIO_METHOD

//go:linkname BIO_SAccept C.BIO_s_accept
func BIO_SAccept() *BIO_METHOD

//go:linkname BIO_SFd C.BIO_s_fd
func BIO_SFd() *BIO_METHOD

//go:linkname BIO_SLog C.BIO_s_log
func BIO_SLog() *BIO_METHOD

//go:linkname BIO_SBio C.BIO_s_bio
func BIO_SBio() *BIO_METHOD

//go:linkname BIO_SNull C.BIO_s_null
func BIO_SNull() *BIO_METHOD

//go:linkname BIO_FNull C.BIO_f_null
func BIO_FNull() *BIO_METHOD

//go:linkname BIO_FBuffer C.BIO_f_buffer
func BIO_FBuffer() *BIO_METHOD

//go:linkname BIO_FReadbuffer C.BIO_f_readbuffer
func BIO_FReadbuffer() *BIO_METHOD

//go:linkname BIO_FLinebuffer C.BIO_f_linebuffer
func BIO_FLinebuffer() *BIO_METHOD

//go:linkname BIO_FNbioTest C.BIO_f_nbio_test
func BIO_FNbioTest() *BIO_METHOD

//go:linkname BIO_FPrefix C.BIO_f_prefix
func BIO_FPrefix() *BIO_METHOD

//go:linkname BIO_SCore C.BIO_s_core
func BIO_SCore() *BIO_METHOD

//go:linkname BIO_SDgramPair C.BIO_s_dgram_pair
func BIO_SDgramPair() *BIO_METHOD

//go:linkname BIO_SDatagram C.BIO_s_datagram
func BIO_SDatagram() *BIO_METHOD

//go:linkname BIODgramNonFatalError C.BIO_dgram_non_fatal_error
func BIODgramNonFatalError(error c.Int) c.Int

//go:linkname BIONewDgram C.BIO_new_dgram
func BIONewDgram(fd c.Int, close_flag c.Int) *BIO

//go:linkname BIOSockShouldRetry C.BIO_sock_should_retry
func BIOSockShouldRetry(i c.Int) c.Int

//go:linkname BIOSockNonFatalError C.BIO_sock_non_fatal_error
func BIOSockNonFatalError(error c.Int) c.Int

//go:linkname BIOErrIsNonFatal C.BIO_err_is_non_fatal
func BIOErrIsNonFatal(errcode c.Uint) c.Int

//go:linkname BIOSocketWait C.BIO_socket_wait
func BIOSocketWait(fd c.Int, for_read c.Int, max_time time.TimeT) c.Int

//go:linkname BIOSetSendFlags C.BIO_set_send_flags
func BIOSetSendFlags(b *BIO, flags c.Int) c.Long

//go:linkname BIOWait C.BIO_wait
func BIOWait(bio *BIO, max_time time.TimeT, nap_milliseconds c.Uint) c.Int

//go:linkname BIODoConnectRetry C.BIO_do_connect_retry
func BIODoConnectRetry(bio *BIO, timeout c.Int, nap_milliseconds c.Int) c.Int

//go:linkname BIOFdShouldRetry C.BIO_fd_should_retry
func BIOFdShouldRetry(i c.Int) c.Int

//go:linkname BIOFdNonFatalError C.BIO_fd_non_fatal_error
func BIOFdNonFatalError(error c.Int) c.Int

//go:linkname BIODumpCb C.BIO_dump_cb
func BIODumpCb(cb func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 c.SizeT, _llcppg_param3 unsafe.Pointer) c.Int, u unsafe.Pointer, s unsafe.Pointer, len c.Int) c.Int

//go:linkname BIODumpIndentCb C.BIO_dump_indent_cb
func BIODumpIndentCb(cb func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 c.SizeT, _llcppg_param3 unsafe.Pointer) c.Int, u unsafe.Pointer, s unsafe.Pointer, len c.Int, indent c.Int) c.Int

//go:linkname BIODump C.BIO_dump
func BIODump(b *BIO, bytes unsafe.Pointer, len c.Int) c.Int

//go:linkname BIODumpIndent C.BIO_dump_indent
func BIODumpIndent(b *BIO, bytes unsafe.Pointer, len c.Int, indent c.Int) c.Int

//go:linkname BIODumpFp C.BIO_dump_fp
func BIODumpFp(fp *c.FILE, s unsafe.Pointer, len c.Int) c.Int

//go:linkname BIODumpIndentFp C.BIO_dump_indent_fp
func BIODumpIndentFp(fp *c.FILE, s unsafe.Pointer, len c.Int, indent c.Int) c.Int

//go:linkname BIOHexString C.BIO_hex_string
func BIOHexString(out *BIO, indent c.Int, width c.Int, data unsafe.Pointer, datalen c.Int) c.Int

//go:linkname BIO_ADDRNew C.BIO_ADDR_new
func BIO_ADDRNew() *BIO_ADDR

//go:linkname BIO_ADDRCopy C.BIO_ADDR_copy
func BIO_ADDRCopy(dst *BIO_ADDR, src *BIO_ADDR) c.Int

//go:linkname BIO_ADDRDup C.BIO_ADDR_dup
func BIO_ADDRDup(ap *BIO_ADDR) *BIO_ADDR

//go:linkname BIO_ADDRRawmake C.BIO_ADDR_rawmake
func BIO_ADDRRawmake(ap *BIO_ADDR, family c.Int, where unsafe.Pointer, wherelen c.SizeT, port uint16) c.Int

//go:linkname BIO_ADDRFree C.BIO_ADDR_free
func BIO_ADDRFree(_llcppg_param1 *BIO_ADDR)

//go:linkname BIO_ADDRClear C.BIO_ADDR_clear
func BIO_ADDRClear(ap *BIO_ADDR)

//go:linkname BIO_ADDRFamily C.BIO_ADDR_family
func BIO_ADDRFamily(ap *BIO_ADDR) c.Int

//go:linkname BIO_ADDRRawaddress C.BIO_ADDR_rawaddress
func BIO_ADDRRawaddress(ap *BIO_ADDR, p unsafe.Pointer, l *c.SizeT) c.Int

//go:linkname BIO_ADDRRawport C.BIO_ADDR_rawport
func BIO_ADDRRawport(ap *BIO_ADDR) uint16

//go:linkname BIO_ADDRHostnameString C.BIO_ADDR_hostname_string
func BIO_ADDRHostnameString(ap *BIO_ADDR, numeric c.Int) *c.Char

//go:linkname BIO_ADDRServiceString C.BIO_ADDR_service_string
func BIO_ADDRServiceString(ap *BIO_ADDR, numeric c.Int) *c.Char

//go:linkname BIO_ADDRPathString C.BIO_ADDR_path_string
func BIO_ADDRPathString(ap *BIO_ADDR) *c.Char

//go:linkname BIO_ADDRINFONext C.BIO_ADDRINFO_next
func BIO_ADDRINFONext(bai *BIO_ADDRINFO) *BIO_ADDRINFO

//go:linkname BIO_ADDRINFOFamily C.BIO_ADDRINFO_family
func BIO_ADDRINFOFamily(bai *BIO_ADDRINFO) c.Int

//go:linkname BIO_ADDRINFOSocktype C.BIO_ADDRINFO_socktype
func BIO_ADDRINFOSocktype(bai *BIO_ADDRINFO) c.Int

//go:linkname BIO_ADDRINFOProtocol C.BIO_ADDRINFO_protocol
func BIO_ADDRINFOProtocol(bai *BIO_ADDRINFO) c.Int

//go:linkname BIO_ADDRINFOAddress C.BIO_ADDRINFO_address
func BIO_ADDRINFOAddress(bai *BIO_ADDRINFO) *BIO_ADDR

//go:linkname BIO_ADDRINFOFree C.BIO_ADDRINFO_free
func BIO_ADDRINFOFree(bai *BIO_ADDRINFO)

//go:linkname BIOParseHostserv C.BIO_parse_hostserv
func BIOParseHostserv(hostserv *c.Char, host **c.Char, service **c.Char, hostserv_prio BIOHostservPriorities) c.Int

//go:linkname BIOLookup C.BIO_lookup
func BIOLookup(host *c.Char, service *c.Char, lookup_type BIOLookupType, family c.Int, socktype c.Int, res **BIO_ADDRINFO) c.Int

//go:linkname BIOLookupEx C.BIO_lookup_ex
func BIOLookupEx(host *c.Char, service *c.Char, lookup_type c.Int, family c.Int, socktype c.Int, protocol c.Int, res **BIO_ADDRINFO) c.Int

//go:linkname BIOSockError C.BIO_sock_error
func BIOSockError(sock c.Int) c.Int

//go:linkname BIOSocketIoctl C.BIO_socket_ioctl
func BIOSocketIoctl(fd c.Int, type_ c.Long, arg unsafe.Pointer) c.Int

//go:linkname BIOSocketNbio C.BIO_socket_nbio
func BIOSocketNbio(fd c.Int, mode c.Int) c.Int

//go:linkname BIOSockInit C.BIO_sock_init
func BIOSockInit() c.Int

//go:linkname BIOSetTcpNdelay C.BIO_set_tcp_ndelay
func BIOSetTcpNdelay(sock c.Int, turn_on c.Int) c.Int

//go:linkname BIOGethostbyname C.BIO_gethostbyname
func BIOGethostbyname(name *c.Char) *Hostent

//go:linkname BIOGetPort C.BIO_get_port
func BIOGetPort(str *c.Char, port_ptr *uint16) c.Int

//go:linkname BIOGetHostIp C.BIO_get_host_ip
func BIOGetHostIp(str *c.Char, ip *uint8) c.Int

//go:linkname BIOGetAcceptSocket C.BIO_get_accept_socket
func BIOGetAcceptSocket(host_port *c.Char, mode c.Int) c.Int

//go:linkname BIOAccept C.BIO_accept
func BIOAccept(sock c.Int, ip_port **c.Char) c.Int
func (p *BIOSockInfoU) XGof_ref_addr() **BIO_ADDR {
	return (**BIO_ADDR)(unsafe.Pointer(p))
}

//go:linkname BIOSockInfo C.BIO_sock_info
func BIOSockInfo(sock c.Int, type_ BIOSockInfoType, info *BIOSockInfoU) c.Int

//go:linkname BIOSocket C.BIO_socket
func BIOSocket(domain c.Int, socktype c.Int, protocol c.Int, options c.Int) c.Int

//go:linkname BIOConnect C.BIO_connect
func BIOConnect(sock c.Int, addr *BIO_ADDR, options c.Int) c.Int

//go:linkname BIOBind C.BIO_bind
func BIOBind(sock c.Int, addr *BIO_ADDR, options c.Int) c.Int

//go:linkname BIOListen C.BIO_listen
func BIOListen(sock c.Int, addr *BIO_ADDR, options c.Int) c.Int

//go:linkname BIOAcceptEx C.BIO_accept_ex
func BIOAcceptEx(accept_sock c.Int, addr *BIO_ADDR, options c.Int) c.Int

//go:linkname BIOClosesocket C.BIO_closesocket
func BIOClosesocket(sock c.Int) c.Int

//go:linkname BIONewSocket C.BIO_new_socket
func BIONewSocket(sock c.Int, close_flag c.Int) *BIO

//go:linkname BIONewConnect C.BIO_new_connect
func BIONewConnect(host_port *c.Char) *BIO

//go:linkname BIONewAccept C.BIO_new_accept
func BIONewAccept(host_port *c.Char) *BIO

//go:linkname BIONewFd C.BIO_new_fd
func BIONewFd(fd c.Int, close_flag c.Int) *BIO

//go:linkname BIONewBioPair C.BIO_new_bio_pair
func BIONewBioPair(bio1 **BIO, writebuf1 c.SizeT, bio2 **BIO, writebuf2 c.SizeT) c.Int

//go:linkname BIONewBioDgramPair C.BIO_new_bio_dgram_pair
func BIONewBioDgramPair(bio1 **BIO, writebuf1 c.SizeT, bio2 **BIO, writebuf2 c.SizeT) c.Int

// If successful, returns 1 and in *bio1, *bio2 two BIO pair endpoints.
// Otherwise returns 0 and sets *bio1 and *bio2 to NULL. Size 0 uses default
// value.
//
//go:linkname BIOCopyNextRetry C.BIO_copy_next_retry
func BIOCopyNextRetry(b *BIO)

//go:linkname BIOPrintf C.BIO_printf
func BIOPrintf(bio *BIO, format *c.Char, __llgo_va_list ...any) c.Int

//go:linkname BIOVprintf C.BIO_vprintf
func BIOVprintf(bio *BIO, format *c.Char, args c.VaList) c.Int

//go:linkname BIOSnprintf C.BIO_snprintf
func BIOSnprintf(buf *c.Char, n c.SizeT, format *c.Char, __llgo_va_list ...any) c.Int

//go:linkname BIOVsnprintf C.BIO_vsnprintf
func BIOVsnprintf(buf *c.Char, n c.SizeT, format *c.Char, args c.VaList) c.Int

//go:linkname BIOMethNew C.BIO_meth_new
func BIOMethNew(type_ c.Int, name *c.Char) *BIO_METHOD

//go:linkname BIOMethFree C.BIO_meth_free
func BIOMethFree(biom *BIO_METHOD)

//go:linkname BIOMethSetWrite C.BIO_meth_set_write
func BIOMethSetWrite(biom *BIO_METHOD, write func(_llcppg_param1 *BIO, _llcppg_param2 *c.Char, _llcppg_param3 c.Int) c.Int) c.Int

//go:linkname BIOMethSetWriteEx C.BIO_meth_set_write_ex
func BIOMethSetWriteEx(biom *BIO_METHOD, bwrite func(_llcppg_param1 *BIO, _llcppg_param2 *c.Char, _llcppg_param3 c.SizeT, _llcppg_param4 *c.SizeT) c.Int) c.Int

//go:linkname BIOMethSetSendmmsg C.BIO_meth_set_sendmmsg
func BIOMethSetSendmmsg(biom *BIO_METHOD, f func(_llcppg_param1 *BIO, _llcppg_param2 *BIO_MSG, _llcppg_param3 c.SizeT, _llcppg_param4 c.SizeT, _llcppg_param5 c.Uint64T, _llcppg_param6 *c.SizeT) c.Int) c.Int

//go:linkname BIOMethSetRead C.BIO_meth_set_read
func BIOMethSetRead(biom *BIO_METHOD, read func(_llcppg_param1 *BIO, _llcppg_param2 *c.Char, _llcppg_param3 c.Int) c.Int) c.Int

//go:linkname BIOMethSetReadEx C.BIO_meth_set_read_ex
func BIOMethSetReadEx(biom *BIO_METHOD, bread func(_llcppg_param1 *BIO, _llcppg_param2 *c.Char, _llcppg_param3 c.SizeT, _llcppg_param4 *c.SizeT) c.Int) c.Int

//go:linkname BIOMethSetRecvmmsg C.BIO_meth_set_recvmmsg
func BIOMethSetRecvmmsg(biom *BIO_METHOD, f func(_llcppg_param1 *BIO, _llcppg_param2 *BIO_MSG, _llcppg_param3 c.SizeT, _llcppg_param4 c.SizeT, _llcppg_param5 c.Uint64T, _llcppg_param6 *c.SizeT) c.Int) c.Int

//go:linkname BIOMethSetPuts C.BIO_meth_set_puts
func BIOMethSetPuts(biom *BIO_METHOD, puts func(_llcppg_param1 *BIO, _llcppg_param2 *c.Char) c.Int) c.Int

//go:linkname BIOMethSetGets C.BIO_meth_set_gets
func BIOMethSetGets(biom *BIO_METHOD, ossl_gets func(_llcppg_param1 *BIO, _llcppg_param2 *c.Char, _llcppg_param3 c.Int) c.Int) c.Int

//go:linkname BIOMethSetCtrl C.BIO_meth_set_ctrl
func BIOMethSetCtrl(biom *BIO_METHOD, ctrl func(_llcppg_param1 *BIO, _llcppg_param2 c.Int, _llcppg_param3 c.Long, _llcppg_param4 unsafe.Pointer) c.Long) c.Int

//go:linkname BIOMethSetCreate C.BIO_meth_set_create
func BIOMethSetCreate(biom *BIO_METHOD, create func(_llcppg_param1 *BIO) c.Int) c.Int

//go:linkname BIOMethSetDestroy C.BIO_meth_set_destroy
func BIOMethSetDestroy(biom *BIO_METHOD, destroy func(_llcppg_param1 *BIO) c.Int) c.Int

//go:linkname BIOMethSetCallbackCtrl C.BIO_meth_set_callback_ctrl
func BIOMethSetCallbackCtrl(biom *BIO_METHOD, callback_ctrl func(_llcppg_param1 *BIO, _llcppg_param2 c.Int, _llcppg_param3 *BIOInfoCb) c.Long) c.Int

//go:linkname BIOMethGetWrite C.BIO_meth_get_write
func BIOMethGetWrite(biom *BIO_METHOD) func(_llcppg_param1 *BIO, _llcppg_param2 *c.Char, _llcppg_param3 c.Int) c.Int

//go:linkname BIOMethGetWriteEx C.BIO_meth_get_write_ex
func BIOMethGetWriteEx(biom *BIO_METHOD) func(_llcppg_param1 *BIO, _llcppg_param2 *c.Char, _llcppg_param3 c.SizeT, _llcppg_param4 *c.SizeT) c.Int

//go:linkname BIOMethGetSendmmsg C.BIO_meth_get_sendmmsg
func BIOMethGetSendmmsg(biom *BIO_METHOD) func(_llcppg_param1 *BIO, _llcppg_param2 *BIO_MSG, _llcppg_param3 c.SizeT, _llcppg_param4 c.SizeT, _llcppg_param5 c.Uint64T, _llcppg_param6 *c.SizeT) c.Int

//go:linkname BIOMethGetRead C.BIO_meth_get_read
func BIOMethGetRead(biom *BIO_METHOD) func(_llcppg_param1 *BIO, _llcppg_param2 *c.Char, _llcppg_param3 c.Int) c.Int

//go:linkname BIOMethGetReadEx C.BIO_meth_get_read_ex
func BIOMethGetReadEx(biom *BIO_METHOD) func(_llcppg_param1 *BIO, _llcppg_param2 *c.Char, _llcppg_param3 c.SizeT, _llcppg_param4 *c.SizeT) c.Int

//go:linkname BIOMethGetRecvmmsg C.BIO_meth_get_recvmmsg
func BIOMethGetRecvmmsg(biom *BIO_METHOD) func(_llcppg_param1 *BIO, _llcppg_param2 *BIO_MSG, _llcppg_param3 c.SizeT, _llcppg_param4 c.SizeT, _llcppg_param5 c.Uint64T, _llcppg_param6 *c.SizeT) c.Int

//go:linkname BIOMethGetPuts C.BIO_meth_get_puts
func BIOMethGetPuts(biom *BIO_METHOD) func(_llcppg_param1 *BIO, _llcppg_param2 *c.Char) c.Int

//go:linkname BIOMethGetGets C.BIO_meth_get_gets
func BIOMethGetGets(biom *BIO_METHOD) func(_llcppg_param1 *BIO, _llcppg_param2 *c.Char, _llcppg_param3 c.Int) c.Int

//go:linkname BIOMethGetCtrl C.BIO_meth_get_ctrl
func BIOMethGetCtrl(biom *BIO_METHOD) func(_llcppg_param1 *BIO, _llcppg_param2 c.Int, _llcppg_param3 c.Long, _llcppg_param4 unsafe.Pointer) c.Long

//go:linkname BIOMethGetCreate C.BIO_meth_get_create
func BIOMethGetCreate(bion *BIO_METHOD) func(_llcppg_param1 *BIO) c.Int

//go:linkname BIOMethGetDestroy C.BIO_meth_get_destroy
func BIOMethGetDestroy(biom *BIO_METHOD) func(_llcppg_param1 *BIO) c.Int

//go:linkname BIOMethGetCallbackCtrl C.BIO_meth_get_callback_ctrl
func BIOMethGetCallbackCtrl(biom *BIO_METHOD) func(_llcppg_param1 *BIO, _llcppg_param2 c.Int, _llcppg_param3 *BIOInfoCb) c.Long
