// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const BUF_MEM_FLAG_SECURE = 1

type BufMemSt struct {
	Length c.SizeT
	Data   *c.Char
	Max    c.SizeT
	Flags  c.Ulong
}

//go:linkname BUF_MEMNew C.BUF_MEM_new
func BUF_MEMNew() *BUF_MEM

//go:linkname BUF_MEMNewEx C.BUF_MEM_new_ex
func BUF_MEMNewEx(flags c.Ulong) *BUF_MEM

//go:linkname BUF_MEMFree C.BUF_MEM_free
func BUF_MEMFree(a *BUF_MEM)

//go:linkname BUF_MEMGrow C.BUF_MEM_grow
func BUF_MEMGrow(str *BUF_MEM, len c.SizeT) c.SizeT

//go:linkname BUF_MEMGrowClean C.BUF_MEM_grow_clean
func BUF_MEMGrowClean(str *BUF_MEM, len c.SizeT) c.SizeT

//go:linkname BUFReverse C.BUF_reverse
func BUFReverse(out *uint8, in *uint8, siz c.SizeT)
