// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type SslCompSt struct {
}
type SSL_COMP = SslCompSt
type StackStSSL_COMP struct {
}

// clang-format off
//
// llgo:type C
type SkSSL_COMPCompfunc = func(_llcppg_param1 **SSL_COMP, _llcppg_param2 **SSL_COMP) c.Int

// clang-format off
//
// llgo:type C
type SkSSL_COMPFreefunc = func(_llcppg_param1 *SSL_COMP)

// clang-format off
//
// llgo:type C
type SkSSL_COMPCopyfunc = func(_llcppg_param1 *SSL_COMP) *SSL_COMP

//go:linkname COMP_CTXNew C.COMP_CTX_new
func COMP_CTXNew(meth *COMP_METHOD) *COMP_CTX

//go:linkname COMP_CTXGetMethod C.COMP_CTX_get_method
func COMP_CTXGetMethod(ctx *COMP_CTX) *COMP_METHOD

//go:linkname COMP_CTXGetType C.COMP_CTX_get_type
func COMP_CTXGetType(comp *COMP_CTX) c.Int

//go:linkname COMPGetType C.COMP_get_type
func COMPGetType(meth *COMP_METHOD) c.Int

//go:linkname COMPGetName C.COMP_get_name
func COMPGetName(meth *COMP_METHOD) *c.Char

//go:linkname COMP_CTXFree C.COMP_CTX_free
func COMP_CTXFree(ctx *COMP_CTX)

//go:linkname COMPCompressBlock C.COMP_compress_block
func COMPCompressBlock(ctx *COMP_CTX, out *uint8, olen c.Int, in *uint8, ilen c.Int) c.Int

//go:linkname COMPExpandBlock C.COMP_expand_block
func COMPExpandBlock(ctx *COMP_CTX, out *uint8, olen c.Int, in *uint8, ilen c.Int) c.Int

//go:linkname COMPZlib C.COMP_zlib
func COMPZlib() *COMP_METHOD

//go:linkname COMPZlibOneshot C.COMP_zlib_oneshot
func COMPZlibOneshot() *COMP_METHOD

//go:linkname COMPBrotli C.COMP_brotli
func COMPBrotli() *COMP_METHOD

//go:linkname COMPBrotliOneshot C.COMP_brotli_oneshot
func COMPBrotliOneshot() *COMP_METHOD

//go:linkname COMPZstd C.COMP_zstd
func COMPZstd() *COMP_METHOD

//go:linkname COMPZstdOneshot C.COMP_zstd_oneshot
func COMPZstdOneshot() *COMP_METHOD
