// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const CONF_MFLAGS_IGNORE_ERRORS = 1
const CONF_MFLAGS_IGNORE_RETURN_CODES = 2
const CONF_MFLAGS_SILENT = 4
const CONF_MFLAGS_NO_DSO = 8
const CONF_MFLAGS_IGNORE_MISSING_FILE = 16
const CONF_MFLAGS_DEFAULT_SECTION = 32

type CONF_VALUE struct {
	Section *c.Char
	Name    *c.Char
	Value   *c.Char
}
type StackStCONF_VALUE struct {
}

// clang-format off
//
// llgo:type C
type SkCONF_VALUECompfunc = func(_llcppg_param1 **CONF_VALUE, _llcppg_param2 **CONF_VALUE) c.Int

// clang-format off
//
// llgo:type C
type SkCONF_VALUEFreefunc = func(_llcppg_param1 *CONF_VALUE)

// clang-format off
//
// llgo:type C
type SkCONF_VALUECopyfunc = func(_llcppg_param1 *CONF_VALUE) *CONF_VALUE
type LhashStCONF_VALUE struct {
	Dummy LhCONF_VALUEDummy
}
type LhCONF_VALUEDummy struct {
	_xgo_union [1]uint64
}

// llgo:type C
type LhCONF_VALUECompfunc = func(_llcppg_param1 *CONF_VALUE, _llcppg_param2 *CONF_VALUE) c.Int

// llgo:type C
type LhCONF_VALUEHashfunc = func(_llcppg_param1 *CONF_VALUE) c.Ulong

// llgo:type C
type LhCONF_VALUEDoallfunc = func(_llcppg_param1 *CONF_VALUE)
type CONF_METHOD = ConfMethodSt
type ConfImoduleSt struct {
}

// Module definitions
type CONF_IMODULE = ConfImoduleSt
type ConfModuleSt struct {
}
type CONF_MODULE = ConfModuleSt
type StackStCONF_MODULE struct {
}
type StackStCONF_IMODULE struct {
}

// DSO module function typedefs
//
// llgo:type C
type ConfInitFunc = func(_llcppg_param1 *CONF_IMODULE, _llcppg_param2 *CONF) c.Int

// llgo:type C
type ConfFinishFunc = func(_llcppg_param1 *CONF_IMODULE)

func (p *LhCONF_VALUEDummy) XGof_ref_d1() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(p))
}
func (p *LhCONF_VALUEDummy) XGof_ref_d2() *c.Ulong {
	return (*c.Ulong)(unsafe.Pointer(p))
}
func (p *LhCONF_VALUEDummy) XGof_ref_d3() *c.Int {
	return (*c.Int)(unsafe.Pointer(p))
}

//go:linkname CONFSetDefaultMethod C.CONF_set_default_method
func CONFSetDefaultMethod(meth *CONF_METHOD) c.Int

//go:linkname CONFSetNconf C.CONF_set_nconf
func CONFSetNconf(conf *CONF, hash *LhashStCONF_VALUE)

//go:linkname CONFLoad C.CONF_load
func CONFLoad(conf *LhashStCONF_VALUE, file *c.Char, eline *c.Long) *LhashStCONF_VALUE

//go:linkname CONFLoadFp C.CONF_load_fp
func CONFLoadFp(conf *LhashStCONF_VALUE, fp *c.FILE, eline *c.Long) *LhashStCONF_VALUE

//go:linkname CONFLoadBio C.CONF_load_bio
func CONFLoadBio(conf *LhashStCONF_VALUE, bp *BIO, eline *c.Long) *LhashStCONF_VALUE

//go:linkname CONFGetSection C.CONF_get_section
func CONFGetSection(conf *LhashStCONF_VALUE, section *c.Char) *StackStCONF_VALUE

//go:linkname CONFGetString C.CONF_get_string
func CONFGetString(conf *LhashStCONF_VALUE, group *c.Char, name *c.Char) *c.Char

//go:linkname CONFGetNumber C.CONF_get_number
func CONFGetNumber(conf *LhashStCONF_VALUE, group *c.Char, name *c.Char) c.Long

//go:linkname CONFFree C.CONF_free
func CONFFree(conf *LhashStCONF_VALUE)

//go:linkname CONFDumpFp C.CONF_dump_fp
func CONFDumpFp(conf *LhashStCONF_VALUE, out *c.FILE) c.Int

//go:linkname CONFDumpBio C.CONF_dump_bio
func CONFDumpBio(conf *LhashStCONF_VALUE, out *BIO) c.Int

//go:linkname OPENSSLConfig C.OPENSSL_config
func OPENSSLConfig(config_name *c.Char)

// New conf code.  The semantics are different from the functions above. If
// that wasn't the case, the above functions would have been replaced
//
//go:linkname NCONFNewEx C.NCONF_new_ex
func NCONFNewEx(libctx *OSSL_LIB_CTX, meth *CONF_METHOD) *CONF

//go:linkname NCONFGet0Libctx C.NCONF_get0_libctx
func NCONFGet0Libctx(conf *CONF) *OSSL_LIB_CTX

//go:linkname NCONFNew C.NCONF_new
func NCONFNew(meth *CONF_METHOD) *CONF

//go:linkname NCONFDefault C.NCONF_default
func NCONFDefault() *CONF_METHOD

//go:linkname NCONF_WIN32 C.NCONF_WIN32
func NCONF_WIN32() *CONF_METHOD

//go:linkname NCONFFree C.NCONF_free
func NCONFFree(conf *CONF)

//go:linkname NCONFFreeData C.NCONF_free_data
func NCONFFreeData(conf *CONF)

//go:linkname NCONFLoad C.NCONF_load
func NCONFLoad(conf *CONF, file *c.Char, eline *c.Long) c.Int

//go:linkname NCONFLoadFp C.NCONF_load_fp
func NCONFLoadFp(conf *CONF, fp *c.FILE, eline *c.Long) c.Int

//go:linkname NCONFLoadBio C.NCONF_load_bio
func NCONFLoadBio(conf *CONF, bp *BIO, eline *c.Long) c.Int

//go:linkname NCONFGetSectionNames C.NCONF_get_section_names
func NCONFGetSectionNames(conf *CONF) *StackStOPENSSL_CSTRING

//go:linkname NCONFGetSection C.NCONF_get_section
func NCONFGetSection(conf *CONF, section *c.Char) *StackStCONF_VALUE

//go:linkname NCONFGetString C.NCONF_get_string
func NCONFGetString(conf *CONF, group *c.Char, name *c.Char) *c.Char

//go:linkname NCONFGetNumberE C.NCONF_get_number_e
func NCONFGetNumberE(conf *CONF, group *c.Char, name *c.Char, result *c.Long) c.Int

//go:linkname NCONFDumpFp C.NCONF_dump_fp
func NCONFDumpFp(conf *CONF, out *c.FILE) c.Int

//go:linkname NCONFDumpBio C.NCONF_dump_bio
func NCONFDumpBio(conf *CONF, out *BIO) c.Int

// Module functions
//
//go:linkname CONFModulesLoad C.CONF_modules_load
func CONFModulesLoad(cnf *CONF, appname *c.Char, flags c.Ulong) c.Int

//go:linkname CONFModulesLoadFileEx C.CONF_modules_load_file_ex
func CONFModulesLoadFileEx(libctx *OSSL_LIB_CTX, filename *c.Char, appname *c.Char, flags c.Ulong) c.Int

//go:linkname CONFModulesLoadFile C.CONF_modules_load_file
func CONFModulesLoadFile(filename *c.Char, appname *c.Char, flags c.Ulong) c.Int

//go:linkname CONFModulesUnload C.CONF_modules_unload
func CONFModulesUnload(all c.Int)

//go:linkname CONFModulesFinish C.CONF_modules_finish
func CONFModulesFinish()

//go:linkname CONFModuleAdd C.CONF_module_add
func CONFModuleAdd(name *c.Char, ifunc *ConfInitFunc, ffunc *ConfFinishFunc) c.Int

//go:linkname CONFImoduleGetName C.CONF_imodule_get_name
func CONFImoduleGetName(md *CONF_IMODULE) *c.Char

//go:linkname CONFImoduleGetValue C.CONF_imodule_get_value
func CONFImoduleGetValue(md *CONF_IMODULE) *c.Char

//go:linkname CONFImoduleGetUsrData C.CONF_imodule_get_usr_data
func CONFImoduleGetUsrData(md *CONF_IMODULE) unsafe.Pointer

//go:linkname CONFImoduleSetUsrData C.CONF_imodule_set_usr_data
func CONFImoduleSetUsrData(md *CONF_IMODULE, usr_data unsafe.Pointer)

//go:linkname CONFImoduleGetModule C.CONF_imodule_get_module
func CONFImoduleGetModule(md *CONF_IMODULE) *CONF_MODULE

//go:linkname CONFImoduleGetFlags C.CONF_imodule_get_flags
func CONFImoduleGetFlags(md *CONF_IMODULE) c.Ulong

//go:linkname CONFImoduleSetFlags C.CONF_imodule_set_flags
func CONFImoduleSetFlags(md *CONF_IMODULE, flags c.Ulong)

//go:linkname CONFModuleGetUsrData C.CONF_module_get_usr_data
func CONFModuleGetUsrData(pmod *CONF_MODULE) unsafe.Pointer

//go:linkname CONFModuleSetUsrData C.CONF_module_set_usr_data
func CONFModuleSetUsrData(pmod *CONF_MODULE, usr_data unsafe.Pointer)

//go:linkname CONFGet1DefaultConfigFile C.CONF_get1_default_config_file
func CONFGet1DefaultConfigFile() *c.Char

//go:linkname CONFParseList C.CONF_parse_list
func CONFParseList(list *c.Char, sep c.Int, nospc c.Int, list_cb func(_llcppg_param1 *c.Char, _llcppg_param2 c.Int, _llcppg_param3 unsafe.Pointer) c.Int, arg unsafe.Pointer) c.Int

//go:linkname OPENSSLLoadBuiltinModules C.OPENSSL_load_builtin_modules
func OPENSSLLoadBuiltinModules()
