// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

// clang-format on
type ConfSt struct {
	Meth         *CONF_METHOD
	MethData     unsafe.Pointer
	Data         *LhashStCONF_VALUE
	FlagDollarid c.Int
	FlagAbspath  c.Int
	Includedir   *c.Char
	Libctx       *OSSL_LIB_CTX
}

// The contents of this file are deprecated and will be made opaque
//
// llgo:type C
type ConfMethodSt struct {
	Name        *c.Char
	Create      func(_llcppg_param1 *CONF_METHOD) *CONF
	Init        func(_llcppg_param1 *CONF) c.Int
	Destroy     func(_llcppg_param1 *CONF) c.Int
	DestroyData func(_llcppg_param1 *CONF) c.Int
	LoadBio     func(_llcppg_param1 *CONF, _llcppg_param2 *BIO, _llcppg_param3 *c.Long) c.Int
	Dump        func(_llcppg_param1 *CONF, _llcppg_param2 *BIO) c.Int
	IsNumber    func(_llcppg_param1 *CONF, _llcppg_param2 c.Char) c.Int
	ToInt       func(_llcppg_param1 *CONF, _llcppg_param2 c.Char) c.Int
	Load        func(_llcppg_param1 *CONF, _llcppg_param2 *c.Char, _llcppg_param3 *c.Long) c.Int
}
