// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const OSSL_PARAM_INTEGER = 1
const OSSL_PARAM_UNSIGNED_INTEGER = 2
const OSSL_PARAM_REAL = 3
const OSSL_PARAM_UTF8_STRING = 4
const OSSL_PARAM_OCTET_STRING = 5
const OSSL_PARAM_UTF8_PTR = 6
const OSSL_PARAM_OCTET_PTR = 7

// Dispatch table element.  function_id numbers and the functions are defined
// in core_dispatch.h, see macros with 'OSSL_CORE_MAKE_FUNC' in their names.
//
// An array of these is always terminated by function_id == 0
//
// llgo:type C
type OsslDispatchSt struct {
	FunctionId c.Int
	Function   func()
}

// Other items, essentially an int<->pointer map element.
//
// We make this type distinct from OSSL_DISPATCH to ensure that dispatch
// tables remain tables with function pointers only.
//
// This is used whenever we need to pass things like a table of error reason
// codes <-> reason string maps, ...
//
// Usage determines which field works as key if any, rather than field order.
//
// An array of these is always terminated by id == 0 && ptr == NULL
type OsslItemSt struct {
	Id  c.Uint
	Ptr unsafe.Pointer
}

// Type to tie together algorithm names, property definition string and
// the algorithm implementation in the form of a dispatch table.
//
// An array of these is always terminated by algorithm_names == NULL
type OsslAlgorithmSt struct {
	AlgorithmNames       *c.Char
	PropertyDefinition   *c.Char
	Implementation       *OSSL_DISPATCH
	AlgorithmDescription *c.Char
}

// Type to pass object data in a uniform way, without exposing the object
// structure.
//
// An array of these is always terminated by key == NULL
type OsslParamSt struct {
	Key        *c.Char
	DataType   c.Uint
	Data       unsafe.Pointer
	DataSize   c.SizeT
	ReturnSize c.SizeT
}
type OsslCoreHandleSt struct {
}

// Opaque handles to be used with core upcall functions from providers
type OSSL_CORE_HANDLE = OsslCoreHandleSt
type OpensslCoreCtxSt struct {
}
type OPENSSL_CORE_CTX = OpensslCoreCtxSt
type OsslCoreBioSt struct {
}
type OSSL_CORE_BIO = OsslCoreBioSt

// Typedef for the thread stop handling callback. Used both internally and by
// providers.
//
// Providers may register for notifications about threads stopping by
// registering a callback to hear about such events. Providers register the
// callback using the OSSL_FUNC_CORE_THREAD_START function in the |in| dispatch
// table passed to OSSL_provider_init(). The arg passed back to a provider will
// be the provider side context object.
//
// llgo:type C
type OSSLThreadStopHandlerFn = func(_llcppg_param1 unsafe.Pointer)

// -
// Provider entry point
// --------------------
//
// This function is expected to be present in any dynamically loadable
// provider module.  By definition, if this function doesn't exist in a
// module, that module is not an OpenSSL provider module.
//
// -
// |handle|     pointer to opaque type OSSL_CORE_HANDLE.  This can be used
//              together with some functions passed via |in| to query data.
// |in|         is the array of functions that the Core passes to the provider.
// |out|        will be the array of base functions that the provider passes
//              back to the Core.
// |provctx|    a provider side context object, optionally created if the
//              provider needs it.  This value is passed to other provider
//              functions, notably other context constructors.
//
// llgo:type C
type OSSLProviderInitFn = func(_llcppg_param1 *OSSL_CORE_HANDLE, _llcppg_param2 *OSSL_DISPATCH, _llcppg_param3 **OSSL_DISPATCH, _llcppg_param4 *unsafe.Pointer) c.Int

// Generic callback function signature.
//
// The expectation is that any provider function that wants to offer
// a callback / hook can do so by taking an argument with this type,
// as well as a pointer to caller-specific data.  When calling the
// callback, the provider function can populate an OSSL_PARAM array
// with data of its choice and pass that in the callback call, along
// with the caller data argument.
//
// libcrypto may use the OSSL_PARAM array to create arguments for an
// application callback it knows about.
//
// llgo:type C
type OSSL_CALLBACK = func(_llcppg_param1 *OSSL_PARAM, _llcppg_param2 unsafe.Pointer) c.Int

// llgo:type C
type OSSL_INOUT_CALLBACK = func(_llcppg_param1 *OSSL_PARAM, _llcppg_param2 *OSSL_PARAM, _llcppg_param3 unsafe.Pointer) c.Int

// Passphrase callback function signature
//
// This is similar to the generic callback function above, but adds a
// result parameter.
//
// llgo:type C
type OSSL_PASSPHRASE_CALLBACK = func(_llcppg_param1 *c.Char, _llcppg_param2 c.SizeT, _llcppg_param3 *c.SizeT, _llcppg_param4 *OSSL_PARAM, _llcppg_param5 unsafe.Pointer) c.Int

//go:linkname OSSLProviderInit C.OSSL_provider_init
func OSSLProviderInit(_llcppg_param1 *OSSL_CORE_HANDLE, _llcppg_param2 *OSSL_DISPATCH, _llcppg_param3 **OSSL_DISPATCH, _llcppg_param4 *unsafe.Pointer) c.Int
