// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const SCT_MIN_RSA_BITS = 2048
const CT_V1_HASHLEN = 32

// clang-format on
type CtLogEntryTypeT c.Int

const (
	CT_LOG_ENTRY_TYPE_NOT_SET CtLogEntryTypeT = -1
	CT_LOG_ENTRY_TYPE_X509    CtLogEntryTypeT = 0
	CT_LOG_ENTRY_TYPE_PRECERT CtLogEntryTypeT = 1
)

type SctVersionT c.Int

const (
	SCT_VERSION_NOT_SET SctVersionT = -1
	SCT_VERSION_V1      SctVersionT = 0
)

type SctSourceT c.Uint

const (
	SCT_SOURCE_UNKNOWN               SctSourceT = 0
	SCT_SOURCE_TLS_EXTENSION         SctSourceT = 1
	SCT_SOURCE_X509V3_EXTENSION      SctSourceT = 2
	SCT_SOURCE_OCSP_STAPLED_RESPONSE SctSourceT = 3
)

type SctValidationStatusT c.Uint

const (
	SCT_VALIDATION_STATUS_NOT_SET         SctValidationStatusT = 0
	SCT_VALIDATION_STATUS_UNKNOWN_LOG     SctValidationStatusT = 1
	SCT_VALIDATION_STATUS_VALID           SctValidationStatusT = 2
	SCT_VALIDATION_STATUS_INVALID         SctValidationStatusT = 3
	SCT_VALIDATION_STATUS_UNVERIFIED      SctValidationStatusT = 4
	SCT_VALIDATION_STATUS_UNKNOWN_VERSION SctValidationStatusT = 5
)

type StackStSCT struct {
}

// clang-format off
//
// llgo:type C
type SkSCTCompfunc = func(_llcppg_param1 **SCT, _llcppg_param2 **SCT) c.Int

// clang-format off
//
// llgo:type C
type SkSCTFreefunc = func(_llcppg_param1 *SCT)

// clang-format off
//
// llgo:type C
type SkSCTCopyfunc = func(_llcppg_param1 *SCT) *SCT
type StackStCTLOG struct {
}

// llgo:type C
type SkCTLOGCompfunc = func(_llcppg_param1 **CTLOG, _llcppg_param2 **CTLOG) c.Int

// llgo:type C
type SkCTLOGFreefunc = func(_llcppg_param1 *CTLOG)

// llgo:type C
type SkCTLOGCopyfunc = func(_llcppg_param1 *CTLOG) *CTLOG

// Creates a new, empty policy evaluation context associated with the given
// library context and property query string.
// The caller is responsible for calling CT_POLICY_EVAL_CTX_free when finished
// with the CT_POLICY_EVAL_CTX.
//
//go:linkname CT_POLICY_EVAL_CTXNewEx C.CT_POLICY_EVAL_CTX_new_ex
func CT_POLICY_EVAL_CTXNewEx(libctx *OSSL_LIB_CTX, propq *c.Char) *CT_POLICY_EVAL_CTX

// The same as CT_POLICY_EVAL_CTX_new_ex() but the default library
// context and property query string is used.
//
//go:linkname CT_POLICY_EVAL_CTXNew C.CT_POLICY_EVAL_CTX_new
func CT_POLICY_EVAL_CTXNew() *CT_POLICY_EVAL_CTX

// Deletes a policy evaluation context and anything it owns.
//
//go:linkname CT_POLICY_EVAL_CTXFree C.CT_POLICY_EVAL_CTX_free
func CT_POLICY_EVAL_CTXFree(ctx *CT_POLICY_EVAL_CTX)

// Gets the peer certificate that the SCTs are for
//
//go:linkname CT_POLICY_EVAL_CTXGet0Cert C.CT_POLICY_EVAL_CTX_get0_cert
func CT_POLICY_EVAL_CTXGet0Cert(ctx *CT_POLICY_EVAL_CTX) *X509

// Sets the certificate associated with the received SCTs.
// Increments the reference count of cert.
// Returns 1 on success, 0 otherwise.
//
//go:linkname CT_POLICY_EVAL_CTXSet1Cert C.CT_POLICY_EVAL_CTX_set1_cert
func CT_POLICY_EVAL_CTXSet1Cert(ctx *CT_POLICY_EVAL_CTX, cert *X509) c.Int

// Gets the issuer of the aforementioned certificate
//
//go:linkname CT_POLICY_EVAL_CTXGet0Issuer C.CT_POLICY_EVAL_CTX_get0_issuer
func CT_POLICY_EVAL_CTXGet0Issuer(ctx *CT_POLICY_EVAL_CTX) *X509

// Sets the issuer of the certificate associated with the received SCTs.
// Increments the reference count of issuer.
// Returns 1 on success, 0 otherwise.
//
//go:linkname CT_POLICY_EVAL_CTXSet1Issuer C.CT_POLICY_EVAL_CTX_set1_issuer
func CT_POLICY_EVAL_CTXSet1Issuer(ctx *CT_POLICY_EVAL_CTX, issuer *X509) c.Int

// Gets the CT logs that are trusted sources of SCTs
//
//go:linkname CT_POLICY_EVAL_CTXGet0LogStore C.CT_POLICY_EVAL_CTX_get0_log_store
func CT_POLICY_EVAL_CTXGet0LogStore(ctx *CT_POLICY_EVAL_CTX) *CTLOG_STORE

// Sets the log store that is in use. It must outlive the CT_POLICY_EVAL_CTX.
//
//go:linkname CT_POLICY_EVAL_CTXSetSharedCTLOG_STORE C.CT_POLICY_EVAL_CTX_set_shared_CTLOG_STORE
func CT_POLICY_EVAL_CTXSetSharedCTLOG_STORE(ctx *CT_POLICY_EVAL_CTX, log_store *CTLOG_STORE)

// Gets the time, in milliseconds since the Unix epoch, that will be used as the
// current time when checking whether an SCT was issued in the future.
// Such SCTs will fail validation, as required by RFC6962.
//
//go:linkname CT_POLICY_EVAL_CTXGetTime C.CT_POLICY_EVAL_CTX_get_time
func CT_POLICY_EVAL_CTXGetTime(ctx *CT_POLICY_EVAL_CTX) c.Uint64T

// Sets the time to evaluate SCTs against, in milliseconds since the Unix epoch.
// If an SCT's timestamp is after this time, it will be interpreted as having
// been issued in the future. RFC6962 states that "TLS clients MUST reject SCTs
// whose timestamp is in the future", so an SCT will not validate in this case.
//
//go:linkname CT_POLICY_EVAL_CTXSetTime C.CT_POLICY_EVAL_CTX_set_time
func CT_POLICY_EVAL_CTXSetTime(ctx *CT_POLICY_EVAL_CTX, time_in_ms c.Uint64T)

// Creates a new, blank SCT.
// The caller is responsible for calling SCT_free when finished with the SCT.
//
//go:linkname SCTNew C.SCT_new
func SCTNew() *SCT

// Creates a new SCT from some base64-encoded strings.
// The caller is responsible for calling SCT_free when finished with the SCT.
//
//go:linkname SCTNewFromBase64 C.SCT_new_from_base64
func SCTNewFromBase64(version uint8, logid_base64 *c.Char, entry_type CtLogEntryTypeT, timestamp c.Uint64T, extensions_base64 *c.Char, signature_base64 *c.Char) *SCT

// Frees the SCT and the underlying data structures.
//
//go:linkname SCTFree C.SCT_free
func SCTFree(sct *SCT)

// Free a stack of SCTs, and the underlying SCTs themselves.
// Intended to be compatible with X509V3_EXT_FREE.
//
//go:linkname SCT_LISTFree C.SCT_LIST_free
func SCT_LISTFree(a *StackStSCT)

// Returns the version of the SCT.
//
//go:linkname SCTGetVersion C.SCT_get_version
func SCTGetVersion(sct *SCT) SctVersionT

// Set the version of an SCT.
// Returns 1 on success, 0 if the version is unrecognized.
//
//go:linkname SCTSetVersion C.SCT_set_version
func SCTSetVersion(sct *SCT, version SctVersionT) c.Int

// Returns the log entry type of the SCT.
//
//go:linkname SCTGetLogEntryType C.SCT_get_log_entry_type
func SCTGetLogEntryType(sct *SCT) CtLogEntryTypeT

// Set the log entry type of an SCT.
// Returns 1 on success, 0 otherwise.
//
//go:linkname SCTSetLogEntryType C.SCT_set_log_entry_type
func SCTSetLogEntryType(sct *SCT, entry_type CtLogEntryTypeT) c.Int

// Gets the ID of the log that an SCT came from.
// Ownership of the log ID remains with the SCT.
// Returns the length of the log ID.
//
//go:linkname SCTGet0LogId C.SCT_get0_log_id
func SCTGet0LogId(sct *SCT, log_id **uint8) c.SizeT

// Set the log ID of an SCT to point directly to the *log_id specified.
// The SCT takes ownership of the specified pointer.
// Returns 1 on success, 0 otherwise.
//
//go:linkname SCTSet0LogId C.SCT_set0_log_id
func SCTSet0LogId(sct *SCT, log_id *uint8, log_id_len c.SizeT) c.Int

// Set the log ID of an SCT.
// This makes a copy of the log_id.
// Returns 1 on success, 0 otherwise.
//
//go:linkname SCTSet1LogId C.SCT_set1_log_id
func SCTSet1LogId(sct *SCT, log_id *uint8, log_id_len c.SizeT) c.Int

// Returns the timestamp for the SCT (epoch time in milliseconds).
//
//go:linkname SCTGetTimestamp C.SCT_get_timestamp
func SCTGetTimestamp(sct *SCT) c.Uint64T

// Set the timestamp of an SCT (epoch time in milliseconds).
//
//go:linkname SCTSetTimestamp C.SCT_set_timestamp
func SCTSetTimestamp(sct *SCT, timestamp c.Uint64T)

// Return the NID for the signature used by the SCT.
// For CT v1, this will be either NID_sha256WithRSAEncryption or
// NID_ecdsa_with_SHA256 (or NID_undef if incorrect/unset).
//
//go:linkname SCTGetSignatureNid C.SCT_get_signature_nid
func SCTGetSignatureNid(sct *SCT) c.Int

// Set the signature type of an SCT
// For CT v1, this should be either NID_sha256WithRSAEncryption or
// NID_ecdsa_with_SHA256.
// Returns 1 on success, 0 otherwise.
//
//go:linkname SCTSetSignatureNid C.SCT_set_signature_nid
func SCTSetSignatureNid(sct *SCT, nid c.Int) c.Int

// Set *ext to point to the extension data for the SCT. ext must not be NULL.
// The SCT retains ownership of this pointer.
// Returns length of the data pointed to.
//
//go:linkname SCTGet0Extensions C.SCT_get0_extensions
func SCTGet0Extensions(sct *SCT, ext **uint8) c.SizeT

// Set the extensions of an SCT to point directly to the *ext specified.
// The SCT takes ownership of the specified pointer.
//
//go:linkname SCTSet0Extensions C.SCT_set0_extensions
func SCTSet0Extensions(sct *SCT, ext *uint8, ext_len c.SizeT)

// Set the extensions of an SCT.
// This takes a copy of the ext.
// Returns 1 on success, 0 otherwise.
//
//go:linkname SCTSet1Extensions C.SCT_set1_extensions
func SCTSet1Extensions(sct *SCT, ext *uint8, ext_len c.SizeT) c.Int

// Set *sig to point to the signature for the SCT. sig must not be NULL.
// The SCT retains ownership of this pointer.
// Returns length of the data pointed to.
//
//go:linkname SCTGet0Signature C.SCT_get0_signature
func SCTGet0Signature(sct *SCT, sig **uint8) c.SizeT

// Set the signature of an SCT to point directly to the *sig specified.
// The SCT takes ownership of the specified pointer.
//
//go:linkname SCTSet0Signature C.SCT_set0_signature
func SCTSet0Signature(sct *SCT, sig *uint8, sig_len c.SizeT)

// Set the signature of an SCT to be a copy of the *sig specified.
// Returns 1 on success, 0 otherwise.
//
//go:linkname SCTSet1Signature C.SCT_set1_signature
func SCTSet1Signature(sct *SCT, sig *uint8, sig_len c.SizeT) c.Int

// The origin of this SCT, e.g. TLS extension, OCSP response, etc.
//
//go:linkname SCTGetSource C.SCT_get_source
func SCTGetSource(sct *SCT) SctSourceT

// Set the origin of this SCT, e.g. TLS extension, OCSP response, etc.
// Returns 1 on success, 0 otherwise.
//
//go:linkname SCTSetSource C.SCT_set_source
func SCTSetSource(sct *SCT, source SctSourceT) c.Int

// Returns a text string describing the validation status of |sct|.
//
//go:linkname SCTValidationStatusString C.SCT_validation_status_string
func SCTValidationStatusString(sct *SCT) *c.Char

// Pretty-prints an |sct| to |out|.
// It will be indented by the number of spaces specified by |indent|.
// If |logs| is not NULL, it will be used to lookup the CT log that the SCT came
// from, so that the log name can be printed.
//
//go:linkname SCTPrint C.SCT_print
func SCTPrint(sct *SCT, out *BIO, indent c.Int, logs *CTLOG_STORE)

// Pretty-prints an |sct_list| to |out|.
// It will be indented by the number of spaces specified by |indent|.
// SCTs will be delimited by |separator|.
// If |logs| is not NULL, it will be used to lookup the CT log that each SCT
// came from, so that the log names can be printed.
//
//go:linkname SCT_LISTPrint C.SCT_LIST_print
func SCT_LISTPrint(sct_list *StackStSCT, out *BIO, indent c.Int, separator *c.Char, logs *CTLOG_STORE)

// Gets the last result of validating this SCT.
// If it has not been validated yet, returns SCT_VALIDATION_STATUS_NOT_SET.
//
//go:linkname SCTGetValidationStatus C.SCT_get_validation_status
func SCTGetValidationStatus(sct *SCT) SctValidationStatusT

// Validates the given SCT with the provided context.
// Sets the "validation_status" field of the SCT.
// Returns 1 if the SCT is valid and the signature verifies.
// Returns 0 if the SCT is invalid or could not be verified.
// Returns -1 if an error occurs.
//
//go:linkname SCTValidate C.SCT_validate
func SCTValidate(sct *SCT, ctx *CT_POLICY_EVAL_CTX) c.Int

// Validates the given list of SCTs with the provided context.
// Sets the "validation_status" field of each SCT.
// Returns 1 if there are no invalid SCTs and all signatures verify.
// Returns 0 if at least one SCT is invalid or could not be verified.
// Returns a negative integer if an error occurs.
//
//go:linkname SCT_LISTValidate C.SCT_LIST_validate
func SCT_LISTValidate(scts *StackStSCT, ctx *CT_POLICY_EVAL_CTX) c.Int

// Serialize (to TLS format) a stack of SCTs and return the length.
// "a" must not be NULL.
// If "pp" is NULL, just return the length of what would have been serialized.
// If "pp" is not NULL and "*pp" is null, function will allocate a new pointer
// for data that caller is responsible for freeing (only if function returns
// successfully).
// If "pp" is NULL and "*pp" is not NULL, caller is responsible for ensuring
// that "*pp" is large enough to accept all of the serialized data.
// Returns < 0 on error, >= 0 indicating bytes written (or would have been)
// on success.
//
//go:linkname I2oSCT_LIST C.i2o_SCT_LIST
func I2oSCT_LIST(a *StackStSCT, pp **uint8) c.Int

// Convert TLS format SCT list to a stack of SCTs.
// If "a" or "*a" is NULL, a new stack will be created that the caller is
// responsible for freeing (by calling SCT_LIST_free).
// "**pp" and "*pp" must not be NULL.
// Upon success, "*pp" will point to after the last bytes read, and a stack
// will be returned.
// Upon failure, a NULL pointer will be returned, and the position of "*pp" is
// not defined.
//
//go:linkname O2iSCT_LIST C.o2i_SCT_LIST
func O2iSCT_LIST(a **StackStSCT, pp **uint8, len c.SizeT) *StackStSCT

// Serialize (to DER format) a stack of SCTs and return the length.
// "a" must not be NULL.
// If "pp" is NULL, just returns the length of what would have been serialized.
// If "pp" is not NULL and "*pp" is null, function will allocate a new pointer
// for data that caller is responsible for freeing (only if function returns
// successfully).
// If "pp" is NULL and "*pp" is not NULL, caller is responsible for ensuring
// that "*pp" is large enough to accept all of the serialized data.
// Returns < 0 on error, >= 0 indicating bytes written (or would have been)
// on success.
//
//go:linkname I2dSCT_LIST C.i2d_SCT_LIST
func I2dSCT_LIST(a *StackStSCT, pp **uint8) c.Int

// Parses an SCT list in DER format and returns it.
// If "a" or "*a" is NULL, a new stack will be created that the caller is
// responsible for freeing (by calling SCT_LIST_free).
// "**pp" and "*pp" must not be NULL.
// Upon success, "*pp" will point to after the last bytes read, and a stack
// will be returned.
// Upon failure, a NULL pointer will be returned, and the position of "*pp" is
// not defined.
//
//go:linkname D2iSCT_LIST C.d2i_SCT_LIST
func D2iSCT_LIST(a **StackStSCT, pp **uint8, len c.Long) *StackStSCT

// Serialize (to TLS format) an |sct| and write it to |out|.
// If |out| is null, no SCT will be output but the length will still be returned.
// If |out| points to a null pointer, a string will be allocated to hold the
// TLS-format SCT. It is the responsibility of the caller to free it.
// If |out| points to an allocated string, the TLS-format SCT will be written
// to it.
// The length of the SCT in TLS format will be returned.
//
//go:linkname I2oSCT C.i2o_SCT
func I2oSCT(sct *SCT, out **uint8) c.Int

// Parses an SCT in TLS format and returns it.
// If |psct| is not null, it will end up pointing to the parsed SCT. If it
// already points to a non-null pointer, the pointer will be free'd.
// |in| should be a pointer to a string containing the TLS-format SCT.
// |in| will be advanced to the end of the SCT if parsing succeeds.
// |len| should be the length of the SCT in |in|.
// Returns NULL if an error occurs.
// If the SCT is an unsupported version, only the SCT's 'sct' and 'sct_len'
// fields will be populated (with |in| and |len| respectively).
//
//go:linkname O2iSCT C.o2i_SCT
func O2iSCT(psct **SCT, in **uint8, len c.SizeT) *SCT

// Creates a new CT log instance with the given |public_key| and |name| and
// associates it with the give library context |libctx| and property query
// string |propq|.
// Takes ownership of |public_key| but copies |name|.
// Returns NULL if malloc fails or if |public_key| cannot be converted to DER.
// Should be deleted by the caller using CTLOG_free when no longer needed.
//
//go:linkname CTLOGNewEx C.CTLOG_new_ex
func CTLOGNewEx(public_key *EVP_PKEY, name *c.Char, libctx *OSSL_LIB_CTX, propq *c.Char) *CTLOG

// The same as CTLOG_new_ex except that the default library context and
// property query string are used.
//
//go:linkname CTLOGNew C.CTLOG_new
func CTLOGNew(public_key *EVP_PKEY, name *c.Char) *CTLOG

// Creates a new CTLOG instance with the base64-encoded SubjectPublicKeyInfo DER
// in |pkey_base64| and associated with the given library context |libctx| and
// property query string |propq|. The |name| is a string to help users identify
// this log.
// Returns 1 on success, 0 on failure.
// Should be deleted by the caller using CTLOG_free when no longer needed.
//
//go:linkname CTLOGNewFromBase64Ex C.CTLOG_new_from_base64_ex
func CTLOGNewFromBase64Ex(ct_log **CTLOG, pkey_base64 *c.Char, name *c.Char, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

// The same as CTLOG_new_from_base64_ex() except that the default
// library context and property query string are used.
// Returns 1 on success, 0 on failure.
//
//go:linkname CTLOGNewFromBase64 C.CTLOG_new_from_base64
func CTLOGNewFromBase64(ct_log **CTLOG, pkey_base64 *c.Char, name *c.Char) c.Int

// Deletes a CT log instance and its fields.
//
//go:linkname CTLOGFree C.CTLOG_free
func CTLOGFree(log *CTLOG)

// Gets the name of the CT log
//
//go:linkname CTLOGGet0Name C.CTLOG_get0_name
func CTLOGGet0Name(log *CTLOG) *c.Char

// Gets the ID of the CT log
//
//go:linkname CTLOGGet0LogId C.CTLOG_get0_log_id
func CTLOGGet0LogId(log *CTLOG, log_id **c.Uint8T, log_id_len *c.SizeT)

// Gets the public key of the CT log
//
//go:linkname CTLOGGet0PublicKey C.CTLOG_get0_public_key
func CTLOGGet0PublicKey(log *CTLOG) *EVP_PKEY

// Creates a new CT log store and associates it with the given libctx and
// property query string.
// Should be deleted by the caller using CTLOG_STORE_free when no longer needed.
//
//go:linkname CTLOG_STORENewEx C.CTLOG_STORE_new_ex
func CTLOG_STORENewEx(libctx *OSSL_LIB_CTX, propq *c.Char) *CTLOG_STORE

// Same as CTLOG_STORE_new_ex except that the default libctx and
// property query string are used.
// Should be deleted by the caller using CTLOG_STORE_free when no longer needed.
//
//go:linkname CTLOG_STORENew C.CTLOG_STORE_new
func CTLOG_STORENew() *CTLOG_STORE

// Deletes a CT log store and all of the CT log instances held within.
//
//go:linkname CTLOG_STOREFree C.CTLOG_STORE_free
func CTLOG_STOREFree(store *CTLOG_STORE)

// Finds a CT log in the store based on its log ID.
// Returns the CT log, or NULL if no match is found.
//
//go:linkname CTLOG_STOREGet0LogById C.CTLOG_STORE_get0_log_by_id
func CTLOG_STOREGet0LogById(store *CTLOG_STORE, log_id *c.Uint8T, log_id_len c.SizeT) *CTLOG

// Loads a CT log list into a |store| from a |file|.
// Returns 1 if loading is successful, or 0 otherwise.
//
//go:linkname CTLOG_STORELoadFile C.CTLOG_STORE_load_file
func CTLOG_STORELoadFile(store *CTLOG_STORE, file *c.Char) c.Int

// Loads the default CT log list into a |store|.
// Returns 1 if loading is successful, or 0 otherwise.
//
//go:linkname CTLOG_STORELoadDefaultFile C.CTLOG_STORE_load_default_file
func CTLOG_STORELoadDefaultFile(store *CTLOG_STORE) c.Int
