// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const DH_PARAMGEN_TYPE_GENERATOR = 0
const DH_PARAMGEN_TYPE_FIPS_186_2 = 1
const DH_PARAMGEN_TYPE_FIPS_186_4 = 2
const DH_PARAMGEN_TYPE_GROUP = 3
const EVP_PKEY_CTRL_DH_PARAMGEN_PRIME_LEN = 4097
const EVP_PKEY_CTRL_DH_PARAMGEN_GENERATOR = 4098
const EVP_PKEY_CTRL_DH_RFC5114 = 4099
const EVP_PKEY_CTRL_DH_PARAMGEN_SUBPRIME_LEN = 4100
const EVP_PKEY_CTRL_DH_PARAMGEN_TYPE = 4101
const EVP_PKEY_CTRL_DH_KDF_TYPE = 4102
const EVP_PKEY_CTRL_DH_KDF_MD = 4103
const EVP_PKEY_CTRL_GET_DH_KDF_MD = 4104
const EVP_PKEY_CTRL_DH_KDF_OUTLEN = 4105
const EVP_PKEY_CTRL_GET_DH_KDF_OUTLEN = 4106
const EVP_PKEY_CTRL_DH_KDF_UKM = 4107
const EVP_PKEY_CTRL_GET_DH_KDF_UKM = 4108
const EVP_PKEY_CTRL_DH_KDF_OID = 4109
const EVP_PKEY_CTRL_GET_DH_KDF_OID = 4110
const EVP_PKEY_CTRL_DH_NID = 4111
const EVP_PKEY_CTRL_DH_PAD = 4112
const EVP_PKEY_DH_KDF_NONE = 1
const EVP_PKEY_DH_KDF_X9_42 = 2
const OPENSSL_DH_MAX_MODULUS_BITS = 10000
const OPENSSL_DH_CHECK_MAX_MODULUS_BITS = 32768
const OPENSSL_DH_FIPS_MIN_MODULUS_BITS = 1024
const DH_FLAG_CACHE_MONT_P = 1
const DH_FLAG_TYPE_MASK = 61440
const DH_FLAG_TYPE_DH = 0
const DH_FLAG_TYPE_DHX = 4096
const DH_FLAG_NO_EXP_CONSTTIME = 0
const DH_FLAG_FIPS_METHOD = 1024
const DH_FLAG_NON_FIPS_ALLOW = 1024
const DH_GENERATOR_2 = 2
const DH_GENERATOR_3 = 3
const DH_GENERATOR_5 = 5
const DH_CHECK_P_NOT_PRIME = 1
const DH_CHECK_P_NOT_SAFE_PRIME = 2
const DH_UNABLE_TO_CHECK_GENERATOR = 4
const DH_NOT_SUITABLE_GENERATOR = 8
const DH_CHECK_Q_NOT_PRIME = 16
const DH_CHECK_INVALID_Q_VALUE = 32
const DH_CHECK_INVALID_J_VALUE = 64
const DH_MODULUS_TOO_SMALL = 128
const DH_MODULUS_TOO_LARGE = 256
const DH_CHECK_PUBKEY_TOO_SMALL = 1
const DH_CHECK_PUBKEY_TOO_LARGE = 2
const DH_CHECK_PUBKEY_INVALID = 4
const DH_CHECK_P_NOT_STRONG_PRIME = 2

//go:linkname EVP_PKEY_CTXSetDhParamgenType C.EVP_PKEY_CTX_set_dh_paramgen_type
func EVP_PKEY_CTXSetDhParamgenType(ctx *EVP_PKEY_CTX, typ c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetDhParamgenGindex C.EVP_PKEY_CTX_set_dh_paramgen_gindex
func EVP_PKEY_CTXSetDhParamgenGindex(ctx *EVP_PKEY_CTX, gindex c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetDhParamgenSeed C.EVP_PKEY_CTX_set_dh_paramgen_seed
func EVP_PKEY_CTXSetDhParamgenSeed(ctx *EVP_PKEY_CTX, seed *uint8, seedlen c.SizeT) c.Int

//go:linkname EVP_PKEY_CTXSetDhParamgenPrimeLen C.EVP_PKEY_CTX_set_dh_paramgen_prime_len
func EVP_PKEY_CTXSetDhParamgenPrimeLen(ctx *EVP_PKEY_CTX, pbits c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetDhParamgenSubprimeLen C.EVP_PKEY_CTX_set_dh_paramgen_subprime_len
func EVP_PKEY_CTXSetDhParamgenSubprimeLen(ctx *EVP_PKEY_CTX, qlen c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetDhParamgenGenerator C.EVP_PKEY_CTX_set_dh_paramgen_generator
func EVP_PKEY_CTXSetDhParamgenGenerator(ctx *EVP_PKEY_CTX, gen c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetDhNid C.EVP_PKEY_CTX_set_dh_nid
func EVP_PKEY_CTXSetDhNid(ctx *EVP_PKEY_CTX, nid c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetDhRfc5114 C.EVP_PKEY_CTX_set_dh_rfc5114
func EVP_PKEY_CTXSetDhRfc5114(ctx *EVP_PKEY_CTX, gen c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetDhxRfc5114 C.EVP_PKEY_CTX_set_dhx_rfc5114
func EVP_PKEY_CTXSetDhxRfc5114(ctx *EVP_PKEY_CTX, gen c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetDhPad C.EVP_PKEY_CTX_set_dh_pad
func EVP_PKEY_CTXSetDhPad(ctx *EVP_PKEY_CTX, pad c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetDhKdfType C.EVP_PKEY_CTX_set_dh_kdf_type
func EVP_PKEY_CTXSetDhKdfType(ctx *EVP_PKEY_CTX, kdf c.Int) c.Int

//go:linkname EVP_PKEY_CTXGetDhKdfType C.EVP_PKEY_CTX_get_dh_kdf_type
func EVP_PKEY_CTXGetDhKdfType(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEY_CTXSet0DhKdfOid C.EVP_PKEY_CTX_set0_dh_kdf_oid
func EVP_PKEY_CTXSet0DhKdfOid(ctx *EVP_PKEY_CTX, oid *ASN1_OBJECT) c.Int

//go:linkname EVP_PKEY_CTXGet0DhKdfOid C.EVP_PKEY_CTX_get0_dh_kdf_oid
func EVP_PKEY_CTXGet0DhKdfOid(ctx *EVP_PKEY_CTX, oid **ASN1_OBJECT) c.Int

//go:linkname EVP_PKEY_CTXSetDhKdfMd C.EVP_PKEY_CTX_set_dh_kdf_md
func EVP_PKEY_CTXSetDhKdfMd(ctx *EVP_PKEY_CTX, md *EVP_MD) c.Int

//go:linkname EVP_PKEY_CTXGetDhKdfMd C.EVP_PKEY_CTX_get_dh_kdf_md
func EVP_PKEY_CTXGetDhKdfMd(ctx *EVP_PKEY_CTX, md **EVP_MD) c.Int

//go:linkname EVP_PKEY_CTXSetDhKdfOutlen C.EVP_PKEY_CTX_set_dh_kdf_outlen
func EVP_PKEY_CTXSetDhKdfOutlen(ctx *EVP_PKEY_CTX, len c.Int) c.Int

//go:linkname EVP_PKEY_CTXGetDhKdfOutlen C.EVP_PKEY_CTX_get_dh_kdf_outlen
func EVP_PKEY_CTXGetDhKdfOutlen(ctx *EVP_PKEY_CTX, len *c.Int) c.Int

//go:linkname EVP_PKEY_CTXSet0DhKdfUkm C.EVP_PKEY_CTX_set0_dh_kdf_ukm
func EVP_PKEY_CTXSet0DhKdfUkm(ctx *EVP_PKEY_CTX, ukm *uint8, len c.Int) c.Int

//go:linkname EVP_PKEY_CTXGet0DhKdfUkm C.EVP_PKEY_CTX_get0_dh_kdf_ukm
func EVP_PKEY_CTXGet0DhKdfUkm(ctx *EVP_PKEY_CTX, ukm **uint8) c.Int

// Already defined in ossl_typ.h
// typedef struct dh_st DH;
// typedef struct dh_method DH_METHOD;
//
//go:linkname DHparamsIt C.DHparams_it
func DHparamsIt() *ASN1_ITEM

//go:linkname DHparamsDup C.DHparams_dup
func DHparamsDup(a *DH) *DH

//go:linkname DH_OpenSSL C.DH_OpenSSL
func DH_OpenSSL() *DH_METHOD

//go:linkname DHSetDefaultMethod C.DH_set_default_method
func DHSetDefaultMethod(meth *DH_METHOD)

//go:linkname DHGetDefaultMethod C.DH_get_default_method
func DHGetDefaultMethod() *DH_METHOD

//go:linkname DHSetMethod C.DH_set_method
func DHSetMethod(dh *DH, meth *DH_METHOD) c.Int

//go:linkname DHNewMethod C.DH_new_method
func DHNewMethod(engine *ENGINE) *DH

//go:linkname DHNew C.DH_new
func DHNew() *DH

//go:linkname DHFree C.DH_free
func DHFree(dh *DH)

//go:linkname DHUpRef C.DH_up_ref
func DHUpRef(dh *DH) c.Int

//go:linkname DHBits C.DH_bits
func DHBits(dh *DH) c.Int

//go:linkname DHSize C.DH_size
func DHSize(dh *DH) c.Int

//go:linkname DHSecurityBits C.DH_security_bits
func DHSecurityBits(dh *DH) c.Int

//go:linkname DHSetExData C.DH_set_ex_data
func DHSetExData(d *DH, idx c.Int, arg unsafe.Pointer) c.Int

//go:linkname DHGetExData C.DH_get_ex_data
func DHGetExData(d *DH, idx c.Int) unsafe.Pointer

//go:linkname DHGenerateParametersEx C.DH_generate_parameters_ex
func DHGenerateParametersEx(dh *DH, prime_len c.Int, generator c.Int, cb *BN_GENCB) c.Int

//go:linkname DHCheckParamsEx C.DH_check_params_ex
func DHCheckParamsEx(dh *DH) c.Int

//go:linkname DHCheckEx C.DH_check_ex
func DHCheckEx(dh *DH) c.Int

//go:linkname DHCheckPubKeyEx C.DH_check_pub_key_ex
func DHCheckPubKeyEx(dh *DH, pub_key *BIGNUM) c.Int

//go:linkname DHCheckParams C.DH_check_params
func DHCheckParams(dh *DH, ret *c.Int) c.Int

//go:linkname DHCheck C.DH_check
func DHCheck(dh *DH, codes *c.Int) c.Int

//go:linkname DHCheckPubKey C.DH_check_pub_key
func DHCheckPubKey(dh *DH, pub_key *BIGNUM, codes *c.Int) c.Int

//go:linkname DHGenerateKey C.DH_generate_key
func DHGenerateKey(dh *DH) c.Int

//go:linkname DHComputeKey C.DH_compute_key
func DHComputeKey(key *uint8, pub_key *BIGNUM, dh *DH) c.Int

//go:linkname DHComputeKeyPadded C.DH_compute_key_padded
func DHComputeKeyPadded(key *uint8, pub_key *BIGNUM, dh *DH) c.Int

//go:linkname D2iDHparams C.d2i_DHparams
func D2iDHparams(a **DH, in **uint8, len c.Long) *DH

//go:linkname I2dDHparams C.i2d_DHparams
func I2dDHparams(a *DH, out **uint8) c.Int

//go:linkname D2iDHxparams C.d2i_DHxparams
func D2iDHxparams(a **DH, in **uint8, len c.Long) *DH

//go:linkname I2dDHxparams C.i2d_DHxparams
func I2dDHxparams(a *DH, out **uint8) c.Int

//go:linkname DHparamsPrintFp C.DHparams_print_fp
func DHparamsPrintFp(fp *c.FILE, x *DH) c.Int

//go:linkname DHparamsPrint C.DHparams_print
func DHparamsPrint(bp *BIO, x *DH) c.Int

// RFC 5114 parameters
//
//go:linkname DHGet1024160 C.DH_get_1024_160
func DHGet1024160() *DH

//go:linkname DHGet2048224 C.DH_get_2048_224
func DHGet2048224() *DH

//go:linkname DHGet2048256 C.DH_get_2048_256
func DHGet2048256() *DH

// Named parameters, currently RFC7919 and RFC3526
//
//go:linkname DHNewByNid C.DH_new_by_nid
func DHNewByNid(nid c.Int) *DH

//go:linkname DHGetNid C.DH_get_nid
func DHGetNid(dh *DH) c.Int

// RFC2631 KDF
//
//go:linkname DH_KDF_X9_42 C.DH_KDF_X9_42
func DH_KDF_X9_42(out *uint8, outlen c.SizeT, Z *uint8, Zlen c.SizeT, key_oid *ASN1_OBJECT, ukm *uint8, ukmlen c.SizeT, md *EVP_MD) c.Int

//go:linkname DHGet0Pqg C.DH_get0_pqg
func DHGet0Pqg(dh *DH, p **BIGNUM, q **BIGNUM, g **BIGNUM)

//go:linkname DHSet0Pqg C.DH_set0_pqg
func DHSet0Pqg(dh *DH, p *BIGNUM, q *BIGNUM, g *BIGNUM) c.Int

//go:linkname DHGet0Key C.DH_get0_key
func DHGet0Key(dh *DH, pub_key **BIGNUM, priv_key **BIGNUM)

//go:linkname DHSet0Key C.DH_set0_key
func DHSet0Key(dh *DH, pub_key *BIGNUM, priv_key *BIGNUM) c.Int

//go:linkname DHGet0P C.DH_get0_p
func DHGet0P(dh *DH) *BIGNUM

//go:linkname DHGet0Q C.DH_get0_q
func DHGet0Q(dh *DH) *BIGNUM

//go:linkname DHGet0G C.DH_get0_g
func DHGet0G(dh *DH) *BIGNUM

//go:linkname DHGet0PrivKey C.DH_get0_priv_key
func DHGet0PrivKey(dh *DH) *BIGNUM

//go:linkname DHGet0PubKey C.DH_get0_pub_key
func DHGet0PubKey(dh *DH) *BIGNUM

//go:linkname DHClearFlags C.DH_clear_flags
func DHClearFlags(dh *DH, flags c.Int)

//go:linkname DHTestFlags C.DH_test_flags
func DHTestFlags(dh *DH, flags c.Int) c.Int

//go:linkname DHSetFlags C.DH_set_flags
func DHSetFlags(dh *DH, flags c.Int)

//go:linkname DHGetLength C.DH_get_length
func DHGetLength(dh *DH) c.Long

//go:linkname DHSetLength C.DH_set_length
func DHSetLength(dh *DH, length c.Long) c.Int

//go:linkname DHMethNew C.DH_meth_new
func DHMethNew(name *c.Char, flags c.Int) *DH_METHOD

//go:linkname DHMethFree C.DH_meth_free
func DHMethFree(dhm *DH_METHOD)

//go:linkname DHMethDup C.DH_meth_dup
func DHMethDup(dhm *DH_METHOD) *DH_METHOD

//go:linkname DHMethGet0Name C.DH_meth_get0_name
func DHMethGet0Name(dhm *DH_METHOD) *c.Char

//go:linkname DHMethSet1Name C.DH_meth_set1_name
func DHMethSet1Name(dhm *DH_METHOD, name *c.Char) c.Int

//go:linkname DHMethGetFlags C.DH_meth_get_flags
func DHMethGetFlags(dhm *DH_METHOD) c.Int

//go:linkname DHMethSetFlags C.DH_meth_set_flags
func DHMethSetFlags(dhm *DH_METHOD, flags c.Int) c.Int

//go:linkname DHMethGet0AppData C.DH_meth_get0_app_data
func DHMethGet0AppData(dhm *DH_METHOD) unsafe.Pointer

//go:linkname DHMethSet0AppData C.DH_meth_set0_app_data
func DHMethSet0AppData(dhm *DH_METHOD, app_data unsafe.Pointer) c.Int

//go:linkname DHMethGetGenerateKey C.DH_meth_get_generate_key
func DHMethGetGenerateKey(dhm *DH_METHOD) func(_llcppg_param1 *DH) c.Int

//go:linkname DHMethSetGenerateKey C.DH_meth_set_generate_key
func DHMethSetGenerateKey(dhm *DH_METHOD, generate_key func(_llcppg_param1 *DH) c.Int) c.Int

//go:linkname DHMethGetComputeKey C.DH_meth_get_compute_key
func DHMethGetComputeKey(dhm *DH_METHOD) func(_llcppg_param1 *uint8, _llcppg_param2 *BIGNUM, _llcppg_param3 *DH) c.Int

//go:linkname DHMethSetComputeKey C.DH_meth_set_compute_key
func DHMethSetComputeKey(dhm *DH_METHOD, compute_key func(_llcppg_param1 *uint8, _llcppg_param2 *BIGNUM, _llcppg_param3 *DH) c.Int) c.Int

//go:linkname DHMethGetBnModExp C.DH_meth_get_bn_mod_exp
func DHMethGetBnModExp(dhm *DH_METHOD) func(_llcppg_param1 *DH, _llcppg_param2 *BIGNUM, _llcppg_param3 *BIGNUM, _llcppg_param4 *BIGNUM, _llcppg_param5 *BIGNUM, _llcppg_param6 *BN_CTX, _llcppg_param7 *BN_MONT_CTX) c.Int

//go:linkname DHMethSetBnModExp C.DH_meth_set_bn_mod_exp
func DHMethSetBnModExp(dhm *DH_METHOD, bn_mod_exp func(_llcppg_param1 *DH, _llcppg_param2 *BIGNUM, _llcppg_param3 *BIGNUM, _llcppg_param4 *BIGNUM, _llcppg_param5 *BIGNUM, _llcppg_param6 *BN_CTX, _llcppg_param7 *BN_MONT_CTX) c.Int) c.Int

//go:linkname DHMethGetInit C.DH_meth_get_init
func DHMethGetInit(dhm *DH_METHOD) func(_llcppg_param1 *DH) c.Int

//go:linkname DHMethSetInit C.DH_meth_set_init
func DHMethSetInit(dhm *DH_METHOD, init func(_llcppg_param1 *DH) c.Int) c.Int

//go:linkname DHMethGetFinish C.DH_meth_get_finish
func DHMethGetFinish(dhm *DH_METHOD) func(_llcppg_param1 *DH) c.Int

//go:linkname DHMethSetFinish C.DH_meth_set_finish
func DHMethSetFinish(dhm *DH_METHOD, finish func(_llcppg_param1 *DH) c.Int) c.Int

//go:linkname DHMethGetGenerateParams C.DH_meth_get_generate_params
func DHMethGetGenerateParams(dhm *DH_METHOD) func(_llcppg_param1 *DH, _llcppg_param2 c.Int, _llcppg_param3 c.Int, _llcppg_param4 *BN_GENCB) c.Int

//go:linkname DHMethSetGenerateParams C.DH_meth_set_generate_params
func DHMethSetGenerateParams(dhm *DH_METHOD, generate_params func(_llcppg_param1 *DH, _llcppg_param2 c.Int, _llcppg_param3 c.Int, _llcppg_param4 *BN_GENCB) c.Int) c.Int

//go:linkname DHGenerateParameters C.DH_generate_parameters
func DHGenerateParameters(prime_len c.Int, generator c.Int, callback func(_llcppg_param1 c.Int, _llcppg_param2 c.Int, _llcppg_param3 unsafe.Pointer), cb_arg unsafe.Pointer) *DH
