// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"github.com/goplus/lib/c/time"
	_ "unsafe"
)

const OSSL_ECH_MAX_PAYLOAD_LEN = 1500
const OSSL_ECH_MIN_ECHCONFIG_LEN = 32
const OSSL_ECH_MAX_ECHCONFIG_LEN = 1500
const OSSL_ECH_MAX_ECHCONFIGEXT_LEN = 512
const OSSL_ECH_MAX_MAXNAMELEN = 255
const OSSL_ECH_MAX_PUBLICNAME = 255
const OSSL_ECH_MAX_ALPNLEN = 255
const OSSL_ECH_OUTERS_MAX = 20
const OSSL_ECH_ALLEXTS_MAX = 32
const OSSL_ECH_RFC9849_VERSION = 65037
const OSSL_ECH_CURRENT_VERSION = 65037
const SSL_ECH_STATUS_BACKEND = 4
const SSL_ECH_STATUS_GREASE_ECH = 3
const SSL_ECH_STATUS_GREASE = 2
const SSL_ECH_STATUS_SUCCESS = 1
const SSL_ECH_STATUS_FAILED = 0
const SSL_ECH_STATUS_BAD_CALL = -100
const SSL_ECH_STATUS_NOT_TRIED = -101
const SSL_ECH_STATUS_BAD_NAME = -102
const SSL_ECH_STATUS_NOT_CONFIGURED = -103
const SSL_ECH_STATUS_FAILED_ECH = -105
const SSL_ECH_STATUS_FAILED_ECH_BAD_NAME = -106
const OSSL_ECHSTORE_LAST = -1
const OSSL_ECHSTORE_ALL = -2
const OSSL_ECH_FOR_RETRY = 1
const OSSL_ECH_NO_RETRY = 0

// llgo:type C
type SSLEchCbFunc = func(_llcppg_param1 *SSL, _llcppg_param2 *c.Char) c.Uint

// API calls built around OSSL_ECHSTORE
//
//go:linkname OSSL_ECHSTORENew C.OSSL_ECHSTORE_new
func OSSL_ECHSTORENew(libctx *OSSL_LIB_CTX, propq *c.Char) *OSSL_ECHSTORE

//go:linkname OSSL_ECHSTOREFree C.OSSL_ECHSTORE_free
func OSSL_ECHSTOREFree(es *OSSL_ECHSTORE)

//go:linkname OSSL_ECHSTORENewConfig C.OSSL_ECHSTORE_new_config
func OSSL_ECHSTORENewConfig(es *OSSL_ECHSTORE, echversion c.Uint16T, max_name_length c.Uint8T, public_name *c.Char, suite OSSL_HPKE_SUITE) c.Int

//go:linkname OSSL_ECHSTOREWritePem C.OSSL_ECHSTORE_write_pem
func OSSL_ECHSTOREWritePem(es *OSSL_ECHSTORE, index c.Int, out *BIO) c.Int

//go:linkname OSSL_ECHSTOREReadEchconfiglist C.OSSL_ECHSTORE_read_echconfiglist
func OSSL_ECHSTOREReadEchconfiglist(es *OSSL_ECHSTORE, in *BIO) c.Int

//go:linkname OSSL_ECHSTOREGet1Info C.OSSL_ECHSTORE_get1_info
func OSSL_ECHSTOREGet1Info(es *OSSL_ECHSTORE, index c.Int, loaded_secs *time.TimeT, public_name **c.Char, echconfig **c.Char, has_private *c.Int, for_retry *c.Int) c.Int

//go:linkname OSSL_ECHSTOREDownselect C.OSSL_ECHSTORE_downselect
func OSSL_ECHSTOREDownselect(es *OSSL_ECHSTORE, index c.Int) c.Int

//go:linkname OSSL_ECHSTORESet1KeyAndReadPem C.OSSL_ECHSTORE_set1_key_and_read_pem
func OSSL_ECHSTORESet1KeyAndReadPem(es *OSSL_ECHSTORE, priv *EVP_PKEY, in *BIO, for_retry c.Int) c.Int

//go:linkname OSSL_ECHSTOREReadPem C.OSSL_ECHSTORE_read_pem
func OSSL_ECHSTOREReadPem(es *OSSL_ECHSTORE, in *BIO, for_retry c.Int) c.Int

//go:linkname OSSL_ECHSTORENumEntries C.OSSL_ECHSTORE_num_entries
func OSSL_ECHSTORENumEntries(es *OSSL_ECHSTORE, numentries *c.Int) c.Int

//go:linkname OSSL_ECHSTORENumKeys C.OSSL_ECHSTORE_num_keys
func OSSL_ECHSTORENumKeys(es *OSSL_ECHSTORE, numkeys *c.Int) c.Int

//go:linkname OSSL_ECHSTOREFlushKeys C.OSSL_ECHSTORE_flush_keys
func OSSL_ECHSTOREFlushKeys(es *OSSL_ECHSTORE, age time.TimeT) c.Int

// APIs relating OSSL_ECHSTORE to SSL/SSL_CTX
//
//go:linkname SSL_CTXSet1Echstore C.SSL_CTX_set1_echstore
func SSL_CTXSet1Echstore(ctx *SSL_CTX, es *OSSL_ECHSTORE) c.Int

//go:linkname SSLSet1Echstore C.SSL_set1_echstore
func SSLSet1Echstore(s *SSL, es *OSSL_ECHSTORE) c.Int

//go:linkname SSL_CTXGet1Echstore C.SSL_CTX_get1_echstore
func SSL_CTXGet1Echstore(ctx *SSL_CTX) *OSSL_ECHSTORE

//go:linkname SSLGet1Echstore C.SSL_get1_echstore
func SSLGet1Echstore(s *SSL) *OSSL_ECHSTORE

//go:linkname SSLEchSet1ServerNames C.SSL_ech_set1_server_names
func SSLEchSet1ServerNames(s *SSL, inner_name *c.Char, outer_name *c.Char, no_outer c.Int) c.Int

//go:linkname SSLEchSet1OuterServerName C.SSL_ech_set1_outer_server_name
func SSLEchSet1OuterServerName(s *SSL, outer_name *c.Char, no_outer c.Int) c.Int

// Note that this function returns 1 for success and 0 for error. This
// contrasts with SSL_set1_alpn_protos() which (unusually for OpenSSL)
// returns 0 for success and 1 on error.
//
//go:linkname SSLEchSet1OuterAlpnProtos C.SSL_ech_set1_outer_alpn_protos
func SSLEchSet1OuterAlpnProtos(s *SSL, protos *uint8, protos_len c.SizeT) c.Int

//go:linkname SSLEchGet1Status C.SSL_ech_get1_status
func SSLEchGet1Status(s *SSL, inner_sni **c.Char, outer_sni **c.Char) c.Int

//go:linkname SSLEchSet1GreaseSuite C.SSL_ech_set1_grease_suite
func SSLEchSet1GreaseSuite(s *SSL, suite *c.Char) c.Int

//go:linkname SSLEchSetGreaseType C.SSL_ech_set_grease_type
func SSLEchSetGreaseType(s *SSL, type_ c.Uint16T) c.Int

//go:linkname SSLEchSetCallback C.SSL_ech_set_callback
func SSLEchSetCallback(s *SSL, f SSLEchCbFunc)

//go:linkname SSLEchGet1RetryConfig C.SSL_ech_get1_retry_config
func SSLEchGet1RetryConfig(s *SSL, ec **uint8, eclen *c.SizeT) c.Int

// Note that this function returns 1 for success and 0 for error. This
// contrasts with SSL_set1_alpn_protos() which (unusually for OpenSSL)
// returns 0 for success and 1 on error.
//
//go:linkname SSL_CTXEchSet1OuterAlpnProtos C.SSL_CTX_ech_set1_outer_alpn_protos
func SSL_CTXEchSet1OuterAlpnProtos(s *SSL_CTX, protos *uint8, protos_len c.SizeT) c.Int

//go:linkname SSL_CTXEchSetCallback C.SSL_CTX_ech_set_callback
func SSL_CTXEchSetCallback(ctx *SSL_CTX, f SSLEchCbFunc)

//go:linkname SSLSet1EchConfigList C.SSL_set1_ech_config_list
func SSLSet1EchConfigList(ssl *SSL, ecl *c.Uint8T, ecl_len c.SizeT) c.Int
