// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const EVP_MAX_MD_SIZE = 64
const EVP_MAX_KEY_LENGTH = 64
const EVP_MAX_IV_LENGTH = 16
const EVP_MAX_BLOCK_LENGTH = 32
const EVP_MAX_AEAD_TAG_LENGTH = 16
const EVP_MAX_PIPES = 32
const PKCS5_SALT_LEN = 8
const PKCS5_DEFAULT_ITER = 2048
const EVP_PK_RSA = 1
const EVP_PK_DSA = 2
const EVP_PK_DH = 4
const EVP_PK_EC = 8
const EVP_PKT_SIGN = 16
const EVP_PKT_ENC = 32
const EVP_PKT_EXCH = 64
const EVP_PKS_RSA = 256
const EVP_PKS_DSA = 512
const EVP_PKS_EC = 1024
const EVP_PKEY_NONE = 0
const EVP_PKEY_RSA = 6
const EVP_PKEY_RSA2 = 19
const EVP_PKEY_RSA_PSS = 912
const EVP_PKEY_DSA = 116
const EVP_PKEY_DSA1 = 67
const EVP_PKEY_DSA2 = 66
const EVP_PKEY_DSA3 = 113
const EVP_PKEY_DSA4 = 70
const EVP_PKEY_DH = 28
const EVP_PKEY_DHX = 920
const EVP_PKEY_EC = 408
const EVP_PKEY_SM2 = 1172
const EVP_PKEY_HMAC = 855
const EVP_PKEY_CMAC = 894
const EVP_PKEY_SCRYPT = 973
const EVP_PKEY_TLS1_PRF = 1021
const EVP_PKEY_HKDF = 1036
const EVP_PKEY_POLY1305 = 1061
const EVP_PKEY_SIPHASH = 1062
const EVP_PKEY_X25519 = 1034
const EVP_PKEY_ED25519 = 1087
const EVP_PKEY_X448 = 1035
const EVP_PKEY_ED448 = 1088
const EVP_PKEY_ML_DSA_44 = 1457
const EVP_PKEY_ML_DSA_65 = 1458
const EVP_PKEY_ML_DSA_87 = 1459
const EVP_PKEY_SLH_DSA_SHA2_128S = 1460
const EVP_PKEY_SLH_DSA_SHA2_128F = 1461
const EVP_PKEY_SLH_DSA_SHA2_192S = 1462
const EVP_PKEY_SLH_DSA_SHA2_192F = 1463
const EVP_PKEY_SLH_DSA_SHA2_256S = 1464
const EVP_PKEY_SLH_DSA_SHA2_256F = 1465
const EVP_PKEY_SLH_DSA_SHAKE_128S = 1466
const EVP_PKEY_SLH_DSA_SHAKE_128F = 1467
const EVP_PKEY_SLH_DSA_SHAKE_192S = 1468
const EVP_PKEY_SLH_DSA_SHAKE_192F = 1469
const EVP_PKEY_SLH_DSA_SHAKE_256S = 1470
const EVP_PKEY_SLH_DSA_SHAKE_256F = 1471
const EVP_PKEY_HSS_LMS = 1501
const EVP_PKEY_KEYMGMT = -1
const EVP_PKEY_KEY_PARAMETERS = 132
const EVP_PKEY_PRIVATE_KEY = 133
const EVP_PKEY_PUBLIC_KEY = 134
const EVP_PKEY_KEYPAIR = 135
const EVP_PKEY_MO_SIGN = 1
const EVP_PKEY_MO_VERIFY = 2
const EVP_PKEY_MO_ENCRYPT = 4
const EVP_PKEY_MO_DECRYPT = 8
const EVP_MD_FLAG_ONESHOT = 1
const EVP_MD_FLAG_XOF = 2
const EVP_MD_FLAG_DIGALGID_MASK = 24
const EVP_MD_FLAG_DIGALGID_NULL = 0
const EVP_MD_FLAG_DIGALGID_ABSENT = 8
const EVP_MD_FLAG_DIGALGID_CUSTOM = 24
const EVP_MD_FLAG_FIPS = 1024
const EVP_MD_CTRL_DIGALGID = 1
const EVP_MD_CTRL_MICALG = 2
const EVP_MD_CTRL_XOF_LEN = 3
const EVP_MD_CTRL_TLSTREE = 4
const EVP_MD_CTRL_ALG_CTRL = 4096
const EVP_MD_CTX_FLAG_ONESHOT = 1
const EVP_MD_CTX_FLAG_CLEANED = 2
const EVP_MD_CTX_FLAG_REUSE = 4
const EVP_MD_CTX_FLAG_NON_FIPS_ALLOW = 8
const EVP_MD_CTX_FLAG_PAD_MASK = 240
const EVP_MD_CTX_FLAG_PAD_PKCS1 = 0
const EVP_MD_CTX_FLAG_PAD_X931 = 16
const EVP_MD_CTX_FLAG_PAD_PSS = 32
const EVP_MD_CTX_FLAG_NO_INIT = 256
const EVP_MD_CTX_FLAG_FINALISE = 512
const EVP_CIPH_STREAM_CIPHER = 0
const EVP_CIPH_ECB_MODE = 1
const EVP_CIPH_CBC_MODE = 2
const EVP_CIPH_CFB_MODE = 3
const EVP_CIPH_OFB_MODE = 4
const EVP_CIPH_CTR_MODE = 5
const EVP_CIPH_GCM_MODE = 6
const EVP_CIPH_CCM_MODE = 7
const EVP_CIPH_XTS_MODE = 65537
const EVP_CIPH_WRAP_MODE = 65538
const EVP_CIPH_OCB_MODE = 65539
const EVP_CIPH_SIV_MODE = 65540
const EVP_CIPH_GCM_SIV_MODE = 65541
const EVP_CIPH_MODE = 983047
const EVP_CIPH_VARIABLE_LENGTH = 8
const EVP_CIPH_CUSTOM_IV = 16
const EVP_CIPH_ALWAYS_CALL_INIT = 32
const EVP_CIPH_CTRL_INIT = 64
const EVP_CIPH_CUSTOM_KEY_LENGTH = 128
const EVP_CIPH_NO_PADDING = 256
const EVP_CIPH_RAND_KEY = 512
const EVP_CIPH_CUSTOM_COPY = 1024
const EVP_CIPH_CUSTOM_IV_LENGTH = 2048
const EVP_CIPH_FLAG_DEFAULT_ASN1 = 0
const EVP_CIPH_FLAG_LENGTH_BITS = 8192
const EVP_CIPH_FLAG_FIPS = 0
const EVP_CIPH_FLAG_NON_FIPS_ALLOW = 0
const EVP_CIPH_FLAG_CTS = 16384
const EVP_CIPH_FLAG_CUSTOM_CIPHER = 1048576
const EVP_CIPH_FLAG_AEAD_CIPHER = 2097152
const EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK = 4194304
const EVP_CIPH_FLAG_PIPELINE = 8388608
const EVP_CIPH_FLAG_CUSTOM_ASN1 = 16777216
const EVP_CIPH_FLAG_CIPHER_WITH_MAC = 33554432
const EVP_CIPH_FLAG_GET_WRAP_CIPHER = 67108864
const EVP_CIPH_FLAG_INVERSE_CIPHER = 134217728
const EVP_CIPH_FLAG_ENC_THEN_MAC = 268435456
const EVP_CIPHER_CTX_FLAG_WRAP_ALLOW = 1
const EVP_CTRL_INIT = 0
const EVP_CTRL_SET_KEY_LENGTH = 1
const EVP_CTRL_GET_RC2_KEY_BITS = 2
const EVP_CTRL_SET_RC2_KEY_BITS = 3
const EVP_CTRL_GET_RC5_ROUNDS = 4
const EVP_CTRL_SET_RC5_ROUNDS = 5
const EVP_CTRL_RAND_KEY = 6
const EVP_CTRL_PBE_PRF_NID = 7
const EVP_CTRL_COPY = 8
const EVP_CTRL_AEAD_SET_IVLEN = 9
const EVP_CTRL_AEAD_GET_TAG = 16
const EVP_CTRL_AEAD_SET_TAG = 17
const EVP_CTRL_AEAD_SET_IV_FIXED = 18
const EVP_CTRL_GCM_SET_IVLEN = 9
const EVP_CTRL_GCM_GET_TAG = 16
const EVP_CTRL_GCM_SET_TAG = 17
const EVP_CTRL_GCM_SET_IV_FIXED = 18
const EVP_CTRL_GCM_IV_GEN = 19
const EVP_CTRL_CCM_SET_IVLEN = 9
const EVP_CTRL_CCM_GET_TAG = 16
const EVP_CTRL_CCM_SET_TAG = 17
const EVP_CTRL_CCM_SET_IV_FIXED = 18
const EVP_CTRL_CCM_SET_L = 20
const EVP_CTRL_CCM_SET_MSGLEN = 21
const EVP_CTRL_AEAD_TLS1_AAD = 22
const EVP_CTRL_AEAD_SET_MAC_KEY = 23
const EVP_CTRL_GCM_SET_IV_INV = 24
const EVP_CTRL_TLS1_1_MULTIBLOCK_AAD = 25
const EVP_CTRL_TLS1_1_MULTIBLOCK_ENCRYPT = 26
const EVP_CTRL_TLS1_1_MULTIBLOCK_DECRYPT = 27
const EVP_CTRL_TLS1_1_MULTIBLOCK_MAX_BUFSIZE = 28
const EVP_CTRL_SSL3_MASTER_SECRET = 29
const EVP_CTRL_SET_SBOX = 30
const EVP_CTRL_SBOX_USED = 31
const EVP_CTRL_KEY_MESH = 32
const EVP_CTRL_BLOCK_PADDING_MODE = 33
const EVP_CTRL_SET_PIPELINE_OUTPUT_BUFS = 34
const EVP_CTRL_SET_PIPELINE_INPUT_BUFS = 35
const EVP_CTRL_SET_PIPELINE_INPUT_LENS = 36
const EVP_CTRL_GET_IVLEN = 37
const EVP_CTRL_SET_SPEED = 39
const EVP_CTRL_PROCESS_UNPROTECTED = 40
const EVP_CTRL_GET_WRAP_CIPHER = 41
const EVP_CTRL_TLSTREE = 42
const EVP_PADDING_PKCS7 = 1
const EVP_PADDING_ISO7816_4 = 2
const EVP_PADDING_ANSI923 = 3
const EVP_PADDING_ISO10126 = 4
const EVP_PADDING_ZERO = 5
const EVP_AEAD_TLS1_AAD_LEN = 13
const EVP_GCM_TLS_FIXED_IV_LEN = 4
const EVP_GCM_TLS_EXPLICIT_IV_LEN = 8
const EVP_GCM_TLS_TAG_LEN = 16
const EVP_CCM_TLS_FIXED_IV_LEN = 4
const EVP_CCM_TLS_EXPLICIT_IV_LEN = 8
const EVP_CCM_TLS_IV_LEN = 12
const EVP_CCM_TLS_TAG_LEN = 16
const EVP_CCM8_TLS_TAG_LEN = 8
const EVP_CHACHAPOLY_TLS_TAG_LEN = 16
const EVP_RAND_STATE_UNINITIALISED = 0
const EVP_RAND_STATE_READY = 1
const EVP_RAND_STATE_ERROR = 2
const EVP_PBE_TYPE_OUTER = 0
const EVP_PBE_TYPE_PRF = 1
const EVP_PBE_TYPE_KDF = 2
const ASN1_PKEY_ALIAS = 1
const ASN1_PKEY_DYNAMIC = 2
const ASN1_PKEY_SIGPARAM_NULL = 4
const ASN1_PKEY_CTRL_PKCS7_SIGN = 1
const ASN1_PKEY_CTRL_PKCS7_ENCRYPT = 2
const ASN1_PKEY_CTRL_DEFAULT_MD_NID = 3
const ASN1_PKEY_CTRL_CMS_SIGN = 5
const ASN1_PKEY_CTRL_CMS_ENVELOPE = 7
const ASN1_PKEY_CTRL_CMS_RI_TYPE = 8
const ASN1_PKEY_CTRL_SET1_TLS_ENCPT = 9
const ASN1_PKEY_CTRL_GET1_TLS_ENCPT = 10
const ASN1_PKEY_CTRL_CMS_IS_RI_TYPE_SUPPORTED = 11
const EVP_PKEY_OP_UNDEFINED = 0
const EVP_PKEY_OP_PARAMGEN = 2
const EVP_PKEY_OP_KEYGEN = 4
const EVP_PKEY_OP_FROMDATA = 8
const EVP_PKEY_OP_SIGN = 16
const EVP_PKEY_OP_VERIFY = 32
const EVP_PKEY_OP_VERIFYRECOVER = 64
const EVP_PKEY_OP_SIGNCTX = 128
const EVP_PKEY_OP_VERIFYCTX = 256
const EVP_PKEY_OP_ENCRYPT = 512
const EVP_PKEY_OP_DECRYPT = 1024
const EVP_PKEY_OP_DERIVE = 2048
const EVP_PKEY_OP_ENCAPSULATE = 4096
const EVP_PKEY_OP_DECAPSULATE = 8192
const EVP_PKEY_OP_SIGNMSG = 16384
const EVP_PKEY_OP_VERIFYMSG = 32768
const EVP_PKEY_OP_ALL = 65535
const EVP_PKEY_OP_TYPE_SIG = 49648
const EVP_PKEY_OP_TYPE_CRYPT = 1536
const EVP_PKEY_OP_TYPE_DERIVE = 2048
const EVP_PKEY_OP_TYPE_DATA = 8
const EVP_PKEY_OP_TYPE_KEM = 12288
const EVP_PKEY_OP_TYPE_GEN = 6
const EVP_PKEY_OP_TYPE_NOGEN = 65529
const EVP_PKEY_CTRL_MD = 1
const EVP_PKEY_CTRL_PEER_KEY = 2
const EVP_PKEY_CTRL_SET_MAC_KEY = 6
const EVP_PKEY_CTRL_DIGESTINIT = 7
const EVP_PKEY_CTRL_SET_IV = 8
const EVP_PKEY_CTRL_PKCS7_ENCRYPT = 3
const EVP_PKEY_CTRL_PKCS7_DECRYPT = 4
const EVP_PKEY_CTRL_PKCS7_SIGN = 5
const EVP_PKEY_CTRL_CMS_ENCRYPT = 9
const EVP_PKEY_CTRL_CMS_DECRYPT = 10
const EVP_PKEY_CTRL_CMS_SIGN = 11
const EVP_PKEY_CTRL_CIPHER = 12
const EVP_PKEY_CTRL_GET_MD = 13
const EVP_PKEY_CTRL_SET_DIGEST_SIZE = 14
const EVP_PKEY_CTRL_SET1_ID = 15
const EVP_PKEY_CTRL_GET1_ID = 16
const EVP_PKEY_CTRL_GET1_ID_LEN = 17
const EVP_PKEY_ALG_CTRL = 4096
const EVP_PKEY_FLAG_AUTOARGLEN = 2
const EVP_PKEY_FLAG_SIGCTX_CUSTOM = 4

type EVP_CTRL_TLS1_1_MULTIBLOCK_PARAM struct {
	Out        *uint8
	Inp        *uint8
	Len        c.SizeT
	Interleave c.Uint
}
type EvpCipherInfoSt struct {
	Cipher *EVP_CIPHER
	Iv     [16]uint8
}
type EVP_CIPHER_INFO = EvpCipherInfoSt

// Password based encryption function
//
// llgo:type C
type EVP_PBE_KEYGEN = func(_llcppg_param1 *EVP_CIPHER_CTX, _llcppg_param2 *c.Char, _llcppg_param3 c.Int, _llcppg_param4 *ASN1_TYPE, _llcppg_param5 *EVP_CIPHER, _llcppg_param6 *EVP_MD, _llcppg_param7 c.Int) c.Int

// llgo:type C
type EVP_PBE_KEYGEN_EX = func(_llcppg_param1 *EVP_CIPHER_CTX, _llcppg_param2 *c.Char, _llcppg_param3 c.Int, _llcppg_param4 *ASN1_TYPE, _llcppg_param5 *EVP_CIPHER, _llcppg_param6 *EVP_MD, _llcppg_param7 c.Int, _llcppg_param8 *OSSL_LIB_CTX, _llcppg_param9 *c.Char) c.Int

// llgo:type C
type EVP_PKEYGenCb = func(_llcppg_param1 *EVP_PKEY_CTX) c.Int

//go:linkname EVPSetDefaultProperties C.EVP_set_default_properties
func EVPSetDefaultProperties(libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname EVPGet1DefaultProperties C.EVP_get1_default_properties
func EVPGet1DefaultProperties(libctx *OSSL_LIB_CTX) *c.Char

//go:linkname EVPDefaultPropertiesIsFipsEnabled C.EVP_default_properties_is_fips_enabled
func EVPDefaultPropertiesIsFipsEnabled(libctx *OSSL_LIB_CTX) c.Int

//go:linkname EVPDefaultPropertiesEnableFips C.EVP_default_properties_enable_fips
func EVPDefaultPropertiesEnableFips(libctx *OSSL_LIB_CTX, enable c.Int) c.Int

//go:linkname EVP_MDGetType C.EVP_MD_get_type
func EVP_MDGetType(md *EVP_MD) c.Int

//go:linkname EVP_MDGet0Name C.EVP_MD_get0_name
func EVP_MDGet0Name(md *EVP_MD) *c.Char

//go:linkname EVP_MDGet0Description C.EVP_MD_get0_description
func EVP_MDGet0Description(md *EVP_MD) *c.Char

//go:linkname EVP_MDIsA C.EVP_MD_is_a
func EVP_MDIsA(md *EVP_MD, name *c.Char) c.Int

//go:linkname EVP_MDNamesDoAll C.EVP_MD_names_do_all
func EVP_MDNamesDoAll(md *EVP_MD, fn func(_llcppg_param1 *c.Char, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer) c.Int

//go:linkname EVP_MDGet0Provider C.EVP_MD_get0_provider
func EVP_MDGet0Provider(md *EVP_MD) *OSSL_PROVIDER

//go:linkname EVP_MDGetPkeyType C.EVP_MD_get_pkey_type
func EVP_MDGetPkeyType(md *EVP_MD) c.Int

//go:linkname EVP_MDGetSize C.EVP_MD_get_size
func EVP_MDGetSize(md *EVP_MD) c.Int

//go:linkname EVP_MDGetBlockSize C.EVP_MD_get_block_size
func EVP_MDGetBlockSize(md *EVP_MD) c.Int

//go:linkname EVP_MDGetFlags C.EVP_MD_get_flags
func EVP_MDGetFlags(md *EVP_MD) c.Ulong

//go:linkname EVP_MDXof C.EVP_MD_xof
func EVP_MDXof(md *EVP_MD) c.Int

//go:linkname EVP_MD_CTXGet0Md C.EVP_MD_CTX_get0_md
func EVP_MD_CTXGet0Md(ctx *EVP_MD_CTX) *EVP_MD

//go:linkname EVP_MD_CTXGet1Md C.EVP_MD_CTX_get1_md
func EVP_MD_CTXGet1Md(ctx *EVP_MD_CTX) *EVP_MD

//go:linkname EVP_MD_CTXMd C.EVP_MD_CTX_md
func EVP_MD_CTXMd(ctx *EVP_MD_CTX) *EVP_MD

//go:linkname EVP_MD_CTXGetSizeEx C.EVP_MD_CTX_get_size_ex
func EVP_MD_CTXGetSizeEx(ctx *EVP_MD_CTX) c.Int

//go:linkname EVP_MD_CTXGetPkeyCtx C.EVP_MD_CTX_get_pkey_ctx
func EVP_MD_CTXGetPkeyCtx(ctx *EVP_MD_CTX) *EVP_PKEY_CTX

//go:linkname EVP_MD_CTXSetPkeyCtx C.EVP_MD_CTX_set_pkey_ctx
func EVP_MD_CTXSetPkeyCtx(ctx *EVP_MD_CTX, pctx *EVP_PKEY_CTX)

//go:linkname EVP_MD_CTXGet0MdData C.EVP_MD_CTX_get0_md_data
func EVP_MD_CTXGet0MdData(ctx *EVP_MD_CTX) unsafe.Pointer

//go:linkname EVP_CIPHERGetNid C.EVP_CIPHER_get_nid
func EVP_CIPHERGetNid(cipher *EVP_CIPHER) c.Int

//go:linkname EVP_CIPHERGet0Name C.EVP_CIPHER_get0_name
func EVP_CIPHERGet0Name(cipher *EVP_CIPHER) *c.Char

//go:linkname EVP_CIPHERGet0Description C.EVP_CIPHER_get0_description
func EVP_CIPHERGet0Description(cipher *EVP_CIPHER) *c.Char

//go:linkname EVP_CIPHERIsA C.EVP_CIPHER_is_a
func EVP_CIPHERIsA(cipher *EVP_CIPHER, name *c.Char) c.Int

//go:linkname EVP_CIPHERNamesDoAll C.EVP_CIPHER_names_do_all
func EVP_CIPHERNamesDoAll(cipher *EVP_CIPHER, fn func(_llcppg_param1 *c.Char, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer) c.Int

//go:linkname EVP_CIPHERGet0Provider C.EVP_CIPHER_get0_provider
func EVP_CIPHERGet0Provider(cipher *EVP_CIPHER) *OSSL_PROVIDER

//go:linkname EVP_CIPHERGetBlockSize C.EVP_CIPHER_get_block_size
func EVP_CIPHERGetBlockSize(cipher *EVP_CIPHER) c.Int

//go:linkname EVP_CIPHERImplCtxSize C.EVP_CIPHER_impl_ctx_size
func EVP_CIPHERImplCtxSize(cipher *EVP_CIPHER) c.Int

//go:linkname EVP_CIPHERGetKeyLength C.EVP_CIPHER_get_key_length
func EVP_CIPHERGetKeyLength(cipher *EVP_CIPHER) c.Int

//go:linkname EVP_CIPHERGetIvLength C.EVP_CIPHER_get_iv_length
func EVP_CIPHERGetIvLength(cipher *EVP_CIPHER) c.Int

//go:linkname EVP_CIPHERGetFlags C.EVP_CIPHER_get_flags
func EVP_CIPHERGetFlags(cipher *EVP_CIPHER) c.Ulong

//go:linkname EVP_CIPHERGetMode C.EVP_CIPHER_get_mode
func EVP_CIPHERGetMode(cipher *EVP_CIPHER) c.Int

//go:linkname EVP_CIPHERGetType C.EVP_CIPHER_get_type
func EVP_CIPHERGetType(cipher *EVP_CIPHER) c.Int

//go:linkname EVP_CIPHERFetch C.EVP_CIPHER_fetch
func EVP_CIPHERFetch(ctx *OSSL_LIB_CTX, algorithm *c.Char, properties *c.Char) *EVP_CIPHER

//go:linkname EVP_CIPHERCanPipeline C.EVP_CIPHER_can_pipeline
func EVP_CIPHERCanPipeline(cipher *EVP_CIPHER, enc c.Int) c.Int

//go:linkname EVP_CIPHERUpRef C.EVP_CIPHER_up_ref
func EVP_CIPHERUpRef(cipher *EVP_CIPHER) c.Int

//go:linkname EVP_CIPHERFree C.EVP_CIPHER_free
func EVP_CIPHERFree(cipher *EVP_CIPHER)

//go:linkname EVP_CIPHER_CTXGet0Cipher C.EVP_CIPHER_CTX_get0_cipher
func EVP_CIPHER_CTXGet0Cipher(ctx *EVP_CIPHER_CTX) *EVP_CIPHER

//go:linkname EVP_CIPHER_CTXGet1Cipher C.EVP_CIPHER_CTX_get1_cipher
func EVP_CIPHER_CTXGet1Cipher(ctx *EVP_CIPHER_CTX) *EVP_CIPHER

//go:linkname EVP_CIPHER_CTXIsEncrypting C.EVP_CIPHER_CTX_is_encrypting
func EVP_CIPHER_CTXIsEncrypting(ctx *EVP_CIPHER_CTX) c.Int

//go:linkname EVP_CIPHER_CTXGetNid C.EVP_CIPHER_CTX_get_nid
func EVP_CIPHER_CTXGetNid(ctx *EVP_CIPHER_CTX) c.Int

//go:linkname EVP_CIPHER_CTXGetBlockSize C.EVP_CIPHER_CTX_get_block_size
func EVP_CIPHER_CTXGetBlockSize(ctx *EVP_CIPHER_CTX) c.Int

//go:linkname EVP_CIPHER_CTXGetKeyLength C.EVP_CIPHER_CTX_get_key_length
func EVP_CIPHER_CTXGetKeyLength(ctx *EVP_CIPHER_CTX) c.Int

//go:linkname EVP_CIPHER_CTXGetIvLength C.EVP_CIPHER_CTX_get_iv_length
func EVP_CIPHER_CTXGetIvLength(ctx *EVP_CIPHER_CTX) c.Int

//go:linkname EVP_CIPHER_CTXGetTagLength C.EVP_CIPHER_CTX_get_tag_length
func EVP_CIPHER_CTXGetTagLength(ctx *EVP_CIPHER_CTX) c.Int

//go:linkname EVP_CIPHER_CTXCipher C.EVP_CIPHER_CTX_cipher
func EVP_CIPHER_CTXCipher(ctx *EVP_CIPHER_CTX) *EVP_CIPHER

//go:linkname EVP_CIPHER_CTXIv C.EVP_CIPHER_CTX_iv
func EVP_CIPHER_CTXIv(ctx *EVP_CIPHER_CTX) *uint8

//go:linkname EVP_CIPHER_CTXOriginalIv C.EVP_CIPHER_CTX_original_iv
func EVP_CIPHER_CTXOriginalIv(ctx *EVP_CIPHER_CTX) *uint8

//go:linkname EVP_CIPHER_CTXIvNoconst C.EVP_CIPHER_CTX_iv_noconst
func EVP_CIPHER_CTXIvNoconst(ctx *EVP_CIPHER_CTX) *uint8

//go:linkname EVP_CIPHER_CTXGetUpdatedIv C.EVP_CIPHER_CTX_get_updated_iv
func EVP_CIPHER_CTXGetUpdatedIv(ctx *EVP_CIPHER_CTX, buf unsafe.Pointer, len c.SizeT) c.Int

//go:linkname EVP_CIPHER_CTXGetOriginalIv C.EVP_CIPHER_CTX_get_original_iv
func EVP_CIPHER_CTXGetOriginalIv(ctx *EVP_CIPHER_CTX, buf unsafe.Pointer, len c.SizeT) c.Int

//go:linkname EVP_CIPHER_CTXBufNoconst C.EVP_CIPHER_CTX_buf_noconst
func EVP_CIPHER_CTXBufNoconst(ctx *EVP_CIPHER_CTX) *uint8

//go:linkname EVP_CIPHER_CTXGetNum C.EVP_CIPHER_CTX_get_num
func EVP_CIPHER_CTXGetNum(ctx *EVP_CIPHER_CTX) c.Int

//go:linkname EVP_CIPHER_CTXSetNum C.EVP_CIPHER_CTX_set_num
func EVP_CIPHER_CTXSetNum(ctx *EVP_CIPHER_CTX, num c.Int) c.Int

//go:linkname EVP_CIPHER_CTXDup C.EVP_CIPHER_CTX_dup
func EVP_CIPHER_CTXDup(in *EVP_CIPHER_CTX) *EVP_CIPHER_CTX

//go:linkname EVP_CIPHER_CTXCopy C.EVP_CIPHER_CTX_copy
func EVP_CIPHER_CTXCopy(out *EVP_CIPHER_CTX, in *EVP_CIPHER_CTX) c.Int

//go:linkname EVP_CIPHER_CTXGetAppData C.EVP_CIPHER_CTX_get_app_data
func EVP_CIPHER_CTXGetAppData(ctx *EVP_CIPHER_CTX) unsafe.Pointer

//go:linkname EVP_CIPHER_CTXSetAppData C.EVP_CIPHER_CTX_set_app_data
func EVP_CIPHER_CTXSetAppData(ctx *EVP_CIPHER_CTX, data unsafe.Pointer)

//go:linkname EVP_CIPHER_CTXGetCipherData C.EVP_CIPHER_CTX_get_cipher_data
func EVP_CIPHER_CTXGetCipherData(ctx *EVP_CIPHER_CTX) unsafe.Pointer

//go:linkname EVP_CIPHER_CTXSetCipherData C.EVP_CIPHER_CTX_set_cipher_data
func EVP_CIPHER_CTXSetCipherData(ctx *EVP_CIPHER_CTX, cipher_data unsafe.Pointer) unsafe.Pointer

//go:linkname EVP_Cipher C.EVP_Cipher
func EVP_Cipher(c *EVP_CIPHER_CTX, out *uint8, in *uint8, inl c.Uint) c.Int

//go:linkname EVP_MDGetParams C.EVP_MD_get_params
func EVP_MDGetParams(digest *EVP_MD, params *OSSL_PARAM) c.Int

//go:linkname EVP_MD_CTXSetParams C.EVP_MD_CTX_set_params
func EVP_MD_CTXSetParams(ctx *EVP_MD_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_MD_CTXGetParams C.EVP_MD_CTX_get_params
func EVP_MD_CTXGetParams(ctx *EVP_MD_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_MDGettableParams C.EVP_MD_gettable_params
func EVP_MDGettableParams(digest *EVP_MD) *OSSL_PARAM

//go:linkname EVP_MDSettableCtxParams C.EVP_MD_settable_ctx_params
func EVP_MDSettableCtxParams(md *EVP_MD) *OSSL_PARAM

//go:linkname EVP_MDGettableCtxParams C.EVP_MD_gettable_ctx_params
func EVP_MDGettableCtxParams(md *EVP_MD) *OSSL_PARAM

//go:linkname EVP_MD_CTXSettableParams C.EVP_MD_CTX_settable_params
func EVP_MD_CTXSettableParams(ctx *EVP_MD_CTX) *OSSL_PARAM

//go:linkname EVP_MD_CTXGettableParams C.EVP_MD_CTX_gettable_params
func EVP_MD_CTXGettableParams(ctx *EVP_MD_CTX) *OSSL_PARAM

//go:linkname EVP_MD_CTXCtrl C.EVP_MD_CTX_ctrl
func EVP_MD_CTXCtrl(ctx *EVP_MD_CTX, cmd c.Int, p1 c.Int, p2 unsafe.Pointer) c.Int

//go:linkname EVP_MD_CTXNew C.EVP_MD_CTX_new
func EVP_MD_CTXNew() *EVP_MD_CTX

//go:linkname EVP_MD_CTXReset C.EVP_MD_CTX_reset
func EVP_MD_CTXReset(ctx *EVP_MD_CTX) c.Int

//go:linkname EVP_MD_CTXFree C.EVP_MD_CTX_free
func EVP_MD_CTXFree(ctx *EVP_MD_CTX)

//go:linkname EVP_MD_CTXDup C.EVP_MD_CTX_dup
func EVP_MD_CTXDup(in *EVP_MD_CTX) *EVP_MD_CTX

//go:linkname EVP_MD_CTXCopyEx C.EVP_MD_CTX_copy_ex
func EVP_MD_CTXCopyEx(out *EVP_MD_CTX, in *EVP_MD_CTX) c.Int

//go:linkname EVP_MD_CTXSetFlags C.EVP_MD_CTX_set_flags
func EVP_MD_CTXSetFlags(ctx *EVP_MD_CTX, flags c.Int)

//go:linkname EVP_MD_CTXClearFlags C.EVP_MD_CTX_clear_flags
func EVP_MD_CTXClearFlags(ctx *EVP_MD_CTX, flags c.Int)

//go:linkname EVP_MD_CTXTestFlags C.EVP_MD_CTX_test_flags
func EVP_MD_CTXTestFlags(ctx *EVP_MD_CTX, flags c.Int) c.Int

//go:linkname EVPDigestInitEx2 C.EVP_DigestInit_ex2
func EVPDigestInitEx2(ctx *EVP_MD_CTX, type_ *EVP_MD, params *OSSL_PARAM) c.Int

//go:linkname EVPDigestInitEx C.EVP_DigestInit_ex
func EVPDigestInitEx(ctx *EVP_MD_CTX, type_ *EVP_MD, impl *ENGINE) c.Int

//go:linkname EVP_DigestUpdate C.EVP_DigestUpdate
func EVP_DigestUpdate(ctx *EVP_MD_CTX, d unsafe.Pointer, cnt c.SizeT) c.Int

//go:linkname EVPDigestFinalEx C.EVP_DigestFinal_ex
func EVPDigestFinalEx(ctx *EVP_MD_CTX, md *uint8, s *c.Uint) c.Int

//go:linkname EVP_Digest C.EVP_Digest
func EVP_Digest(data unsafe.Pointer, count c.SizeT, md *uint8, size *c.Uint, type_ *EVP_MD, impl *ENGINE) c.Int

//go:linkname EVP_QDigest C.EVP_Q_digest
func EVP_QDigest(libctx *OSSL_LIB_CTX, name *c.Char, propq *c.Char, data unsafe.Pointer, datalen c.SizeT, md *uint8, mdlen *c.SizeT) c.Int

//go:linkname EVP_MD_CTXCopy C.EVP_MD_CTX_copy
func EVP_MD_CTXCopy(out *EVP_MD_CTX, in *EVP_MD_CTX) c.Int

//go:linkname EVP_DigestInit C.EVP_DigestInit
func EVP_DigestInit(ctx *EVP_MD_CTX, type_ *EVP_MD) c.Int

//go:linkname EVP_DigestFinal C.EVP_DigestFinal
func EVP_DigestFinal(ctx *EVP_MD_CTX, md *uint8, s *c.Uint) c.Int

//go:linkname EVP_DigestFinalXOF C.EVP_DigestFinalXOF
func EVP_DigestFinalXOF(ctx *EVP_MD_CTX, out *uint8, outlen c.SizeT) c.Int

//go:linkname EVP_DigestSqueeze C.EVP_DigestSqueeze
func EVP_DigestSqueeze(ctx *EVP_MD_CTX, out *uint8, outlen c.SizeT) c.Int

//go:linkname EVP_MD_CTXSerialize C.EVP_MD_CTX_serialize
func EVP_MD_CTXSerialize(ctx *EVP_MD_CTX, out *uint8, outlen *c.SizeT) c.Int

//go:linkname EVP_MD_CTXDeserialize C.EVP_MD_CTX_deserialize
func EVP_MD_CTXDeserialize(ctx *EVP_MD_CTX, in *uint8, inlen c.SizeT) c.Int

//go:linkname EVP_MDFetch C.EVP_MD_fetch
func EVP_MDFetch(ctx *OSSL_LIB_CTX, algorithm *c.Char, properties *c.Char) *EVP_MD

//go:linkname EVP_MDUpRef C.EVP_MD_up_ref
func EVP_MDUpRef(md *EVP_MD) c.Int

//go:linkname EVP_MDFree C.EVP_MD_free
func EVP_MDFree(md *EVP_MD)

//go:linkname EVPReadPwString C.EVP_read_pw_string
func EVPReadPwString(buf *c.Char, length c.Int, prompt *c.Char, verify c.Int) c.Int

//go:linkname EVPReadPwStringMin C.EVP_read_pw_string_min
func EVPReadPwStringMin(buf *c.Char, minlen c.Int, maxlen c.Int, prompt *c.Char, verify c.Int) c.Int

//go:linkname EVPSetPwPrompt C.EVP_set_pw_prompt
func EVPSetPwPrompt(prompt *c.Char)

//go:linkname EVPGetPwPrompt C.EVP_get_pw_prompt
func EVPGetPwPrompt() *c.Char

//go:linkname EVP_BytesToKey C.EVP_BytesToKey
func EVP_BytesToKey(type_ *EVP_CIPHER, md *EVP_MD, salt *uint8, data *uint8, datal c.Int, count c.Int, key *uint8, iv *uint8) c.Int

//go:linkname EVP_CIPHER_CTXSetFlags C.EVP_CIPHER_CTX_set_flags
func EVP_CIPHER_CTXSetFlags(ctx *EVP_CIPHER_CTX, flags c.Int)

//go:linkname EVP_CIPHER_CTXClearFlags C.EVP_CIPHER_CTX_clear_flags
func EVP_CIPHER_CTXClearFlags(ctx *EVP_CIPHER_CTX, flags c.Int)

//go:linkname EVP_CIPHER_CTXTestFlags C.EVP_CIPHER_CTX_test_flags
func EVP_CIPHER_CTXTestFlags(ctx *EVP_CIPHER_CTX, flags c.Int) c.Int

//go:linkname EVP_EncryptInit C.EVP_EncryptInit
func EVP_EncryptInit(ctx *EVP_CIPHER_CTX, cipher *EVP_CIPHER, key *uint8, iv *uint8) c.Int

//go:linkname EVPEncryptInitEx C.EVP_EncryptInit_ex
func EVPEncryptInitEx(ctx *EVP_CIPHER_CTX, cipher *EVP_CIPHER, impl *ENGINE, key *uint8, iv *uint8) c.Int

//go:linkname EVPEncryptInitEx2 C.EVP_EncryptInit_ex2
func EVPEncryptInitEx2(ctx *EVP_CIPHER_CTX, cipher *EVP_CIPHER, key *uint8, iv *uint8, params *OSSL_PARAM) c.Int

//go:linkname EVP_EncryptUpdate C.EVP_EncryptUpdate
func EVP_EncryptUpdate(ctx *EVP_CIPHER_CTX, out *uint8, outl *c.Int, in *uint8, inl c.Int) c.Int

//go:linkname EVPEncryptFinalEx C.EVP_EncryptFinal_ex
func EVPEncryptFinalEx(ctx *EVP_CIPHER_CTX, out *uint8, outl *c.Int) c.Int

//go:linkname EVP_EncryptFinal C.EVP_EncryptFinal
func EVP_EncryptFinal(ctx *EVP_CIPHER_CTX, out *uint8, outl *c.Int) c.Int

//go:linkname EVP_DecryptInit C.EVP_DecryptInit
func EVP_DecryptInit(ctx *EVP_CIPHER_CTX, cipher *EVP_CIPHER, key *uint8, iv *uint8) c.Int

//go:linkname EVPDecryptInitEx C.EVP_DecryptInit_ex
func EVPDecryptInitEx(ctx *EVP_CIPHER_CTX, cipher *EVP_CIPHER, impl *ENGINE, key *uint8, iv *uint8) c.Int

//go:linkname EVPDecryptInitEx2 C.EVP_DecryptInit_ex2
func EVPDecryptInitEx2(ctx *EVP_CIPHER_CTX, cipher *EVP_CIPHER, key *uint8, iv *uint8, params *OSSL_PARAM) c.Int

//go:linkname EVP_DecryptUpdate C.EVP_DecryptUpdate
func EVP_DecryptUpdate(ctx *EVP_CIPHER_CTX, out *uint8, outl *c.Int, in *uint8, inl c.Int) c.Int

//go:linkname EVP_DecryptFinal C.EVP_DecryptFinal
func EVP_DecryptFinal(ctx *EVP_CIPHER_CTX, outm *uint8, outl *c.Int) c.Int

//go:linkname EVPDecryptFinalEx C.EVP_DecryptFinal_ex
func EVPDecryptFinalEx(ctx *EVP_CIPHER_CTX, outm *uint8, outl *c.Int) c.Int

//go:linkname EVP_CipherInit C.EVP_CipherInit
func EVP_CipherInit(ctx *EVP_CIPHER_CTX, cipher *EVP_CIPHER, key *uint8, iv *uint8, enc c.Int) c.Int

//go:linkname EVPCipherInitEx C.EVP_CipherInit_ex
func EVPCipherInitEx(ctx *EVP_CIPHER_CTX, cipher *EVP_CIPHER, impl *ENGINE, key *uint8, iv *uint8, enc c.Int) c.Int

//go:linkname EVP_CipherInit_SKEY C.EVP_CipherInit_SKEY
func EVP_CipherInit_SKEY(ctx *EVP_CIPHER_CTX, cipher *EVP_CIPHER, skey *EVP_SKEY, iv *uint8, iv_len c.SizeT, enc c.Int, params *OSSL_PARAM) c.Int

//go:linkname EVPCipherInitEx2 C.EVP_CipherInit_ex2
func EVPCipherInitEx2(ctx *EVP_CIPHER_CTX, cipher *EVP_CIPHER, key *uint8, iv *uint8, enc c.Int, params *OSSL_PARAM) c.Int

//go:linkname EVP_CipherUpdate C.EVP_CipherUpdate
func EVP_CipherUpdate(ctx *EVP_CIPHER_CTX, out *uint8, outl *c.Int, in *uint8, inl c.Int) c.Int

//go:linkname EVP_CipherFinal C.EVP_CipherFinal
func EVP_CipherFinal(ctx *EVP_CIPHER_CTX, outm *uint8, outl *c.Int) c.Int

//go:linkname EVP_CipherPipelineEncryptInit C.EVP_CipherPipelineEncryptInit
func EVP_CipherPipelineEncryptInit(ctx *EVP_CIPHER_CTX, cipher *EVP_CIPHER, key *uint8, keylen c.SizeT, numpipes c.SizeT, iv **uint8, ivlen c.SizeT) c.Int

//go:linkname EVP_CipherPipelineDecryptInit C.EVP_CipherPipelineDecryptInit
func EVP_CipherPipelineDecryptInit(ctx *EVP_CIPHER_CTX, cipher *EVP_CIPHER, key *uint8, keylen c.SizeT, numpipes c.SizeT, iv **uint8, ivlen c.SizeT) c.Int

//go:linkname EVP_CipherPipelineUpdate C.EVP_CipherPipelineUpdate
func EVP_CipherPipelineUpdate(ctx *EVP_CIPHER_CTX, out **uint8, outl *c.SizeT, outsize *c.SizeT, in **uint8, inl *c.SizeT) c.Int

//go:linkname EVP_CipherPipelineFinal C.EVP_CipherPipelineFinal
func EVP_CipherPipelineFinal(ctx *EVP_CIPHER_CTX, outm **uint8, outl *c.SizeT, outsize *c.SizeT) c.Int

//go:linkname EVPCipherFinalEx C.EVP_CipherFinal_ex
func EVPCipherFinalEx(ctx *EVP_CIPHER_CTX, outm *uint8, outl *c.Int) c.Int

//go:linkname EVP_SignFinal C.EVP_SignFinal
func EVP_SignFinal(ctx *EVP_MD_CTX, md *uint8, s *c.Uint, pkey *EVP_PKEY) c.Int

//go:linkname EVPSignFinalEx C.EVP_SignFinal_ex
func EVPSignFinalEx(ctx *EVP_MD_CTX, md *uint8, s *c.Uint, pkey *EVP_PKEY, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname EVP_DigestSign C.EVP_DigestSign
func EVP_DigestSign(ctx *EVP_MD_CTX, sigret *uint8, siglen *c.SizeT, tbs *uint8, tbslen c.SizeT) c.Int

//go:linkname EVP_VerifyFinal C.EVP_VerifyFinal
func EVP_VerifyFinal(ctx *EVP_MD_CTX, sigbuf *uint8, siglen c.Uint, pkey *EVP_PKEY) c.Int

//go:linkname EVPVerifyFinalEx C.EVP_VerifyFinal_ex
func EVPVerifyFinalEx(ctx *EVP_MD_CTX, sigbuf *uint8, siglen c.Uint, pkey *EVP_PKEY, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname EVP_DigestVerify C.EVP_DigestVerify
func EVP_DigestVerify(ctx *EVP_MD_CTX, sigret *uint8, siglen c.SizeT, tbs *uint8, tbslen c.SizeT) c.Int

//go:linkname EVPDigestSignInitEx C.EVP_DigestSignInit_ex
func EVPDigestSignInitEx(ctx *EVP_MD_CTX, pctx **EVP_PKEY_CTX, mdname *c.Char, libctx *OSSL_LIB_CTX, props *c.Char, pkey *EVP_PKEY, params *OSSL_PARAM) c.Int

//go:linkname EVP_DigestSignInit C.EVP_DigestSignInit
func EVP_DigestSignInit(ctx *EVP_MD_CTX, pctx **EVP_PKEY_CTX, type_ *EVP_MD, e *ENGINE, pkey *EVP_PKEY) c.Int

//go:linkname EVP_DigestSignUpdate C.EVP_DigestSignUpdate
func EVP_DigestSignUpdate(ctx *EVP_MD_CTX, data unsafe.Pointer, dsize c.SizeT) c.Int

//go:linkname EVP_DigestSignFinal C.EVP_DigestSignFinal
func EVP_DigestSignFinal(ctx *EVP_MD_CTX, sigret *uint8, siglen *c.SizeT) c.Int

//go:linkname EVPDigestVerifyInitEx C.EVP_DigestVerifyInit_ex
func EVPDigestVerifyInitEx(ctx *EVP_MD_CTX, pctx **EVP_PKEY_CTX, mdname *c.Char, libctx *OSSL_LIB_CTX, props *c.Char, pkey *EVP_PKEY, params *OSSL_PARAM) c.Int

//go:linkname EVP_DigestVerifyInit C.EVP_DigestVerifyInit
func EVP_DigestVerifyInit(ctx *EVP_MD_CTX, pctx **EVP_PKEY_CTX, type_ *EVP_MD, e *ENGINE, pkey *EVP_PKEY) c.Int

//go:linkname EVP_DigestVerifyUpdate C.EVP_DigestVerifyUpdate
func EVP_DigestVerifyUpdate(ctx *EVP_MD_CTX, data unsafe.Pointer, dsize c.SizeT) c.Int

//go:linkname EVP_DigestVerifyFinal C.EVP_DigestVerifyFinal
func EVP_DigestVerifyFinal(ctx *EVP_MD_CTX, sig *uint8, siglen c.SizeT) c.Int

//go:linkname EVP_OpenInit C.EVP_OpenInit
func EVP_OpenInit(ctx *EVP_CIPHER_CTX, type_ *EVP_CIPHER, ek *uint8, ekl c.Int, iv *uint8, priv *EVP_PKEY) c.Int

//go:linkname EVP_OpenFinal C.EVP_OpenFinal
func EVP_OpenFinal(ctx *EVP_CIPHER_CTX, out *uint8, outl *c.Int) c.Int

//go:linkname EVP_SealInit C.EVP_SealInit
func EVP_SealInit(ctx *EVP_CIPHER_CTX, type_ *EVP_CIPHER, ek **uint8, ekl *c.Int, iv *uint8, pubk **EVP_PKEY, npubk c.Int) c.Int

//go:linkname EVP_SealFinal C.EVP_SealFinal
func EVP_SealFinal(ctx *EVP_CIPHER_CTX, out *uint8, outl *c.Int) c.Int

//go:linkname EVP_ENCODE_CTXNew C.EVP_ENCODE_CTX_new
func EVP_ENCODE_CTXNew() *EVP_ENCODE_CTX

//go:linkname EVP_ENCODE_CTXFree C.EVP_ENCODE_CTX_free
func EVP_ENCODE_CTXFree(ctx *EVP_ENCODE_CTX)

//go:linkname EVP_ENCODE_CTXCopy C.EVP_ENCODE_CTX_copy
func EVP_ENCODE_CTXCopy(dctx *EVP_ENCODE_CTX, sctx *EVP_ENCODE_CTX) c.Int

//go:linkname EVP_ENCODE_CTXNum C.EVP_ENCODE_CTX_num
func EVP_ENCODE_CTXNum(ctx *EVP_ENCODE_CTX) c.Int

//go:linkname EVP_EncodeInit C.EVP_EncodeInit
func EVP_EncodeInit(ctx *EVP_ENCODE_CTX)

//go:linkname EVP_EncodeUpdate C.EVP_EncodeUpdate
func EVP_EncodeUpdate(ctx *EVP_ENCODE_CTX, out *uint8, outl *c.Int, in *uint8, inl c.Int) c.Int

//go:linkname EVP_EncodeFinal C.EVP_EncodeFinal
func EVP_EncodeFinal(ctx *EVP_ENCODE_CTX, out *uint8, outl *c.Int)

//go:linkname EVP_EncodeBlock C.EVP_EncodeBlock
func EVP_EncodeBlock(t *uint8, f *uint8, n c.Int) c.Int

//go:linkname EVP_DecodeInit C.EVP_DecodeInit
func EVP_DecodeInit(ctx *EVP_ENCODE_CTX)

//go:linkname EVP_DecodeUpdate C.EVP_DecodeUpdate
func EVP_DecodeUpdate(ctx *EVP_ENCODE_CTX, out *uint8, outl *c.Int, in *uint8, inl c.Int) c.Int

//go:linkname EVP_DecodeFinal C.EVP_DecodeFinal
func EVP_DecodeFinal(ctx *EVP_ENCODE_CTX, out *uint8, outl *c.Int) c.Int

//go:linkname EVP_DecodeBlock C.EVP_DecodeBlock
func EVP_DecodeBlock(t *uint8, f *uint8, n c.Int) c.Int

//go:linkname EVP_CIPHER_CTXNew C.EVP_CIPHER_CTX_new
func EVP_CIPHER_CTXNew() *EVP_CIPHER_CTX

//go:linkname EVP_CIPHER_CTXReset C.EVP_CIPHER_CTX_reset
func EVP_CIPHER_CTXReset(c *EVP_CIPHER_CTX) c.Int

//go:linkname EVP_CIPHER_CTXFree C.EVP_CIPHER_CTX_free
func EVP_CIPHER_CTXFree(c *EVP_CIPHER_CTX)

//go:linkname EVP_CIPHER_CTXSetKeyLength C.EVP_CIPHER_CTX_set_key_length
func EVP_CIPHER_CTXSetKeyLength(x *EVP_CIPHER_CTX, keylen c.Int) c.Int

//go:linkname EVP_CIPHER_CTXSetPadding C.EVP_CIPHER_CTX_set_padding
func EVP_CIPHER_CTXSetPadding(c *EVP_CIPHER_CTX, pad c.Int) c.Int

//go:linkname EVP_CIPHER_CTXCtrl C.EVP_CIPHER_CTX_ctrl
func EVP_CIPHER_CTXCtrl(ctx *EVP_CIPHER_CTX, type_ c.Int, arg c.Int, ptr unsafe.Pointer) c.Int

//go:linkname EVP_CIPHER_CTXRandKey C.EVP_CIPHER_CTX_rand_key
func EVP_CIPHER_CTXRandKey(ctx *EVP_CIPHER_CTX, key *uint8) c.Int

//go:linkname EVP_CIPHERGetParams C.EVP_CIPHER_get_params
func EVP_CIPHERGetParams(cipher *EVP_CIPHER, params *OSSL_PARAM) c.Int

//go:linkname EVP_CIPHER_CTXSetParams C.EVP_CIPHER_CTX_set_params
func EVP_CIPHER_CTXSetParams(ctx *EVP_CIPHER_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_CIPHER_CTXGetParams C.EVP_CIPHER_CTX_get_params
func EVP_CIPHER_CTXGetParams(ctx *EVP_CIPHER_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_CIPHERGettableParams C.EVP_CIPHER_gettable_params
func EVP_CIPHERGettableParams(cipher *EVP_CIPHER) *OSSL_PARAM

//go:linkname EVP_CIPHERSettableCtxParams C.EVP_CIPHER_settable_ctx_params
func EVP_CIPHERSettableCtxParams(cipher *EVP_CIPHER) *OSSL_PARAM

//go:linkname EVP_CIPHERGettableCtxParams C.EVP_CIPHER_gettable_ctx_params
func EVP_CIPHERGettableCtxParams(cipher *EVP_CIPHER) *OSSL_PARAM

//go:linkname EVP_CIPHER_CTXSettableParams C.EVP_CIPHER_CTX_settable_params
func EVP_CIPHER_CTXSettableParams(ctx *EVP_CIPHER_CTX) *OSSL_PARAM

//go:linkname EVP_CIPHER_CTXGettableParams C.EVP_CIPHER_CTX_gettable_params
func EVP_CIPHER_CTXGettableParams(ctx *EVP_CIPHER_CTX) *OSSL_PARAM

//go:linkname EVP_CIPHER_CTXSetAlgorParams C.EVP_CIPHER_CTX_set_algor_params
func EVP_CIPHER_CTXSetAlgorParams(ctx *EVP_CIPHER_CTX, alg *X509_ALGOR) c.Int

//go:linkname EVP_CIPHER_CTXGetAlgorParams C.EVP_CIPHER_CTX_get_algor_params
func EVP_CIPHER_CTXGetAlgorParams(ctx *EVP_CIPHER_CTX, alg *X509_ALGOR) c.Int

//go:linkname EVP_CIPHER_CTXGetAlgor C.EVP_CIPHER_CTX_get_algor
func EVP_CIPHER_CTXGetAlgor(ctx *EVP_CIPHER_CTX, alg **X509_ALGOR) c.Int

//go:linkname BIO_FMd C.BIO_f_md
func BIO_FMd() *BIO_METHOD

//go:linkname BIO_FBase64 C.BIO_f_base64
func BIO_FBase64() *BIO_METHOD

//go:linkname BIO_FCipher C.BIO_f_cipher
func BIO_FCipher() *BIO_METHOD

//go:linkname BIOSetCipher C.BIO_set_cipher
func BIOSetCipher(b *BIO, c *EVP_CIPHER, k *uint8, i *uint8, enc c.Int) c.Int

//go:linkname EVPMdNull C.EVP_md_null
func EVPMdNull() *EVP_MD

//go:linkname EVPMd4 C.EVP_md4
func EVPMd4() *EVP_MD

//go:linkname EVPMd5 C.EVP_md5
func EVPMd5() *EVP_MD

//go:linkname EVPMd5Sha1 C.EVP_md5_sha1
func EVPMd5Sha1() *EVP_MD

//go:linkname EVPBlake2b512 C.EVP_blake2b512
func EVPBlake2b512() *EVP_MD

//go:linkname EVPBlake2s256 C.EVP_blake2s256
func EVPBlake2s256() *EVP_MD

//go:linkname EVPSha1 C.EVP_sha1
func EVPSha1() *EVP_MD

//go:linkname EVPSha224 C.EVP_sha224
func EVPSha224() *EVP_MD

//go:linkname EVPSha256 C.EVP_sha256
func EVPSha256() *EVP_MD

//go:linkname EVPSha384 C.EVP_sha384
func EVPSha384() *EVP_MD

//go:linkname EVPSha512 C.EVP_sha512
func EVPSha512() *EVP_MD

//go:linkname EVPSha512224 C.EVP_sha512_224
func EVPSha512224() *EVP_MD

//go:linkname EVPSha512256 C.EVP_sha512_256
func EVPSha512256() *EVP_MD

//go:linkname EVPSha3224 C.EVP_sha3_224
func EVPSha3224() *EVP_MD

//go:linkname EVPSha3256 C.EVP_sha3_256
func EVPSha3256() *EVP_MD

//go:linkname EVPSha3384 C.EVP_sha3_384
func EVPSha3384() *EVP_MD

//go:linkname EVPSha3512 C.EVP_sha3_512
func EVPSha3512() *EVP_MD

//go:linkname EVPShake128 C.EVP_shake128
func EVPShake128() *EVP_MD

//go:linkname EVPShake256 C.EVP_shake256
func EVPShake256() *EVP_MD

//go:linkname EVPMdc2 C.EVP_mdc2
func EVPMdc2() *EVP_MD

//go:linkname EVPRipemd160 C.EVP_ripemd160
func EVPRipemd160() *EVP_MD

//go:linkname EVPWhirlpool C.EVP_whirlpool
func EVPWhirlpool() *EVP_MD

//go:linkname EVPSm3 C.EVP_sm3
func EVPSm3() *EVP_MD

//go:linkname EVPEncNull C.EVP_enc_null
func EVPEncNull() *EVP_CIPHER

//go:linkname EVPDesEcb C.EVP_des_ecb
func EVPDesEcb() *EVP_CIPHER

//go:linkname EVPDesEde C.EVP_des_ede
func EVPDesEde() *EVP_CIPHER

//go:linkname EVPDesEde3 C.EVP_des_ede3
func EVPDesEde3() *EVP_CIPHER

//go:linkname EVPDesEdeEcb C.EVP_des_ede_ecb
func EVPDesEdeEcb() *EVP_CIPHER

//go:linkname EVPDesEde3Ecb C.EVP_des_ede3_ecb
func EVPDesEde3Ecb() *EVP_CIPHER

//go:linkname EVPDesCfb64 C.EVP_des_cfb64
func EVPDesCfb64() *EVP_CIPHER

//go:linkname EVPDesCfb1 C.EVP_des_cfb1
func EVPDesCfb1() *EVP_CIPHER

//go:linkname EVPDesCfb8 C.EVP_des_cfb8
func EVPDesCfb8() *EVP_CIPHER

//go:linkname EVPDesEdeCfb64 C.EVP_des_ede_cfb64
func EVPDesEdeCfb64() *EVP_CIPHER

//go:linkname EVPDesEde3Cfb64 C.EVP_des_ede3_cfb64
func EVPDesEde3Cfb64() *EVP_CIPHER

//go:linkname EVPDesEde3Cfb1 C.EVP_des_ede3_cfb1
func EVPDesEde3Cfb1() *EVP_CIPHER

//go:linkname EVPDesEde3Cfb8 C.EVP_des_ede3_cfb8
func EVPDesEde3Cfb8() *EVP_CIPHER

//go:linkname EVPDesOfb C.EVP_des_ofb
func EVPDesOfb() *EVP_CIPHER

//go:linkname EVPDesEdeOfb C.EVP_des_ede_ofb
func EVPDesEdeOfb() *EVP_CIPHER

//go:linkname EVPDesEde3Ofb C.EVP_des_ede3_ofb
func EVPDesEde3Ofb() *EVP_CIPHER

//go:linkname EVPDesCbc C.EVP_des_cbc
func EVPDesCbc() *EVP_CIPHER

//go:linkname EVPDesEdeCbc C.EVP_des_ede_cbc
func EVPDesEdeCbc() *EVP_CIPHER

//go:linkname EVPDesEde3Cbc C.EVP_des_ede3_cbc
func EVPDesEde3Cbc() *EVP_CIPHER

//go:linkname EVPDesxCbc C.EVP_desx_cbc
func EVPDesxCbc() *EVP_CIPHER

//go:linkname EVPDesEde3Wrap C.EVP_des_ede3_wrap
func EVPDesEde3Wrap() *EVP_CIPHER

//go:linkname EVPRc4 C.EVP_rc4
func EVPRc4() *EVP_CIPHER

//go:linkname EVPRc440 C.EVP_rc4_40
func EVPRc440() *EVP_CIPHER

//go:linkname EVPRc4HmacMd5 C.EVP_rc4_hmac_md5
func EVPRc4HmacMd5() *EVP_CIPHER

//go:linkname EVPIdeaEcb C.EVP_idea_ecb
func EVPIdeaEcb() *EVP_CIPHER

//go:linkname EVPIdeaCfb64 C.EVP_idea_cfb64
func EVPIdeaCfb64() *EVP_CIPHER

//go:linkname EVPIdeaOfb C.EVP_idea_ofb
func EVPIdeaOfb() *EVP_CIPHER

//go:linkname EVPIdeaCbc C.EVP_idea_cbc
func EVPIdeaCbc() *EVP_CIPHER

//go:linkname EVPRc2Ecb C.EVP_rc2_ecb
func EVPRc2Ecb() *EVP_CIPHER

//go:linkname EVPRc2Cbc C.EVP_rc2_cbc
func EVPRc2Cbc() *EVP_CIPHER

//go:linkname EVPRc240Cbc C.EVP_rc2_40_cbc
func EVPRc240Cbc() *EVP_CIPHER

//go:linkname EVPRc264Cbc C.EVP_rc2_64_cbc
func EVPRc264Cbc() *EVP_CIPHER

//go:linkname EVPRc2Cfb64 C.EVP_rc2_cfb64
func EVPRc2Cfb64() *EVP_CIPHER

//go:linkname EVPRc2Ofb C.EVP_rc2_ofb
func EVPRc2Ofb() *EVP_CIPHER

//go:linkname EVPBfEcb C.EVP_bf_ecb
func EVPBfEcb() *EVP_CIPHER

//go:linkname EVPBfCbc C.EVP_bf_cbc
func EVPBfCbc() *EVP_CIPHER

//go:linkname EVPBfCfb64 C.EVP_bf_cfb64
func EVPBfCfb64() *EVP_CIPHER

//go:linkname EVPBfOfb C.EVP_bf_ofb
func EVPBfOfb() *EVP_CIPHER

//go:linkname EVPCast5Ecb C.EVP_cast5_ecb
func EVPCast5Ecb() *EVP_CIPHER

//go:linkname EVPCast5Cbc C.EVP_cast5_cbc
func EVPCast5Cbc() *EVP_CIPHER

//go:linkname EVPCast5Cfb64 C.EVP_cast5_cfb64
func EVPCast5Cfb64() *EVP_CIPHER

//go:linkname EVPCast5Ofb C.EVP_cast5_ofb
func EVPCast5Ofb() *EVP_CIPHER

//go:linkname EVPAes128Ecb C.EVP_aes_128_ecb
func EVPAes128Ecb() *EVP_CIPHER

//go:linkname EVPAes128Cbc C.EVP_aes_128_cbc
func EVPAes128Cbc() *EVP_CIPHER

//go:linkname EVPAes128Cfb1 C.EVP_aes_128_cfb1
func EVPAes128Cfb1() *EVP_CIPHER

//go:linkname EVPAes128Cfb8 C.EVP_aes_128_cfb8
func EVPAes128Cfb8() *EVP_CIPHER

//go:linkname EVPAes128Cfb128 C.EVP_aes_128_cfb128
func EVPAes128Cfb128() *EVP_CIPHER

//go:linkname EVPAes128Ofb C.EVP_aes_128_ofb
func EVPAes128Ofb() *EVP_CIPHER

//go:linkname EVPAes128Ctr C.EVP_aes_128_ctr
func EVPAes128Ctr() *EVP_CIPHER

//go:linkname EVPAes128Ccm C.EVP_aes_128_ccm
func EVPAes128Ccm() *EVP_CIPHER

//go:linkname EVPAes128Gcm C.EVP_aes_128_gcm
func EVPAes128Gcm() *EVP_CIPHER

//go:linkname EVPAes128Xts C.EVP_aes_128_xts
func EVPAes128Xts() *EVP_CIPHER

//go:linkname EVPAes128Wrap C.EVP_aes_128_wrap
func EVPAes128Wrap() *EVP_CIPHER

//go:linkname EVPAes128WrapPad C.EVP_aes_128_wrap_pad
func EVPAes128WrapPad() *EVP_CIPHER

//go:linkname EVPAes128Ocb C.EVP_aes_128_ocb
func EVPAes128Ocb() *EVP_CIPHER

//go:linkname EVPAes192Ecb C.EVP_aes_192_ecb
func EVPAes192Ecb() *EVP_CIPHER

//go:linkname EVPAes192Cbc C.EVP_aes_192_cbc
func EVPAes192Cbc() *EVP_CIPHER

//go:linkname EVPAes192Cfb1 C.EVP_aes_192_cfb1
func EVPAes192Cfb1() *EVP_CIPHER

//go:linkname EVPAes192Cfb8 C.EVP_aes_192_cfb8
func EVPAes192Cfb8() *EVP_CIPHER

//go:linkname EVPAes192Cfb128 C.EVP_aes_192_cfb128
func EVPAes192Cfb128() *EVP_CIPHER

//go:linkname EVPAes192Ofb C.EVP_aes_192_ofb
func EVPAes192Ofb() *EVP_CIPHER

//go:linkname EVPAes192Ctr C.EVP_aes_192_ctr
func EVPAes192Ctr() *EVP_CIPHER

//go:linkname EVPAes192Ccm C.EVP_aes_192_ccm
func EVPAes192Ccm() *EVP_CIPHER

//go:linkname EVPAes192Gcm C.EVP_aes_192_gcm
func EVPAes192Gcm() *EVP_CIPHER

//go:linkname EVPAes192Wrap C.EVP_aes_192_wrap
func EVPAes192Wrap() *EVP_CIPHER

//go:linkname EVPAes192WrapPad C.EVP_aes_192_wrap_pad
func EVPAes192WrapPad() *EVP_CIPHER

//go:linkname EVPAes192Ocb C.EVP_aes_192_ocb
func EVPAes192Ocb() *EVP_CIPHER

//go:linkname EVPAes256Ecb C.EVP_aes_256_ecb
func EVPAes256Ecb() *EVP_CIPHER

//go:linkname EVPAes256Cbc C.EVP_aes_256_cbc
func EVPAes256Cbc() *EVP_CIPHER

//go:linkname EVPAes256Cfb1 C.EVP_aes_256_cfb1
func EVPAes256Cfb1() *EVP_CIPHER

//go:linkname EVPAes256Cfb8 C.EVP_aes_256_cfb8
func EVPAes256Cfb8() *EVP_CIPHER

//go:linkname EVPAes256Cfb128 C.EVP_aes_256_cfb128
func EVPAes256Cfb128() *EVP_CIPHER

//go:linkname EVPAes256Ofb C.EVP_aes_256_ofb
func EVPAes256Ofb() *EVP_CIPHER

//go:linkname EVPAes256Ctr C.EVP_aes_256_ctr
func EVPAes256Ctr() *EVP_CIPHER

//go:linkname EVPAes256Ccm C.EVP_aes_256_ccm
func EVPAes256Ccm() *EVP_CIPHER

//go:linkname EVPAes256Gcm C.EVP_aes_256_gcm
func EVPAes256Gcm() *EVP_CIPHER

//go:linkname EVPAes256Xts C.EVP_aes_256_xts
func EVPAes256Xts() *EVP_CIPHER

//go:linkname EVPAes256Wrap C.EVP_aes_256_wrap
func EVPAes256Wrap() *EVP_CIPHER

//go:linkname EVPAes256WrapPad C.EVP_aes_256_wrap_pad
func EVPAes256WrapPad() *EVP_CIPHER

//go:linkname EVPAes256Ocb C.EVP_aes_256_ocb
func EVPAes256Ocb() *EVP_CIPHER

//go:linkname EVPAes128CbcHmacSha1 C.EVP_aes_128_cbc_hmac_sha1
func EVPAes128CbcHmacSha1() *EVP_CIPHER

//go:linkname EVPAes256CbcHmacSha1 C.EVP_aes_256_cbc_hmac_sha1
func EVPAes256CbcHmacSha1() *EVP_CIPHER

//go:linkname EVPAes128CbcHmacSha256 C.EVP_aes_128_cbc_hmac_sha256
func EVPAes128CbcHmacSha256() *EVP_CIPHER

//go:linkname EVPAes256CbcHmacSha256 C.EVP_aes_256_cbc_hmac_sha256
func EVPAes256CbcHmacSha256() *EVP_CIPHER

//go:linkname EVPAria128Ecb C.EVP_aria_128_ecb
func EVPAria128Ecb() *EVP_CIPHER

//go:linkname EVPAria128Cbc C.EVP_aria_128_cbc
func EVPAria128Cbc() *EVP_CIPHER

//go:linkname EVPAria128Cfb1 C.EVP_aria_128_cfb1
func EVPAria128Cfb1() *EVP_CIPHER

//go:linkname EVPAria128Cfb8 C.EVP_aria_128_cfb8
func EVPAria128Cfb8() *EVP_CIPHER

//go:linkname EVPAria128Cfb128 C.EVP_aria_128_cfb128
func EVPAria128Cfb128() *EVP_CIPHER

//go:linkname EVPAria128Ctr C.EVP_aria_128_ctr
func EVPAria128Ctr() *EVP_CIPHER

//go:linkname EVPAria128Ofb C.EVP_aria_128_ofb
func EVPAria128Ofb() *EVP_CIPHER

//go:linkname EVPAria128Gcm C.EVP_aria_128_gcm
func EVPAria128Gcm() *EVP_CIPHER

//go:linkname EVPAria128Ccm C.EVP_aria_128_ccm
func EVPAria128Ccm() *EVP_CIPHER

//go:linkname EVPAria192Ecb C.EVP_aria_192_ecb
func EVPAria192Ecb() *EVP_CIPHER

//go:linkname EVPAria192Cbc C.EVP_aria_192_cbc
func EVPAria192Cbc() *EVP_CIPHER

//go:linkname EVPAria192Cfb1 C.EVP_aria_192_cfb1
func EVPAria192Cfb1() *EVP_CIPHER

//go:linkname EVPAria192Cfb8 C.EVP_aria_192_cfb8
func EVPAria192Cfb8() *EVP_CIPHER

//go:linkname EVPAria192Cfb128 C.EVP_aria_192_cfb128
func EVPAria192Cfb128() *EVP_CIPHER

//go:linkname EVPAria192Ctr C.EVP_aria_192_ctr
func EVPAria192Ctr() *EVP_CIPHER

//go:linkname EVPAria192Ofb C.EVP_aria_192_ofb
func EVPAria192Ofb() *EVP_CIPHER

//go:linkname EVPAria192Gcm C.EVP_aria_192_gcm
func EVPAria192Gcm() *EVP_CIPHER

//go:linkname EVPAria192Ccm C.EVP_aria_192_ccm
func EVPAria192Ccm() *EVP_CIPHER

//go:linkname EVPAria256Ecb C.EVP_aria_256_ecb
func EVPAria256Ecb() *EVP_CIPHER

//go:linkname EVPAria256Cbc C.EVP_aria_256_cbc
func EVPAria256Cbc() *EVP_CIPHER

//go:linkname EVPAria256Cfb1 C.EVP_aria_256_cfb1
func EVPAria256Cfb1() *EVP_CIPHER

//go:linkname EVPAria256Cfb8 C.EVP_aria_256_cfb8
func EVPAria256Cfb8() *EVP_CIPHER

//go:linkname EVPAria256Cfb128 C.EVP_aria_256_cfb128
func EVPAria256Cfb128() *EVP_CIPHER

//go:linkname EVPAria256Ctr C.EVP_aria_256_ctr
func EVPAria256Ctr() *EVP_CIPHER

//go:linkname EVPAria256Ofb C.EVP_aria_256_ofb
func EVPAria256Ofb() *EVP_CIPHER

//go:linkname EVPAria256Gcm C.EVP_aria_256_gcm
func EVPAria256Gcm() *EVP_CIPHER

//go:linkname EVPAria256Ccm C.EVP_aria_256_ccm
func EVPAria256Ccm() *EVP_CIPHER

//go:linkname EVPCamellia128Ecb C.EVP_camellia_128_ecb
func EVPCamellia128Ecb() *EVP_CIPHER

//go:linkname EVPCamellia128Cbc C.EVP_camellia_128_cbc
func EVPCamellia128Cbc() *EVP_CIPHER

//go:linkname EVPCamellia128Cfb1 C.EVP_camellia_128_cfb1
func EVPCamellia128Cfb1() *EVP_CIPHER

//go:linkname EVPCamellia128Cfb8 C.EVP_camellia_128_cfb8
func EVPCamellia128Cfb8() *EVP_CIPHER

//go:linkname EVPCamellia128Cfb128 C.EVP_camellia_128_cfb128
func EVPCamellia128Cfb128() *EVP_CIPHER

//go:linkname EVPCamellia128Ofb C.EVP_camellia_128_ofb
func EVPCamellia128Ofb() *EVP_CIPHER

//go:linkname EVPCamellia128Ctr C.EVP_camellia_128_ctr
func EVPCamellia128Ctr() *EVP_CIPHER

//go:linkname EVPCamellia192Ecb C.EVP_camellia_192_ecb
func EVPCamellia192Ecb() *EVP_CIPHER

//go:linkname EVPCamellia192Cbc C.EVP_camellia_192_cbc
func EVPCamellia192Cbc() *EVP_CIPHER

//go:linkname EVPCamellia192Cfb1 C.EVP_camellia_192_cfb1
func EVPCamellia192Cfb1() *EVP_CIPHER

//go:linkname EVPCamellia192Cfb8 C.EVP_camellia_192_cfb8
func EVPCamellia192Cfb8() *EVP_CIPHER

//go:linkname EVPCamellia192Cfb128 C.EVP_camellia_192_cfb128
func EVPCamellia192Cfb128() *EVP_CIPHER

//go:linkname EVPCamellia192Ofb C.EVP_camellia_192_ofb
func EVPCamellia192Ofb() *EVP_CIPHER

//go:linkname EVPCamellia192Ctr C.EVP_camellia_192_ctr
func EVPCamellia192Ctr() *EVP_CIPHER

//go:linkname EVPCamellia256Ecb C.EVP_camellia_256_ecb
func EVPCamellia256Ecb() *EVP_CIPHER

//go:linkname EVPCamellia256Cbc C.EVP_camellia_256_cbc
func EVPCamellia256Cbc() *EVP_CIPHER

//go:linkname EVPCamellia256Cfb1 C.EVP_camellia_256_cfb1
func EVPCamellia256Cfb1() *EVP_CIPHER

//go:linkname EVPCamellia256Cfb8 C.EVP_camellia_256_cfb8
func EVPCamellia256Cfb8() *EVP_CIPHER

//go:linkname EVPCamellia256Cfb128 C.EVP_camellia_256_cfb128
func EVPCamellia256Cfb128() *EVP_CIPHER

//go:linkname EVPCamellia256Ofb C.EVP_camellia_256_ofb
func EVPCamellia256Ofb() *EVP_CIPHER

//go:linkname EVPCamellia256Ctr C.EVP_camellia_256_ctr
func EVPCamellia256Ctr() *EVP_CIPHER

//go:linkname EVPChacha20 C.EVP_chacha20
func EVPChacha20() *EVP_CIPHER

//go:linkname EVPChacha20Poly1305 C.EVP_chacha20_poly1305
func EVPChacha20Poly1305() *EVP_CIPHER

//go:linkname EVPSeedEcb C.EVP_seed_ecb
func EVPSeedEcb() *EVP_CIPHER

//go:linkname EVPSeedCbc C.EVP_seed_cbc
func EVPSeedCbc() *EVP_CIPHER

//go:linkname EVPSeedCfb128 C.EVP_seed_cfb128
func EVPSeedCfb128() *EVP_CIPHER

//go:linkname EVPSeedOfb C.EVP_seed_ofb
func EVPSeedOfb() *EVP_CIPHER

//go:linkname EVPSm4Ecb C.EVP_sm4_ecb
func EVPSm4Ecb() *EVP_CIPHER

//go:linkname EVPSm4Cbc C.EVP_sm4_cbc
func EVPSm4Cbc() *EVP_CIPHER

//go:linkname EVPSm4Cfb128 C.EVP_sm4_cfb128
func EVPSm4Cfb128() *EVP_CIPHER

//go:linkname EVPSm4Ofb C.EVP_sm4_ofb
func EVPSm4Ofb() *EVP_CIPHER

//go:linkname EVPSm4Ctr C.EVP_sm4_ctr
func EVPSm4Ctr() *EVP_CIPHER

//go:linkname EVPAddCipher C.EVP_add_cipher
func EVPAddCipher(cipher *EVP_CIPHER) c.Int

//go:linkname EVPAddDigest C.EVP_add_digest
func EVPAddDigest(digest *EVP_MD) c.Int

//go:linkname EVPGetCipherbyname C.EVP_get_cipherbyname
func EVPGetCipherbyname(name *c.Char) *EVP_CIPHER

//go:linkname EVPGetDigestbyname C.EVP_get_digestbyname
func EVPGetDigestbyname(name *c.Char) *EVP_MD

//go:linkname EVP_CIPHERDoAll C.EVP_CIPHER_do_all
func EVP_CIPHERDoAll(fn func(_llcppg_param1 *EVP_CIPHER, _llcppg_param2 *c.Char, _llcppg_param3 *c.Char, _llcppg_param4 unsafe.Pointer), arg unsafe.Pointer)

//go:linkname EVP_CIPHERDoAllSorted C.EVP_CIPHER_do_all_sorted
func EVP_CIPHERDoAllSorted(fn func(_llcppg_param1 *EVP_CIPHER, _llcppg_param2 *c.Char, _llcppg_param3 *c.Char, _llcppg_param4 unsafe.Pointer), arg unsafe.Pointer)

//go:linkname EVP_CIPHERDoAllProvided C.EVP_CIPHER_do_all_provided
func EVP_CIPHERDoAllProvided(libctx *OSSL_LIB_CTX, fn func(_llcppg_param1 *EVP_CIPHER, _llcppg_param2 unsafe.Pointer), arg unsafe.Pointer)

//go:linkname EVP_MDDoAll C.EVP_MD_do_all
func EVP_MDDoAll(fn func(_llcppg_param1 *EVP_MD, _llcppg_param2 *c.Char, _llcppg_param3 *c.Char, _llcppg_param4 unsafe.Pointer), arg unsafe.Pointer)

//go:linkname EVP_MDDoAllSorted C.EVP_MD_do_all_sorted
func EVP_MDDoAllSorted(fn func(_llcppg_param1 *EVP_MD, _llcppg_param2 *c.Char, _llcppg_param3 *c.Char, _llcppg_param4 unsafe.Pointer), arg unsafe.Pointer)

//go:linkname EVP_MDDoAllProvided C.EVP_MD_do_all_provided
func EVP_MDDoAllProvided(libctx *OSSL_LIB_CTX, fn func(_llcppg_param1 *EVP_MD, _llcppg_param2 unsafe.Pointer), arg unsafe.Pointer)

// MAC stuff
//
//go:linkname EVP_MACFetch C.EVP_MAC_fetch
func EVP_MACFetch(libctx *OSSL_LIB_CTX, algorithm *c.Char, properties *c.Char) *EVP_MAC

//go:linkname EVP_MACUpRef C.EVP_MAC_up_ref
func EVP_MACUpRef(mac *EVP_MAC) c.Int

//go:linkname EVP_MACFree C.EVP_MAC_free
func EVP_MACFree(mac *EVP_MAC)

//go:linkname EVP_MACGet0Name C.EVP_MAC_get0_name
func EVP_MACGet0Name(mac *EVP_MAC) *c.Char

//go:linkname EVP_MACGet0Description C.EVP_MAC_get0_description
func EVP_MACGet0Description(mac *EVP_MAC) *c.Char

//go:linkname EVP_MACIsA C.EVP_MAC_is_a
func EVP_MACIsA(mac *EVP_MAC, name *c.Char) c.Int

//go:linkname EVP_MACGet0Provider C.EVP_MAC_get0_provider
func EVP_MACGet0Provider(mac *EVP_MAC) *OSSL_PROVIDER

//go:linkname EVP_MACGetParams C.EVP_MAC_get_params
func EVP_MACGetParams(mac *EVP_MAC, params *OSSL_PARAM) c.Int

//go:linkname EVP_MAC_CTXNew C.EVP_MAC_CTX_new
func EVP_MAC_CTXNew(mac *EVP_MAC) *EVP_MAC_CTX

//go:linkname EVP_MAC_CTXFree C.EVP_MAC_CTX_free
func EVP_MAC_CTXFree(ctx *EVP_MAC_CTX)

//go:linkname EVP_MAC_CTXDup C.EVP_MAC_CTX_dup
func EVP_MAC_CTXDup(src *EVP_MAC_CTX) *EVP_MAC_CTX

//go:linkname EVP_MAC_CTXGet0Mac C.EVP_MAC_CTX_get0_mac
func EVP_MAC_CTXGet0Mac(ctx *EVP_MAC_CTX) *EVP_MAC

//go:linkname EVP_MAC_CTXGetParams C.EVP_MAC_CTX_get_params
func EVP_MAC_CTXGetParams(ctx *EVP_MAC_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_MAC_CTXSetParams C.EVP_MAC_CTX_set_params
func EVP_MAC_CTXSetParams(ctx *EVP_MAC_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_MAC_CTXGetMacSize C.EVP_MAC_CTX_get_mac_size
func EVP_MAC_CTXGetMacSize(ctx *EVP_MAC_CTX) c.SizeT

//go:linkname EVP_MAC_CTXGetBlockSize C.EVP_MAC_CTX_get_block_size
func EVP_MAC_CTXGetBlockSize(ctx *EVP_MAC_CTX) c.SizeT

//go:linkname EVP_QMac C.EVP_Q_mac
func EVP_QMac(libctx *OSSL_LIB_CTX, name *c.Char, propq *c.Char, subalg *c.Char, params *OSSL_PARAM, key unsafe.Pointer, keylen c.SizeT, data *uint8, datalen c.SizeT, out *uint8, outsize c.SizeT, outlen *c.SizeT) *uint8

//go:linkname EVP_MACInit C.EVP_MAC_init
func EVP_MACInit(ctx *EVP_MAC_CTX, key *uint8, keylen c.SizeT, params *OSSL_PARAM) c.Int

//go:linkname EVP_MACInitSKEY C.EVP_MAC_init_SKEY
func EVP_MACInitSKEY(ctx *EVP_MAC_CTX, skey *EVP_SKEY, params *OSSL_PARAM) c.Int

//go:linkname EVP_MACUpdate C.EVP_MAC_update
func EVP_MACUpdate(ctx *EVP_MAC_CTX, data *uint8, datalen c.SizeT) c.Int

//go:linkname EVP_MACFinal C.EVP_MAC_final
func EVP_MACFinal(ctx *EVP_MAC_CTX, out *uint8, outl *c.SizeT, outsize c.SizeT) c.Int

//go:linkname EVP_MAC_FinalXOF C.EVP_MAC_finalXOF
func EVP_MAC_FinalXOF(ctx *EVP_MAC_CTX, out *uint8, outsize c.SizeT) c.Int

//go:linkname EVP_MACGettableParams C.EVP_MAC_gettable_params
func EVP_MACGettableParams(mac *EVP_MAC) *OSSL_PARAM

//go:linkname EVP_MACGettableCtxParams C.EVP_MAC_gettable_ctx_params
func EVP_MACGettableCtxParams(mac *EVP_MAC) *OSSL_PARAM

//go:linkname EVP_MACSettableCtxParams C.EVP_MAC_settable_ctx_params
func EVP_MACSettableCtxParams(mac *EVP_MAC) *OSSL_PARAM

//go:linkname EVP_MAC_CTXGettableParams C.EVP_MAC_CTX_gettable_params
func EVP_MAC_CTXGettableParams(ctx *EVP_MAC_CTX) *OSSL_PARAM

//go:linkname EVP_MAC_CTXSettableParams C.EVP_MAC_CTX_settable_params
func EVP_MAC_CTXSettableParams(ctx *EVP_MAC_CTX) *OSSL_PARAM

//go:linkname EVP_MACDoAllProvided C.EVP_MAC_do_all_provided
func EVP_MACDoAllProvided(libctx *OSSL_LIB_CTX, fn func(_llcppg_param1 *EVP_MAC, _llcppg_param2 unsafe.Pointer), arg unsafe.Pointer)

//go:linkname EVP_MACNamesDoAll C.EVP_MAC_names_do_all
func EVP_MACNamesDoAll(mac *EVP_MAC, fn func(_llcppg_param1 *c.Char, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer) c.Int

// RAND stuff
//
//go:linkname EVP_RANDFetch C.EVP_RAND_fetch
func EVP_RANDFetch(libctx *OSSL_LIB_CTX, algorithm *c.Char, properties *c.Char) *EVP_RAND

//go:linkname EVP_RANDUpRef C.EVP_RAND_up_ref
func EVP_RANDUpRef(rand *EVP_RAND) c.Int

//go:linkname EVP_RANDFree C.EVP_RAND_free
func EVP_RANDFree(rand *EVP_RAND)

//go:linkname EVP_RANDGet0Name C.EVP_RAND_get0_name
func EVP_RANDGet0Name(rand *EVP_RAND) *c.Char

//go:linkname EVP_RANDGet0Description C.EVP_RAND_get0_description
func EVP_RANDGet0Description(md *EVP_RAND) *c.Char

//go:linkname EVP_RANDIsA C.EVP_RAND_is_a
func EVP_RANDIsA(rand *EVP_RAND, name *c.Char) c.Int

//go:linkname EVP_RANDGet0Provider C.EVP_RAND_get0_provider
func EVP_RANDGet0Provider(rand *EVP_RAND) *OSSL_PROVIDER

//go:linkname EVP_RANDGetParams C.EVP_RAND_get_params
func EVP_RANDGetParams(rand *EVP_RAND, params *OSSL_PARAM) c.Int

//go:linkname EVP_RAND_CTXNew C.EVP_RAND_CTX_new
func EVP_RAND_CTXNew(rand *EVP_RAND, parent *EVP_RAND_CTX) *EVP_RAND_CTX

//go:linkname EVP_RAND_CTXUpRef C.EVP_RAND_CTX_up_ref
func EVP_RAND_CTXUpRef(ctx *EVP_RAND_CTX) c.Int

//go:linkname EVP_RAND_CTXFree C.EVP_RAND_CTX_free
func EVP_RAND_CTXFree(ctx *EVP_RAND_CTX)

//go:linkname EVP_RAND_CTXGet0Rand C.EVP_RAND_CTX_get0_rand
func EVP_RAND_CTXGet0Rand(ctx *EVP_RAND_CTX) *EVP_RAND

//go:linkname EVP_RAND_CTXGetParams C.EVP_RAND_CTX_get_params
func EVP_RAND_CTXGetParams(ctx *EVP_RAND_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_RAND_CTXSetParams C.EVP_RAND_CTX_set_params
func EVP_RAND_CTXSetParams(ctx *EVP_RAND_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_RANDGettableParams C.EVP_RAND_gettable_params
func EVP_RANDGettableParams(rand *EVP_RAND) *OSSL_PARAM

//go:linkname EVP_RANDGettableCtxParams C.EVP_RAND_gettable_ctx_params
func EVP_RANDGettableCtxParams(rand *EVP_RAND) *OSSL_PARAM

//go:linkname EVP_RANDSettableCtxParams C.EVP_RAND_settable_ctx_params
func EVP_RANDSettableCtxParams(rand *EVP_RAND) *OSSL_PARAM

//go:linkname EVP_RAND_CTXGettableParams C.EVP_RAND_CTX_gettable_params
func EVP_RAND_CTXGettableParams(ctx *EVP_RAND_CTX) *OSSL_PARAM

//go:linkname EVP_RAND_CTXSettableParams C.EVP_RAND_CTX_settable_params
func EVP_RAND_CTXSettableParams(ctx *EVP_RAND_CTX) *OSSL_PARAM

//go:linkname EVP_RANDDoAllProvided C.EVP_RAND_do_all_provided
func EVP_RANDDoAllProvided(libctx *OSSL_LIB_CTX, fn func(_llcppg_param1 *EVP_RAND, _llcppg_param2 unsafe.Pointer), arg unsafe.Pointer)

//go:linkname EVP_RANDNamesDoAll C.EVP_RAND_names_do_all
func EVP_RANDNamesDoAll(rand *EVP_RAND, fn func(_llcppg_param1 *c.Char, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer) c.Int

//go:linkname EVP_RANDInstantiate C.EVP_RAND_instantiate
func EVP_RANDInstantiate(ctx *EVP_RAND_CTX, strength c.Uint, prediction_resistance c.Int, pstr *uint8, pstr_len c.SizeT, params *OSSL_PARAM) c.Int

//go:linkname EVP_RANDUninstantiate C.EVP_RAND_uninstantiate
func EVP_RANDUninstantiate(ctx *EVP_RAND_CTX) c.Int

//go:linkname EVP_RANDGenerate C.EVP_RAND_generate
func EVP_RANDGenerate(ctx *EVP_RAND_CTX, out *uint8, outlen c.SizeT, strength c.Uint, prediction_resistance c.Int, addin *uint8, addin_len c.SizeT) c.Int

//go:linkname EVP_RANDReseed C.EVP_RAND_reseed
func EVP_RANDReseed(ctx *EVP_RAND_CTX, prediction_resistance c.Int, ent *uint8, ent_len c.SizeT, addin *uint8, addin_len c.SizeT) c.Int

//go:linkname EVP_RANDNonce C.EVP_RAND_nonce
func EVP_RANDNonce(ctx *EVP_RAND_CTX, out *uint8, outlen c.SizeT) c.Int

//go:linkname EVP_RANDEnableLocking C.EVP_RAND_enable_locking
func EVP_RANDEnableLocking(ctx *EVP_RAND_CTX) c.Int

//go:linkname EVP_RANDVerifyZeroization C.EVP_RAND_verify_zeroization
func EVP_RANDVerifyZeroization(ctx *EVP_RAND_CTX) c.Int

//go:linkname EVP_RANDGetStrength C.EVP_RAND_get_strength
func EVP_RANDGetStrength(ctx *EVP_RAND_CTX) c.Uint

//go:linkname EVP_RANDGetState C.EVP_RAND_get_state
func EVP_RANDGetState(ctx *EVP_RAND_CTX) c.Int

//go:linkname EVP_PKEYDecryptOld C.EVP_PKEY_decrypt_old
func EVP_PKEYDecryptOld(dec_key *uint8, enc_key *uint8, enc_key_len c.Int, private_key *EVP_PKEY) c.Int

//go:linkname EVP_PKEYEncryptOld C.EVP_PKEY_encrypt_old
func EVP_PKEYEncryptOld(enc_key *uint8, key *uint8, key_len c.Int, pub_key *EVP_PKEY) c.Int

//go:linkname EVP_PKEYIsA C.EVP_PKEY_is_a
func EVP_PKEYIsA(pkey *EVP_PKEY, name *c.Char) c.Int

//go:linkname EVP_PKEYTypeNamesDoAll C.EVP_PKEY_type_names_do_all
func EVP_PKEYTypeNamesDoAll(pkey *EVP_PKEY, fn func(_llcppg_param1 *c.Char, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer) c.Int

//go:linkname EVP_PKEYType C.EVP_PKEY_type
func EVP_PKEYType(type_ c.Int) c.Int

//go:linkname EVP_PKEYGetId C.EVP_PKEY_get_id
func EVP_PKEYGetId(pkey *EVP_PKEY) c.Int

//go:linkname EVP_PKEYGetBaseId C.EVP_PKEY_get_base_id
func EVP_PKEYGetBaseId(pkey *EVP_PKEY) c.Int

//go:linkname EVP_PKEYGetBits C.EVP_PKEY_get_bits
func EVP_PKEYGetBits(pkey *EVP_PKEY) c.Int

//go:linkname EVP_PKEYGetSecurityBits C.EVP_PKEY_get_security_bits
func EVP_PKEYGetSecurityBits(pkey *EVP_PKEY) c.Int

//go:linkname EVP_PKEYGetSecurityCategory C.EVP_PKEY_get_security_category
func EVP_PKEYGetSecurityCategory(pkey *EVP_PKEY) c.Int

//go:linkname EVP_PKEYGetSize C.EVP_PKEY_get_size
func EVP_PKEYGetSize(pkey *EVP_PKEY) c.Int

//go:linkname EVP_PKEYCanSign C.EVP_PKEY_can_sign
func EVP_PKEYCanSign(pkey *EVP_PKEY) c.Int

//go:linkname EVP_PKEYSetType C.EVP_PKEY_set_type
func EVP_PKEYSetType(pkey *EVP_PKEY, type_ c.Int) c.Int

//go:linkname EVP_PKEYSetTypeStr C.EVP_PKEY_set_type_str
func EVP_PKEYSetTypeStr(pkey *EVP_PKEY, str *c.Char, len c.Int) c.Int

//go:linkname EVP_PKEYSetTypeByKeymgmt C.EVP_PKEY_set_type_by_keymgmt
func EVP_PKEYSetTypeByKeymgmt(pkey *EVP_PKEY, keymgmt *EVP_KEYMGMT) c.Int

//go:linkname EVP_PKEYAssign C.EVP_PKEY_assign
func EVP_PKEYAssign(pkey *EVP_PKEY, type_ c.Int, key unsafe.Pointer) c.Int

//go:linkname EVP_PKEYGet0 C.EVP_PKEY_get0
func EVP_PKEYGet0(pkey *EVP_PKEY) unsafe.Pointer

//go:linkname EVP_PKEYGet0Hmac C.EVP_PKEY_get0_hmac
func EVP_PKEYGet0Hmac(pkey *EVP_PKEY, len *c.SizeT) *uint8

//go:linkname EVP_PKEYGet0Poly1305 C.EVP_PKEY_get0_poly1305
func EVP_PKEYGet0Poly1305(pkey *EVP_PKEY, len *c.SizeT) *uint8

//go:linkname EVP_PKEYGet0Siphash C.EVP_PKEY_get0_siphash
func EVP_PKEYGet0Siphash(pkey *EVP_PKEY, len *c.SizeT) *uint8

//go:linkname EVP_PKEYSet1RSA C.EVP_PKEY_set1_RSA
func EVP_PKEYSet1RSA(pkey *EVP_PKEY, key *RsaSt) c.Int

//go:linkname EVP_PKEYGet0RSA C.EVP_PKEY_get0_RSA
func EVP_PKEYGet0RSA(pkey *EVP_PKEY) *RsaSt

//go:linkname EVP_PKEYGet1RSA C.EVP_PKEY_get1_RSA
func EVP_PKEYGet1RSA(pkey *EVP_PKEY) *RsaSt

//go:linkname EVP_PKEYSet1DSA C.EVP_PKEY_set1_DSA
func EVP_PKEYSet1DSA(pkey *EVP_PKEY, key *DsaSt) c.Int

//go:linkname EVP_PKEYGet0DSA C.EVP_PKEY_get0_DSA
func EVP_PKEYGet0DSA(pkey *EVP_PKEY) *DsaSt

//go:linkname EVP_PKEYGet1DSA C.EVP_PKEY_get1_DSA
func EVP_PKEYGet1DSA(pkey *EVP_PKEY) *DsaSt

//go:linkname EVP_PKEYSet1DH C.EVP_PKEY_set1_DH
func EVP_PKEYSet1DH(pkey *EVP_PKEY, key *DhSt) c.Int

//go:linkname EVP_PKEYGet0DH C.EVP_PKEY_get0_DH
func EVP_PKEYGet0DH(pkey *EVP_PKEY) *DhSt

//go:linkname EVP_PKEYGet1DH C.EVP_PKEY_get1_DH
func EVP_PKEYGet1DH(pkey *EVP_PKEY) *DhSt

//go:linkname EVP_PKEYSet1EC_KEY C.EVP_PKEY_set1_EC_KEY
func EVP_PKEYSet1EC_KEY(pkey *EVP_PKEY, key *EcKeySt) c.Int

//go:linkname EVP_PKEYGet0EC_KEY C.EVP_PKEY_get0_EC_KEY
func EVP_PKEYGet0EC_KEY(pkey *EVP_PKEY) *EcKeySt

//go:linkname EVP_PKEYGet1EC_KEY C.EVP_PKEY_get1_EC_KEY
func EVP_PKEYGet1EC_KEY(pkey *EVP_PKEY) *EcKeySt

//go:linkname EVP_PKEYNew C.EVP_PKEY_new
func EVP_PKEYNew() *EVP_PKEY

//go:linkname EVP_PKEYUpRef C.EVP_PKEY_up_ref
func EVP_PKEYUpRef(pkey *EVP_PKEY) c.Int

//go:linkname EVP_PKEYDup C.EVP_PKEY_dup
func EVP_PKEYDup(pkey *EVP_PKEY) *EVP_PKEY

//go:linkname EVP_PKEYFree C.EVP_PKEY_free
func EVP_PKEYFree(pkey *EVP_PKEY)

//go:linkname EVP_PKEYGet0Description C.EVP_PKEY_get0_description
func EVP_PKEYGet0Description(pkey *EVP_PKEY) *c.Char

//go:linkname EVP_PKEYGet0Provider C.EVP_PKEY_get0_provider
func EVP_PKEYGet0Provider(key *EVP_PKEY) *OSSL_PROVIDER

//go:linkname D2iPublicKey C.d2i_PublicKey
func D2iPublicKey(type_ c.Int, a **EVP_PKEY, pp **uint8, length c.Long) *EVP_PKEY

//go:linkname I2dPublicKey C.i2d_PublicKey
func I2dPublicKey(a *EVP_PKEY, pp **uint8) c.Int

//go:linkname D2iPrivateKeyEx C.d2i_PrivateKey_ex
func D2iPrivateKeyEx(type_ c.Int, a **EVP_PKEY, pp **uint8, length c.Long, libctx *OSSL_LIB_CTX, propq *c.Char) *EVP_PKEY

//go:linkname D2iPrivateKey C.d2i_PrivateKey
func D2iPrivateKey(type_ c.Int, a **EVP_PKEY, pp **uint8, length c.Long) *EVP_PKEY

//go:linkname D2iAutoPrivateKeyEx C.d2i_AutoPrivateKey_ex
func D2iAutoPrivateKeyEx(a **EVP_PKEY, pp **uint8, length c.Long, libctx *OSSL_LIB_CTX, propq *c.Char) *EVP_PKEY

//go:linkname D2iAutoPrivateKey C.d2i_AutoPrivateKey
func D2iAutoPrivateKey(a **EVP_PKEY, pp **uint8, length c.Long) *EVP_PKEY

//go:linkname I2dPrivateKey C.i2d_PrivateKey
func I2dPrivateKey(a *EVP_PKEY, pp **uint8) c.Int

//go:linkname I2dPKCS8PrivateKey C.i2d_PKCS8PrivateKey
func I2dPKCS8PrivateKey(a *EVP_PKEY, pp **uint8) c.Int

//go:linkname I2dKeyParams C.i2d_KeyParams
func I2dKeyParams(a *EVP_PKEY, pp **uint8) c.Int

//go:linkname D2iKeyParams C.d2i_KeyParams
func D2iKeyParams(type_ c.Int, a **EVP_PKEY, pp **uint8, length c.Long) *EVP_PKEY

//go:linkname I2dKeyParamsBio C.i2d_KeyParams_bio
func I2dKeyParamsBio(bp *BIO, pkey *EVP_PKEY) c.Int

//go:linkname D2iKeyParamsBio C.d2i_KeyParams_bio
func D2iKeyParamsBio(type_ c.Int, a **EVP_PKEY, in *BIO) *EVP_PKEY

//go:linkname EVP_PKEYCopyParameters C.EVP_PKEY_copy_parameters
func EVP_PKEYCopyParameters(to *EVP_PKEY, from *EVP_PKEY) c.Int

//go:linkname EVP_PKEYMissingParameters C.EVP_PKEY_missing_parameters
func EVP_PKEYMissingParameters(pkey *EVP_PKEY) c.Int

//go:linkname EVP_PKEYSaveParameters C.EVP_PKEY_save_parameters
func EVP_PKEYSaveParameters(pkey *EVP_PKEY, mode c.Int) c.Int

//go:linkname EVP_PKEYParametersEq C.EVP_PKEY_parameters_eq
func EVP_PKEYParametersEq(a *EVP_PKEY, b *EVP_PKEY) c.Int

//go:linkname EVP_PKEYEq C.EVP_PKEY_eq
func EVP_PKEYEq(a *EVP_PKEY, b *EVP_PKEY) c.Int

//go:linkname EVP_PKEYCmpParameters C.EVP_PKEY_cmp_parameters
func EVP_PKEYCmpParameters(a *EVP_PKEY, b *EVP_PKEY) c.Int

//go:linkname EVP_PKEYCmp C.EVP_PKEY_cmp
func EVP_PKEYCmp(a *EVP_PKEY, b *EVP_PKEY) c.Int

//go:linkname EVP_PKEYPrintPublic C.EVP_PKEY_print_public
func EVP_PKEYPrintPublic(out *BIO, pkey *EVP_PKEY, indent c.Int, pctx *ASN1_PCTX) c.Int

//go:linkname EVP_PKEYPrintPrivate C.EVP_PKEY_print_private
func EVP_PKEYPrintPrivate(out *BIO, pkey *EVP_PKEY, indent c.Int, pctx *ASN1_PCTX) c.Int

//go:linkname EVP_PKEYPrintParams C.EVP_PKEY_print_params
func EVP_PKEYPrintParams(out *BIO, pkey *EVP_PKEY, indent c.Int, pctx *ASN1_PCTX) c.Int

//go:linkname EVP_PKEYPrintPublicFp C.EVP_PKEY_print_public_fp
func EVP_PKEYPrintPublicFp(fp *c.FILE, pkey *EVP_PKEY, indent c.Int, pctx *ASN1_PCTX) c.Int

//go:linkname EVP_PKEYPrintPrivateFp C.EVP_PKEY_print_private_fp
func EVP_PKEYPrintPrivateFp(fp *c.FILE, pkey *EVP_PKEY, indent c.Int, pctx *ASN1_PCTX) c.Int

//go:linkname EVP_PKEYPrintParamsFp C.EVP_PKEY_print_params_fp
func EVP_PKEYPrintParamsFp(fp *c.FILE, pkey *EVP_PKEY, indent c.Int, pctx *ASN1_PCTX) c.Int

//go:linkname EVP_PKEYGetDefaultDigestNid C.EVP_PKEY_get_default_digest_nid
func EVP_PKEYGetDefaultDigestNid(pkey *EVP_PKEY, pnid *c.Int) c.Int

//go:linkname EVP_PKEYGetDefaultDigestName C.EVP_PKEY_get_default_digest_name
func EVP_PKEYGetDefaultDigestName(pkey *EVP_PKEY, mdname *c.Char, mdname_sz c.SizeT) c.Int

//go:linkname EVP_PKEYDigestsignSupportsDigest C.EVP_PKEY_digestsign_supports_digest
func EVP_PKEYDigestsignSupportsDigest(pkey *EVP_PKEY, libctx *OSSL_LIB_CTX, name *c.Char, propq *c.Char) c.Int

//go:linkname EVP_PKEYSet1EncodedPublicKey C.EVP_PKEY_set1_encoded_public_key
func EVP_PKEYSet1EncodedPublicKey(pkey *EVP_PKEY, pub *uint8, publen c.SizeT) c.Int

//go:linkname EVP_PKEYGet1EncodedPublicKey C.EVP_PKEY_get1_encoded_public_key
func EVP_PKEYGet1EncodedPublicKey(pkey *EVP_PKEY, ppub **uint8) c.SizeT

// calls methods
//
//go:linkname EVP_CIPHERParamToAsn1 C.EVP_CIPHER_param_to_asn1
func EVP_CIPHERParamToAsn1(c *EVP_CIPHER_CTX, type_ *ASN1_TYPE) c.Int

//go:linkname EVP_CIPHERAsn1ToParam C.EVP_CIPHER_asn1_to_param
func EVP_CIPHERAsn1ToParam(c *EVP_CIPHER_CTX, type_ *ASN1_TYPE) c.Int

// These are used by EVP_CIPHER methods
//
//go:linkname EVP_CIPHERSetAsn1Iv C.EVP_CIPHER_set_asn1_iv
func EVP_CIPHERSetAsn1Iv(c *EVP_CIPHER_CTX, type_ *ASN1_TYPE) c.Int

//go:linkname EVP_CIPHERGetAsn1Iv C.EVP_CIPHER_get_asn1_iv
func EVP_CIPHERGetAsn1Iv(c *EVP_CIPHER_CTX, type_ *ASN1_TYPE) c.Int

// PKCS5 password based encryption
//
//go:linkname PKCS5PBEKeyivgen C.PKCS5_PBE_keyivgen
func PKCS5PBEKeyivgen(ctx *EVP_CIPHER_CTX, pass *c.Char, passlen c.Int, param *ASN1_TYPE, cipher *EVP_CIPHER, md *EVP_MD, en_de c.Int) c.Int

//go:linkname PKCS5PBEKeyivgenEx C.PKCS5_PBE_keyivgen_ex
func PKCS5PBEKeyivgenEx(cctx *EVP_CIPHER_CTX, pass *c.Char, passlen c.Int, param *ASN1_TYPE, cipher *EVP_CIPHER, md *EVP_MD, en_de c.Int, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname PKCS5_PBKDF2_HMAC_SHA1 C.PKCS5_PBKDF2_HMAC_SHA1
func PKCS5_PBKDF2_HMAC_SHA1(pass *c.Char, passlen c.Int, salt *uint8, saltlen c.Int, iter c.Int, keylen c.Int, out *uint8) c.Int

//go:linkname PKCS5_PBKDF2_HMAC C.PKCS5_PBKDF2_HMAC
func PKCS5_PBKDF2_HMAC(pass *c.Char, passlen c.Int, salt *uint8, saltlen c.Int, iter c.Int, digest *EVP_MD, keylen c.Int, out *uint8) c.Int

//go:linkname PKCS5V2PBEKeyivgen C.PKCS5_v2_PBE_keyivgen
func PKCS5V2PBEKeyivgen(ctx *EVP_CIPHER_CTX, pass *c.Char, passlen c.Int, param *ASN1_TYPE, cipher *EVP_CIPHER, md *EVP_MD, en_de c.Int) c.Int

//go:linkname PKCS5V2PBEKeyivgenEx C.PKCS5_v2_PBE_keyivgen_ex
func PKCS5V2PBEKeyivgenEx(ctx *EVP_CIPHER_CTX, pass *c.Char, passlen c.Int, param *ASN1_TYPE, cipher *EVP_CIPHER, md *EVP_MD, en_de c.Int, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname EVP_PBEScrypt C.EVP_PBE_scrypt
func EVP_PBEScrypt(pass *c.Char, passlen c.SizeT, salt *uint8, saltlen c.SizeT, N c.Uint64T, r c.Uint64T, p c.Uint64T, maxmem c.Uint64T, key *uint8, keylen c.SizeT) c.Int

//go:linkname EVP_PBEScryptEx C.EVP_PBE_scrypt_ex
func EVP_PBEScryptEx(pass *c.Char, passlen c.SizeT, salt *uint8, saltlen c.SizeT, N c.Uint64T, r c.Uint64T, p c.Uint64T, maxmem c.Uint64T, key *uint8, keylen c.SizeT, ctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname PKCS5V2ScryptKeyivgen C.PKCS5_v2_scrypt_keyivgen
func PKCS5V2ScryptKeyivgen(ctx *EVP_CIPHER_CTX, pass *c.Char, passlen c.Int, param *ASN1_TYPE, c *EVP_CIPHER, md *EVP_MD, en_de c.Int) c.Int

//go:linkname PKCS5V2ScryptKeyivgenEx C.PKCS5_v2_scrypt_keyivgen_ex
func PKCS5V2ScryptKeyivgenEx(ctx *EVP_CIPHER_CTX, pass *c.Char, passlen c.Int, param *ASN1_TYPE, c *EVP_CIPHER, md *EVP_MD, en_de c.Int, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname PKCS5PBEAdd C.PKCS5_PBE_add
func PKCS5PBEAdd()

//go:linkname EVP_PBE_CipherInit C.EVP_PBE_CipherInit
func EVP_PBE_CipherInit(pbe_obj *ASN1_OBJECT, pass *c.Char, passlen c.Int, param *ASN1_TYPE, ctx *EVP_CIPHER_CTX, en_de c.Int) c.Int

//go:linkname EVP_PBECipherInitEx C.EVP_PBE_CipherInit_ex
func EVP_PBECipherInitEx(pbe_obj *ASN1_OBJECT, pass *c.Char, passlen c.Int, param *ASN1_TYPE, ctx *EVP_CIPHER_CTX, en_de c.Int, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname EVP_PBEAlgAddType C.EVP_PBE_alg_add_type
func EVP_PBEAlgAddType(pbe_type c.Int, pbe_nid c.Int, cipher_nid c.Int, md_nid c.Int, keygen *EVP_PBE_KEYGEN) c.Int

//go:linkname EVP_PBEAlgAdd C.EVP_PBE_alg_add
func EVP_PBEAlgAdd(nid c.Int, cipher *EVP_CIPHER, md *EVP_MD, keygen *EVP_PBE_KEYGEN) c.Int

//go:linkname EVP_PBEFind C.EVP_PBE_find
func EVP_PBEFind(type_ c.Int, pbe_nid c.Int, pcnid *c.Int, pmnid *c.Int, pkeygen **EVP_PBE_KEYGEN) c.Int

//go:linkname EVP_PBEFindEx C.EVP_PBE_find_ex
func EVP_PBEFindEx(type_ c.Int, pbe_nid c.Int, pcnid *c.Int, pmnid *c.Int, pkeygen **EVP_PBE_KEYGEN, pkeygen_ex **EVP_PBE_KEYGEN_EX) c.Int

//go:linkname EVP_PBECleanup C.EVP_PBE_cleanup
func EVP_PBECleanup()

//go:linkname EVP_PBEGet C.EVP_PBE_get
func EVP_PBEGet(ptype *c.Int, ppbe_nid *c.Int, num c.SizeT) c.Int

//go:linkname EVP_PKEY_CTXGetSignatureMd C.EVP_PKEY_CTX_get_signature_md
func EVP_PKEY_CTXGetSignatureMd(ctx *EVP_PKEY_CTX, md **EVP_MD) c.Int

//go:linkname EVP_PKEY_CTXSetSignatureMd C.EVP_PKEY_CTX_set_signature_md
func EVP_PKEY_CTXSetSignatureMd(ctx *EVP_PKEY_CTX, md *EVP_MD) c.Int

//go:linkname EVP_PKEY_CTXSet1Id C.EVP_PKEY_CTX_set1_id
func EVP_PKEY_CTXSet1Id(ctx *EVP_PKEY_CTX, id unsafe.Pointer, len c.Int) c.Int

//go:linkname EVP_PKEY_CTXGet1Id C.EVP_PKEY_CTX_get1_id
func EVP_PKEY_CTXGet1Id(ctx *EVP_PKEY_CTX, id unsafe.Pointer) c.Int

//go:linkname EVP_PKEY_CTXGet1IdLen C.EVP_PKEY_CTX_get1_id_len
func EVP_PKEY_CTXGet1IdLen(ctx *EVP_PKEY_CTX, id_len *c.SizeT) c.Int

//go:linkname EVP_PKEY_CTXSetKemOp C.EVP_PKEY_CTX_set_kem_op
func EVP_PKEY_CTXSetKemOp(ctx *EVP_PKEY_CTX, op *c.Char) c.Int

//go:linkname EVP_PKEYGet0TypeName C.EVP_PKEY_get0_type_name
func EVP_PKEYGet0TypeName(key *EVP_PKEY) *c.Char

//go:linkname EVP_PKEY_CTXSetMacKey C.EVP_PKEY_CTX_set_mac_key
func EVP_PKEY_CTXSetMacKey(ctx *EVP_PKEY_CTX, key *uint8, keylen c.Int) c.Int

//go:linkname EVP_KEYMGMTFetch C.EVP_KEYMGMT_fetch
func EVP_KEYMGMTFetch(ctx *OSSL_LIB_CTX, algorithm *c.Char, properties *c.Char) *EVP_KEYMGMT

//go:linkname EVP_KEYMGMTUpRef C.EVP_KEYMGMT_up_ref
func EVP_KEYMGMTUpRef(keymgmt *EVP_KEYMGMT) c.Int

//go:linkname EVP_KEYMGMTFree C.EVP_KEYMGMT_free
func EVP_KEYMGMTFree(keymgmt *EVP_KEYMGMT)

//go:linkname EVP_KEYMGMTGet0Provider C.EVP_KEYMGMT_get0_provider
func EVP_KEYMGMTGet0Provider(keymgmt *EVP_KEYMGMT) *OSSL_PROVIDER

//go:linkname EVP_KEYMGMTGet0Name C.EVP_KEYMGMT_get0_name
func EVP_KEYMGMTGet0Name(keymgmt *EVP_KEYMGMT) *c.Char

//go:linkname EVP_KEYMGMTGet0Description C.EVP_KEYMGMT_get0_description
func EVP_KEYMGMTGet0Description(keymgmt *EVP_KEYMGMT) *c.Char

//go:linkname EVP_KEYMGMTIsA C.EVP_KEYMGMT_is_a
func EVP_KEYMGMTIsA(keymgmt *EVP_KEYMGMT, name *c.Char) c.Int

//go:linkname EVP_KEYMGMTDoAllProvided C.EVP_KEYMGMT_do_all_provided
func EVP_KEYMGMTDoAllProvided(libctx *OSSL_LIB_CTX, fn func(_llcppg_param1 *EVP_KEYMGMT, _llcppg_param2 unsafe.Pointer), arg unsafe.Pointer)

//go:linkname EVP_KEYMGMTNamesDoAll C.EVP_KEYMGMT_names_do_all
func EVP_KEYMGMTNamesDoAll(keymgmt *EVP_KEYMGMT, fn func(_llcppg_param1 *c.Char, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer) c.Int

//go:linkname EVP_KEYMGMTGettableParams C.EVP_KEYMGMT_gettable_params
func EVP_KEYMGMTGettableParams(keymgmt *EVP_KEYMGMT) *OSSL_PARAM

//go:linkname EVP_KEYMGMTSettableParams C.EVP_KEYMGMT_settable_params
func EVP_KEYMGMTSettableParams(keymgmt *EVP_KEYMGMT) *OSSL_PARAM

//go:linkname EVP_KEYMGMTGenSettableParams C.EVP_KEYMGMT_gen_settable_params
func EVP_KEYMGMTGenSettableParams(keymgmt *EVP_KEYMGMT) *OSSL_PARAM

//go:linkname EVP_KEYMGMTGenGettableParams C.EVP_KEYMGMT_gen_gettable_params
func EVP_KEYMGMTGenGettableParams(keymgmt *EVP_KEYMGMT) *OSSL_PARAM

//go:linkname EVP_SKEYMGMTFetch C.EVP_SKEYMGMT_fetch
func EVP_SKEYMGMTFetch(ctx *OSSL_LIB_CTX, algorithm *c.Char, properties *c.Char) *EVP_SKEYMGMT

//go:linkname EVP_SKEYMGMTUpRef C.EVP_SKEYMGMT_up_ref
func EVP_SKEYMGMTUpRef(keymgmt *EVP_SKEYMGMT) c.Int

//go:linkname EVP_SKEYMGMTFree C.EVP_SKEYMGMT_free
func EVP_SKEYMGMTFree(keymgmt *EVP_SKEYMGMT)

//go:linkname EVP_SKEYMGMTGet0Provider C.EVP_SKEYMGMT_get0_provider
func EVP_SKEYMGMTGet0Provider(keymgmt *EVP_SKEYMGMT) *OSSL_PROVIDER

//go:linkname EVP_SKEYMGMTGet0Name C.EVP_SKEYMGMT_get0_name
func EVP_SKEYMGMTGet0Name(keymgmt *EVP_SKEYMGMT) *c.Char

//go:linkname EVP_SKEYMGMTGet0Description C.EVP_SKEYMGMT_get0_description
func EVP_SKEYMGMTGet0Description(keymgmt *EVP_SKEYMGMT) *c.Char

//go:linkname EVP_SKEYMGMTIsA C.EVP_SKEYMGMT_is_a
func EVP_SKEYMGMTIsA(keymgmt *EVP_SKEYMGMT, name *c.Char) c.Int

//go:linkname EVP_SKEYMGMTDoAllProvided C.EVP_SKEYMGMT_do_all_provided
func EVP_SKEYMGMTDoAllProvided(libctx *OSSL_LIB_CTX, fn func(_llcppg_param1 *EVP_SKEYMGMT, _llcppg_param2 unsafe.Pointer), arg unsafe.Pointer)

//go:linkname EVP_SKEYMGMTNamesDoAll C.EVP_SKEYMGMT_names_do_all
func EVP_SKEYMGMTNamesDoAll(keymgmt *EVP_SKEYMGMT, fn func(_llcppg_param1 *c.Char, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer) c.Int

//go:linkname EVP_SKEYMGMTGet0GenSettableParams C.EVP_SKEYMGMT_get0_gen_settable_params
func EVP_SKEYMGMTGet0GenSettableParams(skeymgmt *EVP_SKEYMGMT) *OSSL_PARAM

//go:linkname EVP_SKEYMGMTGet0ImpSettableParams C.EVP_SKEYMGMT_get0_imp_settable_params
func EVP_SKEYMGMTGet0ImpSettableParams(skeymgmt *EVP_SKEYMGMT) *OSSL_PARAM

//go:linkname EVP_PKEY_CTXNew C.EVP_PKEY_CTX_new
func EVP_PKEY_CTXNew(pkey *EVP_PKEY, e *ENGINE) *EVP_PKEY_CTX

//go:linkname EVP_PKEY_CTXNewId C.EVP_PKEY_CTX_new_id
func EVP_PKEY_CTXNewId(id c.Int, e *ENGINE) *EVP_PKEY_CTX

//go:linkname EVP_PKEY_CTXNewFromName C.EVP_PKEY_CTX_new_from_name
func EVP_PKEY_CTXNewFromName(libctx *OSSL_LIB_CTX, name *c.Char, propquery *c.Char) *EVP_PKEY_CTX

//go:linkname EVP_PKEY_CTXNewFromPkey C.EVP_PKEY_CTX_new_from_pkey
func EVP_PKEY_CTXNewFromPkey(libctx *OSSL_LIB_CTX, pkey *EVP_PKEY, propquery *c.Char) *EVP_PKEY_CTX

//go:linkname EVP_PKEY_CTXDup C.EVP_PKEY_CTX_dup
func EVP_PKEY_CTXDup(ctx *EVP_PKEY_CTX) *EVP_PKEY_CTX

//go:linkname EVP_PKEY_CTXFree C.EVP_PKEY_CTX_free
func EVP_PKEY_CTXFree(ctx *EVP_PKEY_CTX)

//go:linkname EVP_PKEY_CTXIsA C.EVP_PKEY_CTX_is_a
func EVP_PKEY_CTXIsA(ctx *EVP_PKEY_CTX, keytype *c.Char) c.Int

//go:linkname EVP_PKEY_CTXGetParams C.EVP_PKEY_CTX_get_params
func EVP_PKEY_CTXGetParams(ctx *EVP_PKEY_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEY_CTXGettableParams C.EVP_PKEY_CTX_gettable_params
func EVP_PKEY_CTXGettableParams(ctx *EVP_PKEY_CTX) *OSSL_PARAM

//go:linkname EVP_PKEY_CTXSetParams C.EVP_PKEY_CTX_set_params
func EVP_PKEY_CTXSetParams(ctx *EVP_PKEY_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEY_CTXSettableParams C.EVP_PKEY_CTX_settable_params
func EVP_PKEY_CTXSettableParams(ctx *EVP_PKEY_CTX) *OSSL_PARAM

//go:linkname EVP_PKEY_CTXSetAlgorParams C.EVP_PKEY_CTX_set_algor_params
func EVP_PKEY_CTXSetAlgorParams(ctx *EVP_PKEY_CTX, alg *X509_ALGOR) c.Int

//go:linkname EVP_PKEY_CTXGetAlgorParams C.EVP_PKEY_CTX_get_algor_params
func EVP_PKEY_CTXGetAlgorParams(ctx *EVP_PKEY_CTX, alg *X509_ALGOR) c.Int

//go:linkname EVP_PKEY_CTXGetAlgor C.EVP_PKEY_CTX_get_algor
func EVP_PKEY_CTXGetAlgor(ctx *EVP_PKEY_CTX, alg **X509_ALGOR) c.Int

//go:linkname EVP_PKEY_CTXCtrl C.EVP_PKEY_CTX_ctrl
func EVP_PKEY_CTXCtrl(ctx *EVP_PKEY_CTX, keytype c.Int, optype c.Int, cmd c.Int, p1 c.Int, p2 unsafe.Pointer) c.Int

//go:linkname EVP_PKEY_CTXCtrlStr C.EVP_PKEY_CTX_ctrl_str
func EVP_PKEY_CTXCtrlStr(ctx *EVP_PKEY_CTX, type_ *c.Char, value *c.Char) c.Int

//go:linkname EVP_PKEY_CTXCtrlUint64 C.EVP_PKEY_CTX_ctrl_uint64
func EVP_PKEY_CTXCtrlUint64(ctx *EVP_PKEY_CTX, keytype c.Int, optype c.Int, cmd c.Int, value c.Uint64T) c.Int

//go:linkname EVP_PKEY_CTXStr2ctrl C.EVP_PKEY_CTX_str2ctrl
func EVP_PKEY_CTXStr2ctrl(ctx *EVP_PKEY_CTX, cmd c.Int, str *c.Char) c.Int

//go:linkname EVP_PKEY_CTXHex2ctrl C.EVP_PKEY_CTX_hex2ctrl
func EVP_PKEY_CTXHex2ctrl(ctx *EVP_PKEY_CTX, cmd c.Int, hex *c.Char) c.Int

//go:linkname EVP_PKEY_CTXMd C.EVP_PKEY_CTX_md
func EVP_PKEY_CTXMd(ctx *EVP_PKEY_CTX, optype c.Int, cmd c.Int, md *c.Char) c.Int

//go:linkname EVP_PKEY_CTXGetOperation C.EVP_PKEY_CTX_get_operation
func EVP_PKEY_CTXGetOperation(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEY_CTXSet0KeygenInfo C.EVP_PKEY_CTX_set0_keygen_info
func EVP_PKEY_CTXSet0KeygenInfo(ctx *EVP_PKEY_CTX, dat *c.Int, datlen c.Int)

//go:linkname EVP_PKEYNewMacKey C.EVP_PKEY_new_mac_key
func EVP_PKEYNewMacKey(type_ c.Int, e *ENGINE, key *uint8, keylen c.Int) *EVP_PKEY

//go:linkname EVP_PKEYNewRawPrivateKeyEx C.EVP_PKEY_new_raw_private_key_ex
func EVP_PKEYNewRawPrivateKeyEx(libctx *OSSL_LIB_CTX, keytype *c.Char, propq *c.Char, priv *uint8, len c.SizeT) *EVP_PKEY

//go:linkname EVP_PKEYNewRawPrivateKey C.EVP_PKEY_new_raw_private_key
func EVP_PKEYNewRawPrivateKey(type_ c.Int, e *ENGINE, priv *uint8, len c.SizeT) *EVP_PKEY

//go:linkname EVP_PKEYNewRawPublicKeyEx C.EVP_PKEY_new_raw_public_key_ex
func EVP_PKEYNewRawPublicKeyEx(libctx *OSSL_LIB_CTX, keytype *c.Char, propq *c.Char, pub *uint8, len c.SizeT) *EVP_PKEY

//go:linkname EVP_PKEYNewRawPublicKey C.EVP_PKEY_new_raw_public_key
func EVP_PKEYNewRawPublicKey(type_ c.Int, e *ENGINE, pub *uint8, len c.SizeT) *EVP_PKEY

//go:linkname EVP_PKEYGetRawPrivateKey C.EVP_PKEY_get_raw_private_key
func EVP_PKEYGetRawPrivateKey(pkey *EVP_PKEY, priv *uint8, len *c.SizeT) c.Int

//go:linkname EVP_PKEYGetRawPublicKey C.EVP_PKEY_get_raw_public_key
func EVP_PKEYGetRawPublicKey(pkey *EVP_PKEY, pub *uint8, len *c.SizeT) c.Int

//go:linkname EVP_PKEYNewCMACKey C.EVP_PKEY_new_CMAC_key
func EVP_PKEYNewCMACKey(e *ENGINE, priv *uint8, len c.SizeT, cipher *EVP_CIPHER) *EVP_PKEY

//go:linkname EVP_PKEY_CTXSetData C.EVP_PKEY_CTX_set_data
func EVP_PKEY_CTXSetData(ctx *EVP_PKEY_CTX, data unsafe.Pointer)

//go:linkname EVP_PKEY_CTXGetData C.EVP_PKEY_CTX_get_data
func EVP_PKEY_CTXGetData(ctx *EVP_PKEY_CTX) unsafe.Pointer

//go:linkname EVP_PKEY_CTXGet0Pkey C.EVP_PKEY_CTX_get0_pkey
func EVP_PKEY_CTXGet0Pkey(ctx *EVP_PKEY_CTX) *EVP_PKEY

//go:linkname EVP_PKEY_CTXGet0Peerkey C.EVP_PKEY_CTX_get0_peerkey
func EVP_PKEY_CTXGet0Peerkey(ctx *EVP_PKEY_CTX) *EVP_PKEY

//go:linkname EVP_PKEY_CTXSetAppData C.EVP_PKEY_CTX_set_app_data
func EVP_PKEY_CTXSetAppData(ctx *EVP_PKEY_CTX, data unsafe.Pointer)

//go:linkname EVP_PKEY_CTXGetAppData C.EVP_PKEY_CTX_get_app_data
func EVP_PKEY_CTXGetAppData(ctx *EVP_PKEY_CTX) unsafe.Pointer

//go:linkname EVP_PKEY_CTXSetSignature C.EVP_PKEY_CTX_set_signature
func EVP_PKEY_CTXSetSignature(pctx *EVP_PKEY_CTX, sig *uint8, siglen c.SizeT) c.Int

//go:linkname EVP_SIGNATUREFree C.EVP_SIGNATURE_free
func EVP_SIGNATUREFree(signature *EVP_SIGNATURE)

//go:linkname EVP_SIGNATUREUpRef C.EVP_SIGNATURE_up_ref
func EVP_SIGNATUREUpRef(signature *EVP_SIGNATURE) c.Int

//go:linkname EVP_SIGNATUREGet0Provider C.EVP_SIGNATURE_get0_provider
func EVP_SIGNATUREGet0Provider(signature *EVP_SIGNATURE) *OSSL_PROVIDER

//go:linkname EVP_SIGNATUREFetch C.EVP_SIGNATURE_fetch
func EVP_SIGNATUREFetch(ctx *OSSL_LIB_CTX, algorithm *c.Char, properties *c.Char) *EVP_SIGNATURE

//go:linkname EVP_SIGNATUREIsA C.EVP_SIGNATURE_is_a
func EVP_SIGNATUREIsA(signature *EVP_SIGNATURE, name *c.Char) c.Int

//go:linkname EVP_SIGNATUREGet0Name C.EVP_SIGNATURE_get0_name
func EVP_SIGNATUREGet0Name(signature *EVP_SIGNATURE) *c.Char

//go:linkname EVP_SIGNATUREGet0Description C.EVP_SIGNATURE_get0_description
func EVP_SIGNATUREGet0Description(signature *EVP_SIGNATURE) *c.Char

//go:linkname EVP_SIGNATUREDoAllProvided C.EVP_SIGNATURE_do_all_provided
func EVP_SIGNATUREDoAllProvided(libctx *OSSL_LIB_CTX, fn func(_llcppg_param1 *EVP_SIGNATURE, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer)

//go:linkname EVP_SIGNATURENamesDoAll C.EVP_SIGNATURE_names_do_all
func EVP_SIGNATURENamesDoAll(signature *EVP_SIGNATURE, fn func(_llcppg_param1 *c.Char, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer) c.Int

//go:linkname EVP_SIGNATUREGettableCtxParams C.EVP_SIGNATURE_gettable_ctx_params
func EVP_SIGNATUREGettableCtxParams(sig *EVP_SIGNATURE) *OSSL_PARAM

//go:linkname EVP_SIGNATURESettableCtxParams C.EVP_SIGNATURE_settable_ctx_params
func EVP_SIGNATURESettableCtxParams(sig *EVP_SIGNATURE) *OSSL_PARAM

//go:linkname EVP_SIGNATUREHasMessageUpdate C.EVP_SIGNATURE_has_message_update
func EVP_SIGNATUREHasMessageUpdate(sig *EVP_SIGNATURE) c.Int

//go:linkname EVP_ASYM_CIPHERFree C.EVP_ASYM_CIPHER_free
func EVP_ASYM_CIPHERFree(cipher *EVP_ASYM_CIPHER)

//go:linkname EVP_ASYM_CIPHERUpRef C.EVP_ASYM_CIPHER_up_ref
func EVP_ASYM_CIPHERUpRef(cipher *EVP_ASYM_CIPHER) c.Int

//go:linkname EVP_ASYM_CIPHERGet0Provider C.EVP_ASYM_CIPHER_get0_provider
func EVP_ASYM_CIPHERGet0Provider(cipher *EVP_ASYM_CIPHER) *OSSL_PROVIDER

//go:linkname EVP_ASYM_CIPHERFetch C.EVP_ASYM_CIPHER_fetch
func EVP_ASYM_CIPHERFetch(ctx *OSSL_LIB_CTX, algorithm *c.Char, properties *c.Char) *EVP_ASYM_CIPHER

//go:linkname EVP_ASYM_CIPHERIsA C.EVP_ASYM_CIPHER_is_a
func EVP_ASYM_CIPHERIsA(cipher *EVP_ASYM_CIPHER, name *c.Char) c.Int

//go:linkname EVP_ASYM_CIPHERGet0Name C.EVP_ASYM_CIPHER_get0_name
func EVP_ASYM_CIPHERGet0Name(cipher *EVP_ASYM_CIPHER) *c.Char

//go:linkname EVP_ASYM_CIPHERGet0Description C.EVP_ASYM_CIPHER_get0_description
func EVP_ASYM_CIPHERGet0Description(cipher *EVP_ASYM_CIPHER) *c.Char

//go:linkname EVP_ASYM_CIPHERDoAllProvided C.EVP_ASYM_CIPHER_do_all_provided
func EVP_ASYM_CIPHERDoAllProvided(libctx *OSSL_LIB_CTX, fn func(_llcppg_param1 *EVP_ASYM_CIPHER, _llcppg_param2 unsafe.Pointer), arg unsafe.Pointer)

//go:linkname EVP_ASYM_CIPHERNamesDoAll C.EVP_ASYM_CIPHER_names_do_all
func EVP_ASYM_CIPHERNamesDoAll(cipher *EVP_ASYM_CIPHER, fn func(_llcppg_param1 *c.Char, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer) c.Int

//go:linkname EVP_ASYM_CIPHERGettableCtxParams C.EVP_ASYM_CIPHER_gettable_ctx_params
func EVP_ASYM_CIPHERGettableCtxParams(ciph *EVP_ASYM_CIPHER) *OSSL_PARAM

//go:linkname EVP_ASYM_CIPHERSettableCtxParams C.EVP_ASYM_CIPHER_settable_ctx_params
func EVP_ASYM_CIPHERSettableCtxParams(ciph *EVP_ASYM_CIPHER) *OSSL_PARAM

//go:linkname EVP_KEMFree C.EVP_KEM_free
func EVP_KEMFree(wrap *EVP_KEM)

//go:linkname EVP_KEMUpRef C.EVP_KEM_up_ref
func EVP_KEMUpRef(wrap *EVP_KEM) c.Int

//go:linkname EVP_KEMGet0Provider C.EVP_KEM_get0_provider
func EVP_KEMGet0Provider(wrap *EVP_KEM) *OSSL_PROVIDER

//go:linkname EVP_KEMFetch C.EVP_KEM_fetch
func EVP_KEMFetch(ctx *OSSL_LIB_CTX, algorithm *c.Char, properties *c.Char) *EVP_KEM

//go:linkname EVP_KEMIsA C.EVP_KEM_is_a
func EVP_KEMIsA(wrap *EVP_KEM, name *c.Char) c.Int

//go:linkname EVP_KEMGet0Name C.EVP_KEM_get0_name
func EVP_KEMGet0Name(wrap *EVP_KEM) *c.Char

//go:linkname EVP_KEMGet0Description C.EVP_KEM_get0_description
func EVP_KEMGet0Description(wrap *EVP_KEM) *c.Char

//go:linkname EVP_KEMDoAllProvided C.EVP_KEM_do_all_provided
func EVP_KEMDoAllProvided(libctx *OSSL_LIB_CTX, fn func(_llcppg_param1 *EVP_KEM, _llcppg_param2 unsafe.Pointer), arg unsafe.Pointer)

//go:linkname EVP_KEMNamesDoAll C.EVP_KEM_names_do_all
func EVP_KEMNamesDoAll(wrap *EVP_KEM, fn func(_llcppg_param1 *c.Char, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer) c.Int

//go:linkname EVP_KEMGettableCtxParams C.EVP_KEM_gettable_ctx_params
func EVP_KEMGettableCtxParams(kem *EVP_KEM) *OSSL_PARAM

//go:linkname EVP_KEMSettableCtxParams C.EVP_KEM_settable_ctx_params
func EVP_KEMSettableCtxParams(kem *EVP_KEM) *OSSL_PARAM

//go:linkname EVP_PKEYSignInit C.EVP_PKEY_sign_init
func EVP_PKEYSignInit(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYSignInitEx C.EVP_PKEY_sign_init_ex
func EVP_PKEYSignInitEx(ctx *EVP_PKEY_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYSignInitEx2 C.EVP_PKEY_sign_init_ex2
func EVP_PKEYSignInitEx2(ctx *EVP_PKEY_CTX, algo *EVP_SIGNATURE, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYSign C.EVP_PKEY_sign
func EVP_PKEYSign(ctx *EVP_PKEY_CTX, sig *uint8, siglen *c.SizeT, tbs *uint8, tbslen c.SizeT) c.Int

//go:linkname EVP_PKEYSignMessageInit C.EVP_PKEY_sign_message_init
func EVP_PKEYSignMessageInit(ctx *EVP_PKEY_CTX, algo *EVP_SIGNATURE, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYSignMessageUpdate C.EVP_PKEY_sign_message_update
func EVP_PKEYSignMessageUpdate(ctx *EVP_PKEY_CTX, in *uint8, inlen c.SizeT) c.Int

//go:linkname EVP_PKEYSignMessageFinal C.EVP_PKEY_sign_message_final
func EVP_PKEYSignMessageFinal(ctx *EVP_PKEY_CTX, sig *uint8, siglen *c.SizeT) c.Int

//go:linkname EVP_PKEYVerifyInit C.EVP_PKEY_verify_init
func EVP_PKEYVerifyInit(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYVerifyInitEx C.EVP_PKEY_verify_init_ex
func EVP_PKEYVerifyInitEx(ctx *EVP_PKEY_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYVerifyInitEx2 C.EVP_PKEY_verify_init_ex2
func EVP_PKEYVerifyInitEx2(ctx *EVP_PKEY_CTX, algo *EVP_SIGNATURE, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYVerify C.EVP_PKEY_verify
func EVP_PKEYVerify(ctx *EVP_PKEY_CTX, sig *uint8, siglen c.SizeT, tbs *uint8, tbslen c.SizeT) c.Int

//go:linkname EVP_PKEYVerifyMessageInit C.EVP_PKEY_verify_message_init
func EVP_PKEYVerifyMessageInit(ctx *EVP_PKEY_CTX, algo *EVP_SIGNATURE, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYVerifyMessageUpdate C.EVP_PKEY_verify_message_update
func EVP_PKEYVerifyMessageUpdate(ctx *EVP_PKEY_CTX, in *uint8, inlen c.SizeT) c.Int

//go:linkname EVP_PKEYVerifyMessageFinal C.EVP_PKEY_verify_message_final
func EVP_PKEYVerifyMessageFinal(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYVerifyRecoverInit C.EVP_PKEY_verify_recover_init
func EVP_PKEYVerifyRecoverInit(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYVerifyRecoverInitEx C.EVP_PKEY_verify_recover_init_ex
func EVP_PKEYVerifyRecoverInitEx(ctx *EVP_PKEY_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYVerifyRecoverInitEx2 C.EVP_PKEY_verify_recover_init_ex2
func EVP_PKEYVerifyRecoverInitEx2(ctx *EVP_PKEY_CTX, algo *EVP_SIGNATURE, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYVerifyRecover C.EVP_PKEY_verify_recover
func EVP_PKEYVerifyRecover(ctx *EVP_PKEY_CTX, rout *uint8, routlen *c.SizeT, sig *uint8, siglen c.SizeT) c.Int

//go:linkname EVP_PKEYEncryptInit C.EVP_PKEY_encrypt_init
func EVP_PKEYEncryptInit(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYEncryptInitEx C.EVP_PKEY_encrypt_init_ex
func EVP_PKEYEncryptInitEx(ctx *EVP_PKEY_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYEncrypt C.EVP_PKEY_encrypt
func EVP_PKEYEncrypt(ctx *EVP_PKEY_CTX, out *uint8, outlen *c.SizeT, in *uint8, inlen c.SizeT) c.Int

//go:linkname EVP_PKEYDecryptInit C.EVP_PKEY_decrypt_init
func EVP_PKEYDecryptInit(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYDecryptInitEx C.EVP_PKEY_decrypt_init_ex
func EVP_PKEYDecryptInitEx(ctx *EVP_PKEY_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYDecrypt C.EVP_PKEY_decrypt
func EVP_PKEYDecrypt(ctx *EVP_PKEY_CTX, out *uint8, outlen *c.SizeT, in *uint8, inlen c.SizeT) c.Int

//go:linkname EVP_PKEYDeriveInit C.EVP_PKEY_derive_init
func EVP_PKEYDeriveInit(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYDeriveInitEx C.EVP_PKEY_derive_init_ex
func EVP_PKEYDeriveInitEx(ctx *EVP_PKEY_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYDeriveSetPeerEx C.EVP_PKEY_derive_set_peer_ex
func EVP_PKEYDeriveSetPeerEx(ctx *EVP_PKEY_CTX, peer *EVP_PKEY, validate_peer c.Int) c.Int

//go:linkname EVP_PKEYDeriveSetPeer C.EVP_PKEY_derive_set_peer
func EVP_PKEYDeriveSetPeer(ctx *EVP_PKEY_CTX, peer *EVP_PKEY) c.Int

//go:linkname EVP_PKEYDerive C.EVP_PKEY_derive
func EVP_PKEYDerive(ctx *EVP_PKEY_CTX, key *uint8, keylen *c.SizeT) c.Int

//go:linkname EVP_PKEYDeriveSKEY C.EVP_PKEY_derive_SKEY
func EVP_PKEYDeriveSKEY(ctx *EVP_PKEY_CTX, mgmt *EVP_SKEYMGMT, key_type *c.Char, propquery *c.Char, keylen c.SizeT, params *OSSL_PARAM) *EVP_SKEY

//go:linkname EVP_PKEYEncapsulateInit C.EVP_PKEY_encapsulate_init
func EVP_PKEYEncapsulateInit(ctx *EVP_PKEY_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYAuthEncapsulateInit C.EVP_PKEY_auth_encapsulate_init
func EVP_PKEYAuthEncapsulateInit(ctx *EVP_PKEY_CTX, authpriv *EVP_PKEY, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYEncapsulate C.EVP_PKEY_encapsulate
func EVP_PKEYEncapsulate(ctx *EVP_PKEY_CTX, wrappedkey *uint8, wrappedkeylen *c.SizeT, genkey *uint8, genkeylen *c.SizeT) c.Int

//go:linkname EVP_PKEYDecapsulateInit C.EVP_PKEY_decapsulate_init
func EVP_PKEYDecapsulateInit(ctx *EVP_PKEY_CTX, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYAuthDecapsulateInit C.EVP_PKEY_auth_decapsulate_init
func EVP_PKEYAuthDecapsulateInit(ctx *EVP_PKEY_CTX, authpub *EVP_PKEY, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYDecapsulate C.EVP_PKEY_decapsulate
func EVP_PKEYDecapsulate(ctx *EVP_PKEY_CTX, unwrapped *uint8, unwrappedlen *c.SizeT, wrapped *uint8, wrappedlen c.SizeT) c.Int

//go:linkname EVP_PKEYFromdataInit C.EVP_PKEY_fromdata_init
func EVP_PKEYFromdataInit(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYFromdata C.EVP_PKEY_fromdata
func EVP_PKEYFromdata(ctx *EVP_PKEY_CTX, ppkey **EVP_PKEY, selection c.Int, param *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYFromdataSettable C.EVP_PKEY_fromdata_settable
func EVP_PKEYFromdataSettable(ctx *EVP_PKEY_CTX, selection c.Int) *OSSL_PARAM

//go:linkname EVP_PKEYTodata C.EVP_PKEY_todata
func EVP_PKEYTodata(pkey *EVP_PKEY, selection c.Int, params **OSSL_PARAM) c.Int

//go:linkname EVP_PKEYExport C.EVP_PKEY_export
func EVP_PKEYExport(pkey *EVP_PKEY, selection c.Int, export_cb *OSSL_CALLBACK, export_cbarg unsafe.Pointer) c.Int

//go:linkname EVP_PKEYGettableParams C.EVP_PKEY_gettable_params
func EVP_PKEYGettableParams(pkey *EVP_PKEY) *OSSL_PARAM

//go:linkname EVP_PKEYGetParams C.EVP_PKEY_get_params
func EVP_PKEYGetParams(pkey *EVP_PKEY, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYGetIntParam C.EVP_PKEY_get_int_param
func EVP_PKEYGetIntParam(pkey *EVP_PKEY, key_name *c.Char, out *c.Int) c.Int

//go:linkname EVP_PKEYGetSizeTParam C.EVP_PKEY_get_size_t_param
func EVP_PKEYGetSizeTParam(pkey *EVP_PKEY, key_name *c.Char, out *c.SizeT) c.Int

//go:linkname EVP_PKEYGetBnParam C.EVP_PKEY_get_bn_param
func EVP_PKEYGetBnParam(pkey *EVP_PKEY, key_name *c.Char, bn **BIGNUM) c.Int

//go:linkname EVP_PKEYGetUtf8StringParam C.EVP_PKEY_get_utf8_string_param
func EVP_PKEYGetUtf8StringParam(pkey *EVP_PKEY, key_name *c.Char, str *c.Char, max_buf_sz c.SizeT, out_sz *c.SizeT) c.Int

//go:linkname EVP_PKEYGetOctetStringParam C.EVP_PKEY_get_octet_string_param
func EVP_PKEYGetOctetStringParam(pkey *EVP_PKEY, key_name *c.Char, buf *uint8, max_buf_sz c.SizeT, out_sz *c.SizeT) c.Int

//go:linkname EVP_PKEYSettableParams C.EVP_PKEY_settable_params
func EVP_PKEYSettableParams(pkey *EVP_PKEY) *OSSL_PARAM

//go:linkname EVP_PKEYSetParams C.EVP_PKEY_set_params
func EVP_PKEYSetParams(pkey *EVP_PKEY, params *OSSL_PARAM) c.Int

//go:linkname EVP_PKEYSetIntParam C.EVP_PKEY_set_int_param
func EVP_PKEYSetIntParam(pkey *EVP_PKEY, key_name *c.Char, in c.Int) c.Int

//go:linkname EVP_PKEYSetSizeTParam C.EVP_PKEY_set_size_t_param
func EVP_PKEYSetSizeTParam(pkey *EVP_PKEY, key_name *c.Char, in c.SizeT) c.Int

//go:linkname EVP_PKEYSetBnParam C.EVP_PKEY_set_bn_param
func EVP_PKEYSetBnParam(pkey *EVP_PKEY, key_name *c.Char, bn *BIGNUM) c.Int

//go:linkname EVP_PKEYSetUtf8StringParam C.EVP_PKEY_set_utf8_string_param
func EVP_PKEYSetUtf8StringParam(pkey *EVP_PKEY, key_name *c.Char, str *c.Char) c.Int

//go:linkname EVP_PKEYSetOctetStringParam C.EVP_PKEY_set_octet_string_param
func EVP_PKEYSetOctetStringParam(pkey *EVP_PKEY, key_name *c.Char, buf *uint8, bsize c.SizeT) c.Int

//go:linkname EVP_PKEYGetEcPointConvForm C.EVP_PKEY_get_ec_point_conv_form
func EVP_PKEYGetEcPointConvForm(pkey *EVP_PKEY) c.Int

//go:linkname EVP_PKEYGetFieldType C.EVP_PKEY_get_field_type
func EVP_PKEYGetFieldType(pkey *EVP_PKEY) c.Int

//go:linkname EVP_PKEY_QKeygen C.EVP_PKEY_Q_keygen
func EVP_PKEY_QKeygen(libctx *OSSL_LIB_CTX, propq *c.Char, type_ *c.Char, __llgo_va_list ...any) *EVP_PKEY

//go:linkname EVP_PKEYParamgenInit C.EVP_PKEY_paramgen_init
func EVP_PKEYParamgenInit(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYParamgen C.EVP_PKEY_paramgen
func EVP_PKEYParamgen(ctx *EVP_PKEY_CTX, ppkey **EVP_PKEY) c.Int

//go:linkname EVP_PKEYKeygenInit C.EVP_PKEY_keygen_init
func EVP_PKEYKeygenInit(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYKeygen C.EVP_PKEY_keygen
func EVP_PKEYKeygen(ctx *EVP_PKEY_CTX, ppkey **EVP_PKEY) c.Int

//go:linkname EVP_PKEYGenerate C.EVP_PKEY_generate
func EVP_PKEYGenerate(ctx *EVP_PKEY_CTX, ppkey **EVP_PKEY) c.Int

//go:linkname EVP_PKEYCheck C.EVP_PKEY_check
func EVP_PKEYCheck(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYPublicCheck C.EVP_PKEY_public_check
func EVP_PKEYPublicCheck(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYPublicCheckQuick C.EVP_PKEY_public_check_quick
func EVP_PKEYPublicCheckQuick(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYParamCheck C.EVP_PKEY_param_check
func EVP_PKEYParamCheck(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYParamCheckQuick C.EVP_PKEY_param_check_quick
func EVP_PKEYParamCheckQuick(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYPrivateCheck C.EVP_PKEY_private_check
func EVP_PKEYPrivateCheck(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYPairwiseCheck C.EVP_PKEY_pairwise_check
func EVP_PKEYPairwiseCheck(ctx *EVP_PKEY_CTX) c.Int

//go:linkname EVP_PKEYSetExData C.EVP_PKEY_set_ex_data
func EVP_PKEYSetExData(key *EVP_PKEY, idx c.Int, arg unsafe.Pointer) c.Int

//go:linkname EVP_PKEYGetExData C.EVP_PKEY_get_ex_data
func EVP_PKEYGetExData(key *EVP_PKEY, idx c.Int) unsafe.Pointer

//go:linkname EVP_PKEY_CTXSetCb C.EVP_PKEY_CTX_set_cb
func EVP_PKEY_CTXSetCb(ctx *EVP_PKEY_CTX, cb *EVP_PKEYGenCb)

//go:linkname EVP_PKEY_CTXGetCb C.EVP_PKEY_CTX_get_cb
func EVP_PKEY_CTXGetCb(ctx *EVP_PKEY_CTX) *EVP_PKEYGenCb

//go:linkname EVP_PKEY_CTXGetKeygenInfo C.EVP_PKEY_CTX_get_keygen_info
func EVP_PKEY_CTXGetKeygenInfo(ctx *EVP_PKEY_CTX, idx c.Int) c.Int

//go:linkname EVP_KEYEXCHFree C.EVP_KEYEXCH_free
func EVP_KEYEXCHFree(exchange *EVP_KEYEXCH)

//go:linkname EVP_KEYEXCHUpRef C.EVP_KEYEXCH_up_ref
func EVP_KEYEXCHUpRef(exchange *EVP_KEYEXCH) c.Int

//go:linkname EVP_KEYEXCHFetch C.EVP_KEYEXCH_fetch
func EVP_KEYEXCHFetch(ctx *OSSL_LIB_CTX, algorithm *c.Char, properties *c.Char) *EVP_KEYEXCH

//go:linkname EVP_KEYEXCHGet0Provider C.EVP_KEYEXCH_get0_provider
func EVP_KEYEXCHGet0Provider(exchange *EVP_KEYEXCH) *OSSL_PROVIDER

//go:linkname EVP_KEYEXCHIsA C.EVP_KEYEXCH_is_a
func EVP_KEYEXCHIsA(keyexch *EVP_KEYEXCH, name *c.Char) c.Int

//go:linkname EVP_KEYEXCHGet0Name C.EVP_KEYEXCH_get0_name
func EVP_KEYEXCHGet0Name(keyexch *EVP_KEYEXCH) *c.Char

//go:linkname EVP_KEYEXCHGet0Description C.EVP_KEYEXCH_get0_description
func EVP_KEYEXCHGet0Description(keyexch *EVP_KEYEXCH) *c.Char

//go:linkname EVP_KEYEXCHDoAllProvided C.EVP_KEYEXCH_do_all_provided
func EVP_KEYEXCHDoAllProvided(libctx *OSSL_LIB_CTX, fn func(_llcppg_param1 *EVP_KEYEXCH, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer)

//go:linkname EVP_KEYEXCHNamesDoAll C.EVP_KEYEXCH_names_do_all
func EVP_KEYEXCHNamesDoAll(keyexch *EVP_KEYEXCH, fn func(_llcppg_param1 *c.Char, _llcppg_param2 unsafe.Pointer), data unsafe.Pointer) c.Int

//go:linkname EVP_KEYEXCHGettableCtxParams C.EVP_KEYEXCH_gettable_ctx_params
func EVP_KEYEXCHGettableCtxParams(keyexch *EVP_KEYEXCH) *OSSL_PARAM

//go:linkname EVP_KEYEXCHSettableCtxParams C.EVP_KEYEXCH_settable_ctx_params
func EVP_KEYEXCHSettableCtxParams(keyexch *EVP_KEYEXCH) *OSSL_PARAM

//go:linkname EVPAddAlgModule C.EVP_add_alg_module
func EVPAddAlgModule()

//go:linkname EVP_PKEY_CTXSetGroupName C.EVP_PKEY_CTX_set_group_name
func EVP_PKEY_CTXSetGroupName(ctx *EVP_PKEY_CTX, name *c.Char) c.Int

//go:linkname EVP_PKEY_CTXGetGroupName C.EVP_PKEY_CTX_get_group_name
func EVP_PKEY_CTXGetGroupName(ctx *EVP_PKEY_CTX, name *c.Char, namelen c.SizeT) c.Int

//go:linkname EVP_PKEYGetGroupName C.EVP_PKEY_get_group_name
func EVP_PKEYGetGroupName(pkey *EVP_PKEY, name *c.Char, name_sz c.SizeT, gname_len *c.SizeT) c.Int

//go:linkname EVP_PKEY_CTXGet0Libctx C.EVP_PKEY_CTX_get0_libctx
func EVP_PKEY_CTXGet0Libctx(ctx *EVP_PKEY_CTX) *OSSL_LIB_CTX

//go:linkname EVP_PKEY_CTXGet0Propq C.EVP_PKEY_CTX_get0_propq
func EVP_PKEY_CTXGet0Propq(ctx *EVP_PKEY_CTX) *c.Char

//go:linkname EVP_PKEY_CTXGet0Provider C.EVP_PKEY_CTX_get0_provider
func EVP_PKEY_CTXGet0Provider(ctx *EVP_PKEY_CTX) *OSSL_PROVIDER

//go:linkname EVP_SKEYIsA C.EVP_SKEY_is_a
func EVP_SKEYIsA(skey *EVP_SKEY, name *c.Char) c.Int

//go:linkname EVP_SKEYImport C.EVP_SKEY_import
func EVP_SKEYImport(libctx *OSSL_LIB_CTX, skeymgmtname *c.Char, propquery *c.Char, selection c.Int, params *OSSL_PARAM) *EVP_SKEY

//go:linkname EVP_SKEYGenerate C.EVP_SKEY_generate
func EVP_SKEYGenerate(libctx *OSSL_LIB_CTX, skeymgmtname *c.Char, propquery *c.Char, params *OSSL_PARAM) *EVP_SKEY

//go:linkname EVP_SKEYImportRawKey C.EVP_SKEY_import_raw_key
func EVP_SKEYImportRawKey(libctx *OSSL_LIB_CTX, skeymgmtname *c.Char, key *uint8, keylen c.SizeT, propquery *c.Char) *EVP_SKEY

//go:linkname EVP_SKEYImportSKEYMGMT C.EVP_SKEY_import_SKEYMGMT
func EVP_SKEYImportSKEYMGMT(libctx *OSSL_LIB_CTX, skeymgmt *EVP_SKEYMGMT, selection c.Int, params *OSSL_PARAM) *EVP_SKEY

//go:linkname EVP_SKEYGet0RawKey C.EVP_SKEY_get0_raw_key
func EVP_SKEYGet0RawKey(skey *EVP_SKEY, key **uint8, len *c.SizeT) c.Int

//go:linkname EVP_SKEYGet0KeyId C.EVP_SKEY_get0_key_id
func EVP_SKEYGet0KeyId(skey *EVP_SKEY) *c.Char

//go:linkname EVP_SKEYExport C.EVP_SKEY_export
func EVP_SKEYExport(skey *EVP_SKEY, selection c.Int, export_cb *OSSL_CALLBACK, export_cbarg unsafe.Pointer) c.Int

//go:linkname EVP_SKEYUpRef C.EVP_SKEY_up_ref
func EVP_SKEYUpRef(skey *EVP_SKEY) c.Int

//go:linkname EVP_SKEYFree C.EVP_SKEY_free
func EVP_SKEYFree(skey *EVP_SKEY)

//go:linkname EVP_SKEYGet0SkeymgmtName C.EVP_SKEY_get0_skeymgmt_name
func EVP_SKEYGet0SkeymgmtName(skey *EVP_SKEY) *c.Char

//go:linkname EVP_SKEYGet0ProviderName C.EVP_SKEY_get0_provider_name
func EVP_SKEYGet0ProviderName(skey *EVP_SKEY) *c.Char

//go:linkname EVP_SKEYToProvider C.EVP_SKEY_to_provider
func EVP_SKEYToProvider(skey *EVP_SKEY, libctx *OSSL_LIB_CTX, prov *OSSL_PROVIDER, propquery *c.Char) *EVP_SKEY
