// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const HMAC_MAX_MD_CBLOCK = 200

//go:linkname HMACSize C.HMAC_size
func HMACSize(e *HMAC_CTX) c.SizeT

//go:linkname HMAC_CTXNew C.HMAC_CTX_new
func HMAC_CTXNew() *HMAC_CTX

//go:linkname HMAC_CTXReset C.HMAC_CTX_reset
func HMAC_CTXReset(ctx *HMAC_CTX) c.Int

//go:linkname HMAC_CTXFree C.HMAC_CTX_free
func HMAC_CTXFree(ctx *HMAC_CTX)

//go:linkname HMAC_Init C.HMAC_Init
func HMAC_Init(ctx *HMAC_CTX, key unsafe.Pointer, len c.Int, md *EVP_MD) c.Int

//go:linkname HMACInitEx C.HMAC_Init_ex
func HMACInitEx(ctx *HMAC_CTX, key unsafe.Pointer, len c.Int, md *EVP_MD, impl *ENGINE) c.Int

//go:linkname HMAC_Update C.HMAC_Update
func HMAC_Update(ctx *HMAC_CTX, data *uint8, len c.SizeT) c.Int

//go:linkname HMAC_Final C.HMAC_Final
func HMAC_Final(ctx *HMAC_CTX, md *uint8, len *c.Uint) c.Int

//go:linkname HMAC_CTXCopy C.HMAC_CTX_copy
func HMAC_CTXCopy(dctx *HMAC_CTX, sctx *HMAC_CTX) c.Int

//go:linkname HMAC_CTXSetFlags C.HMAC_CTX_set_flags
func HMAC_CTXSetFlags(ctx *HMAC_CTX, flags c.Ulong)

//go:linkname HMAC_CTXGetMd C.HMAC_CTX_get_md
func HMAC_CTXGetMd(ctx *HMAC_CTX) *EVP_MD

//go:linkname HMAC C.HMAC
func HMAC(evp_md *EVP_MD, key unsafe.Pointer, key_len c.Int, data *uint8, data_len c.SizeT, md *uint8, md_len *c.Uint) *uint8
