// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const OSSL_HPKE_MODE_BASE = 0
const OSSL_HPKE_MODE_PSK = 1
const OSSL_HPKE_MODE_AUTH = 2
const OSSL_HPKE_MODE_PSKAUTH = 3
const OSSL_HPKE_MAX_PARMLEN = 66
const OSSL_HPKE_MIN_PSKLEN = 32
const OSSL_HPKE_MAX_INFOLEN = 1024
const OSSL_HPKE_KEM_ID_RESERVED = 0
const OSSL_HPKE_KEM_ID_P256 = 16
const OSSL_HPKE_KEM_ID_P384 = 17
const OSSL_HPKE_KEM_ID_P521 = 18
const OSSL_HPKE_KEM_ID_X25519 = 32
const OSSL_HPKE_KEM_ID_X448 = 33
const OSSL_HPKE_KDF_ID_RESERVED = 0
const OSSL_HPKE_KDF_ID_HKDF_SHA256 = 1
const OSSL_HPKE_KDF_ID_HKDF_SHA384 = 2
const OSSL_HPKE_KDF_ID_HKDF_SHA512 = 3
const OSSL_HPKE_AEAD_ID_RESERVED = 0
const OSSL_HPKE_AEAD_ID_AES_GCM_128 = 1
const OSSL_HPKE_AEAD_ID_AES_GCM_256 = 2
const OSSL_HPKE_AEAD_ID_CHACHA_POLY1305 = 3
const OSSL_HPKE_AEAD_ID_EXPORTONLY = 65535
const OSSL_HPKE_KEMSTR_P256 = "P-256"
const OSSL_HPKE_KEMSTR_P384 = "P-384"
const OSSL_HPKE_KEMSTR_P521 = "P-521"
const OSSL_HPKE_KEMSTR_X25519 = "X25519"
const OSSL_HPKE_KEMSTR_X448 = "X448"
const OSSL_HPKE_KDFSTR_256 = "hkdf-sha256"
const OSSL_HPKE_KDFSTR_384 = "hkdf-sha384"
const OSSL_HPKE_KDFSTR_512 = "hkdf-sha512"
const OSSL_HPKE_AEADSTR_AES128GCM = "aes-128-gcm"
const OSSL_HPKE_AEADSTR_AES256GCM = "aes-256-gcm"
const OSSL_HPKE_AEADSTR_CP = "chacha20-poly1305"
const OSSL_HPKE_AEADSTR_EXP = "exporter"
const OSSL_HPKE_ROLE_SENDER = 0
const OSSL_HPKE_ROLE_RECEIVER = 1

type OSSL_HPKE_SUITE struct {
	KemId  c.Uint16T
	KdfId  c.Uint16T
	AeadId c.Uint16T
}
type OsslHpkeCtxSt struct {
}
type OSSL_HPKE_CTX = OsslHpkeCtxSt

//go:linkname OSSL_HPKE_CTXNew C.OSSL_HPKE_CTX_new
func OSSL_HPKE_CTXNew(mode c.Int, suite OSSL_HPKE_SUITE, role c.Int, libctx *OSSL_LIB_CTX, propq *c.Char) *OSSL_HPKE_CTX

//go:linkname OSSL_HPKE_CTXFree C.OSSL_HPKE_CTX_free
func OSSL_HPKE_CTXFree(ctx *OSSL_HPKE_CTX)

//go:linkname OSSL_HPKEEncap C.OSSL_HPKE_encap
func OSSL_HPKEEncap(ctx *OSSL_HPKE_CTX, enc *uint8, enclen *c.SizeT, pub *uint8, publen c.SizeT, info *uint8, infolen c.SizeT) c.Int

//go:linkname OSSL_HPKESeal C.OSSL_HPKE_seal
func OSSL_HPKESeal(ctx *OSSL_HPKE_CTX, ct *uint8, ctlen *c.SizeT, aad *uint8, aadlen c.SizeT, pt *uint8, ptlen c.SizeT) c.Int

//go:linkname OSSL_HPKEKeygen C.OSSL_HPKE_keygen
func OSSL_HPKEKeygen(suite OSSL_HPKE_SUITE, pub *uint8, publen *c.SizeT, priv **EVP_PKEY, ikm *uint8, ikmlen c.SizeT, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname OSSL_HPKEDecap C.OSSL_HPKE_decap
func OSSL_HPKEDecap(ctx *OSSL_HPKE_CTX, enc *uint8, enclen c.SizeT, recippriv *EVP_PKEY, info *uint8, infolen c.SizeT) c.Int

//go:linkname OSSL_HPKEOpen C.OSSL_HPKE_open
func OSSL_HPKEOpen(ctx *OSSL_HPKE_CTX, pt *uint8, ptlen *c.SizeT, aad *uint8, aadlen c.SizeT, ct *uint8, ctlen c.SizeT) c.Int

//go:linkname OSSL_HPKEExport C.OSSL_HPKE_export
func OSSL_HPKEExport(ctx *OSSL_HPKE_CTX, secret *uint8, secretlen c.SizeT, label *uint8, labellen c.SizeT) c.Int

//go:linkname OSSL_HPKE_CTXSet1Authpriv C.OSSL_HPKE_CTX_set1_authpriv
func OSSL_HPKE_CTXSet1Authpriv(ctx *OSSL_HPKE_CTX, priv *EVP_PKEY) c.Int

//go:linkname OSSL_HPKE_CTXSet1Authpub C.OSSL_HPKE_CTX_set1_authpub
func OSSL_HPKE_CTXSet1Authpub(ctx *OSSL_HPKE_CTX, pub *uint8, publen c.SizeT) c.Int

//go:linkname OSSL_HPKE_CTXSet1Psk C.OSSL_HPKE_CTX_set1_psk
func OSSL_HPKE_CTXSet1Psk(ctx *OSSL_HPKE_CTX, pskid *c.Char, psk *uint8, psklen c.SizeT) c.Int

//go:linkname OSSL_HPKE_CTXSet1Ikme C.OSSL_HPKE_CTX_set1_ikme
func OSSL_HPKE_CTXSet1Ikme(ctx *OSSL_HPKE_CTX, ikme *uint8, ikmelen c.SizeT) c.Int

//go:linkname OSSL_HPKE_CTXSetSeq C.OSSL_HPKE_CTX_set_seq
func OSSL_HPKE_CTXSetSeq(ctx *OSSL_HPKE_CTX, seq c.Uint64T) c.Int

//go:linkname OSSL_HPKE_CTXGetSeq C.OSSL_HPKE_CTX_get_seq
func OSSL_HPKE_CTXGetSeq(ctx *OSSL_HPKE_CTX, seq *c.Uint64T) c.Int

//go:linkname OSSL_HPKESuiteCheck C.OSSL_HPKE_suite_check
func OSSL_HPKESuiteCheck(suite OSSL_HPKE_SUITE) c.Int

//go:linkname OSSL_HPKEGetGreaseValue C.OSSL_HPKE_get_grease_value
func OSSL_HPKEGetGreaseValue(suite_in *OSSL_HPKE_SUITE, suite *OSSL_HPKE_SUITE, enc *uint8, enclen *c.SizeT, ct *uint8, ctlen c.SizeT, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname OSSL_HPKEStr2suite C.OSSL_HPKE_str2suite
func OSSL_HPKEStr2suite(str *c.Char, suite *OSSL_HPKE_SUITE) c.Int

//go:linkname OSSL_HPKEGetCiphertextSize C.OSSL_HPKE_get_ciphertext_size
func OSSL_HPKEGetCiphertextSize(suite OSSL_HPKE_SUITE, clearlen c.SizeT) c.SizeT

//go:linkname OSSL_HPKEGetPublicEncapSize C.OSSL_HPKE_get_public_encap_size
func OSSL_HPKEGetPublicEncapSize(suite OSSL_HPKE_SUITE) c.SizeT

//go:linkname OSSL_HPKEGetRecommendedIkmelen C.OSSL_HPKE_get_recommended_ikmelen
func OSSL_HPKEGetRecommendedIkmelen(suite OSSL_HPKE_SUITE) c.SizeT
