// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const OSSL_HTTP_NAME = "http"
const OSSL_HTTPS_NAME = "https"
const OSSL_HTTP_PORT = "80"
const OSSL_HTTPS_PORT = "443"
const OPENSSL_NO_PROXY = "NO_PROXY"
const OPENSSL_HTTP_PROXY = "HTTP_PROXY"
const OPENSSL_HTTPS_PROXY = "HTTPS_PROXY"
const OSSL_HTTP_DEFAULT_MAX_LINE_LEN = 4096
const OSSL_HTTP_DEFAULT_MAX_RESP_LEN = 102400
const OSSL_HTTP_DEFAULT_MAX_CRL_LEN = 33554432
const OSSL_HTTP_DEFAULT_MAX_RESP_HDR_LINES = 256

// High-level HTTP API
//
// llgo:type C
type OSSL_HTTPBioCbT = func(_llcppg_param1 *BIO, _llcppg_param2 unsafe.Pointer, _llcppg_param3 c.Int, _llcppg_param4 c.Int) *BIO

// We want to have this even in case of OPENSSL_NO_HTTP
//
//go:linkname OSSLParseUrl C.OSSL_parse_url
func OSSLParseUrl(url *c.Char, pscheme **c.Char, puser **c.Char, phost **c.Char, pport **c.Char, pport_num *c.Int, ppath **c.Char, pquery **c.Char, pfrag **c.Char) c.Int

// Low-level HTTP API
//
//go:linkname OSSL_HTTP_REQ_CTXNew C.OSSL_HTTP_REQ_CTX_new
func OSSL_HTTP_REQ_CTXNew(wbio *BIO, rbio *BIO, buf_size c.Int) *OSSL_HTTP_REQ_CTX

//go:linkname OSSL_HTTP_REQ_CTXFree C.OSSL_HTTP_REQ_CTX_free
func OSSL_HTTP_REQ_CTXFree(rctx *OSSL_HTTP_REQ_CTX)

//go:linkname OSSL_HTTP_REQ_CTXSetRequestLine C.OSSL_HTTP_REQ_CTX_set_request_line
func OSSL_HTTP_REQ_CTXSetRequestLine(rctx *OSSL_HTTP_REQ_CTX, method_POST c.Int, server *c.Char, port *c.Char, path *c.Char) c.Int

//go:linkname OSSL_HTTP_REQ_CTXAdd1Header C.OSSL_HTTP_REQ_CTX_add1_header
func OSSL_HTTP_REQ_CTXAdd1Header(rctx *OSSL_HTTP_REQ_CTX, name *c.Char, value *c.Char) c.Int

//go:linkname OSSL_HTTP_REQ_CTXSetExpected C.OSSL_HTTP_REQ_CTX_set_expected
func OSSL_HTTP_REQ_CTXSetExpected(rctx *OSSL_HTTP_REQ_CTX, content_type *c.Char, asn1 c.Int, timeout c.Int, keep_alive c.Int) c.Int

//go:linkname OSSL_HTTP_REQ_CTXSet1Req C.OSSL_HTTP_REQ_CTX_set1_req
func OSSL_HTTP_REQ_CTXSet1Req(rctx *OSSL_HTTP_REQ_CTX, content_type *c.Char, it *ASN1_ITEM, req *ASN1_VALUE) c.Int

//go:linkname OSSL_HTTP_REQ_CTXNbio C.OSSL_HTTP_REQ_CTX_nbio
func OSSL_HTTP_REQ_CTXNbio(rctx *OSSL_HTTP_REQ_CTX) c.Int

//go:linkname OSSL_HTTP_REQ_CTXNbioD2i C.OSSL_HTTP_REQ_CTX_nbio_d2i
func OSSL_HTTP_REQ_CTXNbioD2i(rctx *OSSL_HTTP_REQ_CTX, pval **ASN1_VALUE, it *ASN1_ITEM) c.Int

//go:linkname OSSL_HTTP_REQ_CTXExchange C.OSSL_HTTP_REQ_CTX_exchange
func OSSL_HTTP_REQ_CTXExchange(rctx *OSSL_HTTP_REQ_CTX) *BIO

//go:linkname OSSL_HTTP_REQ_CTXGet0MemBio C.OSSL_HTTP_REQ_CTX_get0_mem_bio
func OSSL_HTTP_REQ_CTXGet0MemBio(rctx *OSSL_HTTP_REQ_CTX) *BIO

//go:linkname OSSL_HTTP_REQ_CTXGetRespLen C.OSSL_HTTP_REQ_CTX_get_resp_len
func OSSL_HTTP_REQ_CTXGetRespLen(rctx *OSSL_HTTP_REQ_CTX) c.SizeT

//go:linkname OSSL_HTTP_REQ_CTXSetMaxResponseLength C.OSSL_HTTP_REQ_CTX_set_max_response_length
func OSSL_HTTP_REQ_CTXSetMaxResponseLength(rctx *OSSL_HTTP_REQ_CTX, len c.Ulong)

//go:linkname OSSL_HTTP_REQ_CTXSetMaxResponseHdrLines C.OSSL_HTTP_REQ_CTX_set_max_response_hdr_lines
func OSSL_HTTP_REQ_CTXSetMaxResponseHdrLines(rctx *OSSL_HTTP_REQ_CTX, count c.SizeT)

//go:linkname OSSL_HTTPIsAlive C.OSSL_HTTP_is_alive
func OSSL_HTTPIsAlive(rctx *OSSL_HTTP_REQ_CTX) c.Int

//go:linkname OSSL_HTTPOpen C.OSSL_HTTP_open
func OSSL_HTTPOpen(server *c.Char, port *c.Char, proxy *c.Char, no_proxy *c.Char, use_ssl c.Int, bio *BIO, rbio *BIO, bio_update_fn OSSL_HTTPBioCbT, arg unsafe.Pointer, buf_size c.Int, overall_timeout c.Int) *OSSL_HTTP_REQ_CTX

//go:linkname OSSL_HTTPProxyConnect C.OSSL_HTTP_proxy_connect
func OSSL_HTTPProxyConnect(bio *BIO, server *c.Char, port *c.Char, proxyuser *c.Char, proxypass *c.Char, timeout c.Int, bio_err *BIO, prog *c.Char) c.Int

//go:linkname OSSL_HTTPSet1Request C.OSSL_HTTP_set1_request
func OSSL_HTTPSet1Request(rctx *OSSL_HTTP_REQ_CTX, path *c.Char, headers *StackStCONF_VALUE, content_type *c.Char, req *BIO, expected_content_type *c.Char, expect_asn1 c.Int, max_resp_len c.SizeT, timeout c.Int, keep_alive c.Int) c.Int

//go:linkname OSSL_HTTPExchange C.OSSL_HTTP_exchange
func OSSL_HTTPExchange(rctx *OSSL_HTTP_REQ_CTX, redirection_url **c.Char) *BIO

//go:linkname OSSL_HTTPGet C.OSSL_HTTP_get
func OSSL_HTTPGet(url *c.Char, proxy *c.Char, no_proxy *c.Char, bio *BIO, rbio *BIO, bio_update_fn OSSL_HTTPBioCbT, arg unsafe.Pointer, buf_size c.Int, headers *StackStCONF_VALUE, expected_content_type *c.Char, expect_asn1 c.Int, max_resp_len c.SizeT, timeout c.Int) *BIO

//go:linkname OSSL_HTTPTransfer C.OSSL_HTTP_transfer
func OSSL_HTTPTransfer(prctx **OSSL_HTTP_REQ_CTX, server *c.Char, port *c.Char, path *c.Char, use_ssl c.Int, proxy *c.Char, no_proxy *c.Char, bio *BIO, rbio *BIO, bio_update_fn OSSL_HTTPBioCbT, arg unsafe.Pointer, buf_size c.Int, headers *StackStCONF_VALUE, content_type *c.Char, req *BIO, expected_content_type *c.Char, expect_asn1 c.Int, max_resp_len c.SizeT, timeout c.Int, keep_alive c.Int) *BIO

//go:linkname OSSL_HTTPClose C.OSSL_HTTP_close
func OSSL_HTTPClose(rctx *OSSL_HTTP_REQ_CTX, ok c.Int) c.Int

// Auxiliary functions
//
//go:linkname OSSL_HTTPParseUrl C.OSSL_HTTP_parse_url
func OSSL_HTTPParseUrl(url *c.Char, pssl *c.Int, puser **c.Char, phost **c.Char, pport **c.Char, pport_num *c.Int, ppath **c.Char, pquery **c.Char, pfrag **c.Char) c.Int

//go:linkname OSSL_HTTPAdaptProxy C.OSSL_HTTP_adapt_proxy
func OSSL_HTTPAdaptProxy(proxy *c.Char, no_proxy *c.Char, server *c.Char, use_ssl c.Int) *c.Char
