// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"github.com/goplus/lib/c/time"
	"unsafe"
)

// Search an OSSL_PARAM array for a matching name
//
//go:linkname OSSL_PARAMLocate C.OSSL_PARAM_locate
func OSSL_PARAMLocate(p *OSSL_PARAM, key *c.Char) *OSSL_PARAM

//go:linkname OSSL_PARAMLocateConst C.OSSL_PARAM_locate_const
func OSSL_PARAMLocateConst(p *OSSL_PARAM, key *c.Char) *OSSL_PARAM

// Basic parameter type run-time construction
//
//go:linkname OSSL_PARAMConstructInt C.OSSL_PARAM_construct_int
func OSSL_PARAMConstructInt(key *c.Char, buf *c.Int) OSSL_PARAM

//go:linkname OSSL_PARAMConstructUint C.OSSL_PARAM_construct_uint
func OSSL_PARAMConstructUint(key *c.Char, buf *c.Uint) OSSL_PARAM

//go:linkname OSSL_PARAMConstructLong C.OSSL_PARAM_construct_long
func OSSL_PARAMConstructLong(key *c.Char, buf *c.Long) OSSL_PARAM

//go:linkname OSSL_PARAMConstructUlong C.OSSL_PARAM_construct_ulong
func OSSL_PARAMConstructUlong(key *c.Char, buf *c.Ulong) OSSL_PARAM

//go:linkname OSSL_PARAMConstructInt32 C.OSSL_PARAM_construct_int32
func OSSL_PARAMConstructInt32(key *c.Char, buf *c.Int32T) OSSL_PARAM

//go:linkname OSSL_PARAMConstructUint32 C.OSSL_PARAM_construct_uint32
func OSSL_PARAMConstructUint32(key *c.Char, buf *c.Uint32T) OSSL_PARAM

//go:linkname OSSL_PARAMConstructInt64 C.OSSL_PARAM_construct_int64
func OSSL_PARAMConstructInt64(key *c.Char, buf *c.Int64T) OSSL_PARAM

//go:linkname OSSL_PARAMConstructUint64 C.OSSL_PARAM_construct_uint64
func OSSL_PARAMConstructUint64(key *c.Char, buf *c.Uint64T) OSSL_PARAM

//go:linkname OSSL_PARAMConstructSizeT C.OSSL_PARAM_construct_size_t
func OSSL_PARAMConstructSizeT(key *c.Char, buf *c.SizeT) OSSL_PARAM

//go:linkname OSSL_PARAMConstructTimeT C.OSSL_PARAM_construct_time_t
func OSSL_PARAMConstructTimeT(key *c.Char, buf *time.TimeT) OSSL_PARAM

//go:linkname OSSL_PARAMConstructBN C.OSSL_PARAM_construct_BN
func OSSL_PARAMConstructBN(key *c.Char, buf *uint8, bsize c.SizeT) OSSL_PARAM

//go:linkname OSSL_PARAMConstructDouble C.OSSL_PARAM_construct_double
func OSSL_PARAMConstructDouble(key *c.Char, buf *c.Double) OSSL_PARAM

//go:linkname OSSL_PARAMConstructUtf8String C.OSSL_PARAM_construct_utf8_string
func OSSL_PARAMConstructUtf8String(key *c.Char, buf *c.Char, bsize c.SizeT) OSSL_PARAM

//go:linkname OSSL_PARAMConstructUtf8Ptr C.OSSL_PARAM_construct_utf8_ptr
func OSSL_PARAMConstructUtf8Ptr(key *c.Char, buf **c.Char, bsize c.SizeT) OSSL_PARAM

//go:linkname OSSL_PARAMConstructOctetString C.OSSL_PARAM_construct_octet_string
func OSSL_PARAMConstructOctetString(key *c.Char, buf unsafe.Pointer, bsize c.SizeT) OSSL_PARAM

//go:linkname OSSL_PARAMConstructOctetPtr C.OSSL_PARAM_construct_octet_ptr
func OSSL_PARAMConstructOctetPtr(key *c.Char, buf *unsafe.Pointer, bsize c.SizeT) OSSL_PARAM

//go:linkname OSSL_PARAMConstructEnd C.OSSL_PARAM_construct_end
func OSSL_PARAMConstructEnd() OSSL_PARAM

//go:linkname OSSL_PARAMAllocateFromText C.OSSL_PARAM_allocate_from_text
func OSSL_PARAMAllocateFromText(to *OSSL_PARAM, paramdefs *OSSL_PARAM, key *c.Char, value *c.Char, value_n c.SizeT, found *c.Int) c.Int

//go:linkname OSSL_PARAMPrintToBio C.OSSL_PARAM_print_to_bio
func OSSL_PARAMPrintToBio(params *OSSL_PARAM, bio *BIO, print_values c.Int) c.Int

//go:linkname OSSL_PARAMGetInt C.OSSL_PARAM_get_int
func OSSL_PARAMGetInt(p *OSSL_PARAM, val *c.Int) c.Int

//go:linkname OSSL_PARAMGetUint C.OSSL_PARAM_get_uint
func OSSL_PARAMGetUint(p *OSSL_PARAM, val *c.Uint) c.Int

//go:linkname OSSL_PARAMGetLong C.OSSL_PARAM_get_long
func OSSL_PARAMGetLong(p *OSSL_PARAM, val *c.Long) c.Int

//go:linkname OSSL_PARAMGetUlong C.OSSL_PARAM_get_ulong
func OSSL_PARAMGetUlong(p *OSSL_PARAM, val *c.Ulong) c.Int

//go:linkname OSSL_PARAMGetInt32 C.OSSL_PARAM_get_int32
func OSSL_PARAMGetInt32(p *OSSL_PARAM, val *c.Int32T) c.Int

//go:linkname OSSL_PARAMGetUint32 C.OSSL_PARAM_get_uint32
func OSSL_PARAMGetUint32(p *OSSL_PARAM, val *c.Uint32T) c.Int

//go:linkname OSSL_PARAMGetInt64 C.OSSL_PARAM_get_int64
func OSSL_PARAMGetInt64(p *OSSL_PARAM, val *c.Int64T) c.Int

//go:linkname OSSL_PARAMGetUint64 C.OSSL_PARAM_get_uint64
func OSSL_PARAMGetUint64(p *OSSL_PARAM, val *c.Uint64T) c.Int

//go:linkname OSSL_PARAMGetSizeT C.OSSL_PARAM_get_size_t
func OSSL_PARAMGetSizeT(p *OSSL_PARAM, val *c.SizeT) c.Int

//go:linkname OSSL_PARAMGetTimeT C.OSSL_PARAM_get_time_t
func OSSL_PARAMGetTimeT(p *OSSL_PARAM, val *time.TimeT) c.Int

//go:linkname OSSL_PARAMSetInt C.OSSL_PARAM_set_int
func OSSL_PARAMSetInt(p *OSSL_PARAM, val c.Int) c.Int

//go:linkname OSSL_PARAMSetUint C.OSSL_PARAM_set_uint
func OSSL_PARAMSetUint(p *OSSL_PARAM, val c.Uint) c.Int

//go:linkname OSSL_PARAMSetLong C.OSSL_PARAM_set_long
func OSSL_PARAMSetLong(p *OSSL_PARAM, val c.Long) c.Int

//go:linkname OSSL_PARAMSetUlong C.OSSL_PARAM_set_ulong
func OSSL_PARAMSetUlong(p *OSSL_PARAM, val c.Ulong) c.Int

//go:linkname OSSL_PARAMSetInt32 C.OSSL_PARAM_set_int32
func OSSL_PARAMSetInt32(p *OSSL_PARAM, val c.Int32T) c.Int

//go:linkname OSSL_PARAMSetUint32 C.OSSL_PARAM_set_uint32
func OSSL_PARAMSetUint32(p *OSSL_PARAM, val c.Uint32T) c.Int

//go:linkname OSSL_PARAMSetInt64 C.OSSL_PARAM_set_int64
func OSSL_PARAMSetInt64(p *OSSL_PARAM, val c.Int64T) c.Int

//go:linkname OSSL_PARAMSetUint64 C.OSSL_PARAM_set_uint64
func OSSL_PARAMSetUint64(p *OSSL_PARAM, val c.Uint64T) c.Int

//go:linkname OSSL_PARAMSetSizeT C.OSSL_PARAM_set_size_t
func OSSL_PARAMSetSizeT(p *OSSL_PARAM, val c.SizeT) c.Int

//go:linkname OSSL_PARAMSetTimeT C.OSSL_PARAM_set_time_t
func OSSL_PARAMSetTimeT(p *OSSL_PARAM, val time.TimeT) c.Int

//go:linkname OSSL_PARAMGetDouble C.OSSL_PARAM_get_double
func OSSL_PARAMGetDouble(p *OSSL_PARAM, val *c.Double) c.Int

//go:linkname OSSL_PARAMSetDouble C.OSSL_PARAM_set_double
func OSSL_PARAMSetDouble(p *OSSL_PARAM, val c.Double) c.Int

//go:linkname OSSL_PARAMGetBN C.OSSL_PARAM_get_BN
func OSSL_PARAMGetBN(p *OSSL_PARAM, val **BIGNUM) c.Int

//go:linkname OSSL_PARAMSetBN C.OSSL_PARAM_set_BN
func OSSL_PARAMSetBN(p *OSSL_PARAM, val *BIGNUM) c.Int

//go:linkname OSSL_PARAMGetUtf8String C.OSSL_PARAM_get_utf8_string
func OSSL_PARAMGetUtf8String(p *OSSL_PARAM, val **c.Char, max_len c.SizeT) c.Int

//go:linkname OSSL_PARAMSetUtf8String C.OSSL_PARAM_set_utf8_string
func OSSL_PARAMSetUtf8String(p *OSSL_PARAM, val *c.Char) c.Int

//go:linkname OSSL_PARAMGetOctetString C.OSSL_PARAM_get_octet_string
func OSSL_PARAMGetOctetString(p *OSSL_PARAM, val *unsafe.Pointer, max_len c.SizeT, used_len *c.SizeT) c.Int

//go:linkname OSSL_PARAMSetOctetString C.OSSL_PARAM_set_octet_string
func OSSL_PARAMSetOctetString(p *OSSL_PARAM, val unsafe.Pointer, len c.SizeT) c.Int

//go:linkname OSSL_PARAMGetUtf8Ptr C.OSSL_PARAM_get_utf8_ptr
func OSSL_PARAMGetUtf8Ptr(p *OSSL_PARAM, val **c.Char) c.Int

//go:linkname OSSL_PARAMSetUtf8Ptr C.OSSL_PARAM_set_utf8_ptr
func OSSL_PARAMSetUtf8Ptr(p *OSSL_PARAM, val *c.Char) c.Int

//go:linkname OSSL_PARAMGetOctetPtr C.OSSL_PARAM_get_octet_ptr
func OSSL_PARAMGetOctetPtr(p *OSSL_PARAM, val *unsafe.Pointer, used_len *c.SizeT) c.Int

//go:linkname OSSL_PARAMSetOctetPtr C.OSSL_PARAM_set_octet_ptr
func OSSL_PARAMSetOctetPtr(p *OSSL_PARAM, val unsafe.Pointer, used_len c.SizeT) c.Int

//go:linkname OSSL_PARAMGetUtf8StringPtr C.OSSL_PARAM_get_utf8_string_ptr
func OSSL_PARAMGetUtf8StringPtr(p *OSSL_PARAM, val **c.Char) c.Int

//go:linkname OSSL_PARAMGetOctetStringPtr C.OSSL_PARAM_get_octet_string_ptr
func OSSL_PARAMGetOctetStringPtr(p *OSSL_PARAM, val *unsafe.Pointer, used_len *c.SizeT) c.Int

//go:linkname OSSL_PARAMModified C.OSSL_PARAM_modified
func OSSL_PARAMModified(p *OSSL_PARAM) c.Int

//go:linkname OSSL_PARAMSetAllUnmodified C.OSSL_PARAM_set_all_unmodified
func OSSL_PARAMSetAllUnmodified(p *OSSL_PARAM)

//go:linkname OSSL_PARAMDup C.OSSL_PARAM_dup
func OSSL_PARAMDup(p *OSSL_PARAM) *OSSL_PARAM

//go:linkname OSSL_PARAMMerge C.OSSL_PARAM_merge
func OSSL_PARAMMerge(p1 *OSSL_PARAM, p2 *OSSL_PARAM) *OSSL_PARAM

//go:linkname OSSL_PARAMFree C.OSSL_PARAM_free
func OSSL_PARAMFree(p *OSSL_PARAM)

//go:linkname OSSL_PARAMClearFree C.OSSL_PARAM_clear_free
func OSSL_PARAMClearFree(p *OSSL_PARAM)

//go:linkname OSSL_PARAMSetOctetStringOrPtr C.OSSL_PARAM_set_octet_string_or_ptr
func OSSL_PARAMSetOctetStringOrPtr(p *OSSL_PARAM, val unsafe.Pointer, len c.SizeT) c.Int
