// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const PKCS7_S_HEADER = 0
const PKCS7_S_BODY = 1
const PKCS7_S_TAIL = 2
const PKCS7_OP_SET_DETACHED_SIGNATURE = 1
const PKCS7_OP_GET_DETACHED_SIGNATURE = 2
const PKCS7_TEXT = 1
const PKCS7_NOCERTS = 2
const PKCS7_NOSIGS = 4
const PKCS7_NOCHAIN = 8
const PKCS7_NOINTERN = 16
const PKCS7_NOVERIFY = 32
const PKCS7_DETACHED = 64
const PKCS7_BINARY = 128
const PKCS7_NOATTR = 256
const PKCS7_NOSMIMECAP = 512
const PKCS7_NOOLDMIMETYPE = 1024
const PKCS7_CRLFEOL = 2048
const PKCS7_STREAM = 4096
const PKCS7_NOCRL = 8192
const PKCS7_PARTIAL = 16384
const PKCS7_REUSE_DIGEST = 32768
const PKCS7_NO_DUAL_CONTENT = 65536
const SMIME_TEXT = 1
const SMIME_NOCERTS = 2
const SMIME_NOSIGS = 4
const SMIME_NOCHAIN = 8
const SMIME_NOINTERN = 16
const SMIME_NOVERIFY = 32
const SMIME_DETACHED = 64
const SMIME_BINARY = 128
const SMIME_NOATTR = 256
const SMIME_ASCIICRLF = 524288

// -
// Encryption_ID           DES-CBC
// Digest_ID               MD5
// Digest_Encryption_ID    rsaEncryption
// Key_Encryption_ID       rsaEncryption
type PKCS7CTXSt struct {
	Libctx *OSSL_LIB_CTX
	Propq  *c.Char
}

// -
// Encryption_ID           DES-CBC
// Digest_ID               MD5
// Digest_Encryption_ID    rsaEncryption
// Key_Encryption_ID       rsaEncryption
type PKCS7_CTX = PKCS7CTXSt
type Pkcs7IssuerAndSerialSt struct {
	Issuer *X509_NAME
	Serial *ASN1_INTEGER
}
type PKCS7_ISSUER_AND_SERIAL = Pkcs7IssuerAndSerialSt
type Pkcs7SignerInfoSt struct {
	Version         *ASN1_INTEGER
	IssuerAndSerial *PKCS7_ISSUER_AND_SERIAL
	DigestAlg       *X509_ALGOR
	AuthAttr        *StackStX509ATTRIBUTE
	DigestEncAlg    *X509_ALGOR
	EncDigest       *ASN1_OCTET_STRING
	UnauthAttr      *StackStX509ATTRIBUTE
	Pkey            *EVP_PKEY
	Ctx             *PKCS7_CTX
}
type PKCS7_SIGNER_INFO = Pkcs7SignerInfoSt
type StackStPKCS7SIGNER_INFO struct {
}

// clang-format off
//
// llgo:type C
type SkPKCS7SIGNER_INFOCompfunc = func(_llcppg_param1 **PKCS7_SIGNER_INFO, _llcppg_param2 **PKCS7_SIGNER_INFO) c.Int

// clang-format off
//
// llgo:type C
type SkPKCS7SIGNER_INFOFreefunc = func(_llcppg_param1 *PKCS7_SIGNER_INFO)

// clang-format off
//
// llgo:type C
type SkPKCS7SIGNER_INFOCopyfunc = func(_llcppg_param1 *PKCS7_SIGNER_INFO) *PKCS7_SIGNER_INFO

// clang-format on
type Pkcs7RecipInfoSt struct {
	Version         *ASN1_INTEGER
	IssuerAndSerial *PKCS7_ISSUER_AND_SERIAL
	KeyEncAlgor     *X509_ALGOR
	EncKey          *ASN1_OCTET_STRING
	Cert            *X509
	Ctx             *PKCS7_CTX
}

// clang-format on
type PKCS7_RECIP_INFO = Pkcs7RecipInfoSt
type StackStPKCS7RECIP_INFO struct {
}

// clang-format off
//
// llgo:type C
type SkPKCS7RECIP_INFOCompfunc = func(_llcppg_param1 **PKCS7_RECIP_INFO, _llcppg_param2 **PKCS7_RECIP_INFO) c.Int

// clang-format off
//
// llgo:type C
type SkPKCS7RECIP_INFOFreefunc = func(_llcppg_param1 *PKCS7_RECIP_INFO)

// clang-format off
//
// llgo:type C
type SkPKCS7RECIP_INFOCopyfunc = func(_llcppg_param1 *PKCS7_RECIP_INFO) *PKCS7_RECIP_INFO

// clang-format on
type Pkcs7SignedSt struct {
	Version    *ASN1_INTEGER
	MdAlgs     *StackStX509ALGOR
	Cert       *StackStX509
	Crl        *StackStX509CRL
	SignerInfo *StackStPKCS7SIGNER_INFO
	Contents   *Pkcs7St
}
type Pkcs7St struct {
	Asn1     *uint8
	Length   c.Long
	State    c.Int
	Detached c.Int
	Type     *ASN1_OBJECT
	D        _llcppg_anon_3
	Ctx      PKCS7_CTX
}

// clang-format on
type PKCS7_SIGNED = Pkcs7SignedSt

// The above structure is very very similar to PKCS7_SIGN_ENVELOPE. How about
// merging the two
type Pkcs7EncContentSt struct {
	ContentType *ASN1_OBJECT
	Algorithm   *X509_ALGOR
	EncData     *ASN1_OCTET_STRING
	Cipher      *EVP_CIPHER
	Ctx         *PKCS7_CTX
}

// The above structure is very very similar to PKCS7_SIGN_ENVELOPE. How about
// merging the two
type PKCS7_ENC_CONTENT = Pkcs7EncContentSt
type Pkcs7EnvelopedSt struct {
	Version       *ASN1_INTEGER
	Recipientinfo *StackStPKCS7RECIP_INFO
	EncData       *PKCS7_ENC_CONTENT
}
type PKCS7_ENVELOPE = Pkcs7EnvelopedSt
type Pkcs7SignedandenvelopedSt struct {
	Version       *ASN1_INTEGER
	MdAlgs        *StackStX509ALGOR
	Cert          *StackStX509
	Crl           *StackStX509CRL
	SignerInfo    *StackStPKCS7SIGNER_INFO
	EncData       *PKCS7_ENC_CONTENT
	Recipientinfo *StackStPKCS7RECIP_INFO
}
type PKCS7_SIGN_ENVELOPE = Pkcs7SignedandenvelopedSt
type Pkcs7DigestSt struct {
	Version  *ASN1_INTEGER
	Md       *X509_ALGOR
	Contents *Pkcs7St
	Digest   *ASN1_OCTET_STRING
}
type PKCS7_DIGEST = Pkcs7DigestSt
type Pkcs7EncryptedSt struct {
	Version *ASN1_INTEGER
	EncData *PKCS7_ENC_CONTENT
}
type PKCS7_ENCRYPT = Pkcs7EncryptedSt
type _llcppg_anon_3 struct {
	_xgo_union [1]uint64
}
type PKCS7 = Pkcs7St
type StackStPKCS7 struct {
}

// clang-format off
//
// llgo:type C
type SkPKCS7Compfunc = func(_llcppg_param1 **PKCS7, _llcppg_param2 **PKCS7) c.Int

// clang-format off
//
// llgo:type C
type SkPKCS7Freefunc = func(_llcppg_param1 *PKCS7)

// clang-format off
//
// llgo:type C
type SkPKCS7Copyfunc = func(_llcppg_param1 *PKCS7) *PKCS7

func (p *_llcppg_anon_3) XGof_ref_ptr() **c.Char {
	return (**c.Char)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_3) XGof_ref_data() **ASN1_OCTET_STRING {
	return (**ASN1_OCTET_STRING)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_3) XGof_ref_sign() **PKCS7_SIGNED {
	return (**PKCS7_SIGNED)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_3) XGof_ref_enveloped() **PKCS7_ENVELOPE {
	return (**PKCS7_ENVELOPE)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_3) XGof_ref_signed_and_enveloped() **PKCS7_SIGN_ENVELOPE {
	return (**PKCS7_SIGN_ENVELOPE)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_3) XGof_ref_digest() **PKCS7_DIGEST {
	return (**PKCS7_DIGEST)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_3) XGof_ref_encrypted() **PKCS7_ENCRYPT {
	return (**PKCS7_ENCRYPT)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_3) XGof_ref_other() **ASN1_TYPE {
	return (**ASN1_TYPE)(unsafe.Pointer(p))
}

//go:linkname PKCS7ISSUER_AND_SERIALNew C.PKCS7_ISSUER_AND_SERIAL_new
func PKCS7ISSUER_AND_SERIALNew() *PKCS7_ISSUER_AND_SERIAL

//go:linkname PKCS7ISSUER_AND_SERIALFree C.PKCS7_ISSUER_AND_SERIAL_free
func PKCS7ISSUER_AND_SERIALFree(a *PKCS7_ISSUER_AND_SERIAL)

//go:linkname D2iPKCS7ISSUER_AND_SERIAL C.d2i_PKCS7_ISSUER_AND_SERIAL
func D2iPKCS7ISSUER_AND_SERIAL(a **PKCS7_ISSUER_AND_SERIAL, in **uint8, len c.Long) *PKCS7_ISSUER_AND_SERIAL

//go:linkname I2dPKCS7ISSUER_AND_SERIAL C.i2d_PKCS7_ISSUER_AND_SERIAL
func I2dPKCS7ISSUER_AND_SERIAL(a *PKCS7_ISSUER_AND_SERIAL, out **uint8) c.Int

//go:linkname PKCS7ISSUER_AND_SERIALIt C.PKCS7_ISSUER_AND_SERIAL_it
func PKCS7ISSUER_AND_SERIALIt() *ASN1_ITEM

//go:linkname PKCS7ISSUER_AND_SERIALDigest C.PKCS7_ISSUER_AND_SERIAL_digest
func PKCS7ISSUER_AND_SERIALDigest(data *PKCS7_ISSUER_AND_SERIAL, type_ *EVP_MD, md *uint8, len *c.Uint) c.Int

//go:linkname D2iPKCS7Fp C.d2i_PKCS7_fp
func D2iPKCS7Fp(fp *c.FILE, p7 **PKCS7) *PKCS7

//go:linkname I2dPKCS7Fp C.i2d_PKCS7_fp
func I2dPKCS7Fp(fp *c.FILE, p7 *PKCS7) c.Int

//go:linkname PKCS7Dup C.PKCS7_dup
func PKCS7Dup(a *PKCS7) *PKCS7

//go:linkname D2iPKCS7Bio C.d2i_PKCS7_bio
func D2iPKCS7Bio(bp *BIO, p7 **PKCS7) *PKCS7

//go:linkname I2dPKCS7Bio C.i2d_PKCS7_bio
func I2dPKCS7Bio(bp *BIO, p7 *PKCS7) c.Int

//go:linkname I2dPKCS7BioStream C.i2d_PKCS7_bio_stream
func I2dPKCS7BioStream(out *BIO, p7 *PKCS7, in *BIO, flags c.Int) c.Int

//go:linkname PEMWriteBioPKCS7Stream C.PEM_write_bio_PKCS7_stream
func PEMWriteBioPKCS7Stream(out *BIO, p7 *PKCS7, in *BIO, flags c.Int) c.Int

//go:linkname PKCS7SIGNER_INFONew C.PKCS7_SIGNER_INFO_new
func PKCS7SIGNER_INFONew() *PKCS7_SIGNER_INFO

//go:linkname PKCS7SIGNER_INFOFree C.PKCS7_SIGNER_INFO_free
func PKCS7SIGNER_INFOFree(a *PKCS7_SIGNER_INFO)

//go:linkname D2iPKCS7SIGNER_INFO C.d2i_PKCS7_SIGNER_INFO
func D2iPKCS7SIGNER_INFO(a **PKCS7_SIGNER_INFO, in **uint8, len c.Long) *PKCS7_SIGNER_INFO

//go:linkname I2dPKCS7SIGNER_INFO C.i2d_PKCS7_SIGNER_INFO
func I2dPKCS7SIGNER_INFO(a *PKCS7_SIGNER_INFO, out **uint8) c.Int

//go:linkname PKCS7SIGNER_INFOIt C.PKCS7_SIGNER_INFO_it
func PKCS7SIGNER_INFOIt() *ASN1_ITEM

//go:linkname PKCS7RECIP_INFONew C.PKCS7_RECIP_INFO_new
func PKCS7RECIP_INFONew() *PKCS7_RECIP_INFO

//go:linkname PKCS7RECIP_INFOFree C.PKCS7_RECIP_INFO_free
func PKCS7RECIP_INFOFree(a *PKCS7_RECIP_INFO)

//go:linkname D2iPKCS7RECIP_INFO C.d2i_PKCS7_RECIP_INFO
func D2iPKCS7RECIP_INFO(a **PKCS7_RECIP_INFO, in **uint8, len c.Long) *PKCS7_RECIP_INFO

//go:linkname I2dPKCS7RECIP_INFO C.i2d_PKCS7_RECIP_INFO
func I2dPKCS7RECIP_INFO(a *PKCS7_RECIP_INFO, out **uint8) c.Int

//go:linkname PKCS7RECIP_INFOIt C.PKCS7_RECIP_INFO_it
func PKCS7RECIP_INFOIt() *ASN1_ITEM

//go:linkname PKCS7SIGNEDNew C.PKCS7_SIGNED_new
func PKCS7SIGNEDNew() *PKCS7_SIGNED

//go:linkname PKCS7SIGNEDFree C.PKCS7_SIGNED_free
func PKCS7SIGNEDFree(a *PKCS7_SIGNED)

//go:linkname D2iPKCS7SIGNED C.d2i_PKCS7_SIGNED
func D2iPKCS7SIGNED(a **PKCS7_SIGNED, in **uint8, len c.Long) *PKCS7_SIGNED

//go:linkname I2dPKCS7SIGNED C.i2d_PKCS7_SIGNED
func I2dPKCS7SIGNED(a *PKCS7_SIGNED, out **uint8) c.Int

//go:linkname PKCS7SIGNEDIt C.PKCS7_SIGNED_it
func PKCS7SIGNEDIt() *ASN1_ITEM

//go:linkname PKCS7ENC_CONTENTNew C.PKCS7_ENC_CONTENT_new
func PKCS7ENC_CONTENTNew() *PKCS7_ENC_CONTENT

//go:linkname PKCS7ENC_CONTENTFree C.PKCS7_ENC_CONTENT_free
func PKCS7ENC_CONTENTFree(a *PKCS7_ENC_CONTENT)

//go:linkname D2iPKCS7ENC_CONTENT C.d2i_PKCS7_ENC_CONTENT
func D2iPKCS7ENC_CONTENT(a **PKCS7_ENC_CONTENT, in **uint8, len c.Long) *PKCS7_ENC_CONTENT

//go:linkname I2dPKCS7ENC_CONTENT C.i2d_PKCS7_ENC_CONTENT
func I2dPKCS7ENC_CONTENT(a *PKCS7_ENC_CONTENT, out **uint8) c.Int

//go:linkname PKCS7ENC_CONTENTIt C.PKCS7_ENC_CONTENT_it
func PKCS7ENC_CONTENTIt() *ASN1_ITEM

//go:linkname PKCS7ENVELOPENew C.PKCS7_ENVELOPE_new
func PKCS7ENVELOPENew() *PKCS7_ENVELOPE

//go:linkname PKCS7ENVELOPEFree C.PKCS7_ENVELOPE_free
func PKCS7ENVELOPEFree(a *PKCS7_ENVELOPE)

//go:linkname D2iPKCS7ENVELOPE C.d2i_PKCS7_ENVELOPE
func D2iPKCS7ENVELOPE(a **PKCS7_ENVELOPE, in **uint8, len c.Long) *PKCS7_ENVELOPE

//go:linkname I2dPKCS7ENVELOPE C.i2d_PKCS7_ENVELOPE
func I2dPKCS7ENVELOPE(a *PKCS7_ENVELOPE, out **uint8) c.Int

//go:linkname PKCS7ENVELOPEIt C.PKCS7_ENVELOPE_it
func PKCS7ENVELOPEIt() *ASN1_ITEM

//go:linkname PKCS7SIGN_ENVELOPENew C.PKCS7_SIGN_ENVELOPE_new
func PKCS7SIGN_ENVELOPENew() *PKCS7_SIGN_ENVELOPE

//go:linkname PKCS7SIGN_ENVELOPEFree C.PKCS7_SIGN_ENVELOPE_free
func PKCS7SIGN_ENVELOPEFree(a *PKCS7_SIGN_ENVELOPE)

//go:linkname D2iPKCS7SIGN_ENVELOPE C.d2i_PKCS7_SIGN_ENVELOPE
func D2iPKCS7SIGN_ENVELOPE(a **PKCS7_SIGN_ENVELOPE, in **uint8, len c.Long) *PKCS7_SIGN_ENVELOPE

//go:linkname I2dPKCS7SIGN_ENVELOPE C.i2d_PKCS7_SIGN_ENVELOPE
func I2dPKCS7SIGN_ENVELOPE(a *PKCS7_SIGN_ENVELOPE, out **uint8) c.Int

//go:linkname PKCS7SIGN_ENVELOPEIt C.PKCS7_SIGN_ENVELOPE_it
func PKCS7SIGN_ENVELOPEIt() *ASN1_ITEM

//go:linkname PKCS7DIGESTNew C.PKCS7_DIGEST_new
func PKCS7DIGESTNew() *PKCS7_DIGEST

//go:linkname PKCS7DIGESTFree C.PKCS7_DIGEST_free
func PKCS7DIGESTFree(a *PKCS7_DIGEST)

//go:linkname D2iPKCS7DIGEST C.d2i_PKCS7_DIGEST
func D2iPKCS7DIGEST(a **PKCS7_DIGEST, in **uint8, len c.Long) *PKCS7_DIGEST

//go:linkname I2dPKCS7DIGEST C.i2d_PKCS7_DIGEST
func I2dPKCS7DIGEST(a *PKCS7_DIGEST, out **uint8) c.Int

//go:linkname PKCS7DIGESTIt C.PKCS7_DIGEST_it
func PKCS7DIGESTIt() *ASN1_ITEM

//go:linkname PKCS7ENCRYPTNew C.PKCS7_ENCRYPT_new
func PKCS7ENCRYPTNew() *PKCS7_ENCRYPT

//go:linkname PKCS7ENCRYPTFree C.PKCS7_ENCRYPT_free
func PKCS7ENCRYPTFree(a *PKCS7_ENCRYPT)

//go:linkname D2iPKCS7ENCRYPT C.d2i_PKCS7_ENCRYPT
func D2iPKCS7ENCRYPT(a **PKCS7_ENCRYPT, in **uint8, len c.Long) *PKCS7_ENCRYPT

//go:linkname I2dPKCS7ENCRYPT C.i2d_PKCS7_ENCRYPT
func I2dPKCS7ENCRYPT(a *PKCS7_ENCRYPT, out **uint8) c.Int

//go:linkname PKCS7ENCRYPTIt C.PKCS7_ENCRYPT_it
func PKCS7ENCRYPTIt() *ASN1_ITEM

//go:linkname PKCS7New C.PKCS7_new
func PKCS7New() *PKCS7

//go:linkname PKCS7Free C.PKCS7_free
func PKCS7Free(a *PKCS7)

//go:linkname D2iPKCS7 C.d2i_PKCS7
func D2iPKCS7(a **PKCS7, in **uint8, len c.Long) *PKCS7

//go:linkname I2dPKCS7 C.i2d_PKCS7
func I2dPKCS7(a *PKCS7, out **uint8) c.Int

//go:linkname PKCS7It C.PKCS7_it
func PKCS7It() *ASN1_ITEM

//go:linkname PKCS7NewEx C.PKCS7_new_ex
func PKCS7NewEx(libctx *OSSL_LIB_CTX, propq *c.Char) *PKCS7

//go:linkname PKCS7ATTR_SIGNIt C.PKCS7_ATTR_SIGN_it
func PKCS7ATTR_SIGNIt() *ASN1_ITEM

//go:linkname PKCS7ATTR_VERIFYIt C.PKCS7_ATTR_VERIFY_it
func PKCS7ATTR_VERIFYIt() *ASN1_ITEM

//go:linkname I2dPKCS7NDEF C.i2d_PKCS7_NDEF
func I2dPKCS7NDEF(a *PKCS7, out **uint8) c.Int

//go:linkname PKCS7PrintCtx C.PKCS7_print_ctx
func PKCS7PrintCtx(out *BIO, x *PKCS7, indent c.Int, pctx *ASN1_PCTX) c.Int

//go:linkname PKCS7Ctrl C.PKCS7_ctrl
func PKCS7Ctrl(p7 *PKCS7, cmd c.Int, larg c.Long, parg *c.Char) c.Long

//go:linkname PKCS7TypeIsOther C.PKCS7_type_is_other
func PKCS7TypeIsOther(p7 *PKCS7) c.Int

//go:linkname PKCS7SetType C.PKCS7_set_type
func PKCS7SetType(p7 *PKCS7, type_ c.Int) c.Int

//go:linkname PKCS7Set0TypeOther C.PKCS7_set0_type_other
func PKCS7Set0TypeOther(p7 *PKCS7, type_ c.Int, other *ASN1_TYPE) c.Int

//go:linkname PKCS7SetContent C.PKCS7_set_content
func PKCS7SetContent(p7 *PKCS7, p7_data *PKCS7) c.Int

//go:linkname PKCS7SIGNER_INFOSet C.PKCS7_SIGNER_INFO_set
func PKCS7SIGNER_INFOSet(p7i *PKCS7_SIGNER_INFO, x509 *X509, pkey *EVP_PKEY, dgst *EVP_MD) c.Int

//go:linkname PKCS7SIGNER_INFOSign C.PKCS7_SIGNER_INFO_sign
func PKCS7SIGNER_INFOSign(si *PKCS7_SIGNER_INFO) c.Int

//go:linkname PKCS7AddSigner C.PKCS7_add_signer
func PKCS7AddSigner(p7 *PKCS7, p7i *PKCS7_SIGNER_INFO) c.Int

//go:linkname PKCS7AddCertificate C.PKCS7_add_certificate
func PKCS7AddCertificate(p7 *PKCS7, cert *X509) c.Int

//go:linkname PKCS7AddCrl C.PKCS7_add_crl
func PKCS7AddCrl(p7 *PKCS7, crl *X509_CRL) c.Int

//go:linkname PKCS7ContentNew C.PKCS7_content_new
func PKCS7ContentNew(p7 *PKCS7, nid c.Int) c.Int

//go:linkname PKCS7DataVerify C.PKCS7_dataVerify
func PKCS7DataVerify(cert_store *X509_STORE, ctx *X509_STORE_CTX, bio *BIO, p7 *PKCS7, si *PKCS7_SIGNER_INFO) c.Int

//go:linkname PKCS7SignatureVerify C.PKCS7_signatureVerify
func PKCS7SignatureVerify(bio *BIO, p7 *PKCS7, si *PKCS7_SIGNER_INFO, signer *X509) c.Int

//go:linkname PKCS7DataInit C.PKCS7_dataInit
func PKCS7DataInit(p7 *PKCS7, bio *BIO) *BIO

//go:linkname PKCS7DataFinal C.PKCS7_dataFinal
func PKCS7DataFinal(p7 *PKCS7, bio *BIO) c.Int

//go:linkname PKCS7DataDecode C.PKCS7_dataDecode
func PKCS7DataDecode(p7 *PKCS7, pkey *EVP_PKEY, in_bio *BIO, pcert *X509) *BIO

//go:linkname PKCS7AddSignature C.PKCS7_add_signature
func PKCS7AddSignature(p7 *PKCS7, x509 *X509, pkey *EVP_PKEY, dgst *EVP_MD) *PKCS7_SIGNER_INFO

//go:linkname PKCS7CertFromSignerInfo C.PKCS7_cert_from_signer_info
func PKCS7CertFromSignerInfo(p7 *PKCS7, si *PKCS7_SIGNER_INFO) *X509

//go:linkname PKCS7SetDigest C.PKCS7_set_digest
func PKCS7SetDigest(p7 *PKCS7, md *EVP_MD) c.Int

//go:linkname PKCS7GetSignerInfo C.PKCS7_get_signer_info
func PKCS7GetSignerInfo(p7 *PKCS7) *StackStPKCS7SIGNER_INFO

//go:linkname PKCS7AddRecipient C.PKCS7_add_recipient
func PKCS7AddRecipient(p7 *PKCS7, x509 *X509) *PKCS7_RECIP_INFO

//go:linkname PKCS7SIGNER_INFOGet0Algs C.PKCS7_SIGNER_INFO_get0_algs
func PKCS7SIGNER_INFOGet0Algs(si *PKCS7_SIGNER_INFO, pk **EVP_PKEY, pdig **X509_ALGOR, psig **X509_ALGOR)

//go:linkname PKCS7RECIP_INFOGet0Alg C.PKCS7_RECIP_INFO_get0_alg
func PKCS7RECIP_INFOGet0Alg(ri *PKCS7_RECIP_INFO, penc **X509_ALGOR)

//go:linkname PKCS7AddRecipientInfo C.PKCS7_add_recipient_info
func PKCS7AddRecipientInfo(p7 *PKCS7, ri *PKCS7_RECIP_INFO) c.Int

//go:linkname PKCS7RECIP_INFOSet C.PKCS7_RECIP_INFO_set
func PKCS7RECIP_INFOSet(p7i *PKCS7_RECIP_INFO, x509 *X509) c.Int

//go:linkname PKCS7SetCipher C.PKCS7_set_cipher
func PKCS7SetCipher(p7 *PKCS7, cipher *EVP_CIPHER) c.Int

//go:linkname PKCS7Stream C.PKCS7_stream
func PKCS7Stream(boundary ***uint8, p7 *PKCS7) c.Int

//go:linkname PKCS7GetIssuerAndSerial C.PKCS7_get_issuer_and_serial
func PKCS7GetIssuerAndSerial(p7 *PKCS7, idx c.Int) *PKCS7_ISSUER_AND_SERIAL

//go:linkname PKCS7GetOctetString C.PKCS7_get_octet_string
func PKCS7GetOctetString(p7 *PKCS7) *ASN1_OCTET_STRING

//go:linkname PKCS7DigestFromAttributes C.PKCS7_digest_from_attributes
func PKCS7DigestFromAttributes(sk *StackStX509ATTRIBUTE) *ASN1_OCTET_STRING

//go:linkname PKCS7AddSignedAttribute C.PKCS7_add_signed_attribute
func PKCS7AddSignedAttribute(p7si *PKCS7_SIGNER_INFO, nid c.Int, type_ c.Int, data unsafe.Pointer) c.Int

//go:linkname PKCS7AddAttribute C.PKCS7_add_attribute
func PKCS7AddAttribute(p7si *PKCS7_SIGNER_INFO, nid c.Int, atrtype c.Int, value unsafe.Pointer) c.Int

//go:linkname PKCS7GetAttribute C.PKCS7_get_attribute
func PKCS7GetAttribute(si *PKCS7_SIGNER_INFO, nid c.Int) *ASN1_TYPE

//go:linkname PKCS7GetSignedAttribute C.PKCS7_get_signed_attribute
func PKCS7GetSignedAttribute(si *PKCS7_SIGNER_INFO, nid c.Int) *ASN1_TYPE

//go:linkname PKCS7SetSignedAttributes C.PKCS7_set_signed_attributes
func PKCS7SetSignedAttributes(p7si *PKCS7_SIGNER_INFO, sk *StackStX509ATTRIBUTE) c.Int

//go:linkname PKCS7SetAttributes C.PKCS7_set_attributes
func PKCS7SetAttributes(p7si *PKCS7_SIGNER_INFO, sk *StackStX509ATTRIBUTE) c.Int

//go:linkname PKCS7Sign C.PKCS7_sign
func PKCS7Sign(signcert *X509, pkey *EVP_PKEY, certs *StackStX509, data *BIO, flags c.Int) *PKCS7

//go:linkname PKCS7SignEx C.PKCS7_sign_ex
func PKCS7SignEx(signcert *X509, pkey *EVP_PKEY, certs *StackStX509, data *BIO, flags c.Int, libctx *OSSL_LIB_CTX, propq *c.Char) *PKCS7

//go:linkname PKCS7SignAddSigner C.PKCS7_sign_add_signer
func PKCS7SignAddSigner(p7 *PKCS7, signcert *X509, pkey *EVP_PKEY, md *EVP_MD, flags c.Int) *PKCS7_SIGNER_INFO

//go:linkname PKCS7Final C.PKCS7_final
func PKCS7Final(p7 *PKCS7, data *BIO, flags c.Int) c.Int

//go:linkname PKCS7Verify C.PKCS7_verify
func PKCS7Verify(p7 *PKCS7, certs *StackStX509, store *X509_STORE, indata *BIO, out *BIO, flags c.Int) c.Int

//go:linkname PKCS7Get0Signers C.PKCS7_get0_signers
func PKCS7Get0Signers(p7 *PKCS7, certs *StackStX509, flags c.Int) *StackStX509

//go:linkname PKCS7Encrypt C.PKCS7_encrypt
func PKCS7Encrypt(certs *StackStX509, in *BIO, cipher *EVP_CIPHER, flags c.Int) *PKCS7

//go:linkname PKCS7EncryptEx C.PKCS7_encrypt_ex
func PKCS7EncryptEx(certs *StackStX509, in *BIO, cipher *EVP_CIPHER, flags c.Int, libctx *OSSL_LIB_CTX, propq *c.Char) *PKCS7

//go:linkname PKCS7Decrypt C.PKCS7_decrypt
func PKCS7Decrypt(p7 *PKCS7, pkey *EVP_PKEY, cert *X509, data *BIO, flags c.Int) c.Int

//go:linkname PKCS7AddAttribSmimecap C.PKCS7_add_attrib_smimecap
func PKCS7AddAttribSmimecap(si *PKCS7_SIGNER_INFO, cap *StackStX509ALGOR) c.Int

//go:linkname PKCS7GetSmimecap C.PKCS7_get_smimecap
func PKCS7GetSmimecap(si *PKCS7_SIGNER_INFO) *StackStX509ALGOR

//go:linkname PKCS7SimpleSmimecap C.PKCS7_simple_smimecap
func PKCS7SimpleSmimecap(sk *StackStX509ALGOR, nid c.Int, arg c.Int) c.Int

//go:linkname PKCS7AddAttribContentType C.PKCS7_add_attrib_content_type
func PKCS7AddAttribContentType(si *PKCS7_SIGNER_INFO, coid *ASN1_OBJECT) c.Int

//go:linkname PKCS7Add0AttribSigningTime C.PKCS7_add0_attrib_signing_time
func PKCS7Add0AttribSigningTime(si *PKCS7_SIGNER_INFO, t *ASN1_TIME) c.Int

//go:linkname PKCS7Add1AttribDigest C.PKCS7_add1_attrib_digest
func PKCS7Add1AttribDigest(si *PKCS7_SIGNER_INFO, md *uint8, mdlen c.Int) c.Int

//go:linkname SMIMEWritePKCS7 C.SMIME_write_PKCS7
func SMIMEWritePKCS7(bio *BIO, p7 *PKCS7, data *BIO, flags c.Int) c.Int

//go:linkname SMIMEReadPKCS7Ex C.SMIME_read_PKCS7_ex
func SMIMEReadPKCS7Ex(bio *BIO, bcont **BIO, p7 **PKCS7) *PKCS7

//go:linkname SMIMEReadPKCS7 C.SMIME_read_PKCS7
func SMIMEReadPKCS7(bio *BIO, bcont **BIO) *PKCS7

//go:linkname BIONewPKCS7 C.BIO_new_PKCS7
func BIONewPKCS7(out *BIO, p7 *PKCS7) *BIO
