// Code generated by llcppg; DO NOT EDIT.

package openssl

import _ "unsafe"

const OSSL_QUIC_ERR_NO_ERROR = 0
const OSSL_QUIC_ERR_INTERNAL_ERROR = 1
const OSSL_QUIC_ERR_CONNECTION_REFUSED = 2
const OSSL_QUIC_ERR_FLOW_CONTROL_ERROR = 3
const OSSL_QUIC_ERR_STREAM_LIMIT_ERROR = 4
const OSSL_QUIC_ERR_STREAM_STATE_ERROR = 5
const OSSL_QUIC_ERR_FINAL_SIZE_ERROR = 6
const OSSL_QUIC_ERR_FRAME_ENCODING_ERROR = 7
const OSSL_QUIC_ERR_TRANSPORT_PARAMETER_ERROR = 8
const OSSL_QUIC_ERR_CONNECTION_ID_LIMIT_ERROR = 9
const OSSL_QUIC_ERR_PROTOCOL_VIOLATION = 10
const OSSL_QUIC_ERR_INVALID_TOKEN = 11
const OSSL_QUIC_ERR_APPLICATION_ERROR = 12
const OSSL_QUIC_ERR_CRYPTO_BUFFER_EXCEEDED = 13
const OSSL_QUIC_ERR_KEY_UPDATE_ERROR = 14
const OSSL_QUIC_ERR_AEAD_LIMIT_REACHED = 15
const OSSL_QUIC_ERR_NO_VIABLE_PATH = 16
const OSSL_QUIC_ERR_CRYPTO_ERR_BEGIN = 256
const OSSL_QUIC_ERR_CRYPTO_ERR_END = 511

// Method used for non-thread-assisted QUIC client operation.
//
//go:linkname OSSL_QUICClientMethod C.OSSL_QUIC_client_method
func OSSL_QUICClientMethod() *SSL_METHOD

// Method used for thread-assisted QUIC client operation.
//
//go:linkname OSSL_QUICClientThreadMethod C.OSSL_QUIC_client_thread_method
func OSSL_QUICClientThreadMethod() *SSL_METHOD

// Method used for QUIC server operation.
//
//go:linkname OSSL_QUICServerMethod C.OSSL_QUIC_server_method
func OSSL_QUICServerMethod() *SSL_METHOD

// Method used for QUIC client/server connection
//
//go:linkname OSSL_QUICMethod C.OSSL_QUIC_method
func OSSL_QUICMethod() *SSL_METHOD
