// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const OPENSSL_RSA_MAX_MODULUS_BITS = 16384
const OPENSSL_RSA_FIPS_MIN_MODULUS_BITS = 2048
const OPENSSL_RSA_SMALL_MODULUS_BITS = 3072
const OPENSSL_RSA_MAX_PUBEXP_BITS = 64
const RSA_ASN1_VERSION_DEFAULT = 0
const RSA_ASN1_VERSION_MULTI = 1
const RSA_DEFAULT_PRIME_NUM = 2
const RSA_METHOD_FLAG_NO_CHECK = 1
const RSA_FLAG_CACHE_PUBLIC = 2
const RSA_FLAG_CACHE_PRIVATE = 4
const RSA_FLAG_BLINDING = 8
const RSA_FLAG_THREAD_SAFE = 16
const RSA_FLAG_EXT_PKEY = 32
const RSA_FLAG_NO_BLINDING = 128
const RSA_FLAG_NO_CONSTTIME = 0
const RSA_FLAG_NO_EXP_CONSTTIME = 0
const RSA_FLAG_TYPE_MASK = 61440
const RSA_FLAG_TYPE_RSA = 0
const RSA_FLAG_TYPE_RSASSAPSS = 4096
const RSA_FLAG_TYPE_RSAESOAEP = 8192
const RSA_PSS_SALTLEN_DIGEST = -1
const RSA_PSS_SALTLEN_AUTO = -2
const RSA_PSS_SALTLEN_MAX = -3
const RSA_PSS_SALTLEN_AUTO_DIGEST_MAX = -4
const RSA_PSS_SALTLEN_MAX_SIGN = -2
const EVP_PKEY_CTRL_RSA_PADDING = 4097
const EVP_PKEY_CTRL_RSA_PSS_SALTLEN = 4098
const EVP_PKEY_CTRL_RSA_KEYGEN_BITS = 4099
const EVP_PKEY_CTRL_RSA_KEYGEN_PUBEXP = 4100
const EVP_PKEY_CTRL_RSA_MGF1_MD = 4101
const EVP_PKEY_CTRL_GET_RSA_PADDING = 4102
const EVP_PKEY_CTRL_GET_RSA_PSS_SALTLEN = 4103
const EVP_PKEY_CTRL_GET_RSA_MGF1_MD = 4104
const EVP_PKEY_CTRL_RSA_OAEP_MD = 4105
const EVP_PKEY_CTRL_RSA_OAEP_LABEL = 4106
const EVP_PKEY_CTRL_GET_RSA_OAEP_MD = 4107
const EVP_PKEY_CTRL_GET_RSA_OAEP_LABEL = 4108
const EVP_PKEY_CTRL_RSA_KEYGEN_PRIMES = 4109
const EVP_PKEY_CTRL_RSA_IMPLICIT_REJECTION = 4110
const RSA_PKCS1_PADDING = 1
const RSA_NO_PADDING = 3
const RSA_PKCS1_OAEP_PADDING = 4
const RSA_X931_PADDING = 5
const RSA_PKCS1_PSS_PADDING = 6
const RSA_PKCS1_WITH_TLS_PADDING = 7
const RSA_PKCS1_NO_IMPLICIT_REJECT_PADDING = 8
const RSA_PKCS1_PADDING_SIZE = 11
const RSA_FLAG_FIPS_METHOD = 1024
const RSA_FLAG_NON_FIPS_ALLOW = 1024
const RSA_FLAG_CHECKED = 2048

type RsaPssParamsSt struct {
	HashAlgorithm    *X509_ALGOR
	MaskGenAlgorithm *X509_ALGOR
	SaltLength       *ASN1_INTEGER
	TrailerField     *ASN1_INTEGER
	MaskHash         *X509_ALGOR
}
type RsaOaepParamsSt struct {
	HashFunc    *X509_ALGOR
	MaskGenFunc *X509_ALGOR
	PSourceFunc *X509_ALGOR
	MaskHash    *X509_ALGOR
}

//go:linkname EVP_PKEY_CTXSetRsaPadding C.EVP_PKEY_CTX_set_rsa_padding
func EVP_PKEY_CTXSetRsaPadding(ctx *EVP_PKEY_CTX, pad_mode c.Int) c.Int

//go:linkname EVP_PKEY_CTXGetRsaPadding C.EVP_PKEY_CTX_get_rsa_padding
func EVP_PKEY_CTXGetRsaPadding(ctx *EVP_PKEY_CTX, pad_mode *c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetRsaPssSaltlen C.EVP_PKEY_CTX_set_rsa_pss_saltlen
func EVP_PKEY_CTXSetRsaPssSaltlen(ctx *EVP_PKEY_CTX, saltlen c.Int) c.Int

//go:linkname EVP_PKEY_CTXGetRsaPssSaltlen C.EVP_PKEY_CTX_get_rsa_pss_saltlen
func EVP_PKEY_CTXGetRsaPssSaltlen(ctx *EVP_PKEY_CTX, saltlen *c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetRsaKeygenBits C.EVP_PKEY_CTX_set_rsa_keygen_bits
func EVP_PKEY_CTXSetRsaKeygenBits(ctx *EVP_PKEY_CTX, bits c.Int) c.Int

//go:linkname EVP_PKEY_CTXSet1RsaKeygenPubexp C.EVP_PKEY_CTX_set1_rsa_keygen_pubexp
func EVP_PKEY_CTXSet1RsaKeygenPubexp(ctx *EVP_PKEY_CTX, pubexp *BIGNUM) c.Int

//go:linkname EVP_PKEY_CTXSetRsaKeygenPrimes C.EVP_PKEY_CTX_set_rsa_keygen_primes
func EVP_PKEY_CTXSetRsaKeygenPrimes(ctx *EVP_PKEY_CTX, primes c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetRsaPssKeygenSaltlen C.EVP_PKEY_CTX_set_rsa_pss_keygen_saltlen
func EVP_PKEY_CTXSetRsaPssKeygenSaltlen(ctx *EVP_PKEY_CTX, saltlen c.Int) c.Int

//go:linkname EVP_PKEY_CTXSetRsaKeygenPubexp C.EVP_PKEY_CTX_set_rsa_keygen_pubexp
func EVP_PKEY_CTXSetRsaKeygenPubexp(ctx *EVP_PKEY_CTX, pubexp *BIGNUM) c.Int

//go:linkname EVP_PKEY_CTXSetRsaMgf1Md C.EVP_PKEY_CTX_set_rsa_mgf1_md
func EVP_PKEY_CTXSetRsaMgf1Md(ctx *EVP_PKEY_CTX, md *EVP_MD) c.Int

//go:linkname EVP_PKEY_CTXSetRsaMgf1MdName C.EVP_PKEY_CTX_set_rsa_mgf1_md_name
func EVP_PKEY_CTXSetRsaMgf1MdName(ctx *EVP_PKEY_CTX, mdname *c.Char, mdprops *c.Char) c.Int

//go:linkname EVP_PKEY_CTXGetRsaMgf1Md C.EVP_PKEY_CTX_get_rsa_mgf1_md
func EVP_PKEY_CTXGetRsaMgf1Md(ctx *EVP_PKEY_CTX, md **EVP_MD) c.Int

//go:linkname EVP_PKEY_CTXGetRsaMgf1MdName C.EVP_PKEY_CTX_get_rsa_mgf1_md_name
func EVP_PKEY_CTXGetRsaMgf1MdName(ctx *EVP_PKEY_CTX, name *c.Char, namelen c.SizeT) c.Int

//go:linkname EVP_PKEY_CTXSetRsaPssKeygenMgf1Md C.EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md
func EVP_PKEY_CTXSetRsaPssKeygenMgf1Md(ctx *EVP_PKEY_CTX, md *EVP_MD) c.Int

//go:linkname EVP_PKEY_CTXSetRsaPssKeygenMgf1MdName C.EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md_name
func EVP_PKEY_CTXSetRsaPssKeygenMgf1MdName(ctx *EVP_PKEY_CTX, mdname *c.Char) c.Int

//go:linkname EVP_PKEY_CTXSetRsaPssKeygenMd C.EVP_PKEY_CTX_set_rsa_pss_keygen_md
func EVP_PKEY_CTXSetRsaPssKeygenMd(ctx *EVP_PKEY_CTX, md *EVP_MD) c.Int

//go:linkname EVP_PKEY_CTXSetRsaPssKeygenMdName C.EVP_PKEY_CTX_set_rsa_pss_keygen_md_name
func EVP_PKEY_CTXSetRsaPssKeygenMdName(ctx *EVP_PKEY_CTX, mdname *c.Char, mdprops *c.Char) c.Int

//go:linkname EVP_PKEY_CTXSetRsaOaepMd C.EVP_PKEY_CTX_set_rsa_oaep_md
func EVP_PKEY_CTXSetRsaOaepMd(ctx *EVP_PKEY_CTX, md *EVP_MD) c.Int

//go:linkname EVP_PKEY_CTXSetRsaOaepMdName C.EVP_PKEY_CTX_set_rsa_oaep_md_name
func EVP_PKEY_CTXSetRsaOaepMdName(ctx *EVP_PKEY_CTX, mdname *c.Char, mdprops *c.Char) c.Int

//go:linkname EVP_PKEY_CTXGetRsaOaepMd C.EVP_PKEY_CTX_get_rsa_oaep_md
func EVP_PKEY_CTXGetRsaOaepMd(ctx *EVP_PKEY_CTX, md **EVP_MD) c.Int

//go:linkname EVP_PKEY_CTXGetRsaOaepMdName C.EVP_PKEY_CTX_get_rsa_oaep_md_name
func EVP_PKEY_CTXGetRsaOaepMdName(ctx *EVP_PKEY_CTX, name *c.Char, namelen c.SizeT) c.Int

//go:linkname EVP_PKEY_CTXSet0RsaOaepLabel C.EVP_PKEY_CTX_set0_rsa_oaep_label
func EVP_PKEY_CTXSet0RsaOaepLabel(ctx *EVP_PKEY_CTX, label unsafe.Pointer, llen c.Int) c.Int

//go:linkname EVP_PKEY_CTXGet0RsaOaepLabel C.EVP_PKEY_CTX_get0_rsa_oaep_label
func EVP_PKEY_CTXGet0RsaOaepLabel(ctx *EVP_PKEY_CTX, label **uint8) c.Int

//go:linkname RSANew C.RSA_new
func RSANew() *RSA

//go:linkname RSANewMethod C.RSA_new_method
func RSANewMethod(engine *ENGINE) *RSA

//go:linkname RSABits C.RSA_bits
func RSABits(rsa *RSA) c.Int

//go:linkname RSASize C.RSA_size
func RSASize(rsa *RSA) c.Int

//go:linkname RSASecurityBits C.RSA_security_bits
func RSASecurityBits(rsa *RSA) c.Int

//go:linkname RSASet0Key C.RSA_set0_key
func RSASet0Key(r *RSA, n *BIGNUM, e *BIGNUM, d *BIGNUM) c.Int

//go:linkname RSASet0Factors C.RSA_set0_factors
func RSASet0Factors(r *RSA, p *BIGNUM, q *BIGNUM) c.Int

//go:linkname RSASet0CrtParams C.RSA_set0_crt_params
func RSASet0CrtParams(r *RSA, dmp1 *BIGNUM, dmq1 *BIGNUM, iqmp *BIGNUM) c.Int

//go:linkname RSASet0MultiPrimeParams C.RSA_set0_multi_prime_params
func RSASet0MultiPrimeParams(r *RSA, primes **BIGNUM, exps **BIGNUM, coeffs **BIGNUM, pnum c.Int) c.Int

//go:linkname RSAGet0Key C.RSA_get0_key
func RSAGet0Key(r *RSA, n **BIGNUM, e **BIGNUM, d **BIGNUM)

//go:linkname RSAGet0Factors C.RSA_get0_factors
func RSAGet0Factors(r *RSA, p **BIGNUM, q **BIGNUM)

//go:linkname RSAGetMultiPrimeExtraCount C.RSA_get_multi_prime_extra_count
func RSAGetMultiPrimeExtraCount(r *RSA) c.Int

//go:linkname RSAGet0MultiPrimeFactors C.RSA_get0_multi_prime_factors
func RSAGet0MultiPrimeFactors(r *RSA, primes **BIGNUM) c.Int

//go:linkname RSAGet0CrtParams C.RSA_get0_crt_params
func RSAGet0CrtParams(r *RSA, dmp1 **BIGNUM, dmq1 **BIGNUM, iqmp **BIGNUM)

//go:linkname RSAGet0MultiPrimeCrtParams C.RSA_get0_multi_prime_crt_params
func RSAGet0MultiPrimeCrtParams(r *RSA, exps **BIGNUM, coeffs **BIGNUM) c.Int

//go:linkname RSAGet0N C.RSA_get0_n
func RSAGet0N(d *RSA) *BIGNUM

//go:linkname RSAGet0E C.RSA_get0_e
func RSAGet0E(d *RSA) *BIGNUM

//go:linkname RSAGet0D C.RSA_get0_d
func RSAGet0D(d *RSA) *BIGNUM

//go:linkname RSAGet0P C.RSA_get0_p
func RSAGet0P(d *RSA) *BIGNUM

//go:linkname RSAGet0Q C.RSA_get0_q
func RSAGet0Q(d *RSA) *BIGNUM

//go:linkname RSAGet0Dmp1 C.RSA_get0_dmp1
func RSAGet0Dmp1(r *RSA) *BIGNUM

//go:linkname RSAGet0Dmq1 C.RSA_get0_dmq1
func RSAGet0Dmq1(r *RSA) *BIGNUM

//go:linkname RSAGet0Iqmp C.RSA_get0_iqmp
func RSAGet0Iqmp(r *RSA) *BIGNUM

//go:linkname RSAGet0PssParams C.RSA_get0_pss_params
func RSAGet0PssParams(r *RSA) *RSA_PSS_PARAMS

//go:linkname RSAClearFlags C.RSA_clear_flags
func RSAClearFlags(r *RSA, flags c.Int)

//go:linkname RSATestFlags C.RSA_test_flags
func RSATestFlags(r *RSA, flags c.Int) c.Int

//go:linkname RSASetFlags C.RSA_set_flags
func RSASetFlags(r *RSA, flags c.Int)

//go:linkname RSAGetVersion C.RSA_get_version
func RSAGetVersion(r *RSA) c.Int

//go:linkname RSAGenerateKey C.RSA_generate_key
func RSAGenerateKey(bits c.Int, e c.Ulong, callback func(_llcppg_param1 c.Int, _llcppg_param2 c.Int, _llcppg_param3 unsafe.Pointer), cb_arg unsafe.Pointer) *RSA

//go:linkname RSAGenerateKeyEx C.RSA_generate_key_ex
func RSAGenerateKeyEx(rsa *RSA, bits c.Int, e *BIGNUM, cb *BN_GENCB) c.Int

// Multi-prime version
//
//go:linkname RSAGenerateMultiPrimeKey C.RSA_generate_multi_prime_key
func RSAGenerateMultiPrimeKey(rsa *RSA, bits c.Int, primes c.Int, e *BIGNUM, cb *BN_GENCB) c.Int

//go:linkname RSAX931DeriveEx C.RSA_X931_derive_ex
func RSAX931DeriveEx(rsa *RSA, p1 *BIGNUM, p2 *BIGNUM, q1 *BIGNUM, q2 *BIGNUM, Xp1 *BIGNUM, Xp2 *BIGNUM, Xp *BIGNUM, Xq1 *BIGNUM, Xq2 *BIGNUM, Xq *BIGNUM, e *BIGNUM, cb *BN_GENCB) c.Int

//go:linkname RSAX931GenerateKeyEx C.RSA_X931_generate_key_ex
func RSAX931GenerateKeyEx(rsa *RSA, bits c.Int, e *BIGNUM, cb *BN_GENCB) c.Int

//go:linkname RSACheckKey C.RSA_check_key
func RSACheckKey(_llcppg_param1 *RSA) c.Int

//go:linkname RSACheckKeyEx C.RSA_check_key_ex
func RSACheckKeyEx(_llcppg_param1 *RSA, cb *BN_GENCB) c.Int

// next 4 return -1 on error
//
//go:linkname RSAPublicEncrypt C.RSA_public_encrypt
func RSAPublicEncrypt(flen c.Int, from *uint8, to *uint8, rsa *RSA, padding c.Int) c.Int

//go:linkname RSAPrivateEncrypt C.RSA_private_encrypt
func RSAPrivateEncrypt(flen c.Int, from *uint8, to *uint8, rsa *RSA, padding c.Int) c.Int

//go:linkname RSAPublicDecrypt C.RSA_public_decrypt
func RSAPublicDecrypt(flen c.Int, from *uint8, to *uint8, rsa *RSA, padding c.Int) c.Int

//go:linkname RSAPrivateDecrypt C.RSA_private_decrypt
func RSAPrivateDecrypt(flen c.Int, from *uint8, to *uint8, rsa *RSA, padding c.Int) c.Int

//go:linkname RSAFree C.RSA_free
func RSAFree(r *RSA)

// "up" the RSA object's reference count
//
//go:linkname RSAUpRef C.RSA_up_ref
func RSAUpRef(r *RSA) c.Int

//go:linkname RSAFlags C.RSA_flags
func RSAFlags(r *RSA) c.Int

//go:linkname RSASetDefaultMethod C.RSA_set_default_method
func RSASetDefaultMethod(meth *RSA_METHOD)

//go:linkname RSAGetDefaultMethod C.RSA_get_default_method
func RSAGetDefaultMethod() *RSA_METHOD

//go:linkname RSANullMethod C.RSA_null_method
func RSANullMethod() *RSA_METHOD

//go:linkname RSAGetMethod C.RSA_get_method
func RSAGetMethod(rsa *RSA) *RSA_METHOD

//go:linkname RSASetMethod C.RSA_set_method
func RSASetMethod(rsa *RSA, meth *RSA_METHOD) c.Int

// these are the actual RSA functions
//
//go:linkname RSA_PKCS1_OpenSSL C.RSA_PKCS1_OpenSSL
func RSA_PKCS1_OpenSSL() *RSA_METHOD

//go:linkname D2iRSAPublicKey C.d2i_RSAPublicKey
func D2iRSAPublicKey(a **RSA, in **uint8, len c.Long) *RSA

//go:linkname I2dRSAPublicKey C.i2d_RSAPublicKey
func I2dRSAPublicKey(a *RSA, out **uint8) c.Int

//go:linkname RSAPublicKeyIt C.RSAPublicKey_it
func RSAPublicKeyIt() *ASN1_ITEM

//go:linkname D2iRSAPrivateKey C.d2i_RSAPrivateKey
func D2iRSAPrivateKey(a **RSA, in **uint8, len c.Long) *RSA

//go:linkname I2dRSAPrivateKey C.i2d_RSAPrivateKey
func I2dRSAPrivateKey(a *RSA, out **uint8) c.Int

//go:linkname RSAPrivateKeyIt C.RSAPrivateKey_it
func RSAPrivateKeyIt() *ASN1_ITEM

//go:linkname RSAPkeyCtxCtrl C.RSA_pkey_ctx_ctrl
func RSAPkeyCtxCtrl(ctx *EVP_PKEY_CTX, optype c.Int, cmd c.Int, p1 c.Int, p2 unsafe.Pointer) c.Int

//go:linkname RSA_PSS_PARAMSNew C.RSA_PSS_PARAMS_new
func RSA_PSS_PARAMSNew() *RSA_PSS_PARAMS

//go:linkname RSA_PSS_PARAMSFree C.RSA_PSS_PARAMS_free
func RSA_PSS_PARAMSFree(a *RSA_PSS_PARAMS)

//go:linkname D2iRSA_PSS_PARAMS C.d2i_RSA_PSS_PARAMS
func D2iRSA_PSS_PARAMS(a **RSA_PSS_PARAMS, in **uint8, len c.Long) *RSA_PSS_PARAMS

//go:linkname I2dRSA_PSS_PARAMS C.i2d_RSA_PSS_PARAMS
func I2dRSA_PSS_PARAMS(a *RSA_PSS_PARAMS, out **uint8) c.Int

//go:linkname RSA_PSS_PARAMSIt C.RSA_PSS_PARAMS_it
func RSA_PSS_PARAMSIt() *ASN1_ITEM

//go:linkname RSA_PSS_PARAMSDup C.RSA_PSS_PARAMS_dup
func RSA_PSS_PARAMSDup(a *RSA_PSS_PARAMS) *RSA_PSS_PARAMS

//go:linkname RSA_OAEP_PARAMSNew C.RSA_OAEP_PARAMS_new
func RSA_OAEP_PARAMSNew() *RSA_OAEP_PARAMS

//go:linkname RSA_OAEP_PARAMSFree C.RSA_OAEP_PARAMS_free
func RSA_OAEP_PARAMSFree(a *RSA_OAEP_PARAMS)

//go:linkname D2iRSA_OAEP_PARAMS C.d2i_RSA_OAEP_PARAMS
func D2iRSA_OAEP_PARAMS(a **RSA_OAEP_PARAMS, in **uint8, len c.Long) *RSA_OAEP_PARAMS

//go:linkname I2dRSA_OAEP_PARAMS C.i2d_RSA_OAEP_PARAMS
func I2dRSA_OAEP_PARAMS(a *RSA_OAEP_PARAMS, out **uint8) c.Int

//go:linkname RSA_OAEP_PARAMSIt C.RSA_OAEP_PARAMS_it
func RSA_OAEP_PARAMSIt() *ASN1_ITEM

//go:linkname RSAPrintFp C.RSA_print_fp
func RSAPrintFp(fp *c.FILE, r *RSA, offset c.Int) c.Int

//go:linkname RSAPrint C.RSA_print
func RSAPrint(bp *BIO, r *RSA, offset c.Int) c.Int

// The following 2 functions sign and verify a X509_SIG ASN1 object inside
// PKCS#1 padded RSA encryption
//
//go:linkname RSASign C.RSA_sign
func RSASign(type_ c.Int, m *uint8, m_length c.Uint, sigret *uint8, siglen *c.Uint, rsa *RSA) c.Int

//go:linkname RSAVerify C.RSA_verify
func RSAVerify(type_ c.Int, m *uint8, m_length c.Uint, sigbuf *uint8, siglen c.Uint, rsa *RSA) c.Int

// The following 2 function sign and verify a ASN1_OCTET_STRING object inside
// PKCS#1 padded RSA encryption
//
//go:linkname RSASignASN1OCTET_STRING C.RSA_sign_ASN1_OCTET_STRING
func RSASignASN1OCTET_STRING(type_ c.Int, m *uint8, m_length c.Uint, sigret *uint8, siglen *c.Uint, rsa *RSA) c.Int

//go:linkname RSAVerifyASN1OCTET_STRING C.RSA_verify_ASN1_OCTET_STRING
func RSAVerifyASN1OCTET_STRING(type_ c.Int, m *uint8, m_length c.Uint, sigbuf *uint8, siglen c.Uint, rsa *RSA) c.Int

//go:linkname RSABlindingOn C.RSA_blinding_on
func RSABlindingOn(rsa *RSA, ctx *BN_CTX) c.Int

//go:linkname RSABlindingOff C.RSA_blinding_off
func RSABlindingOff(rsa *RSA)

//go:linkname RSASetupBlinding C.RSA_setup_blinding
func RSASetupBlinding(rsa *RSA, ctx *BN_CTX) *BN_BLINDING

//go:linkname RSAPaddingAddPKCS1Type1 C.RSA_padding_add_PKCS1_type_1
func RSAPaddingAddPKCS1Type1(to *uint8, tlen c.Int, f *uint8, fl c.Int) c.Int

//go:linkname RSAPaddingCheckPKCS1Type1 C.RSA_padding_check_PKCS1_type_1
func RSAPaddingCheckPKCS1Type1(to *uint8, tlen c.Int, f *uint8, fl c.Int, rsa_len c.Int) c.Int

//go:linkname RSAPaddingAddPKCS1Type2 C.RSA_padding_add_PKCS1_type_2
func RSAPaddingAddPKCS1Type2(to *uint8, tlen c.Int, f *uint8, fl c.Int) c.Int

//go:linkname RSAPaddingCheckPKCS1Type2 C.RSA_padding_check_PKCS1_type_2
func RSAPaddingCheckPKCS1Type2(to *uint8, tlen c.Int, f *uint8, fl c.Int, rsa_len c.Int) c.Int

//go:linkname PKCS1_MGF1 C.PKCS1_MGF1
func PKCS1_MGF1(mask *uint8, len c.Long, seed *uint8, seedlen c.Long, dgst *EVP_MD) c.Int

//go:linkname RSAPaddingAddPKCS1OAEP C.RSA_padding_add_PKCS1_OAEP
func RSAPaddingAddPKCS1OAEP(to *uint8, tlen c.Int, f *uint8, fl c.Int, p *uint8, pl c.Int) c.Int

//go:linkname RSAPaddingCheckPKCS1OAEP C.RSA_padding_check_PKCS1_OAEP
func RSAPaddingCheckPKCS1OAEP(to *uint8, tlen c.Int, f *uint8, fl c.Int, rsa_len c.Int, p *uint8, pl c.Int) c.Int

//go:linkname RSAPaddingAddPKCS1OAEPMgf1 C.RSA_padding_add_PKCS1_OAEP_mgf1
func RSAPaddingAddPKCS1OAEPMgf1(to *uint8, tlen c.Int, from *uint8, flen c.Int, param *uint8, plen c.Int, md *EVP_MD, mgf1md *EVP_MD) c.Int

//go:linkname RSAPaddingCheckPKCS1OAEPMgf1 C.RSA_padding_check_PKCS1_OAEP_mgf1
func RSAPaddingCheckPKCS1OAEPMgf1(to *uint8, tlen c.Int, from *uint8, flen c.Int, num c.Int, param *uint8, plen c.Int, md *EVP_MD, mgf1md *EVP_MD) c.Int

//go:linkname RSAPaddingAddNone C.RSA_padding_add_none
func RSAPaddingAddNone(to *uint8, tlen c.Int, f *uint8, fl c.Int) c.Int

//go:linkname RSAPaddingCheckNone C.RSA_padding_check_none
func RSAPaddingCheckNone(to *uint8, tlen c.Int, f *uint8, fl c.Int, rsa_len c.Int) c.Int

//go:linkname RSAPaddingAddX931 C.RSA_padding_add_X931
func RSAPaddingAddX931(to *uint8, tlen c.Int, f *uint8, fl c.Int) c.Int

//go:linkname RSAPaddingCheckX931 C.RSA_padding_check_X931
func RSAPaddingCheckX931(to *uint8, tlen c.Int, f *uint8, fl c.Int, rsa_len c.Int) c.Int

//go:linkname RSAX931HashId C.RSA_X931_hash_id
func RSAX931HashId(nid c.Int) c.Int

//go:linkname RSAVerifyPKCS1PSS C.RSA_verify_PKCS1_PSS
func RSAVerifyPKCS1PSS(rsa *RSA, mHash *uint8, Hash *EVP_MD, EM *uint8, sLen c.Int) c.Int

//go:linkname RSAPaddingAddPKCS1PSS C.RSA_padding_add_PKCS1_PSS
func RSAPaddingAddPKCS1PSS(rsa *RSA, EM *uint8, mHash *uint8, Hash *EVP_MD, sLen c.Int) c.Int

//go:linkname RSAVerifyPKCS1PSSMgf1 C.RSA_verify_PKCS1_PSS_mgf1
func RSAVerifyPKCS1PSSMgf1(rsa *RSA, mHash *uint8, Hash *EVP_MD, mgf1Hash *EVP_MD, EM *uint8, sLen c.Int) c.Int

//go:linkname RSAPaddingAddPKCS1PSSMgf1 C.RSA_padding_add_PKCS1_PSS_mgf1
func RSAPaddingAddPKCS1PSSMgf1(rsa *RSA, EM *uint8, mHash *uint8, Hash *EVP_MD, mgf1Hash *EVP_MD, sLen c.Int) c.Int

//go:linkname RSASetExData C.RSA_set_ex_data
func RSASetExData(r *RSA, idx c.Int, arg unsafe.Pointer) c.Int

//go:linkname RSAGetExData C.RSA_get_ex_data
func RSAGetExData(r *RSA, idx c.Int) unsafe.Pointer

//go:linkname RSAPublicKeyDup C.RSAPublicKey_dup
func RSAPublicKeyDup(a *RSA) *RSA

//go:linkname RSAPrivateKeyDup C.RSAPrivateKey_dup
func RSAPrivateKeyDup(a *RSA) *RSA

//go:linkname RSAMethNew C.RSA_meth_new
func RSAMethNew(name *c.Char, flags c.Int) *RSA_METHOD

//go:linkname RSAMethFree C.RSA_meth_free
func RSAMethFree(meth *RSA_METHOD)

//go:linkname RSAMethDup C.RSA_meth_dup
func RSAMethDup(meth *RSA_METHOD) *RSA_METHOD

//go:linkname RSAMethGet0Name C.RSA_meth_get0_name
func RSAMethGet0Name(meth *RSA_METHOD) *c.Char

//go:linkname RSAMethSet1Name C.RSA_meth_set1_name
func RSAMethSet1Name(meth *RSA_METHOD, name *c.Char) c.Int

//go:linkname RSAMethGetFlags C.RSA_meth_get_flags
func RSAMethGetFlags(meth *RSA_METHOD) c.Int

//go:linkname RSAMethSetFlags C.RSA_meth_set_flags
func RSAMethSetFlags(meth *RSA_METHOD, flags c.Int) c.Int

//go:linkname RSAMethGet0AppData C.RSA_meth_get0_app_data
func RSAMethGet0AppData(meth *RSA_METHOD) unsafe.Pointer

//go:linkname RSAMethSet0AppData C.RSA_meth_set0_app_data
func RSAMethSet0AppData(meth *RSA_METHOD, app_data unsafe.Pointer) c.Int

//go:linkname RSAMethGetPubEnc C.RSA_meth_get_pub_enc
func RSAMethGetPubEnc(meth *RSA_METHOD) func(_llcppg_param1 c.Int, _llcppg_param2 *uint8, _llcppg_param3 *uint8, _llcppg_param4 *RSA, _llcppg_param5 c.Int) c.Int

//go:linkname RSAMethSetPubEnc C.RSA_meth_set_pub_enc
func RSAMethSetPubEnc(rsa *RSA_METHOD, pub_enc func(_llcppg_param1 c.Int, _llcppg_param2 *uint8, _llcppg_param3 *uint8, _llcppg_param4 *RSA, _llcppg_param5 c.Int) c.Int) c.Int

//go:linkname RSAMethGetPubDec C.RSA_meth_get_pub_dec
func RSAMethGetPubDec(meth *RSA_METHOD) func(_llcppg_param1 c.Int, _llcppg_param2 *uint8, _llcppg_param3 *uint8, _llcppg_param4 *RSA, _llcppg_param5 c.Int) c.Int

//go:linkname RSAMethSetPubDec C.RSA_meth_set_pub_dec
func RSAMethSetPubDec(rsa *RSA_METHOD, pub_dec func(_llcppg_param1 c.Int, _llcppg_param2 *uint8, _llcppg_param3 *uint8, _llcppg_param4 *RSA, _llcppg_param5 c.Int) c.Int) c.Int

//go:linkname RSAMethGetPrivEnc C.RSA_meth_get_priv_enc
func RSAMethGetPrivEnc(meth *RSA_METHOD) func(_llcppg_param1 c.Int, _llcppg_param2 *uint8, _llcppg_param3 *uint8, _llcppg_param4 *RSA, _llcppg_param5 c.Int) c.Int

//go:linkname RSAMethSetPrivEnc C.RSA_meth_set_priv_enc
func RSAMethSetPrivEnc(rsa *RSA_METHOD, priv_enc func(_llcppg_param1 c.Int, _llcppg_param2 *uint8, _llcppg_param3 *uint8, _llcppg_param4 *RSA, _llcppg_param5 c.Int) c.Int) c.Int

//go:linkname RSAMethGetPrivDec C.RSA_meth_get_priv_dec
func RSAMethGetPrivDec(meth *RSA_METHOD) func(_llcppg_param1 c.Int, _llcppg_param2 *uint8, _llcppg_param3 *uint8, _llcppg_param4 *RSA, _llcppg_param5 c.Int) c.Int

//go:linkname RSAMethSetPrivDec C.RSA_meth_set_priv_dec
func RSAMethSetPrivDec(rsa *RSA_METHOD, priv_dec func(_llcppg_param1 c.Int, _llcppg_param2 *uint8, _llcppg_param3 *uint8, _llcppg_param4 *RSA, _llcppg_param5 c.Int) c.Int) c.Int

//go:linkname RSAMethGetModExp C.RSA_meth_get_mod_exp
func RSAMethGetModExp(meth *RSA_METHOD) func(_llcppg_param1 *BIGNUM, _llcppg_param2 *BIGNUM, _llcppg_param3 *RSA, _llcppg_param4 *BN_CTX) c.Int

//go:linkname RSAMethSetModExp C.RSA_meth_set_mod_exp
func RSAMethSetModExp(rsa *RSA_METHOD, mod_exp func(_llcppg_param1 *BIGNUM, _llcppg_param2 *BIGNUM, _llcppg_param3 *RSA, _llcppg_param4 *BN_CTX) c.Int) c.Int

//go:linkname RSAMethGetBnModExp C.RSA_meth_get_bn_mod_exp
func RSAMethGetBnModExp(meth *RSA_METHOD) func(_llcppg_param1 *BIGNUM, _llcppg_param2 *BIGNUM, _llcppg_param3 *BIGNUM, _llcppg_param4 *BIGNUM, _llcppg_param5 *BN_CTX, _llcppg_param6 *BN_MONT_CTX) c.Int

//go:linkname RSAMethSetBnModExp C.RSA_meth_set_bn_mod_exp
func RSAMethSetBnModExp(rsa *RSA_METHOD, bn_mod_exp func(_llcppg_param1 *BIGNUM, _llcppg_param2 *BIGNUM, _llcppg_param3 *BIGNUM, _llcppg_param4 *BIGNUM, _llcppg_param5 *BN_CTX, _llcppg_param6 *BN_MONT_CTX) c.Int) c.Int

//go:linkname RSAMethGetInit C.RSA_meth_get_init
func RSAMethGetInit(meth *RSA_METHOD) func(_llcppg_param1 *RSA) c.Int

//go:linkname RSAMethSetInit C.RSA_meth_set_init
func RSAMethSetInit(rsa *RSA_METHOD, init func(_llcppg_param1 *RSA) c.Int) c.Int

//go:linkname RSAMethGetFinish C.RSA_meth_get_finish
func RSAMethGetFinish(meth *RSA_METHOD) func(_llcppg_param1 *RSA) c.Int

//go:linkname RSAMethSetFinish C.RSA_meth_set_finish
func RSAMethSetFinish(rsa *RSA_METHOD, finish func(_llcppg_param1 *RSA) c.Int) c.Int

//go:linkname RSAMethGetSign C.RSA_meth_get_sign
func RSAMethGetSign(meth *RSA_METHOD) func(_llcppg_param1 c.Int, _llcppg_param2 *uint8, _llcppg_param3 c.Uint, _llcppg_param4 *uint8, _llcppg_param5 *c.Uint, _llcppg_param6 *RSA) c.Int

//go:linkname RSAMethSetSign C.RSA_meth_set_sign
func RSAMethSetSign(rsa *RSA_METHOD, sign func(_llcppg_param1 c.Int, _llcppg_param2 *uint8, _llcppg_param3 c.Uint, _llcppg_param4 *uint8, _llcppg_param5 *c.Uint, _llcppg_param6 *RSA) c.Int) c.Int

//go:linkname RSAMethGetVerify C.RSA_meth_get_verify
func RSAMethGetVerify(meth *RSA_METHOD) func(_llcppg_param1 c.Int, _llcppg_param2 *uint8, _llcppg_param3 c.Uint, _llcppg_param4 *uint8, _llcppg_param5 c.Uint, _llcppg_param6 *RSA) c.Int

//go:linkname RSAMethSetVerify C.RSA_meth_set_verify
func RSAMethSetVerify(rsa *RSA_METHOD, verify func(_llcppg_param1 c.Int, _llcppg_param2 *uint8, _llcppg_param3 c.Uint, _llcppg_param4 *uint8, _llcppg_param5 c.Uint, _llcppg_param6 *RSA) c.Int) c.Int

//go:linkname RSAMethGetKeygen C.RSA_meth_get_keygen
func RSAMethGetKeygen(meth *RSA_METHOD) func(_llcppg_param1 *RSA, _llcppg_param2 c.Int, _llcppg_param3 *BIGNUM, _llcppg_param4 *BN_GENCB) c.Int

//go:linkname RSAMethSetKeygen C.RSA_meth_set_keygen
func RSAMethSetKeygen(rsa *RSA_METHOD, keygen func(_llcppg_param1 *RSA, _llcppg_param2 c.Int, _llcppg_param3 *BIGNUM, _llcppg_param4 *BN_GENCB) c.Int) c.Int

//go:linkname RSAMethGetMultiPrimeKeygen C.RSA_meth_get_multi_prime_keygen
func RSAMethGetMultiPrimeKeygen(meth *RSA_METHOD) func(_llcppg_param1 *RSA, _llcppg_param2 c.Int, _llcppg_param3 c.Int, _llcppg_param4 *BIGNUM, _llcppg_param5 *BN_GENCB) c.Int

//go:linkname RSAMethSetMultiPrimeKeygen C.RSA_meth_set_multi_prime_keygen
func RSAMethSetMultiPrimeKeygen(meth *RSA_METHOD, keygen func(_llcppg_param1 *RSA, _llcppg_param2 c.Int, _llcppg_param3 c.Int, _llcppg_param4 *BIGNUM, _llcppg_param5 *BN_GENCB) c.Int) c.Int
