// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

// -
// Strings are special: normally an lhash entry will point to a single
// (somewhat) mutable object. In the case of strings:
//
// a) Instead of a single char, there is an array of chars, NUL-terminated.
// b) The string may have be immutable.
//
// So, they need their own declarations. Especially important for
// type-checking tools, such as Deputy.
//
// In practice, however, it appears to be hard to have a const
// string. For now, I'm settling for dealing with the fact it is a
// string at all.
type OPENSSL_STRING = *c.Char
type OPENSSL_CSTRING = *c.Char
type StackStOPENSSL_STRING struct {
}

// -
// Confusingly, LHASH_OF(STRING) deals with char ** throughout, but
// STACK_OF(STRING) is really more like STACK_OF(char), only, as mentioned
// above, instead of a single char each entry is a NUL-terminated array of
// chars. So, we have to implement STRING specially for STACK_OF. This is
// dealt with in the autogenerated macros below.
//
// clang-format off
//
// llgo:type C
type SkOPENSSL_STRINGCompfunc = func(_llcppg_param1 **c.Char, _llcppg_param2 **c.Char) c.Int

// -
// Confusingly, LHASH_OF(STRING) deals with char ** throughout, but
// STACK_OF(STRING) is really more like STACK_OF(char), only, as mentioned
// above, instead of a single char each entry is a NUL-terminated array of
// chars. So, we have to implement STRING specially for STACK_OF. This is
// dealt with in the autogenerated macros below.
//
// clang-format off
//
// llgo:type C
type SkOPENSSL_STRINGFreefunc = func(_llcppg_param1 *c.Char)

// -
// Confusingly, LHASH_OF(STRING) deals with char ** throughout, but
// STACK_OF(STRING) is really more like STACK_OF(char), only, as mentioned
// above, instead of a single char each entry is a NUL-terminated array of
// chars. So, we have to implement STRING specially for STACK_OF. This is
// dealt with in the autogenerated macros below.
//
// clang-format off
//
// llgo:type C
type SkOPENSSL_STRINGCopyfunc = func(_llcppg_param1 *c.Char) *c.Char
type StackStOPENSSL_CSTRING struct {
}

// llgo:type C
type SkOPENSSL_CSTRINGCompfunc = func(_llcppg_param1 **c.Char, _llcppg_param2 **c.Char) c.Int

// llgo:type C
type SkOPENSSL_CSTRINGFreefunc = func(_llcppg_param1 *c.Char)

// llgo:type C
type SkOPENSSL_CSTRINGCopyfunc = func(_llcppg_param1 *c.Char) *c.Char

// This is not used by OpenSSL.  A block of bytes,  NOT nul-terminated.
// These should also be distinguished from "normal" stacks.
type OPENSSL_BLOCK uintptr
type StackStOPENSSL_BLOCK struct {
}

// clang-format off
//
// llgo:type C
type SkOPENSSL_BLOCKCompfunc = func(_llcppg_param1 *unsafe.Pointer, _llcppg_param2 *unsafe.Pointer) c.Int

// clang-format off
//
// llgo:type C
type SkOPENSSL_BLOCKFreefunc = func(_llcppg_param1 unsafe.Pointer)

// clang-format off
//
// llgo:type C
type SkOPENSSL_BLOCKCopyfunc = func(_llcppg_param1 unsafe.Pointer) unsafe.Pointer
