// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

type StackSt struct {
}
type OPENSSL_STACK = StackSt

// llgo:type C
type OPENSSLSkCompfunc = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 unsafe.Pointer) c.Int

// llgo:type C
type OPENSSLSkFreefunc = func(_llcppg_param1 unsafe.Pointer)

// llgo:type C
type OPENSSLSkFreefuncThunk = func(_llcppg_param1 OPENSSLSkFreefunc, _llcppg_param2 unsafe.Pointer)

// llgo:type C
type OPENSSLSkCopyfunc = func(_llcppg_param1 unsafe.Pointer) unsafe.Pointer

//go:linkname OPENSSLSkNum C.OPENSSL_sk_num
func OPENSSLSkNum(_llcppg_param1 *OPENSSL_STACK) c.Int

//go:linkname OPENSSLSkValue C.OPENSSL_sk_value
func OPENSSLSkValue(_llcppg_param1 *OPENSSL_STACK, _llcppg_param2 c.Int) unsafe.Pointer

//go:linkname OPENSSLSkSet C.OPENSSL_sk_set
func OPENSSLSkSet(st *OPENSSL_STACK, i c.Int, data unsafe.Pointer) unsafe.Pointer

//go:linkname OPENSSLSkNew C.OPENSSL_sk_new
func OPENSSLSkNew(cmp OPENSSLSkCompfunc) *OPENSSL_STACK

//go:linkname OPENSSLSkNewNull C.OPENSSL_sk_new_null
func OPENSSLSkNewNull() *OPENSSL_STACK

//go:linkname OPENSSLSkNewReserve C.OPENSSL_sk_new_reserve
func OPENSSLSkNewReserve(c OPENSSLSkCompfunc, n c.Int) *OPENSSL_STACK

//go:linkname OPENSSLSkSetThunks C.OPENSSL_sk_set_thunks
func OPENSSLSkSetThunks(st *OPENSSL_STACK, f_thunk OPENSSLSkFreefuncThunk) *OPENSSL_STACK

//go:linkname OPENSSLSkSetCmpThunks C.OPENSSL_sk_set_cmp_thunks
func OPENSSLSkSetCmpThunks(st *OPENSSL_STACK, c_thunk func(_llcppg_param1 func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 unsafe.Pointer) c.Int, _llcppg_param2 unsafe.Pointer, _llcppg_param3 unsafe.Pointer) c.Int) *OPENSSL_STACK

//go:linkname OPENSSLSkReserve C.OPENSSL_sk_reserve
func OPENSSLSkReserve(st *OPENSSL_STACK, n c.Int) c.Int

//go:linkname OPENSSLSkFree C.OPENSSL_sk_free
func OPENSSLSkFree(_llcppg_param1 *OPENSSL_STACK)

//go:linkname OPENSSLSkPopFree C.OPENSSL_sk_pop_free
func OPENSSLSkPopFree(st *OPENSSL_STACK, func_ OPENSSLSkFreefunc)

//go:linkname OPENSSLSkDeepCopy C.OPENSSL_sk_deep_copy
func OPENSSLSkDeepCopy(_llcppg_param1 *OPENSSL_STACK, c OPENSSLSkCopyfunc, f OPENSSLSkFreefunc) *OPENSSL_STACK

//go:linkname OPENSSLSkInsert C.OPENSSL_sk_insert
func OPENSSLSkInsert(sk *OPENSSL_STACK, data unsafe.Pointer, where c.Int) c.Int

//go:linkname OPENSSLSkDelete C.OPENSSL_sk_delete
func OPENSSLSkDelete(st *OPENSSL_STACK, loc c.Int) unsafe.Pointer

//go:linkname OPENSSLSkDeletePtr C.OPENSSL_sk_delete_ptr
func OPENSSLSkDeletePtr(st *OPENSSL_STACK, p unsafe.Pointer) unsafe.Pointer

//go:linkname OPENSSLSkFind C.OPENSSL_sk_find
func OPENSSLSkFind(st *OPENSSL_STACK, data unsafe.Pointer) c.Int

//go:linkname OPENSSLSkFindEx C.OPENSSL_sk_find_ex
func OPENSSLSkFindEx(st *OPENSSL_STACK, data unsafe.Pointer) c.Int

//go:linkname OPENSSLSkFindAll C.OPENSSL_sk_find_all
func OPENSSLSkFindAll(st *OPENSSL_STACK, data unsafe.Pointer, pnum *c.Int) c.Int

//go:linkname OPENSSLSkPush C.OPENSSL_sk_push
func OPENSSLSkPush(st *OPENSSL_STACK, data unsafe.Pointer) c.Int

//go:linkname OPENSSLSkUnshift C.OPENSSL_sk_unshift
func OPENSSLSkUnshift(st *OPENSSL_STACK, data unsafe.Pointer) c.Int

//go:linkname OPENSSLSkShift C.OPENSSL_sk_shift
func OPENSSLSkShift(st *OPENSSL_STACK) unsafe.Pointer

//go:linkname OPENSSLSkPop C.OPENSSL_sk_pop
func OPENSSLSkPop(st *OPENSSL_STACK) unsafe.Pointer

//go:linkname OPENSSLSkZero C.OPENSSL_sk_zero
func OPENSSLSkZero(st *OPENSSL_STACK)

//go:linkname OPENSSLSkSetCmpFunc C.OPENSSL_sk_set_cmp_func
func OPENSSLSkSetCmpFunc(sk *OPENSSL_STACK, cmp OPENSSLSkCompfunc) OPENSSLSkCompfunc

//go:linkname OPENSSLSkDup C.OPENSSL_sk_dup
func OPENSSLSkDup(st *OPENSSL_STACK) *OPENSSL_STACK

//go:linkname OPENSSLSkSort C.OPENSSL_sk_sort
func OPENSSLSkSort(st *OPENSSL_STACK)

//go:linkname OPENSSLSkIsSorted C.OPENSSL_sk_is_sorted
func OPENSSLSkIsSorted(st *OPENSSL_STACK) c.Int
