// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

type OsslProviderSt struct {
}
type OSSL_PROVIDER = OsslProviderSt
type Asn1StringSt struct {
}
type ASN1_INTEGER = Asn1StringSt
type ASN1_ENUMERATED = Asn1StringSt
type ASN1_BIT_STRING = Asn1StringSt
type ASN1_OCTET_STRING = Asn1StringSt
type ASN1_PRINTABLESTRING = Asn1StringSt
type ASN1_T61STRING = Asn1StringSt
type ASN1_IA5STRING = Asn1StringSt
type ASN1_GENERALSTRING = Asn1StringSt
type ASN1_UNIVERSALSTRING = Asn1StringSt
type ASN1_BMPSTRING = Asn1StringSt
type ASN1_UTCTIME = Asn1StringSt
type ASN1_TIME = Asn1StringSt
type ASN1_GENERALIZEDTIME = Asn1StringSt
type ASN1_VISIBLESTRING = Asn1StringSt
type ASN1_UTF8STRING = Asn1StringSt
type ASN1_STRING = Asn1StringSt
type ASN1_BOOLEAN = c.Int
type ASN1_NULL = c.Int
type ASN1_TYPE = Asn1TypeSt
type Asn1ObjectSt struct {
}
type ASN1_OBJECT = Asn1ObjectSt
type ASN1_STRING_TABLE = Asn1StringTableSt
type ASN1ITEMSt struct {
}
type ASN1_ITEM = ASN1ITEMSt
type Asn1PctxSt struct {
}
type ASN1_PCTX = Asn1PctxSt
type Asn1SctxSt struct {
}
type ASN1_SCTX = Asn1SctxSt
type BioSt struct {
}
type BIO = BioSt
type BignumSt struct {
}
type BIGNUM = BignumSt
type BignumCtx struct {
}
type BN_CTX = BignumCtx
type BnBlindingSt struct {
}
type BN_BLINDING = BnBlindingSt
type BnMontCtxSt struct {
}
type BN_MONT_CTX = BnMontCtxSt
type BnRecpCtxSt struct {
}
type BN_RECP_CTX = BnRecpCtxSt
type BnGencbSt struct {
}
type BN_GENCB = BnGencbSt
type BUF_MEM = BufMemSt
type StackStBIGNUM struct {
}
type StackStBIGNUMConst struct {
}
type ErrStateSt struct {
}
type ERR_STATE = ErrStateSt
type EvpCipherSt struct {
}
type EVP_CIPHER = EvpCipherSt
type EvpCipherCtxSt struct {
}
type EVP_CIPHER_CTX = EvpCipherCtxSt
type EvpMdSt struct {
}
type EVP_MD = EvpMdSt
type EvpMdCtxSt struct {
}
type EVP_MD_CTX = EvpMdCtxSt
type EvpMacSt struct {
}
type EVP_MAC = EvpMacSt
type EvpMacCtxSt struct {
}
type EVP_MAC_CTX = EvpMacCtxSt
type EvpPkeySt struct {
}
type EVP_PKEY = EvpPkeySt
type EvpSkeySt struct {
}
type EVP_SKEY = EvpSkeySt
type EvpPkeyAsn1MethodSt struct {
}
type EVP_PKEY_ASN1_METHOD = EvpPkeyAsn1MethodSt
type EvpPkeyMethodSt struct {
}
type EVP_PKEY_METHOD = EvpPkeyMethodSt
type EvpPkeyCtxSt struct {
}
type EVP_PKEY_CTX = EvpPkeyCtxSt
type EvpKeymgmtSt struct {
}
type EVP_KEYMGMT = EvpKeymgmtSt
type EvpKdfSt struct {
}
type EVP_KDF = EvpKdfSt
type EvpKdfCtxSt struct {
}
type EVP_KDF_CTX = EvpKdfCtxSt
type EvpRandSt struct {
}
type EVP_RAND = EvpRandSt
type EvpRandCtxSt struct {
}
type EVP_RAND_CTX = EvpRandCtxSt
type EvpKeyexchSt struct {
}
type EVP_KEYEXCH = EvpKeyexchSt
type EvpSignatureSt struct {
}
type EVP_SIGNATURE = EvpSignatureSt
type EvpSkeymgmtSt struct {
}
type EVP_SKEYMGMT = EvpSkeymgmtSt
type EvpAsymCipherSt struct {
}
type EVP_ASYM_CIPHER = EvpAsymCipherSt
type EvpKemSt struct {
}
type EVP_KEM = EvpKemSt
type EvpEncodeCtxSt struct {
}
type EVP_ENCODE_CTX = EvpEncodeCtxSt
type HmacCtxSt struct {
}
type HMAC_CTX = HmacCtxSt
type DhSt struct {
}
type DH = DhSt
type DhMethod struct {
}
type DH_METHOD = DhMethod
type DsaSt struct {
}
type DSA = DsaSt
type DsaMethod struct {
}
type DSA_METHOD = DsaMethod
type RsaSt struct {
}
type RSA = RsaSt
type RsaMethSt struct {
}
type RSA_METHOD = RsaMethSt
type RSA_PSS_PARAMS = RsaPssParamsSt
type RSA_OAEP_PARAMS = RsaOaepParamsSt
type EcKeySt struct {
}
type EC_KEY = EcKeySt
type EcKeyMethodSt struct {
}
type EC_KEY_METHOD = EcKeyMethodSt
type RandMethSt struct {
}
type RAND_METHOD = RandMethSt
type SslDaneSt struct {
}
type SSL_DANE = SslDaneSt
type X509St struct {
}
type X509 = X509St
type X509_ALGOR = X509AlgorSt
type X509CrlSt struct {
}
type X509_CRL = X509CrlSt
type X509CrlMethodSt struct {
}
type X509_CRL_METHOD = X509CrlMethodSt
type X509RevokedSt struct {
}
type X509_REVOKED = X509RevokedSt
type X509NameSt struct {
}
type X509_NAME = X509NameSt
type X509PubkeySt struct {
}
type X509_PUBKEY = X509PubkeySt
type X509StoreSt struct {
}
type X509_STORE = X509StoreSt
type X509StoreCtxSt struct {
}
type X509_STORE_CTX = X509StoreCtxSt
type X509ObjectSt struct {
}
type X509_OBJECT = X509ObjectSt
type X509LookupSt struct {
}
type X509_LOOKUP = X509LookupSt
type X509LookupMethodSt struct {
}
type X509_LOOKUP_METHOD = X509LookupMethodSt
type X509VERIFY_PARAMSt struct {
}
type X509_VERIFY_PARAM = X509VERIFY_PARAMSt
type X509SigInfoSt struct {
}
type X509_SIG_INFO = X509SigInfoSt
type Pkcs8PrivKeyInfoSt struct {
}
type PKCS8_PRIV_KEY_INFO = Pkcs8PrivKeyInfoSt
type V3ExtCtx struct {
}
type X509V3_CTX = V3ExtCtx
type CONF = ConfSt
type OsslInitSettingsSt struct {
}
type OPENSSL_INIT_SETTINGS = OsslInitSettingsSt
type UiSt struct {
}
type UI = UiSt
type UiMethodSt struct {
}
type UI_METHOD = UiMethodSt
type EngineSt struct {
}
type ENGINE = EngineSt
type SslSt struct {
}
type SSL = SslSt
type SslCtxSt struct {
}
type SSL_CTX = SslCtxSt
type CompCtxSt struct {
}
type COMP_CTX = CompCtxSt
type CompMethodSt struct {
}
type COMP_METHOD = CompMethodSt
type X509POLICY_NODESt struct {
}
type X509_POLICY_NODE = X509POLICY_NODESt
type X509POLICY_LEVELSt struct {
}
type X509_POLICY_LEVEL = X509POLICY_LEVELSt
type X509POLICY_TREESt struct {
}
type X509_POLICY_TREE = X509POLICY_TREESt
type X509POLICY_CACHESt struct {
}
type X509_POLICY_CACHE = X509POLICY_CACHESt
type AUTHORITY_KEYIDSt struct {
}
type AUTHORITY_KEYID = AUTHORITY_KEYIDSt
type DIST_POINTSt struct {
}
type DIST_POINT = DIST_POINTSt
type ISSUING_DIST_POINTSt struct {
}
type ISSUING_DIST_POINT = ISSUING_DIST_POINTSt
type NAME_CONSTRAINTSSt struct {
}
type NAME_CONSTRAINTS = NAME_CONSTRAINTSSt
type CRYPTO_EX_DATA = CryptoExDataSt
type OsslHttpReqCtxSt struct {
}
type OSSL_HTTP_REQ_CTX = OsslHttpReqCtxSt
type OcspResponseSt struct {
}
type OCSP_RESPONSE = OcspResponseSt
type OcspResponderIdSt struct {
}
type OCSP_RESPID = OcspResponderIdSt
type SctSt struct {
}
type SCT = SctSt
type SctCtxSt struct {
}
type SCT_CTX = SctCtxSt
type CtlogSt struct {
}
type CTLOG = CtlogSt
type CtlogStoreSt struct {
}
type CTLOG_STORE = CtlogStoreSt
type CtPolicyEvalCtxSt struct {
}
type CT_POLICY_EVAL_CTX = CtPolicyEvalCtxSt
type OsslStoreInfoSt struct {
}
type OSSL_STORE_INFO = OsslStoreInfoSt
type OsslStoreSearchSt struct {
}
type OSSL_STORE_SEARCH = OsslStoreSearchSt
type OsslStoreLoaderSt struct {
}
type OSSL_STORE_LOADER = OsslStoreLoaderSt
type OsslLibCtxSt struct {
}
type OSSL_LIB_CTX = OsslLibCtxSt
type OSSL_DISPATCH = OsslDispatchSt
type OSSL_ITEM = OsslItemSt
type OSSL_ALGORITHM = OsslAlgorithmSt
type OSSL_PARAM = OsslParamSt
type OsslParamBldSt struct {
}
type OSSL_PARAM_BLD = OsslParamBldSt

// llgo:type C
type PemPasswordCb = func(_llcppg_param1 *c.Char, _llcppg_param2 c.Int, _llcppg_param3 c.Int, _llcppg_param4 unsafe.Pointer) c.Int
type OsslEncoderSt struct {
}
type OSSL_ENCODER = OsslEncoderSt
type OsslEncoderCtxSt struct {
}
type OSSL_ENCODER_CTX = OsslEncoderCtxSt
type OsslDecoderSt struct {
}
type OSSL_DECODER = OsslDecoderSt
type OsslDecoderCtxSt struct {
}
type OSSL_DECODER_CTX = OsslDecoderCtxSt
type OsslSelfTestSt struct {
}
type OSSL_SELF_TEST = OsslSelfTestSt
type OsslEchstoreSt struct {
}

// opaque type for ECH related information
type OSSL_ECHSTORE = OsslEchstoreSt
