// Code generated by llcppg; DO NOT EDIT.

package openssl

import (
	"github.com/goplus/lib/c"
	"github.com/goplus/lib/c/time"
	"unsafe"
)

const X509_LU_RETRY = -1
const X509_LU_FAIL = 0
const X509_TRUST_DEFAULT = 0
const X509_TRUST_COMPAT = 1
const X509_TRUST_SSL_CLIENT = 2
const X509_TRUST_SSL_SERVER = 3
const X509_TRUST_EMAIL = 4
const X509_TRUST_OBJECT_SIGN = 5
const X509_TRUST_OCSP_SIGN = 6
const X509_TRUST_OCSP_REQUEST = 7
const X509_TRUST_TSA = 8
const X509_TRUST_MIN = 1
const X509_TRUST_MAX = 8
const X509_TRUST_TRUSTED = 1
const X509_TRUST_REJECTED = 2
const X509_TRUST_UNTRUSTED = 3
const X509_L_FILE_LOAD = 1
const X509_L_ADD_DIR = 2
const X509_L_ADD_STORE = 3
const X509_L_LOAD_STORE = 4
const X509_V_OK = 0
const X509_V_ERR_UNSPECIFIED = 1
const X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT = 2
const X509_V_ERR_UNABLE_TO_GET_CRL = 3
const X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE = 4
const X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE = 5
const X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY = 6
const X509_V_ERR_CERT_SIGNATURE_FAILURE = 7
const X509_V_ERR_CRL_SIGNATURE_FAILURE = 8
const X509_V_ERR_CERT_NOT_YET_VALID = 9
const X509_V_ERR_CERT_HAS_EXPIRED = 10
const X509_V_ERR_CRL_NOT_YET_VALID = 11
const X509_V_ERR_CRL_HAS_EXPIRED = 12
const X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD = 13
const X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD = 14
const X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD = 15
const X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD = 16
const X509_V_ERR_OUT_OF_MEM = 17
const X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT = 18
const X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN = 19
const X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY = 20
const X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE = 21
const X509_V_ERR_CERT_CHAIN_TOO_LONG = 22
const X509_V_ERR_CERT_REVOKED = 23
const X509_V_ERR_NO_ISSUER_PUBLIC_KEY = 24
const X509_V_ERR_PATH_LENGTH_EXCEEDED = 25
const X509_V_ERR_INVALID_PURPOSE = 26
const X509_V_ERR_CERT_UNTRUSTED = 27
const X509_V_ERR_CERT_REJECTED = 28
const X509_V_ERR_SUBJECT_ISSUER_MISMATCH = 29
const X509_V_ERR_AKID_SKID_MISMATCH = 30
const X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH = 31
const X509_V_ERR_KEYUSAGE_NO_CERTSIGN = 32
const X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER = 33
const X509_V_ERR_UNHANDLED_CRITICAL_EXTENSION = 34
const X509_V_ERR_KEYUSAGE_NO_CRL_SIGN = 35
const X509_V_ERR_UNHANDLED_CRITICAL_CRL_EXTENSION = 36
const X509_V_ERR_INVALID_NON_CA = 37
const X509_V_ERR_PROXY_PATH_LENGTH_EXCEEDED = 38
const X509_V_ERR_KEYUSAGE_NO_DIGITAL_SIGNATURE = 39
const X509_V_ERR_PROXY_CERTIFICATES_NOT_ALLOWED = 40
const X509_V_ERR_INVALID_EXTENSION = 41
const X509_V_ERR_INVALID_POLICY_EXTENSION = 42
const X509_V_ERR_NO_EXPLICIT_POLICY = 43
const X509_V_ERR_DIFFERENT_CRL_SCOPE = 44
const X509_V_ERR_UNSUPPORTED_EXTENSION_FEATURE = 45
const X509_V_ERR_UNNESTED_RESOURCE = 46
const X509_V_ERR_PERMITTED_VIOLATION = 47
const X509_V_ERR_EXCLUDED_VIOLATION = 48
const X509_V_ERR_SUBTREE_MINMAX = 49
const X509_V_ERR_APPLICATION_VERIFICATION = 50
const X509_V_ERR_UNSUPPORTED_CONSTRAINT_TYPE = 51
const X509_V_ERR_UNSUPPORTED_CONSTRAINT_SYNTAX = 52
const X509_V_ERR_UNSUPPORTED_NAME_SYNTAX = 53
const X509_V_ERR_CRL_PATH_VALIDATION_ERROR = 54
const X509_V_ERR_PATH_LOOP = 55
const X509_V_ERR_SUITE_B_INVALID_VERSION = 56
const X509_V_ERR_SUITE_B_INVALID_ALGORITHM = 57
const X509_V_ERR_SUITE_B_INVALID_CURVE = 58
const X509_V_ERR_SUITE_B_INVALID_SIGNATURE_ALGORITHM = 59
const X509_V_ERR_SUITE_B_LOS_NOT_ALLOWED = 60
const X509_V_ERR_SUITE_B_CANNOT_SIGN_P_384_WITH_P_256 = 61
const X509_V_ERR_HOSTNAME_MISMATCH = 62
const X509_V_ERR_EMAIL_MISMATCH = 63
const X509_V_ERR_IP_ADDRESS_MISMATCH = 64
const X509_V_ERR_DANE_NO_MATCH = 65
const X509_V_ERR_EE_KEY_TOO_SMALL = 66
const X509_V_ERR_CA_KEY_TOO_SMALL = 67
const X509_V_ERR_CA_MD_TOO_WEAK = 68
const X509_V_ERR_INVALID_CALL = 69
const X509_V_ERR_STORE_LOOKUP = 70
const X509_V_ERR_NO_VALID_SCTS = 71
const X509_V_ERR_PROXY_SUBJECT_NAME_VIOLATION = 72
const X509_V_ERR_OCSP_VERIFY_NEEDED = 73
const X509_V_ERR_OCSP_VERIFY_FAILED = 74
const X509_V_ERR_OCSP_CERT_UNKNOWN = 75
const X509_V_ERR_UNSUPPORTED_SIGNATURE_ALGORITHM = 76
const X509_V_ERR_SIGNATURE_ALGORITHM_MISMATCH = 77
const X509_V_ERR_SIGNATURE_ALGORITHM_INCONSISTENCY = 78
const X509_V_ERR_INVALID_CA = 79
const X509_V_ERR_PATHLEN_INVALID_FOR_NON_CA = 80
const X509_V_ERR_PATHLEN_WITHOUT_KU_KEY_CERT_SIGN = 81
const X509_V_ERR_KU_KEY_CERT_SIGN_INVALID_FOR_NON_CA = 82
const X509_V_ERR_ISSUER_NAME_EMPTY = 83
const X509_V_ERR_SUBJECT_NAME_EMPTY = 84
const X509_V_ERR_MISSING_AUTHORITY_KEY_IDENTIFIER = 85
const X509_V_ERR_MISSING_SUBJECT_KEY_IDENTIFIER = 86
const X509_V_ERR_EMPTY_SUBJECT_ALT_NAME = 87
const X509_V_ERR_EMPTY_SUBJECT_SAN_NOT_CRITICAL = 88
const X509_V_ERR_CA_BCONS_NOT_CRITICAL = 89
const X509_V_ERR_AUTHORITY_KEY_IDENTIFIER_CRITICAL = 90
const X509_V_ERR_SUBJECT_KEY_IDENTIFIER_CRITICAL = 91
const X509_V_ERR_CA_CERT_MISSING_KEY_USAGE = 92
const X509_V_ERR_EXTENSIONS_REQUIRE_VERSION_3 = 93
const X509_V_ERR_EC_KEY_EXPLICIT_PARAMS = 94
const X509_V_ERR_RPK_UNTRUSTED = 95
const X509_V_ERR_OCSP_RESP_INVALID = 96
const X509_V_ERR_OCSP_SIGNATURE_FAILURE = 97
const X509_V_ERR_OCSP_NOT_YET_VALID = 98
const X509_V_ERR_OCSP_HAS_EXPIRED = 99
const X509_V_ERR_OCSP_NO_RESPONSE = 100
const X509_V_ERR_CRL_VERIFY_FAILED = 101
const X509_V_ERR_EMPTY_AUTHORITY_KEY_IDENTIFIER = 102
const X509_V_ERR_AKID_ISSUER_SERIAL_NOT_PAIRED = 103
const X509_V_FLAG_CB_ISSUER_CHECK = 0
const X509_V_FLAG_USE_CHECK_TIME = 2
const X509_V_FLAG_CRL_CHECK = 4
const X509_V_FLAG_CRL_CHECK_ALL = 8
const X509_V_FLAG_IGNORE_CRITICAL = 16
const X509_V_FLAG_X509_STRICT = 32
const X509_V_FLAG_ALLOW_PROXY_CERTS = 64
const X509_V_FLAG_POLICY_CHECK = 128
const X509_V_FLAG_EXPLICIT_POLICY = 256
const X509_V_FLAG_INHIBIT_ANY = 512
const X509_V_FLAG_INHIBIT_MAP = 1024
const X509_V_FLAG_NOTIFY_POLICY = 2048
const X509_V_FLAG_EXTENDED_CRL_SUPPORT = 4096
const X509_V_FLAG_USE_DELTAS = 8192
const X509_V_FLAG_CHECK_SS_SIGNATURE = 16384
const X509_V_FLAG_TRUSTED_FIRST = 32768
const X509_V_FLAG_SUITEB_128_LOS_ONLY = 65536
const X509_V_FLAG_SUITEB_192_LOS = 131072
const X509_V_FLAG_SUITEB_128_LOS = 196608
const X509_V_FLAG_PARTIAL_CHAIN = 524288
const X509_V_FLAG_NO_ALT_CHAINS = 1048576
const X509_V_FLAG_NO_CHECK_TIME = 2097152
const X509_V_FLAG_OCSP_RESP_CHECK = 4194304
const X509_V_FLAG_OCSP_RESP_CHECK_ALL = 8388608
const X509_VP_FLAG_DEFAULT = 1
const X509_VP_FLAG_OVERWRITE = 2
const X509_VP_FLAG_RESET_FLAGS = 4
const X509_VP_FLAG_LOCKED = 8
const X509_VP_FLAG_ONCE = 16
const X509_V_FLAG_POLICY_MASK = 1920
const X509_PCY_TREE_FAILURE = -2
const X509_PCY_TREE_INVALID = -1
const X509_PCY_TREE_INTERNAL = 0
const X509_PCY_TREE_VALID = 1
const X509_PCY_TREE_EMPTY = 2
const X509_PCY_TREE_EXPLICIT = 4

// -
// SSL_CTX -> X509_STORE
// -> X509_LOOKUP
// ->X509_LOOKUP_METHOD
// -> X509_LOOKUP
// ->X509_LOOKUP_METHOD
//
// SSL     -> X509_STORE_CTX
// ->X509_STORE
//
// The X509_STORE holds the tables etc for verification stuff.
// A X509_STORE_CTX is used while validating a single certificate.
// The X509_STORE has X509_LOOKUPs for looking up certs.
// The X509_STORE then calls a function to actually verify the
// certificate chain.
type X509_LOOKUP_TYPE c.Uint

const (
	X509_LU_NONE X509_LOOKUP_TYPE = 0
	X509_LU_X509 X509_LOOKUP_TYPE = 1
	X509_LU_CRL  X509_LOOKUP_TYPE = 2
)

type StackStOCSP_RESPONSE struct {
}

// llgo:type C
type SkOCSP_RESPONSECompfunc = func(_llcppg_param1 **OCSP_RESPONSE, _llcppg_param2 **OCSP_RESPONSE) c.Int

// llgo:type C
type SkOCSP_RESPONSEFreefunc = func(_llcppg_param1 *OCSP_RESPONSE)

// llgo:type C
type SkOCSP_RESPONSECopyfunc = func(_llcppg_param1 *OCSP_RESPONSE) *OCSP_RESPONSE
type StackStX509LOOKUP struct {
}

// clang-format off
//
// llgo:type C
type SkX509LOOKUPCompfunc = func(_llcppg_param1 **X509_LOOKUP, _llcppg_param2 **X509_LOOKUP) c.Int

// clang-format off
//
// llgo:type C
type SkX509LOOKUPFreefunc = func(_llcppg_param1 *X509_LOOKUP)

// clang-format off
//
// llgo:type C
type SkX509LOOKUPCopyfunc = func(_llcppg_param1 *X509_LOOKUP) *X509_LOOKUP
type StackStX509OBJECT struct {
}

// llgo:type C
type SkX509OBJECTCompfunc = func(_llcppg_param1 **X509_OBJECT, _llcppg_param2 **X509_OBJECT) c.Int

// llgo:type C
type SkX509OBJECTFreefunc = func(_llcppg_param1 *X509_OBJECT)

// llgo:type C
type SkX509OBJECTCopyfunc = func(_llcppg_param1 *X509_OBJECT) *X509_OBJECT
type StackStX509VERIFY_PARAM struct {
}

// llgo:type C
type SkX509VERIFY_PARAMCompfunc = func(_llcppg_param1 **X509_VERIFY_PARAM, _llcppg_param2 **X509_VERIFY_PARAM) c.Int

// llgo:type C
type SkX509VERIFY_PARAMFreefunc = func(_llcppg_param1 *X509_VERIFY_PARAM)

// llgo:type C
type SkX509VERIFY_PARAMCopyfunc = func(_llcppg_param1 *X509_VERIFY_PARAM) *X509_VERIFY_PARAM

// This is used for a table of trust checking functions
//
// llgo:type C
type X509TrustSt struct {
	Trust      c.Int
	Flags      c.Int
	CheckTrust func(_llcppg_param1 *X509TrustSt, _llcppg_param2 *X509, _llcppg_param3 c.Int) c.Int
	Name       *c.Char
	Arg1       c.Int
	Arg2       unsafe.Pointer
}

// This is used for a table of trust checking functions
type X509_TRUST = X509TrustSt
type StackStX509TRUST struct {
}

// clang-format off
//
// llgo:type C
type SkX509TRUSTCompfunc = func(_llcppg_param1 **X509_TRUST, _llcppg_param2 **X509_TRUST) c.Int

// clang-format off
//
// llgo:type C
type SkX509TRUSTFreefunc = func(_llcppg_param1 *X509_TRUST)

// clang-format off
//
// llgo:type C
type SkX509TRUSTCopyfunc = func(_llcppg_param1 *X509_TRUST) *X509_TRUST

// llgo:type C
type X509STORE_CTXVerifyCb = func(_llcppg_param1 c.Int, _llcppg_param2 *X509_STORE_CTX) c.Int

// llgo:type C
type X509STORE_CTXVerifyFn = func(_llcppg_param1 *X509_STORE_CTX) c.Int

// llgo:type C
type X509STORE_CTXGetIssuerFn = func(_llcppg_param1 **X509, _llcppg_param2 *X509_STORE_CTX, _llcppg_param3 *X509) c.Int

// llgo:type C
type X509STORE_CTXCheckIssuedFn = func(_llcppg_param1 *X509_STORE_CTX, _llcppg_param2 *X509, _llcppg_param3 *X509) c.Int

// llgo:type C
type X509STORE_CTXCheckRevocationFn = func(_llcppg_param1 *X509_STORE_CTX) c.Int

// llgo:type C
type X509STORE_CTXGetCrlFn = func(_llcppg_param1 *X509_STORE_CTX, _llcppg_param2 **X509_CRL, _llcppg_param3 *X509) c.Int

// llgo:type C
type X509STORE_CTXCheckCrlFn = func(_llcppg_param1 *X509_STORE_CTX, _llcppg_param2 *X509_CRL) c.Int

// llgo:type C
type X509STORE_CTXCertCrlFn = func(_llcppg_param1 *X509_STORE_CTX, _llcppg_param2 *X509_CRL, _llcppg_param3 *X509) c.Int

// llgo:type C
type X509STORE_CTXCheckPolicyFn = func(_llcppg_param1 *X509_STORE_CTX) c.Int

// llgo:type C
type X509STORE_CTXLookupCertsFn = func(_llcppg_param1 *X509_STORE_CTX, _llcppg_param2 *X509_NAME) *StackStX509

// llgo:type C
type X509STORE_CTXLookupCrlsFn = func(_llcppg_param1 *X509_STORE_CTX, _llcppg_param2 *X509_NAME) *StackStX509CRL

// llgo:type C
type X509STORE_CTXCleanupFn = func(_llcppg_param1 *X509_STORE_CTX) c.Int

// llgo:type C
type X509LOOKUPCtrlFn = func(_llcppg_param1 *X509_LOOKUP, _llcppg_param2 c.Int, _llcppg_param3 *c.Char, _llcppg_param4 c.Long, _llcppg_param5 **c.Char) c.Int

// llgo:type C
type X509LOOKUPCtrlExFn = func(_llcppg_param1 *X509_LOOKUP, _llcppg_param2 c.Int, _llcppg_param3 *c.Char, _llcppg_param4 c.Long, _llcppg_param5 **c.Char, _llcppg_param6 *OSSL_LIB_CTX, _llcppg_param7 *c.Char) c.Int

// llgo:type C
type X509LOOKUPGetBySubjectFn = func(_llcppg_param1 *X509_LOOKUP, _llcppg_param2 X509_LOOKUP_TYPE, _llcppg_param3 *X509_NAME, _llcppg_param4 *X509_OBJECT) c.Int

// llgo:type C
type X509LOOKUPGetBySubjectExFn = func(_llcppg_param1 *X509_LOOKUP, _llcppg_param2 X509_LOOKUP_TYPE, _llcppg_param3 *X509_NAME, _llcppg_param4 *X509_OBJECT, _llcppg_param5 *OSSL_LIB_CTX, _llcppg_param6 *c.Char) c.Int

// llgo:type C
type X509LOOKUPGetByIssuerSerialFn = func(_llcppg_param1 *X509_LOOKUP, _llcppg_param2 X509_LOOKUP_TYPE, _llcppg_param3 *X509_NAME, _llcppg_param4 *ASN1_INTEGER, _llcppg_param5 *X509_OBJECT) c.Int

// llgo:type C
type X509LOOKUPGetByFingerprintFn = func(_llcppg_param1 *X509_LOOKUP, _llcppg_param2 X509_LOOKUP_TYPE, _llcppg_param3 *uint8, _llcppg_param4 c.Int, _llcppg_param5 *X509_OBJECT) c.Int

// llgo:type C
type X509LOOKUPGetByAliasFn = func(_llcppg_param1 *X509_LOOKUP, _llcppg_param2 X509_LOOKUP_TYPE, _llcppg_param3 *c.Char, _llcppg_param4 c.Int, _llcppg_param5 *X509_OBJECT) c.Int
type StackStX509POLICY_NODE struct {
}
type StackStPOLICYQUALINFO struct {
}

//go:linkname X509TRUSTSet C.X509_TRUST_set
func X509TRUSTSet(t *c.Int, trust c.Int) c.Int

//go:linkname X509TRUSTGetCount C.X509_TRUST_get_count
func X509TRUSTGetCount() c.Int

//go:linkname X509TRUSTGet0 C.X509_TRUST_get0
func X509TRUSTGet0(idx c.Int) *X509_TRUST

//go:linkname X509TRUSTGetById C.X509_TRUST_get_by_id
func X509TRUSTGetById(id c.Int) c.Int

//go:linkname X509TRUSTAdd C.X509_TRUST_add
func X509TRUSTAdd(id c.Int, flags c.Int, ck func(_llcppg_param1 *X509_TRUST, _llcppg_param2 *X509, _llcppg_param3 c.Int) c.Int, name *c.Char, arg1 c.Int, arg2 unsafe.Pointer) c.Int

//go:linkname X509TRUSTCleanup C.X509_TRUST_cleanup
func X509TRUSTCleanup()

//go:linkname X509TRUSTGetFlags C.X509_TRUST_get_flags
func X509TRUSTGetFlags(xp *X509_TRUST) c.Int

//go:linkname X509TRUSTGet0Name C.X509_TRUST_get0_name
func X509TRUSTGet0Name(xp *X509_TRUST) *c.Char

//go:linkname X509TRUSTGetTrust C.X509_TRUST_get_trust
func X509TRUSTGetTrust(xp *X509_TRUST) c.Int

//go:linkname X509Trusted C.X509_trusted
func X509Trusted(x *X509) c.Int

//go:linkname X509Add1TrustObject C.X509_add1_trust_object
func X509Add1TrustObject(x *X509, obj *ASN1_OBJECT) c.Int

//go:linkname X509Add1RejectObject C.X509_add1_reject_object
func X509Add1RejectObject(x *X509, obj *ASN1_OBJECT) c.Int

//go:linkname X509TrustClear C.X509_trust_clear
func X509TrustClear(x *X509)

//go:linkname X509RejectClear C.X509_reject_clear
func X509RejectClear(x *X509)

//go:linkname X509Get0TrustObjects C.X509_get0_trust_objects
func X509Get0TrustObjects(x *X509) *StackStASN1OBJECT

//go:linkname X509Get0RejectObjects C.X509_get0_reject_objects
func X509Get0RejectObjects(x *X509) *StackStASN1OBJECT

//go:linkname X509TRUSTSetDefault C.X509_TRUST_set_default
func X509TRUSTSetDefault(trust func(_llcppg_param1 c.Int, _llcppg_param2 *X509, _llcppg_param3 c.Int) c.Int) func(_llcppg_param1 c.Int, _llcppg_param2 *X509, _llcppg_param3 c.Int) c.Int

//go:linkname X509CheckTrust C.X509_check_trust
func X509CheckTrust(x *X509, id c.Int, flags c.Int) c.Int

//go:linkname X509VerifyCert C.X509_verify_cert
func X509VerifyCert(ctx *X509_STORE_CTX) c.Int

//go:linkname X509STORE_CTXVerify C.X509_STORE_CTX_verify
func X509STORE_CTXVerify(ctx *X509_STORE_CTX) c.Int

//go:linkname X509BuildChain C.X509_build_chain
func X509BuildChain(target *X509, certs *StackStX509, store *X509_STORE, with_self_signed c.Int, libctx *OSSL_LIB_CTX, propq *c.Char) *StackStX509

//go:linkname X509STORESetDepth C.X509_STORE_set_depth
func X509STORESetDepth(store *X509_STORE, depth c.Int) c.Int

//go:linkname X509STORE_CTXPrintVerifyCb C.X509_STORE_CTX_print_verify_cb
func X509STORE_CTXPrintVerifyCb(ok c.Int, ctx *X509_STORE_CTX) c.Int

//go:linkname X509STORE_CTXSetDepth C.X509_STORE_CTX_set_depth
func X509STORE_CTXSetDepth(ctx *X509_STORE_CTX, depth c.Int)

//go:linkname X509OBJECTIdxBySubject C.X509_OBJECT_idx_by_subject
func X509OBJECTIdxBySubject(h *StackStX509OBJECT, type_ X509_LOOKUP_TYPE, name *X509_NAME) c.Int

//go:linkname X509OBJECTRetrieveBySubject C.X509_OBJECT_retrieve_by_subject
func X509OBJECTRetrieveBySubject(h *StackStX509OBJECT, type_ X509_LOOKUP_TYPE, name *X509_NAME) *X509_OBJECT

//go:linkname X509OBJECTRetrieveMatch C.X509_OBJECT_retrieve_match
func X509OBJECTRetrieveMatch(h *StackStX509OBJECT, x *X509_OBJECT) *X509_OBJECT

//go:linkname X509OBJECTUpRefCount C.X509_OBJECT_up_ref_count
func X509OBJECTUpRefCount(a *X509_OBJECT) c.Int

//go:linkname X509OBJECTNew C.X509_OBJECT_new
func X509OBJECTNew() *X509_OBJECT

//go:linkname X509OBJECTFree C.X509_OBJECT_free
func X509OBJECTFree(a *X509_OBJECT)

//go:linkname X509OBJECTGetType C.X509_OBJECT_get_type
func X509OBJECTGetType(a *X509_OBJECT) X509_LOOKUP_TYPE

//go:linkname X509OBJECTGet0X509 C.X509_OBJECT_get0_X509
func X509OBJECTGet0X509(a *X509_OBJECT) *X509

//go:linkname X509OBJECTSet1X509 C.X509_OBJECT_set1_X509
func X509OBJECTSet1X509(a *X509_OBJECT, obj *X509) c.Int

//go:linkname X509OBJECTGet0X509CRL C.X509_OBJECT_get0_X509_CRL
func X509OBJECTGet0X509CRL(a *X509_OBJECT) *X509_CRL

//go:linkname X509OBJECTSet1X509CRL C.X509_OBJECT_set1_X509_CRL
func X509OBJECTSet1X509CRL(a *X509_OBJECT, obj *X509_CRL) c.Int

//go:linkname X509STORENew C.X509_STORE_new
func X509STORENew() *X509_STORE

//go:linkname X509STOREFree C.X509_STORE_free
func X509STOREFree(xs *X509_STORE)

//go:linkname X509STORELock C.X509_STORE_lock
func X509STORELock(xs *X509_STORE) c.Int

//go:linkname X509STOREUnlock C.X509_STORE_unlock
func X509STOREUnlock(xs *X509_STORE) c.Int

//go:linkname X509STOREUpRef C.X509_STORE_up_ref
func X509STOREUpRef(xs *X509_STORE) c.Int

//go:linkname X509STOREGet0Objects C.X509_STORE_get0_objects
func X509STOREGet0Objects(xs *X509_STORE) *StackStX509OBJECT

//go:linkname X509STOREGet1Objects C.X509_STORE_get1_objects
func X509STOREGet1Objects(xs *X509_STORE) *StackStX509OBJECT

//go:linkname X509STOREGet1AllCerts C.X509_STORE_get1_all_certs
func X509STOREGet1AllCerts(xs *X509_STORE) *StackStX509

//go:linkname X509STORE_CTXGet1Certs C.X509_STORE_CTX_get1_certs
func X509STORE_CTXGet1Certs(xs *X509_STORE_CTX, nm *X509_NAME) *StackStX509

//go:linkname X509STORE_CTXGet1Crls C.X509_STORE_CTX_get1_crls
func X509STORE_CTXGet1Crls(st *X509_STORE_CTX, nm *X509_NAME) *StackStX509CRL

//go:linkname X509STORESetFlags C.X509_STORE_set_flags
func X509STORESetFlags(xs *X509_STORE, flags c.Ulong) c.Int

//go:linkname X509STORESetPurpose C.X509_STORE_set_purpose
func X509STORESetPurpose(xs *X509_STORE, purpose c.Int) c.Int

//go:linkname X509STORESetTrust C.X509_STORE_set_trust
func X509STORESetTrust(xs *X509_STORE, trust c.Int) c.Int

//go:linkname X509STORESet1Param C.X509_STORE_set1_param
func X509STORESet1Param(xs *X509_STORE, pm *X509_VERIFY_PARAM) c.Int

//go:linkname X509STOREGet0Param C.X509_STORE_get0_param
func X509STOREGet0Param(xs *X509_STORE) *X509_VERIFY_PARAM

//go:linkname X509STORESetVerify C.X509_STORE_set_verify
func X509STORESetVerify(xs *X509_STORE, verify X509STORE_CTXVerifyFn)

//go:linkname X509STORE_CTXSetVerify C.X509_STORE_CTX_set_verify
func X509STORE_CTXSetVerify(ctx *X509_STORE_CTX, verify X509STORE_CTXVerifyFn)

//go:linkname X509STOREGetVerify C.X509_STORE_get_verify
func X509STOREGetVerify(xs *X509_STORE) X509STORE_CTXVerifyFn

//go:linkname X509STORESetVerifyCb C.X509_STORE_set_verify_cb
func X509STORESetVerifyCb(xs *X509_STORE, verify_cb X509STORE_CTXVerifyCb)

//go:linkname X509STOREGetVerifyCb C.X509_STORE_get_verify_cb
func X509STOREGetVerifyCb(xs *X509_STORE) X509STORE_CTXVerifyCb

//go:linkname X509STORESetGetIssuer C.X509_STORE_set_get_issuer
func X509STORESetGetIssuer(xs *X509_STORE, get_issuer X509STORE_CTXGetIssuerFn)

//go:linkname X509STOREGetGetIssuer C.X509_STORE_get_get_issuer
func X509STOREGetGetIssuer(xs *X509_STORE) X509STORE_CTXGetIssuerFn

//go:linkname X509STORESetCheckIssued C.X509_STORE_set_check_issued
func X509STORESetCheckIssued(xs *X509_STORE, check_issued X509STORE_CTXCheckIssuedFn)

//go:linkname X509STOREGetCheckIssued C.X509_STORE_get_check_issued
func X509STOREGetCheckIssued(s *X509_STORE) X509STORE_CTXCheckIssuedFn

//go:linkname X509STORESetCheckRevocation C.X509_STORE_set_check_revocation
func X509STORESetCheckRevocation(xs *X509_STORE, check_revocation X509STORE_CTXCheckRevocationFn)

//go:linkname X509STOREGetCheckRevocation C.X509_STORE_get_check_revocation
func X509STOREGetCheckRevocation(xs *X509_STORE) X509STORE_CTXCheckRevocationFn

//go:linkname X509STORESetGetCrl C.X509_STORE_set_get_crl
func X509STORESetGetCrl(xs *X509_STORE, get_crl X509STORE_CTXGetCrlFn)

//go:linkname X509STOREGetGetCrl C.X509_STORE_get_get_crl
func X509STOREGetGetCrl(xs *X509_STORE) X509STORE_CTXGetCrlFn

//go:linkname X509STORESetCheckCrl C.X509_STORE_set_check_crl
func X509STORESetCheckCrl(xs *X509_STORE, check_crl X509STORE_CTXCheckCrlFn)

//go:linkname X509STOREGetCheckCrl C.X509_STORE_get_check_crl
func X509STOREGetCheckCrl(xs *X509_STORE) X509STORE_CTXCheckCrlFn

//go:linkname X509STORESetCertCrl C.X509_STORE_set_cert_crl
func X509STORESetCertCrl(xs *X509_STORE, cert_crl X509STORE_CTXCertCrlFn)

//go:linkname X509STOREGetCertCrl C.X509_STORE_get_cert_crl
func X509STOREGetCertCrl(xs *X509_STORE) X509STORE_CTXCertCrlFn

//go:linkname X509STORESetCheckPolicy C.X509_STORE_set_check_policy
func X509STORESetCheckPolicy(xs *X509_STORE, check_policy X509STORE_CTXCheckPolicyFn)

//go:linkname X509STOREGetCheckPolicy C.X509_STORE_get_check_policy
func X509STOREGetCheckPolicy(s *X509_STORE) X509STORE_CTXCheckPolicyFn

//go:linkname X509STORESetLookupCerts C.X509_STORE_set_lookup_certs
func X509STORESetLookupCerts(xs *X509_STORE, lookup_certs X509STORE_CTXLookupCertsFn)

//go:linkname X509STOREGetLookupCerts C.X509_STORE_get_lookup_certs
func X509STOREGetLookupCerts(s *X509_STORE) X509STORE_CTXLookupCertsFn

//go:linkname X509STORESetLookupCrls C.X509_STORE_set_lookup_crls
func X509STORESetLookupCrls(xs *X509_STORE, lookup_crls X509STORE_CTXLookupCrlsFn)

//go:linkname X509STOREGetLookupCrls C.X509_STORE_get_lookup_crls
func X509STOREGetLookupCrls(xs *X509_STORE) X509STORE_CTXLookupCrlsFn

//go:linkname X509STORESetCleanup C.X509_STORE_set_cleanup
func X509STORESetCleanup(xs *X509_STORE, cleanup X509STORE_CTXCleanupFn)

//go:linkname X509STOREGetCleanup C.X509_STORE_get_cleanup
func X509STOREGetCleanup(xs *X509_STORE) X509STORE_CTXCleanupFn

//go:linkname X509STORESetExData C.X509_STORE_set_ex_data
func X509STORESetExData(xs *X509_STORE, idx c.Int, data unsafe.Pointer) c.Int

//go:linkname X509STOREGetExData C.X509_STORE_get_ex_data
func X509STOREGetExData(xs *X509_STORE, idx c.Int) unsafe.Pointer

//go:linkname X509STORE_CTXNewEx C.X509_STORE_CTX_new_ex
func X509STORE_CTXNewEx(libctx *OSSL_LIB_CTX, propq *c.Char) *X509_STORE_CTX

//go:linkname X509STORE_CTXNew C.X509_STORE_CTX_new
func X509STORE_CTXNew() *X509_STORE_CTX

//go:linkname X509STORE_CTXGet1Issuer C.X509_STORE_CTX_get1_issuer
func X509STORE_CTXGet1Issuer(issuer **X509, ctx *X509_STORE_CTX, x *X509) c.Int

//go:linkname X509STORE_CTXFree C.X509_STORE_CTX_free
func X509STORE_CTXFree(ctx *X509_STORE_CTX)

//go:linkname X509STORE_CTXInit C.X509_STORE_CTX_init
func X509STORE_CTXInit(ctx *X509_STORE_CTX, trust_store *X509_STORE, target *X509, untrusted *StackStX509) c.Int

//go:linkname X509STORE_CTXInitRpk C.X509_STORE_CTX_init_rpk
func X509STORE_CTXInitRpk(ctx *X509_STORE_CTX, trust_store *X509_STORE, rpk *EVP_PKEY) c.Int

//go:linkname X509STORE_CTXSet0TrustedStack C.X509_STORE_CTX_set0_trusted_stack
func X509STORE_CTXSet0TrustedStack(ctx *X509_STORE_CTX, sk *StackStX509)

//go:linkname X509STORE_CTXCleanup C.X509_STORE_CTX_cleanup
func X509STORE_CTXCleanup(ctx *X509_STORE_CTX)

//go:linkname X509STORE_CTXGet0Store C.X509_STORE_CTX_get0_store
func X509STORE_CTXGet0Store(ctx *X509_STORE_CTX) *X509_STORE

//go:linkname X509STORE_CTXGet0Cert C.X509_STORE_CTX_get0_cert
func X509STORE_CTXGet0Cert(ctx *X509_STORE_CTX) *X509

//go:linkname X509STORE_CTXGet0Rpk C.X509_STORE_CTX_get0_rpk
func X509STORE_CTXGet0Rpk(ctx *X509_STORE_CTX) *EVP_PKEY

//go:linkname X509STORE_CTXGet0Untrusted C.X509_STORE_CTX_get0_untrusted
func X509STORE_CTXGet0Untrusted(ctx *X509_STORE_CTX) *StackStX509

//go:linkname X509STORE_CTXSet0Untrusted C.X509_STORE_CTX_set0_untrusted
func X509STORE_CTXSet0Untrusted(ctx *X509_STORE_CTX, sk *StackStX509)

//go:linkname X509STORE_CTXSetVerifyCb C.X509_STORE_CTX_set_verify_cb
func X509STORE_CTXSetVerifyCb(ctx *X509_STORE_CTX, verify X509STORE_CTXVerifyCb)

//go:linkname X509STORE_CTXGetVerifyCb C.X509_STORE_CTX_get_verify_cb
func X509STORE_CTXGetVerifyCb(ctx *X509_STORE_CTX) X509STORE_CTXVerifyCb

//go:linkname X509STORE_CTXGetVerify C.X509_STORE_CTX_get_verify
func X509STORE_CTXGetVerify(ctx *X509_STORE_CTX) X509STORE_CTXVerifyFn

//go:linkname X509STORE_CTXGetGetIssuer C.X509_STORE_CTX_get_get_issuer
func X509STORE_CTXGetGetIssuer(ctx *X509_STORE_CTX) X509STORE_CTXGetIssuerFn

//go:linkname X509STORE_CTXGetCheckIssued C.X509_STORE_CTX_get_check_issued
func X509STORE_CTXGetCheckIssued(ctx *X509_STORE_CTX) X509STORE_CTXCheckIssuedFn

//go:linkname X509STORE_CTXGetCheckRevocation C.X509_STORE_CTX_get_check_revocation
func X509STORE_CTXGetCheckRevocation(ctx *X509_STORE_CTX) X509STORE_CTXCheckRevocationFn

//go:linkname X509STORE_CTXSetGetCrl C.X509_STORE_CTX_set_get_crl
func X509STORE_CTXSetGetCrl(ctx *X509_STORE_CTX, get_crl X509STORE_CTXGetCrlFn)

//go:linkname X509STORE_CTXGetGetCrl C.X509_STORE_CTX_get_get_crl
func X509STORE_CTXGetGetCrl(ctx *X509_STORE_CTX) X509STORE_CTXGetCrlFn

//go:linkname X509STORE_CTXGetCheckCrl C.X509_STORE_CTX_get_check_crl
func X509STORE_CTXGetCheckCrl(ctx *X509_STORE_CTX) X509STORE_CTXCheckCrlFn

//go:linkname X509STORE_CTXGetCertCrl C.X509_STORE_CTX_get_cert_crl
func X509STORE_CTXGetCertCrl(ctx *X509_STORE_CTX) X509STORE_CTXCertCrlFn

//go:linkname X509STORE_CTXGetCheckPolicy C.X509_STORE_CTX_get_check_policy
func X509STORE_CTXGetCheckPolicy(ctx *X509_STORE_CTX) X509STORE_CTXCheckPolicyFn

//go:linkname X509STORE_CTXGetLookupCerts C.X509_STORE_CTX_get_lookup_certs
func X509STORE_CTXGetLookupCerts(ctx *X509_STORE_CTX) X509STORE_CTXLookupCertsFn

//go:linkname X509STORE_CTXGetLookupCrls C.X509_STORE_CTX_get_lookup_crls
func X509STORE_CTXGetLookupCrls(ctx *X509_STORE_CTX) X509STORE_CTXLookupCrlsFn

//go:linkname X509STORE_CTXGetCleanup C.X509_STORE_CTX_get_cleanup
func X509STORE_CTXGetCleanup(ctx *X509_STORE_CTX) X509STORE_CTXCleanupFn

//go:linkname X509STOREAddLookup C.X509_STORE_add_lookup
func X509STOREAddLookup(xs *X509_STORE, m *X509_LOOKUP_METHOD) *X509_LOOKUP

//go:linkname X509LOOKUPHashDir C.X509_LOOKUP_hash_dir
func X509LOOKUPHashDir() *X509_LOOKUP_METHOD

//go:linkname X509LOOKUPFile C.X509_LOOKUP_file
func X509LOOKUPFile() *X509_LOOKUP_METHOD

//go:linkname X509LOOKUPStore C.X509_LOOKUP_store
func X509LOOKUPStore() *X509_LOOKUP_METHOD

//go:linkname X509LOOKUPMethNew C.X509_LOOKUP_meth_new
func X509LOOKUPMethNew(name *c.Char) *X509_LOOKUP_METHOD

//go:linkname X509LOOKUPMethFree C.X509_LOOKUP_meth_free
func X509LOOKUPMethFree(method *X509_LOOKUP_METHOD)

//go:linkname X509LOOKUPMethSetNewItem C.X509_LOOKUP_meth_set_new_item
func X509LOOKUPMethSetNewItem(method *X509_LOOKUP_METHOD, new_item func(_llcppg_param1 *X509_LOOKUP) c.Int) c.Int

//go:linkname X509LOOKUPMethGetNewItem C.X509_LOOKUP_meth_get_new_item
func X509LOOKUPMethGetNewItem(method *X509_LOOKUP_METHOD) func(_llcppg_param1 *X509_LOOKUP) c.Int

//go:linkname X509LOOKUPMethSetFree C.X509_LOOKUP_meth_set_free
func X509LOOKUPMethSetFree(method *X509_LOOKUP_METHOD, free_fn func(_llcppg_param1 *X509_LOOKUP)) c.Int

//go:linkname X509LOOKUPMethGetFree C.X509_LOOKUP_meth_get_free
func X509LOOKUPMethGetFree(method *X509_LOOKUP_METHOD) func(_llcppg_param1 *X509_LOOKUP)

//go:linkname X509LOOKUPMethSetInit C.X509_LOOKUP_meth_set_init
func X509LOOKUPMethSetInit(method *X509_LOOKUP_METHOD, init func(_llcppg_param1 *X509_LOOKUP) c.Int) c.Int

//go:linkname X509LOOKUPMethGetInit C.X509_LOOKUP_meth_get_init
func X509LOOKUPMethGetInit(method *X509_LOOKUP_METHOD) func(_llcppg_param1 *X509_LOOKUP) c.Int

//go:linkname X509LOOKUPMethSetShutdown C.X509_LOOKUP_meth_set_shutdown
func X509LOOKUPMethSetShutdown(method *X509_LOOKUP_METHOD, shutdown func(_llcppg_param1 *X509_LOOKUP) c.Int) c.Int

//go:linkname X509LOOKUPMethGetShutdown C.X509_LOOKUP_meth_get_shutdown
func X509LOOKUPMethGetShutdown(method *X509_LOOKUP_METHOD) func(_llcppg_param1 *X509_LOOKUP) c.Int

//go:linkname X509LOOKUPMethSetCtrl C.X509_LOOKUP_meth_set_ctrl
func X509LOOKUPMethSetCtrl(method *X509_LOOKUP_METHOD, ctrl_fn X509LOOKUPCtrlFn) c.Int

//go:linkname X509LOOKUPMethGetCtrl C.X509_LOOKUP_meth_get_ctrl
func X509LOOKUPMethGetCtrl(method *X509_LOOKUP_METHOD) X509LOOKUPCtrlFn

//go:linkname X509LOOKUPMethSetGetBySubject C.X509_LOOKUP_meth_set_get_by_subject
func X509LOOKUPMethSetGetBySubject(method *X509_LOOKUP_METHOD, fn X509LOOKUPGetBySubjectFn) c.Int

//go:linkname X509LOOKUPMethGetGetBySubject C.X509_LOOKUP_meth_get_get_by_subject
func X509LOOKUPMethGetGetBySubject(method *X509_LOOKUP_METHOD) X509LOOKUPGetBySubjectFn

//go:linkname X509LOOKUPMethSetGetByIssuerSerial C.X509_LOOKUP_meth_set_get_by_issuer_serial
func X509LOOKUPMethSetGetByIssuerSerial(method *X509_LOOKUP_METHOD, fn X509LOOKUPGetByIssuerSerialFn) c.Int

//go:linkname X509LOOKUPMethGetGetByIssuerSerial C.X509_LOOKUP_meth_get_get_by_issuer_serial
func X509LOOKUPMethGetGetByIssuerSerial(method *X509_LOOKUP_METHOD) X509LOOKUPGetByIssuerSerialFn

//go:linkname X509LOOKUPMethSetGetByFingerprint C.X509_LOOKUP_meth_set_get_by_fingerprint
func X509LOOKUPMethSetGetByFingerprint(method *X509_LOOKUP_METHOD, fn X509LOOKUPGetByFingerprintFn) c.Int

//go:linkname X509LOOKUPMethGetGetByFingerprint C.X509_LOOKUP_meth_get_get_by_fingerprint
func X509LOOKUPMethGetGetByFingerprint(method *X509_LOOKUP_METHOD) X509LOOKUPGetByFingerprintFn

//go:linkname X509LOOKUPMethSetGetByAlias C.X509_LOOKUP_meth_set_get_by_alias
func X509LOOKUPMethSetGetByAlias(method *X509_LOOKUP_METHOD, fn X509LOOKUPGetByAliasFn) c.Int

//go:linkname X509LOOKUPMethGetGetByAlias C.X509_LOOKUP_meth_get_get_by_alias
func X509LOOKUPMethGetGetByAlias(method *X509_LOOKUP_METHOD) X509LOOKUPGetByAliasFn

//go:linkname X509STOREAddCert C.X509_STORE_add_cert
func X509STOREAddCert(xs *X509_STORE, x *X509) c.Int

//go:linkname X509STOREAddCrl C.X509_STORE_add_crl
func X509STOREAddCrl(xs *X509_STORE, x *X509_CRL) c.Int

//go:linkname X509STORE_CTXGetBySubject C.X509_STORE_CTX_get_by_subject
func X509STORE_CTXGetBySubject(vs *X509_STORE_CTX, type_ X509_LOOKUP_TYPE, name *X509_NAME, ret *X509_OBJECT) c.Int

//go:linkname X509STORE_CTXGetObjBySubject C.X509_STORE_CTX_get_obj_by_subject
func X509STORE_CTXGetObjBySubject(vs *X509_STORE_CTX, type_ X509_LOOKUP_TYPE, name *X509_NAME) *X509_OBJECT

//go:linkname X509LOOKUPCtrl C.X509_LOOKUP_ctrl
func X509LOOKUPCtrl(ctx *X509_LOOKUP, cmd c.Int, argc *c.Char, argl c.Long, ret **c.Char) c.Int

//go:linkname X509LOOKUPCtrlEx C.X509_LOOKUP_ctrl_ex
func X509LOOKUPCtrlEx(ctx *X509_LOOKUP, cmd c.Int, argc *c.Char, argl c.Long, ret **c.Char, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname X509LoadCertFile C.X509_load_cert_file
func X509LoadCertFile(ctx *X509_LOOKUP, file *c.Char, type_ c.Int) c.Int

//go:linkname X509LoadCertFileEx C.X509_load_cert_file_ex
func X509LoadCertFileEx(ctx *X509_LOOKUP, file *c.Char, type_ c.Int, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname X509LoadCrlFile C.X509_load_crl_file
func X509LoadCrlFile(ctx *X509_LOOKUP, file *c.Char, type_ c.Int) c.Int

//go:linkname X509LoadCertCrlFile C.X509_load_cert_crl_file
func X509LoadCertCrlFile(ctx *X509_LOOKUP, file *c.Char, type_ c.Int) c.Int

//go:linkname X509LoadCertCrlFileEx C.X509_load_cert_crl_file_ex
func X509LoadCertCrlFileEx(ctx *X509_LOOKUP, file *c.Char, type_ c.Int, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname X509LOOKUPNew C.X509_LOOKUP_new
func X509LOOKUPNew(method *X509_LOOKUP_METHOD) *X509_LOOKUP

//go:linkname X509LOOKUPFree C.X509_LOOKUP_free
func X509LOOKUPFree(ctx *X509_LOOKUP)

//go:linkname X509LOOKUPInit C.X509_LOOKUP_init
func X509LOOKUPInit(ctx *X509_LOOKUP) c.Int

//go:linkname X509LOOKUPBySubject C.X509_LOOKUP_by_subject
func X509LOOKUPBySubject(ctx *X509_LOOKUP, type_ X509_LOOKUP_TYPE, name *X509_NAME, ret *X509_OBJECT) c.Int

//go:linkname X509LOOKUPBySubjectEx C.X509_LOOKUP_by_subject_ex
func X509LOOKUPBySubjectEx(ctx *X509_LOOKUP, type_ X509_LOOKUP_TYPE, name *X509_NAME, ret *X509_OBJECT, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname X509LOOKUPByIssuerSerial C.X509_LOOKUP_by_issuer_serial
func X509LOOKUPByIssuerSerial(ctx *X509_LOOKUP, type_ X509_LOOKUP_TYPE, name *X509_NAME, serial *ASN1_INTEGER, ret *X509_OBJECT) c.Int

//go:linkname X509LOOKUPByFingerprint C.X509_LOOKUP_by_fingerprint
func X509LOOKUPByFingerprint(ctx *X509_LOOKUP, type_ X509_LOOKUP_TYPE, bytes *uint8, len c.Int, ret *X509_OBJECT) c.Int

//go:linkname X509LOOKUPByAlias C.X509_LOOKUP_by_alias
func X509LOOKUPByAlias(ctx *X509_LOOKUP, type_ X509_LOOKUP_TYPE, str *c.Char, len c.Int, ret *X509_OBJECT) c.Int

//go:linkname X509LOOKUPSetMethodData C.X509_LOOKUP_set_method_data
func X509LOOKUPSetMethodData(ctx *X509_LOOKUP, data unsafe.Pointer) c.Int

//go:linkname X509LOOKUPGetMethodData C.X509_LOOKUP_get_method_data
func X509LOOKUPGetMethodData(ctx *X509_LOOKUP) unsafe.Pointer

//go:linkname X509LOOKUPGetStore C.X509_LOOKUP_get_store
func X509LOOKUPGetStore(ctx *X509_LOOKUP) *X509_STORE

//go:linkname X509LOOKUPShutdown C.X509_LOOKUP_shutdown
func X509LOOKUPShutdown(ctx *X509_LOOKUP) c.Int

//go:linkname X509STORELoadFile C.X509_STORE_load_file
func X509STORELoadFile(xs *X509_STORE, file *c.Char) c.Int

//go:linkname X509STORELoadPath C.X509_STORE_load_path
func X509STORELoadPath(xs *X509_STORE, path *c.Char) c.Int

//go:linkname X509STORELoadStore C.X509_STORE_load_store
func X509STORELoadStore(xs *X509_STORE, store *c.Char) c.Int

//go:linkname X509STORELoadLocations C.X509_STORE_load_locations
func X509STORELoadLocations(s *X509_STORE, file *c.Char, dir *c.Char) c.Int

//go:linkname X509STORESetDefaultPaths C.X509_STORE_set_default_paths
func X509STORESetDefaultPaths(xs *X509_STORE) c.Int

//go:linkname X509STORELoadFileEx C.X509_STORE_load_file_ex
func X509STORELoadFileEx(xs *X509_STORE, file *c.Char, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname X509STORELoadStoreEx C.X509_STORE_load_store_ex
func X509STORELoadStoreEx(xs *X509_STORE, store *c.Char, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname X509STORELoadLocationsEx C.X509_STORE_load_locations_ex
func X509STORELoadLocationsEx(xs *X509_STORE, file *c.Char, dir *c.Char, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname X509STORESetDefaultPathsEx C.X509_STORE_set_default_paths_ex
func X509STORESetDefaultPathsEx(xs *X509_STORE, libctx *OSSL_LIB_CTX, propq *c.Char) c.Int

//go:linkname X509STORE_CTXSetExData C.X509_STORE_CTX_set_ex_data
func X509STORE_CTXSetExData(ctx *X509_STORE_CTX, idx c.Int, data unsafe.Pointer) c.Int

//go:linkname X509STORE_CTXGetExData C.X509_STORE_CTX_get_ex_data
func X509STORE_CTXGetExData(ctx *X509_STORE_CTX, idx c.Int) unsafe.Pointer

//go:linkname X509STORE_CTXGetError C.X509_STORE_CTX_get_error
func X509STORE_CTXGetError(ctx *X509_STORE_CTX) c.Int

//go:linkname X509STORE_CTXSetError C.X509_STORE_CTX_set_error
func X509STORE_CTXSetError(ctx *X509_STORE_CTX, s c.Int)

//go:linkname X509STORE_CTXGetErrorDepth C.X509_STORE_CTX_get_error_depth
func X509STORE_CTXGetErrorDepth(ctx *X509_STORE_CTX) c.Int

//go:linkname X509STORE_CTXSetErrorDepth C.X509_STORE_CTX_set_error_depth
func X509STORE_CTXSetErrorDepth(ctx *X509_STORE_CTX, depth c.Int)

//go:linkname X509STORE_CTXGetCurrentCert C.X509_STORE_CTX_get_current_cert
func X509STORE_CTXGetCurrentCert(ctx *X509_STORE_CTX) *X509

//go:linkname X509STORE_CTXSetCurrentCert C.X509_STORE_CTX_set_current_cert
func X509STORE_CTXSetCurrentCert(ctx *X509_STORE_CTX, x *X509)

//go:linkname X509STORE_CTXGet0CurrentIssuer C.X509_STORE_CTX_get0_current_issuer
func X509STORE_CTXGet0CurrentIssuer(ctx *X509_STORE_CTX) *X509

//go:linkname X509STORE_CTXGet0CurrentCrl C.X509_STORE_CTX_get0_current_crl
func X509STORE_CTXGet0CurrentCrl(ctx *X509_STORE_CTX) *X509_CRL

//go:linkname X509STORE_CTXGet0ParentCtx C.X509_STORE_CTX_get0_parent_ctx
func X509STORE_CTXGet0ParentCtx(ctx *X509_STORE_CTX) *X509_STORE_CTX

//go:linkname X509STORE_CTXGet0Chain C.X509_STORE_CTX_get0_chain
func X509STORE_CTXGet0Chain(ctx *X509_STORE_CTX) *StackStX509

//go:linkname X509STORE_CTXGet1Chain C.X509_STORE_CTX_get1_chain
func X509STORE_CTXGet1Chain(ctx *X509_STORE_CTX) *StackStX509

//go:linkname X509STORE_CTXSetCert C.X509_STORE_CTX_set_cert
func X509STORE_CTXSetCert(ctx *X509_STORE_CTX, target *X509)

//go:linkname X509STORE_CTXSet0Rpk C.X509_STORE_CTX_set0_rpk
func X509STORE_CTXSet0Rpk(ctx *X509_STORE_CTX, target *EVP_PKEY)

//go:linkname X509STORE_CTXSet0VerifiedChain C.X509_STORE_CTX_set0_verified_chain
func X509STORE_CTXSet0VerifiedChain(c *X509_STORE_CTX, sk *StackStX509)

//go:linkname X509STORE_CTXSet0Crls C.X509_STORE_CTX_set0_crls
func X509STORE_CTXSet0Crls(ctx *X509_STORE_CTX, sk *StackStX509CRL)

//go:linkname X509STORE_CTXSetOcspResp C.X509_STORE_CTX_set_ocsp_resp
func X509STORE_CTXSetOcspResp(ctx *X509_STORE_CTX, sk *StackStOCSP_RESPONSE)

//go:linkname X509STORE_CTXSetPurpose C.X509_STORE_CTX_set_purpose
func X509STORE_CTXSetPurpose(ctx *X509_STORE_CTX, purpose c.Int) c.Int

//go:linkname X509STORE_CTXSetTrust C.X509_STORE_CTX_set_trust
func X509STORE_CTXSetTrust(ctx *X509_STORE_CTX, trust c.Int) c.Int

//go:linkname X509STORE_CTXPurposeInherit C.X509_STORE_CTX_purpose_inherit
func X509STORE_CTXPurposeInherit(ctx *X509_STORE_CTX, def_purpose c.Int, purpose c.Int, trust c.Int) c.Int

//go:linkname X509STORE_CTXSetFlags C.X509_STORE_CTX_set_flags
func X509STORE_CTXSetFlags(ctx *X509_STORE_CTX, flags c.Ulong)

//go:linkname X509STORE_CTXSetTime C.X509_STORE_CTX_set_time
func X509STORE_CTXSetTime(ctx *X509_STORE_CTX, flags c.Ulong, t time.TimeT)

//go:linkname X509STORE_CTXSetCurrentReasons C.X509_STORE_CTX_set_current_reasons
func X509STORE_CTXSetCurrentReasons(ctx *X509_STORE_CTX, current_reasons c.Uint)

//go:linkname X509STORE_CTXGet0PolicyTree C.X509_STORE_CTX_get0_policy_tree
func X509STORE_CTXGet0PolicyTree(ctx *X509_STORE_CTX) *X509_POLICY_TREE

//go:linkname X509STORE_CTXGetExplicitPolicy C.X509_STORE_CTX_get_explicit_policy
func X509STORE_CTXGetExplicitPolicy(ctx *X509_STORE_CTX) c.Int

//go:linkname X509STORE_CTXGetNumUntrusted C.X509_STORE_CTX_get_num_untrusted
func X509STORE_CTXGetNumUntrusted(ctx *X509_STORE_CTX) c.Int

//go:linkname X509STORE_CTXGet0Param C.X509_STORE_CTX_get0_param
func X509STORE_CTXGet0Param(ctx *X509_STORE_CTX) *X509_VERIFY_PARAM

//go:linkname X509STORE_CTXSet0Param C.X509_STORE_CTX_set0_param
func X509STORE_CTXSet0Param(ctx *X509_STORE_CTX, param *X509_VERIFY_PARAM)

//go:linkname X509STORE_CTXSetDefault C.X509_STORE_CTX_set_default
func X509STORE_CTXSetDefault(ctx *X509_STORE_CTX, name *c.Char) c.Int

// Bridge opacity barrier between libcrypt and libssl, also needed to support
// offline testing in test/danetest.c
//
//go:linkname X509STORE_CTXSet0Dane C.X509_STORE_CTX_set0_dane
func X509STORE_CTXSet0Dane(ctx *X509_STORE_CTX, dane *SSL_DANE)

// X509_VERIFY_PARAM functions
//
//go:linkname X509VERIFY_PARAMNew C.X509_VERIFY_PARAM_new
func X509VERIFY_PARAMNew() *X509_VERIFY_PARAM

//go:linkname X509VERIFY_PARAMFree C.X509_VERIFY_PARAM_free
func X509VERIFY_PARAMFree(param *X509_VERIFY_PARAM)

//go:linkname X509VERIFY_PARAMInherit C.X509_VERIFY_PARAM_inherit
func X509VERIFY_PARAMInherit(to *X509_VERIFY_PARAM, from *X509_VERIFY_PARAM) c.Int

//go:linkname X509VERIFY_PARAMSet1 C.X509_VERIFY_PARAM_set1
func X509VERIFY_PARAMSet1(to *X509_VERIFY_PARAM, from *X509_VERIFY_PARAM) c.Int

//go:linkname X509VERIFY_PARAMSet1Name C.X509_VERIFY_PARAM_set1_name
func X509VERIFY_PARAMSet1Name(param *X509_VERIFY_PARAM, name *c.Char) c.Int

//go:linkname X509VERIFY_PARAMSetFlags C.X509_VERIFY_PARAM_set_flags
func X509VERIFY_PARAMSetFlags(param *X509_VERIFY_PARAM, flags c.Ulong) c.Int

//go:linkname X509VERIFY_PARAMClearFlags C.X509_VERIFY_PARAM_clear_flags
func X509VERIFY_PARAMClearFlags(param *X509_VERIFY_PARAM, flags c.Ulong) c.Int

//go:linkname X509VERIFY_PARAMGetFlags C.X509_VERIFY_PARAM_get_flags
func X509VERIFY_PARAMGetFlags(param *X509_VERIFY_PARAM) c.Ulong

//go:linkname X509VERIFY_PARAMSetPurpose C.X509_VERIFY_PARAM_set_purpose
func X509VERIFY_PARAMSetPurpose(param *X509_VERIFY_PARAM, purpose c.Int) c.Int

//go:linkname X509VERIFY_PARAMGetPurpose C.X509_VERIFY_PARAM_get_purpose
func X509VERIFY_PARAMGetPurpose(param *X509_VERIFY_PARAM) c.Int

//go:linkname X509VERIFY_PARAMSetTrust C.X509_VERIFY_PARAM_set_trust
func X509VERIFY_PARAMSetTrust(param *X509_VERIFY_PARAM, trust c.Int) c.Int

//go:linkname X509VERIFY_PARAMSetDepth C.X509_VERIFY_PARAM_set_depth
func X509VERIFY_PARAMSetDepth(param *X509_VERIFY_PARAM, depth c.Int)

//go:linkname X509VERIFY_PARAMSetAuthLevel C.X509_VERIFY_PARAM_set_auth_level
func X509VERIFY_PARAMSetAuthLevel(param *X509_VERIFY_PARAM, auth_level c.Int)

//go:linkname X509VERIFY_PARAMGetTime C.X509_VERIFY_PARAM_get_time
func X509VERIFY_PARAMGetTime(param *X509_VERIFY_PARAM) time.TimeT

//go:linkname X509VERIFY_PARAMSetTime C.X509_VERIFY_PARAM_set_time
func X509VERIFY_PARAMSetTime(param *X509_VERIFY_PARAM, t time.TimeT)

//go:linkname X509VERIFY_PARAMAdd0Policy C.X509_VERIFY_PARAM_add0_policy
func X509VERIFY_PARAMAdd0Policy(param *X509_VERIFY_PARAM, policy *ASN1_OBJECT) c.Int

//go:linkname X509VERIFY_PARAMSet1Policies C.X509_VERIFY_PARAM_set1_policies
func X509VERIFY_PARAMSet1Policies(param *X509_VERIFY_PARAM, policies *StackStASN1OBJECT) c.Int

//go:linkname X509VERIFY_PARAMSetInhFlags C.X509_VERIFY_PARAM_set_inh_flags
func X509VERIFY_PARAMSetInhFlags(param *X509_VERIFY_PARAM, flags c.Uint32T) c.Int

//go:linkname X509VERIFY_PARAMGetInhFlags C.X509_VERIFY_PARAM_get_inh_flags
func X509VERIFY_PARAMGetInhFlags(param *X509_VERIFY_PARAM) c.Uint32T

//go:linkname X509VERIFY_PARAMGet0Host C.X509_VERIFY_PARAM_get0_host
func X509VERIFY_PARAMGet0Host(param *X509_VERIFY_PARAM, idx c.Int) *c.Char

//go:linkname X509VERIFY_PARAMSet1Host C.X509_VERIFY_PARAM_set1_host
func X509VERIFY_PARAMSet1Host(param *X509_VERIFY_PARAM, name *c.Char, namelen c.SizeT) c.Int

//go:linkname X509VERIFY_PARAMAdd1Host C.X509_VERIFY_PARAM_add1_host
func X509VERIFY_PARAMAdd1Host(param *X509_VERIFY_PARAM, name *c.Char, namelen c.SizeT) c.Int

//go:linkname X509VERIFY_PARAMSet1HostInputValidation C.X509_VERIFY_PARAM_set1_host_input_validation
func X509VERIFY_PARAMSet1HostInputValidation(param *X509_VERIFY_PARAM, validate_host func(_llcppg_param1 *c.Char, _llcppg_param2 c.SizeT) c.Int)

//go:linkname X509VERIFY_PARAMSetHostflags C.X509_VERIFY_PARAM_set_hostflags
func X509VERIFY_PARAMSetHostflags(param *X509_VERIFY_PARAM, flags c.Uint)

//go:linkname X509VERIFY_PARAMGetHostflags C.X509_VERIFY_PARAM_get_hostflags
func X509VERIFY_PARAMGetHostflags(param *X509_VERIFY_PARAM) c.Uint

//go:linkname X509VERIFY_PARAMGet0Peername C.X509_VERIFY_PARAM_get0_peername
func X509VERIFY_PARAMGet0Peername(param *X509_VERIFY_PARAM) *c.Char

//go:linkname X509VERIFY_PARAMMovePeername C.X509_VERIFY_PARAM_move_peername
func X509VERIFY_PARAMMovePeername(_llcppg_param1 *X509_VERIFY_PARAM, _llcppg_param2 *X509_VERIFY_PARAM)

//go:linkname X509VERIFY_PARAMGet0Email C.X509_VERIFY_PARAM_get0_email
func X509VERIFY_PARAMGet0Email(param *X509_VERIFY_PARAM) *c.Char

//go:linkname X509VERIFY_PARAMSet1Email C.X509_VERIFY_PARAM_set1_email
func X509VERIFY_PARAMSet1Email(param *X509_VERIFY_PARAM, email *c.Char, emaillen c.SizeT) c.Int

//go:linkname X509VERIFY_PARAMSet1Rfc822 C.X509_VERIFY_PARAM_set1_rfc822
func X509VERIFY_PARAMSet1Rfc822(param *X509_VERIFY_PARAM, email *c.Char, emaillen c.SizeT) c.Int

//go:linkname X509VERIFY_PARAMAdd1Rfc822 C.X509_VERIFY_PARAM_add1_rfc822
func X509VERIFY_PARAMAdd1Rfc822(param *X509_VERIFY_PARAM, email *c.Char, len c.SizeT) c.Int

//go:linkname X509VERIFY_PARAMSet1Rfc822InputValidation C.X509_VERIFY_PARAM_set1_rfc822_input_validation
func X509VERIFY_PARAMSet1Rfc822InputValidation(param *X509_VERIFY_PARAM, validate_rfc822 func(_llcppg_param1 *c.Char, _llcppg_param2 c.SizeT) c.Int)

//go:linkname X509VERIFY_PARAMSet1Smtputf8 C.X509_VERIFY_PARAM_set1_smtputf8
func X509VERIFY_PARAMSet1Smtputf8(param *X509_VERIFY_PARAM, email *c.Char, emaillen c.SizeT) c.Int

//go:linkname X509VERIFY_PARAMAdd1Smtputf8 C.X509_VERIFY_PARAM_add1_smtputf8
func X509VERIFY_PARAMAdd1Smtputf8(param *X509_VERIFY_PARAM, email *c.Char, len c.SizeT) c.Int

//go:linkname X509VERIFY_PARAMSet1Smtputf8InputValidation C.X509_VERIFY_PARAM_set1_smtputf8_input_validation
func X509VERIFY_PARAMSet1Smtputf8InputValidation(param *X509_VERIFY_PARAM, validate_smtputf8 func(_llcppg_param1 *c.Char, _llcppg_param2 c.SizeT) c.Int)

//go:linkname X509VERIFY_PARAMGet1IpAsc C.X509_VERIFY_PARAM_get1_ip_asc
func X509VERIFY_PARAMGet1IpAsc(param *X509_VERIFY_PARAM) *c.Char

//go:linkname X509VERIFY_PARAMSet1Ip C.X509_VERIFY_PARAM_set1_ip
func X509VERIFY_PARAMSet1Ip(param *X509_VERIFY_PARAM, ip *c.Uint8T, iplen c.SizeT) c.Int

//go:linkname X509VERIFY_PARAMSet1IpInputValidation C.X509_VERIFY_PARAM_set1_ip_input_validation
func X509VERIFY_PARAMSet1IpInputValidation(param *X509_VERIFY_PARAM, validate_ip func(_llcppg_param1 *c.Uint8T, _llcppg_param2 c.SizeT) c.Int)

//go:linkname X509VERIFY_PARAMSet1IpAsc C.X509_VERIFY_PARAM_set1_ip_asc
func X509VERIFY_PARAMSet1IpAsc(param *X509_VERIFY_PARAM, ipasc *c.Char) c.Int

//go:linkname X509VERIFY_PARAMAdd1Ip C.X509_VERIFY_PARAM_add1_ip
func X509VERIFY_PARAMAdd1Ip(param *X509_VERIFY_PARAM, ip *c.Uint8T, len c.SizeT) c.Int

//go:linkname X509VERIFY_PARAMAdd1IpAsc C.X509_VERIFY_PARAM_add1_ip_asc
func X509VERIFY_PARAMAdd1IpAsc(param *X509_VERIFY_PARAM, ipasc *c.Char) c.Int

//go:linkname X509VERIFY_PARAMGetDepth C.X509_VERIFY_PARAM_get_depth
func X509VERIFY_PARAMGetDepth(param *X509_VERIFY_PARAM) c.Int

//go:linkname X509VERIFY_PARAMGetAuthLevel C.X509_VERIFY_PARAM_get_auth_level
func X509VERIFY_PARAMGetAuthLevel(param *X509_VERIFY_PARAM) c.Int

//go:linkname X509VERIFY_PARAMGet0Name C.X509_VERIFY_PARAM_get0_name
func X509VERIFY_PARAMGet0Name(param *X509_VERIFY_PARAM) *c.Char

//go:linkname X509VERIFY_PARAMAdd0Table C.X509_VERIFY_PARAM_add0_table
func X509VERIFY_PARAMAdd0Table(param *X509_VERIFY_PARAM) c.Int

//go:linkname X509VERIFY_PARAMGetCount C.X509_VERIFY_PARAM_get_count
func X509VERIFY_PARAMGetCount() c.Int

//go:linkname X509VERIFY_PARAMGet0 C.X509_VERIFY_PARAM_get0
func X509VERIFY_PARAMGet0(id c.Int) *X509_VERIFY_PARAM

//go:linkname X509VERIFY_PARAMLookup C.X509_VERIFY_PARAM_lookup
func X509VERIFY_PARAMLookup(name *c.Char) *X509_VERIFY_PARAM

//go:linkname X509VERIFY_PARAMTableCleanup C.X509_VERIFY_PARAM_table_cleanup
func X509VERIFY_PARAMTableCleanup()

//go:linkname X509PolicyCheck C.X509_policy_check
func X509PolicyCheck(ptree **X509_POLICY_TREE, pexplicit_policy *c.Int, certs *StackStX509, policy_oids *StackStASN1OBJECT, flags c.Uint) c.Int

//go:linkname X509PolicyTreeFree C.X509_policy_tree_free
func X509PolicyTreeFree(tree *X509_POLICY_TREE)

//go:linkname X509PolicyTreeLevelCount C.X509_policy_tree_level_count
func X509PolicyTreeLevelCount(tree *X509_POLICY_TREE) c.Int

//go:linkname X509PolicyTreeGet0Level C.X509_policy_tree_get0_level
func X509PolicyTreeGet0Level(tree *X509_POLICY_TREE, i c.Int) *X509_POLICY_LEVEL

//go:linkname X509PolicyTreeGet0Policies C.X509_policy_tree_get0_policies
func X509PolicyTreeGet0Policies(tree *X509_POLICY_TREE) *StackStX509POLICY_NODE

//go:linkname X509PolicyTreeGet0UserPolicies C.X509_policy_tree_get0_user_policies
func X509PolicyTreeGet0UserPolicies(tree *X509_POLICY_TREE) *StackStX509POLICY_NODE

//go:linkname X509PolicyLevelNodeCount C.X509_policy_level_node_count
func X509PolicyLevelNodeCount(level *X509_POLICY_LEVEL) c.Int

//go:linkname X509PolicyLevelGet0Node C.X509_policy_level_get0_node
func X509PolicyLevelGet0Node(level *X509_POLICY_LEVEL, i c.Int) *X509_POLICY_NODE

//go:linkname X509PolicyNodeGet0Policy C.X509_policy_node_get0_policy
func X509PolicyNodeGet0Policy(node *X509_POLICY_NODE) *ASN1_OBJECT

//go:linkname X509PolicyNodeGet0Qualifiers C.X509_policy_node_get0_qualifiers
func X509PolicyNodeGet0Qualifiers(node *X509_POLICY_NODE) *StackStPOLICYQUALINFO

//go:linkname X509PolicyNodeGet0Parent C.X509_policy_node_get0_parent
func X509PolicyNodeGet0Parent(node *X509_POLICY_NODE) *X509_POLICY_NODE
